### ISSUE TITLE
An ability to specify multi launchTemplate in Provisioner spec

### ISSUE THREAD

**Issue by Noksa** [aws/karpenter#1009]
**Tell us about your request**

Currently we are able to specify only one `launchTemplate` in `Provisioner`.
Like this:
```
  provider:
    instanceProfile: ad-eks-c-NodeInstanceProfile
    subnetSelector:
      kubernetes.io/cluster/ad-eks-c: '*'
    launchTemplate: ad-eks-fs-lt
```

At the same time we can specify two arch in requirements (at the same time or separately): 
```
  requirements:
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64", "arm64"]
```

But if I want to run only on amd or arm I have to change `launchTemplate` as well.

Because custom template has `AMI` only for specific arch and actually we can't specify both of them in requirements if we use custom template.

I would suggest to specify `launchTemplate` as array of templates and `Karpenter` will choose appropriate template from the list using its `requirements`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
