### ISSUE TITLE
Support PodAntiAffinity

### ISSUE THREAD

**Issue by Noksa** [aws/karpenter#1010]
**Tell us about your request**

As you know k8s has great `podAntiAffinity` mechanism that allows us to place the same pods on different nodes.
As example:
```
podAntiAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
          - key: "kazooService"
            operator: In
            values:
              - "kazoo-sbc"
      topologyKey: "kubernetes.io/hostname"
```

At the same time `Karpenter` doesn't support both `podAffinity` and `podAntiAffinity`

We can use `topologySpreadConstraints` instead but it has `maxSkew` 1 as minimum value.
It means that two same pods can be placed on the same node.

So how can we tell `Karpenter` to create a new node for each specific pod instead of trying to place them to an existing node if it still has capacity?

I know that I can use
```
resources:
  requests:
```
to let pod acquire all resources on a node but if I do this all other pods (from other deploy/sts) won't be able to be placed on the node if they satisfy requirements.

Can you please tell me if there is a workaround?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
