### ISSUE TITLE
Subnet Selector default is surprising

### ISSUE THREAD

**Issue by johnktims** [aws/karpenter#1017]
## Version

**Karpenter**: v0.5.2

**Kubernetes**:
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

## Expected Behavior
`subnetSelector` should only include the specified subnet selection criteria

## Actual Behavior
The default subnetSelector is appended to my subnetSelector so Karpenter isn't finding any subnets.

## Steps to Reproduce the Problem

I deployed this provisioner and 2 subnets with only the tag `Name=platform-Subnet`.

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
  provider:
    instanceProfile: KarpenterNodeInstanceProfile-${module.eks.cluster_id}
    subnetSelector:
      Name: platform-Subnet
  ttlSecondsAfterEmpty: 30
```

When I view the logs I see
```
ERROR	controller.controller.metrics	Reconciler error	{"commit": "870e2f6", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner", "name": "default", "namespace": "", "error": "no subnets matched selector map[Name:platform-Subnet kubernetes.io/cluster/prototype:*]"}
```

I used the aws cli to verify that removing the cluster name would fix the issue:
```
aws ec2 describe-subnets     --filters "Name=tag-key,Values=kubernetes.io/cluster/prototype" "Name=tag:Name,Values=platform-Subnet"
{
    "Subnets": []
}
```
but if I remove the cluster tag, I see my subnets
```
aws ec2 describe-subnets     --filters "Name=tag:Name,Values=platform-Subnet"
{
    "Subnets": [
        {
       ...
```

**Comment by ellistarn** [comment]
You must tag your subnets with `kubernetes.io/cluster/prototype: Owned` https://karpenter.sh/docs/getting-started/#tag-subnets.

Is there a reason that subnet tagging is a challenge? We wanted to settle on a default that was already set for many clusters. I'd love to hear more about your subnet tagging process and perhaps we can find a better default.

**Comment by johnktims** [comment]
Unfortunately, the VPC and subnets are owned by a different team.

I guess I don't understand what subnetSelector is for if I still have to tag the subnets. I figured I'd be able to use this to override the defaults and specify my own filter.

**Comment by ellistarn** [comment]
This makes sense to me. I think we're overeagerly defaulting. If the user provides a selector, we should use it, otherwise we should default to something. I'll see if I can get this into the next release.

**Comment by mikesir87** [comment]
I’ll be happy to take this one! 👍

**Comment by olemarkus** [comment]
I think kubernetes require that tag, but it can also be set to shared. The tag is used by service controllers to allow ELBs to talk to the node. (you may also need additional tags for internal ELBs if applicable)

**Comment by ellistarn** [comment]
The tag is used differently by different installers. @olemarkus , is it correct that KOPs labels subnets and security groups with kubernetes.io/cluster/$name: owned | shared?

I could see Karpenter being agnostic to any of these tags and not providing a default at all. Or defining a karpenter specific tag karpenter.sh/discovery. 

The aforementioned relaxation of our defaults still makes sense for me, but I can see potentially changing what that default itself is in the future.

**Comment by olemarkus** [comment]
This doesn't have anything to do with installers. See this code:
* https://github.com/kubernetes/cloud-provider-aws/blob/a91c69e4d9b91b3ffc55c0a7f39c89fdba1fddc2/pkg/providers/v1/aws.go#L4668
* https://github.com/kubernetes/cloud-provider-aws/blob/a91c69e4d9b91b3ffc55c0a7f39c89fdba1fddc2/pkg/providers/v1/tags.go#L133

The requirements come from k/k and AWS Kubernetes Cloud Provider.
There is also similar logic in AWS Load Balancer Controller.

**Comment by olemarkus** [comment]
Relised my first link was for SGs. Here is the one for subnets https://github.com/kubernetes/cloud-provider-aws/blob/a91c69e4d9b91b3ffc55c0a7f39c89fdba1fddc2/pkg/providers/v1/aws.go#L3647

**Comment by olemarkus** [comment]
As for kOps, we tag subnets and such unless users configure kOps not to. Many bring their own subnets, and then it is up to them to ensure tags match what is required. Many want to do their own terraform stuff for example and want kOps to stay out of changing such resources. kOps also use those tags for IAM purposes, but that was outside of what I referred to here.

**Comment by mikesir87** [comment]
I think one of the surprising parts of this is that when you specify the security group selector, the default cluster tag is not auto-added to the collection. So, there's a difference in how those are handled compared to the subnets. I hadn't thought about it, but we're soon going to be transitioning into an environment where we are using a Shared VPC and the subnets are delegated to us, making it difficult for us to get tags on them. Therefore, having the ability to completely control the collection makes sense to me.

**Comment by mikesir87** [comment]
Hmm... I actually just looked at the code (in prep for submitting a PR), but it looks like it's doing exactly what we wanted it to do... it defaults to using the cluster tag if none is provided. But, if one is provided, it uses only the set provided.

```shell
kubectl apply -f - <<EOF
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: provisioner-with-subnets
spec:
  limits:
    resources:
      cpu: 1000
  provider:
    instanceProfile: karpenter-profile
    subnetSelector:
      customTag: value
EOF
```

And then running `kubectl describe provisioner provisioner-with-subnets` gives me the following...

```yaml
Name:         provisioner-with-subnets
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  karpenter.sh/v1alpha5
Kind:         Provisioner
Metadata:
  Creation Timestamp:  2021-12-21T15:06:06Z
  Generation:          2
  Resource Version:  150240672
  UID:               00f672b6-383c-49df-a666-d1331703334d
Spec:
  Kubelet Configuration:
  Limits:
    Resources:
      Cpu:  1k
  Provider:
    API Version:       extensions.karpenter.sh/v1alpha1
    Instance Profile:  karpenter-profile
    Kind:              AWS
    Security Group Selector:
      kubernetes.io/cluster/test-cluster:  *
    Subnet Selector:
      Custom Tag:  value
  Requirements:
    Key:       kubernetes.io/arch
    Operator:  In
    Values:
      amd64
    Key:       karpenter.sh/capacity-type
    Operator:  In
    Values:
      on-demand
Status:
  Resources:
    Cpu:     0
    Memory:  0
Events:      <none>
```

So... it looks like it's listing as anticipated. I don't see anywhere else in the codebase that that key would be added back in (since it happens in the webhook to default values when creating the object). What do you get when you describe your provisioner @johnktims ?
