### ISSUE TITLE
Provide more control over node upgrading

### ISSUE THREAD

**Issue by m00lecule** [aws/karpenter#1018]
Hello, I would like to submit a feature request.

Currently I am trying to replace clusterautoscaler with karpenter but one missing feature is a blocker - **updating cluster nodes spawned by karpenter**. Referencing official docs - https://karpenter.sh/docs/concepts/#upgrading-nodes the only way to update Your current cluster setup is to configure `ttlSecondsUntilExpired` for each node. I believe this wont be acceptable for applications that must be running 24/7 - in some corner cases major part of nodes might be deleted at the same time, causing cluster outage. Also it bring too much entropy to the cluster configuration - *I can imagine that monitoring engineers might be terrified that during midnight shift when they find out that some production facing instances have been unexpectedly deleted*.

More mature tools like `kops` are handling updates in HA manner - please see `kops cluster rolling-update` https://kops.sigs.k8s.io/operations/rolling-update/ or https://docs.aws.amazon.com/eks/latest/userguide/update-managed-node-group.html.

**My proposition is to implement Provisioner CRD versioning**

Motivation - karpenter will assign labels to each node, with version of `Provisioner` that was used to spawn an EC2 instance. Karpenter will detect changes applied to `Provisioner` and apply them to cluster keeping cluster highly available.

### 1.  create original Provisioner CRD
`provsioner-01.yml`
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    (...)
    - key: "node.kubernetes.io/instance-type" 
      operator: In
      values: ["m5.xlarge","m5.large"]
   (...)
  provider:
    (...)
    launchTemplate: eks-XXXX
    launchTemplateVersion: 1 
```

### 2.  karpenter spawns instances basing on  `provsioner-01.yml`

Imagine that we spawned 10 instances with AMI from launch template `eks-XXXX` in version `1`.  Those instances size would be one of `m5.xlarge` or `m5.large`

### 3.  apply some changes to `Provisioner` named `default`

`provsioner-02.yml`
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    (...)
    - key: "node.kubernetes.io/instance-type" 
      operator: In
      values: ["r4.xlarge"]
   (...)
  provider:
    (...)
    launchTemplate: eks-XXXX
    launchTemplateVersion: 2 
```

### 4. now the interesting part take places

Karpenter detects that there were changes applied to `Provisioner` named `default` and tries to replace all instances spawned using `provsioner-01.yml` with most up to date configuration from `provsioner-02.yml` keeping the cluster highly available.

For convenience nodes spawned using Provisioner from `provisioner-02.yml` will be labeled `default-node-02` and those from original configuration `default-node-01`

Those changes would be applied in rolling update manner and the loop would look like:
1. Karpenter cordons all nodes labeled `default-node-01` (prevents from scheduling on pods)
2. Initialy Karpneter would spin instance `default-node-02` using launch template in version `2` (from `provisioner-02.yml`), the instance would be sized `r4.xlarge`.
3. When new node would be ready then It would try to drain and evict node labeled `default-node-01` - if there would be no room for pods from picked node then another instance labeled `default-node-02` would be created.
4. Go to 3. until any node labeled `default-node-01` exist.

thanks to @akestner and @ellistarn for bringing me here

I am looking forward for Your feedback about proposed approach

# Implementation

If I would have to do in on myself then I would propose `MutatingAdmissionWebhook` for `Provisioner CRD` that will notify `karpenter-controller` and trigger karpenter nodes reconfiguration.

https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
