### ISSUE TITLE
Inconsistent cluster name in kube config causes tagging error and node failing to join

### ISSUE THREAD

**Issue by felix-zhe-huang** [aws/karpenter#1075]
## Version

**Karpenter**: v0.5.3

**Kubernetes**: v1.21.2
**eksctl**: 0.77.0
**aws-cli**: 2.2.43

## Expected Behavior

Karpenter tags subnet and security groups correctly.
Karpenter successfully launches new node.

## Actual Behavior

Karpenter Makefile fails to extract correct value for `${CLUSTER_NAME}` when ~/.kube/config is created by eksctl.
When manually provided the correct value, Karpenter will start normally but failed to launch new worker node.
New worker node will stuck at NOT_READY.

Rename the cluster using `aws eks update-kubeconfig --name karpenter` solves the problem.
The aws-cli inserts entries in ~/.kube/config with clusters.cluster.name in the format of arn.
It seems that Karpenter does not work when clusters.cluster.name uses different format other than arn (eksctl uses FQDN `${CLUSTER_NAME}.${REGION}.eksctl.io`).

## Steps to Reproduce the Problem

Following [https://karpenter.sh/docs/getting-started/](url)

**Comment by felix-zhe-huang** [comment]
Kops also uses the FQDN. Need a more consistent and inclusive way to config the Karpenter deployment process.

**Comment by dbgoytia** [comment]
Hi! I'd like to contribute to this problem! May I take this one @felix-zhe-huang

**Comment by felix-zhe-huang** [comment]
> Hi! I'd like to contribute to this problem! May I take this one @felix-zhe-huang

That will be fantastic! Thank you very much!

**Comment by felix-zhe-huang** [comment]
One more observation, when we use kOps we specify the full FQDN as $CLUSTER_NAME and it works just fine. As long as $CLUSTER_NAME and clusters.cluster.name in .kube/config are consistent we should be fine.

**Comment by StarpTech** [comment]
Hi, I'm a bit lost. This issue is only about local testing right? May it be related to my issue https://github.com/aws/karpenter/issues/1098 ?

**Comment by dbgoytia** [comment]
Hi @felix-zhe-huang, I've been testing this issue for the past couple of days and I'm unable to reproduce it 🤔 maybe I'm doing something wrong?

So after deployment of the cluster using eksctl, I get the following configuration:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: ....
  name: diego-karpenter-demo.us-west-2.eksctl.io
contexts:
- context:
    cluster: diego-karpenter-demo.us-west-2.eksctl.io
    user: user@diego-karpenter-demo.us-west-2.eksctl.io
  name: user@diego-karpenter-demo.us-west-2.eksctl.io
current-context: user@diego-karpenter-demo.us-west-2.eksctl.io
kind: Config
preferences: {}
users:
- name: terraform_user_dev@diego-karpenter-demo.us-west-2.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - diego-karpenter-demo
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: us-west-2
```

and I'm able to run the make commands correctly:

```
$ make apply
> 
...
customresourcedefinition.apiextensions.k8s.io/provisioners.karpenter.sh created
serviceaccount/karpenter created
secret/karpenter-webhook-cert created
configmap/config-logging created
clusterrole.rbac.authorization.k8s.io/karpenter-controller created
clusterrole.rbac.authorization.k8s.io/karpenter-webhook created
clusterrolebinding.rbac.authorization.k8s.io/karpenter-controller created
clusterrolebinding.rbac.authorization.k8s.io/karpenter-webhook created
role.rbac.authorization.k8s.io/karpenter-controller created
role.rbac.authorization.k8s.io/karpenter-webhook created
rolebinding.rbac.authorization.k8s.io/karpenter-controller created
rolebinding.rbac.authorization.k8s.io/karpenter-webhook created
service/karpenter-metrics created
service/karpenter-webhook created
deployment.apps/karpenter-controller created
deployment.apps/karpenter-webhook created
mutatingwebhookconfiguration.admissionregistration.k8s.io/defaulting.webhook.provisioners.karpenter.sh created
validatingwebhookconfiguration.admissionregistration.k8s.io/validation.webhook.provisioners.karpenter.sh created
validatingwebhookconfiguration.admissionregistration.k8s.io/validation.webhook.config.karpenter.sh created
```

Can you help me elaborate a bit further on this? I deployed this cluster using eksctl:

```
❯ eksctl version
0.77.0
```
