### ISSUE TITLE
Name not resolvable inside containers running on instances managed by Karpenter

### ISSUE THREAD

**Issue by clementrey-dev** [aws/karpenter#1082]
## Version

**Karpenter**: v0.5.3

**Kubernetes**: v1.0.0
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

## Expected Behavior
I expected name to be resolvable inside container running on instances managed by karpenter

## Actual Behavior
On container running on instance managed by Karpenter I got  many error such as
`Name or service not known` or `Connection was reset by peer`

## Steps to Reproduce the Problem
Cluster has been provisioned using terraform adapted from [official documentation](https://karpenter.sh/docs/getting-started-with-terraform/)

## Resource Specs and Logs
Provisionner spec
```
apiVersion: "karpenter.sh/v1alpha5"
kind: "Provisioner"
metadata:
  name: "default"
spec:
  requirements:
    - key: "karpenter.sh/capacity-type"
      operator: "In"
      values: ["spot"]
  limits:
    resources:
      cpu: 1000
  provider:
    instanceProfile: "KarpenterNodeInstanceProfile-karpenter-test"
    subnetSelector:
      Name: "*private*"
  ttlSecondsAfterEmpty: 30
```

For example from the logs of my fluentbit container I got the errors:
`net_tcp_fd_connect: getaddrinfo(host='kubernetes.default.svc'): Name or service not known`
or
```
[2022/01/04 19:40:42] [ warn] net_tcp_fd_connect: getaddrinfo(host='logs.eu-west-1.amazonaws.com'): Name or service not known
[2022/01/04 19:40:42] [error] [io_tls] flb_io_tls.c:359 NET - Connection was reset by peer
```

* `logs.eu-west-1.amazonaws.com` is resolvable on the instance managed by karpenter
* Fluentbit is running without any issue on instances not managed by karpenter

Thank you for your help

**Comment by ellistarn** [comment]
Is it possible that nodes in your private subnet do not have network access?
```
    subnetSelector:
      Name: "*private*"
```

**Comment by mikesir87** [comment]
Are you using the VPC CNI? If not, you will need to set the dnsClusterIp for in-cluster name resolution to work.

**Comment by clementrey-dev** [comment]
I finally found the issue, pods could not access to `coredns`. 

The terraform EKS module creates a security group that allows pod to pod communication. By using the `securityGroupSelector` and selecting the SG (created by the terraform EKS module) in the provisioner spec the issue was fixed.

**Comment by ellistarn** [comment]
@geoffcline , can you document this?

**Comment by chrisnegus** [comment]
@mikesir87 I'm trying to document this issue in the Karpenter docs. Could you provide a copy of your provisioner spec that solved this problem?

**Comment by ypicard** [comment]
I am encountering the same issue, and it seems to be related to DNS resolution not working on Karpenter instantiated nodes. If I start `coredns` pods on the Karpenter nodes, it works. @clementrey-dev , could you elaborate on which security group you had to add?

**Comment by lud0v1c** [comment]
> I am encountering the same issue, and it seems to be related to DNS resolution not working on Karpenter instantiated nodes. If I start `coredns` pods on the Karpenter nodes, it works. @clementrey-dev , could you elaborate on which security group you had to add?

Also had this issue. The EKS module-generated SG in question is `eks-cluster-sg-<cluster-name>-123456789`, with the generic description: `EKS created security group applied to ENI that is attached to EKS Control Plane master nodes, as well as any managed workloads.`.

If anyone had similar outbound networking/DNS issues using the EKS module, after some debugging with the Reachability Analyser, I had to modify my default providerRef to specify the cluster's private subnets and that security group:

```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    Name: mycluster-private
    karpenter.sh/discovery: mycluster
  securityGroupSelector:
    Name: eks-cluster-sg-mycluster-123456789
```
Just using the `karpenter.sh/discovery: <cluster-name>` tag was way to broad and so I had two tag the specific subnetwork and use the specific SG.
