### ISSUE TITLE
Tutorial: Karpenter node fails to join cluster 

### ISSUE THREAD

**Issue by StarpTech** [aws/karpenter#1098]
## Version

**Karpenter**: v0.5.3

**Kubernetes**: v1.21.5-eks-bc4871b

## Expected Behavior

The node should join the cluster and be ready.

## Actual Behavior
The node is provisioned but remains with the following taints:

- karpenter.sh/not-ready:NoSchedule
- node.kubernetes.io/not-ready:NoSchedule
- node.kubernetes.io/not-ready:NoExecute

## Steps to Reproduce the Problem
I followed the tutorial https://karpenter.sh/docs/getting-started

EKS cluster:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test
  version: "1.21"
  region: eu-central-1

nodeGroups:
  - name: ng-default
    instanceType: m5.xlarge
    minSize: 1
    maxSize: 10
    desiredCapacity: 2
    volumeSize: 100
    volumeType: gp2
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
```

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m5.xlarge"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
  provider:
    instanceProfile: KarpenterNodeInstanceProfile-test
  ttlSecondsAfterEmpty: 30
```

**Comment by StarpTech** [comment]
Hi, I started from scratch and it's working now. 

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test
  version: "1.21"
  region: eu-central-1

managedNodeGroups:
  - name: test-ng
    instanceType: m5.xlarge
    minSize: 1
    maxSize: 10
    desiredCapacity: 2
    volumeSize: 100
    volumeType: gp2
    iam:
      withAddonPolicies:
        imageBuilder: true
        externalDNS: true
        certManager: true
        ebs: true
        efs: true
        albIngress: true

iam:
  withOIDC: true
```

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m5.xlarge"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
  provider:
    instanceProfile: KarpenterNodeInstanceProfile-test
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 
```
