### ISSUE TITLE
disk size setting

### ISSUE THREAD

**Issue by matti** [aws/karpenter#1100]
**Tell us about your request**
currently karpenter starts nodes with 20gb disk

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I can not specify any other disk size

**Are you currently working around this issue?**
none

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by matti** [comment]
Workaround would be to start maintaining own Launch Template etc, but then whats really the point of using karpenter?

**Comment by ellistarn** [comment]
What do you think about this approach: https://github.com/aws/karpenter/issues/939

**Comment by bwagner5** [comment]
FYI Block Device Mappings configuration has been merged and should be released next week. You can check out the preview docs here: https://karpenter.sh/preview/aws/provisioning/#block-device-mappings

**Comment by blackliner** [comment]
But that is not applicable for the boot EBS, correct?

**Comment by FernandoMiguel** [comment]
@blackliner it applies to any devices you choose to.
Bottlerocket has two volumes, one of 2GiBs (for boot) and one of 20GiBs (for data).
here's ours
```yaml
spec:
  amiFamily: ${amiFamily}
  instanceProfile: ${iam_instance_profile_id}
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        volumeSize: 2Gi
        deleteOnTermination: true
    - deviceName: /dev/xvdb
      ebs:
        volumeType: gp3
        volumeSize: ${volumeSize}
        deleteOnTermination: true
```

sadly none of the docs or examples in https://github.com/aws/karpenter/blob/a844339/examples/provisioner shows this
