### ISSUE TITLE
Failed to find instance type option(s)

### ISSUE THREAD

**Issue by Tasmana-banana** [aws/karpenter#1140]
Hi all!
When apply provisioner and scale test deployment i get some error in logs controller:
```
2022-01-13T21:43:17.290Z	INFO	controller.provisioning	Waiting for unschedulable pods	{"commit": "5047f3c", "provisioner": "default"}
2022-01-13T21:43:19.291Z	INFO	controller.provisioning	Batched 4 pods in 1.001107034s	{"commit": "5047f3c", "provisioner": "default"}
2022-01-13T21:43:19.333Z	ERROR	controller.provisioning	Failed to find instance type option(s) for [default/inflate-6b88c9fb68-8vvs5 default/inflate-6b88c9fb68-22hlt default/inflate-6b88c9fb68-dfzgm default/inflate-6b88c9fb68-ttrhh]	{"commit": "5047f3c", "provisioner": "default"}
```
Use Provisioner:
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["eu-west-2a", "eu-west-2b", "eu-west-2c"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["arm64", "amd64", "x86"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: [ "t2.medium", "t3a.medium", "t3.large"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]
  limits:
    resources:
      cpu: 1000
  provider:
    instanceProfile: dev-eks-20211224135100984100000004
  ttlSecondsAfterEmpty: 30
```
Deploy karpenter chart by ansible:

```
- name: Deploy karpenter chart
  kubernetes.core.helm:
    name: "{{ karpenter_namespace }}"
    create_namespace: true
    release_namespace: "{{ karpenter_namespace }}"
    chart_ref: karpenter/karpenter
    chart_version: 0.5.3
    release_values:
      serviceAccount:
        create: true
        name: karpenter
        annotations:
          eks.amazonaws.com/role-arn: "arn:aws:iam::{{ account_id }}:role/EKS-Karpenter-Role"
      controller:
        clusterName: "{{ cluster_name }}"
        clusterEndpoint: "{{ cluster_endpoint }}"
```
Can u help my?
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
