### ISSUE TITLE
Node not able to Join EKS Cluster via Launch Template

### ISSUE THREAD

**Issue by sandeeplamb** [aws/karpenter#1144]
## Version
Karpenter: v0.5.3
Kubernetes: v1.21.4-eks-033ce7e

## Expected Behavior
Node created via LaunchTemplate should be able to join EKS cluster

## Actual Behavior
I create a new Launch template with custom userdata. When Provisioner is created using the new Launch template, Node never joins the EKS cluster.

When I update the provisioner file with Launch template created by Karpenter, nodes does join the cluster but my custom userdata is not getting used in such case.

I want to use my own Launch Template with my own custom userdata

## Steps to Reproduce the Problem
1. Follow/followed steps here https://karpenter.sh/v0.5.3-docs/getting-started-with-terraform/ 
2. Created new Launch Template as described here https://karpenter.sh/v0.5.3-docs/aws/launch-templates/
3. Updated provisioner with Instance Profile and Launch template
```yaml
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
  namespace: karpenter
spec:
  labels:
    app: inflate
  limits:
    resources:
      cpu: 5k
  provider:
    apiVersion: extensions.karpenter.sh/v1alpha1
    kind: AWS
    instanceProfile: "KarpenterNodeInstanceProfile-CLUSTER_NAME"
    launchTemplate: "Karpenter-CLUSTER_NAME-20220114064918810200000001"
    securityGroupSelector:
      kubernetes.io/cluster/CLUSTER_NAME: '*'
    subnetSelector:
      kubernetes.io/cluster/CLUSTER_NAME: 'shared'
    tags:
      karpenter.sh/cluster/CLUSTER_NAME: "owned"
      kubernetes.io/cluster/CLUSTER_NAME: "owned"
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
      - "spot"
    - key: "kubernetes.io/arch" 
      operator: In
      values: ["amd64"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
  namespace: karpenter
spec:
  replicas: 0
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      serviceAccountName: karpenter
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 1
              memory: 100Mi
            limits:
              memory: 200Mi
      nodeSelector:
        kubernetes.io/arch: "amd64"
        karpenter.sh/capacity-type: "spot"
        app: inflate

```

Terraform code to create launch template
```sh
resource "aws_launch_template" "karpenter_workers_launch_template" {
  name_prefix   = "Karpenter-${var.cluster_name}-"
  image_id      = var.eks_ami_id
  key_name      = "MY_KEY"

  iam_instance_profile {
    name = aws_iam_instance_profile.karpenter.name
  }

  vpc_security_group_ids = flatten([
      var.worker_security_group_id,
      var.worker_additional_security_group_id,
      var.common_sg_id,
    ])

  user_data = base64encode(data.template_file.pre_userdata.rendered)

  block_device_mappings {
    device_name = "/dev/xvda"

    ebs {
      volume_size           = 50
      volume_type           = "gp2"
      encrypted             = true
      kms_key_id            = var.eks_kms_key_arn
      delete_on_termination = true
    }
  }

  tag_specifications {
    resource_type = "instance"
    tags          = merge(
      local.tags,
        {
          "kubernetes.io/cluster/${var.cluster_name}" = "owned",
          "karpenter.sh/cluster/${var.cluster_name}"  = "owned",
        }
      )
  }

  tags =  merge(
    local.tags,
    {
      "kubernetes.io/cluster/${var.cluster_name}" = "owned",
      "karpenter.sh/cluster/${var.cluster_name}"  = "owned",
    }
  )

  lifecycle {
    create_before_destroy = true
  }
}
```

Userdata
```sh
#!/bin/bash -xe
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

# Install CA Certificates
curl --insecure --create-dirs --output /etc/pki/ca-trust/source/anchors/CERTS-BUNDLE.crt https://CERTS
curl --insecure --create-dirs --output /etc/pki/ca-trust/source/anchors/CERTS-_BUNDLE-1.crt https://CERTS

update-ca-trust

# Bootstrap and join the cluster
/etc/eks/bootstrap.sh '${CLUSTER_NAME}' \
  --apiserver-endpoint '${CLUSTER_ENDPOINT}' \
  --container-runtime containerd \
  --b64-cluster-ca '${CLUSTER_AUTH_BASE64}'  \
  --kubelet-extra-args '${KUBELET_EXTRA_TAGS}'

````

## Resource Specs and Logs
Node goes in **NotReady,SchedulingDisabled** state.
Following logs repeats. As new nodes repeats in same way.

```
karpenter-controller-698cb4bc87-hhbdq manager 2022-01-14T11:29:45.079Z	INFO	controller.provisioning	Launched instance: i-00b0029abd90e7cda, hostname: ip-100-73-211-252.eu-west-1.compute.internal, type: c5.2xlarge, zone: eu-west-1b, capacityType: spot	{"commit": "5047f3c", "provisioner": "default"}
karpenter-controller-698cb4bc87-hhbdq manager 2022-01-14T11:29:45.174Z	INFO	controller.provisioning	Bound 5 pod(s) to node ip-100-73-211-252.eu-west-1.compute.internal	{"commit": "5047f3c", "provisioner": "default"}
karpenter-controller-698cb4bc87-hhbdq manager 2022-01-14T11:29:45.174Z	INFO	controller.provisioning	Waiting for unschedulable pods	{"commit": "5047f3c", "provisioner": "default"}
karpenter-controller-698cb4bc87-hhbdq manager 2022-01-14T11:29:57.230Z	INFO	controller.termination	Cordoned node	{"commit": "5047f3c", "node": "ip-100-73-211-252.eu-west-1.compute.internal"}
karpenter-controller-698cb4bc87-hhbdq manager 2022-01-14T11:29:58.020Z	INFO	controller.termination	Deleted node	{"commit": "5047f3c", "node": "ip-100-73-210-5.eu-west-1.compute.internal"}
karpenter-controller-698cb4bc87-hhbdq manager 2022-01-14T11:29:58.543Z	INFO	controller.provisioning	Batched 5 pods in 1.178300445s	{"commit": "5047f3c", "provisioner": "default"}
karpenter-controller-698cb4bc87-hhbdq manager 2022-01-14T11:29:58.693Z	INFO	controller.provisioning	Computed packing of 1 node(s) for 5 pod(s) with instance type option(s) [c1.xlarge c4.2xlarge c3.2xlarge c5a.2xlarge c5ad.2xlarge c6i.2xlarge c5.2xlarge c5d.2xlarge c5n.2xlarge m3.2xlarge m5ad.2xlarge m5d.2xlarge t3.2xlarge m4.2xlarge m5a.2xlarge m5dn.2xlarge m6a.2xlarge m5.2xlarge t3a.2xlarge m6i.2xlarge]	{"commit": "5047f3c", "provisioner": "default"}
```
