### ISSUE TITLE
Question | what are Controller and Webhook? How secret get data from webhook? NodeGroups & Tolerations- v0.5.3

### ISSUE THREAD

**Issue by Izvi-digibank** [aws/karpenter#1164]
Using helm chart v0.5.3. 
I've been trying to understand the differences and purpose of controller and webhook. Each one has its own deployment with own values. 
Haven't found any explanations about these components in the documentation.

Also, in webhook deployment file, the secret creation depends on the webhook; it is being injected by karpenter-webhook:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: karpenter-webhook-cert
  namespace: {{ .Release.Namespace }}
data: {} # Injected by karpenter-webhook
```
I would appreciate a more elaborated explanation about it.

Last question is: If I have a node group that I want Karpenter to observe, do I need to specify the nodeGroup details somewhere? what if there are 3 nodeGroups?

Thanks in advance!!
