### ISSUE TITLE
Options for specifying AWS EC2 fleet allocation strategy

### ISSUE THREAD

**Issue by literalice** [aws/karpenter#1240]
**Tell us about your request**

Adding options for specifying EC2 fleet allocation strategy by users.

Currently it's automatically decided by Karpenter:

* capacity-optimized-prioritized - spot
* lowest-price - on-demand

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Specifying other strategies by users should be useful especially in case of cost-sensitive workloads.
Currently Karpenter has no option for this so what the users only can do is to build their own controller from the source.

**Are you currently working around this issue?**
There is no work around now.

**Additional context**
I posted a PR for this issue: #1238 .
Would you like to use the PR for the basis of discussions.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by suket22** [comment]
I'm removing the launch-templates label. This specific issue is related to how we configure the EC2 Fleet - allocation strategies aren't a part of the EC2 LaunchTemplate itself

**Comment by akestner** [comment]
What other strategies would you want to use in Karpenter? Do you want different ones for both Spot and On-Demand?

**Comment by literalice** [comment]
> What other strategies would you want to use in Karpenter?

We'd like to use the options of FleetAPI:
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/create-fleet.html

We could add the options to `AWSNodeTemplate` API like:

```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector: 
    karpenter.sh/discovery: ex-cluster
  securityGroupSelector:
    karpenter.sh/discovery: ex-cluster
  instanceProfile: MyInstanceProfile
  launchTemplate: MyLaunchTemplate
  onDemandOptions:
    allocationStrategy: prioritized
  spotOptions:
    allocationStrategy: lowest-price
```
