### ISSUE TITLE
Failed to retrieve credentials send request failed by sts.eu-west-1.amazonaws.com

### ISSUE THREAD

**Issue by vara-bonthu** [aws/karpenter#1247]
## Version

**Karpenter**: v0.5.6

**Kubernetes**: v1.2.1

## Expected Behavior

Expected that the nodes to be provisioned successfully by Karpenter Controller using the IAM role attached to the service account(IRSA)

## Actual Behavior

I am getting a following error when using IRSA with `Karpenter Controller` Pods and Launch templates with IAM instance role. IAM role attached to Karpenter Controller Pods has got all the recommended permissions to to talk to EC2 including `ec2.DescribeInstanceTypes`. 

```json
2022-01-30T17:59:36.791Z        ERROR   controller.controller.provisioning      Reconciler error     
   
{"commit": "2346ed5", 
"reconciler group": "karpenter.sh", 
"reconciler kind": "Provisioner", 
"name": "default", "namespace": "", 
"error": "fetching instance types using ec2.DescribeInstanceTypes, 
WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.eu-west-1.amazonaws.com/\": dial tcp: i/o timeout"
}
```

## Steps to Reproduce the Problem

1. Created Karpenter Node IAM role and IAM Instance profile using [this](https://karpenter.sh/v0.5.6/getting-started/cloudformation.yaml) 
2. Deployed Helm Chart v0.5.6 successfully with IAM role for service account (IRSA). IRSA IAM role is different from the above Karpenter node role. Karpenter node IAM Instance profile is used in `values.yaml` under defaults
3. Created a new Launch template using this [doc](https://karpenter.sh/v0.5.6/aws/launch-templates/)
4. Deployed the following provisioner

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["eu-west-1a"]                                  
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
    - key: "node.kubernetes.io/instance-type"                  
      operator: In
      values: ["m5.2xlarge", "m5.4xlarge"]
    - key: "kubernetes.io/arch"                               
      operator: In
      values: ["arm64", "amd64"]
  limits:
    resources:
      cpu: 1000
  provider:
#    instanceProfile: "aws-dev-spark-eks-self-managed-ondemand"     # Conflicts with `launchTemplate` field
    launchTemplate: "karpenter-aws-dev-spark-eks"                                 # Understand that instanceProfile attached to this launch Template will be used by the Nodes created by Karpenter
    subnetSelector:
      Name: "*private*"
    securityGroupSelector:
      kubernetes.io/cluster/aws-dev-spark-eks: owned
  ttlSecondsAfterEmpty: 30
```
5. Deployed new pods and i get the above mentioned error in Actual Behaviour
