### ISSUE TITLE
Add ability to update default node Registry Pull QPS

### ISSUE THREAD

**Issue by hscheib** [aws/karpenter#1269]
**Tell us about your request**
Add the ability to configure the registry pull QPS for a node.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We run Gitlab CI/CD jobs in EKS and Karpenter has done a great job choosing a right sized EC2 instance for the pending pipeline jobs. Some of our pipelines spin up over 50 jobs in parallel. Karpenter will spin up some m5.8xlarge's for example and pods get assigned. Since so many pods are scheduled pulling images, we run into.

```WARNING: Failed to pull image with policy "Always": image pull failed: pull QPS exceeded```

The jobs/pods are not part of a deployment, so the pods are not retried unless we configure each Gitlab pipeline individually to retry on Kubernetes error(not practical as we have 100s). We end up with perfectly scaled large EC2 nodes but then around 20% of the jobs fail due to this error and need to be manually retried in the Gitlab GUI and eventually succeed as a mass amount of images are no longer being pulled.

Using `eksctl` you can [customize]( https://eksctl.io/usage/customizing-the-kubelet/ ) the kubelet for unmanaged nodes and I see you can update the `registryPullQPS` via the config defined [here](https://github.com/weaveworks/eksctl/issues/4518#issuecomment-986519435), so I am interested in similar functionality with Karpenter

**Are you currently working around this issue?**
Yes, we only deploy small EC2 nodes for the relative size jobs we create.(we only use m5.xlarge, and m5.2xlarge instances and spread out very wide, so each node can handle the smaller number of image pulls). No more m5.8xlarge's.

**Additional context**
Anything else we should know?
Using helm chart version `0.5.4`

**Attachments**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
This is great! I wonder if we should just default to something much higher like 110 qps per node (to support unique pods). ECR quota is 2,000/second, so we should have some room. I wonder why pods are failing. Perhaps there's a limit to the number of retries going on? Do you know if there's a way to configure this?

**Comment by hscheib** [comment]
Hi!

The failing Gitlab jobs would log out this:
```
Waiting for pod gitlab/runner-abc123-project-1-concurrent-678def to be running, status is Pending
    ContainersNotReady: "containers with unready status: [build helper svc-0]"
    ContainersNotReady: "containers with unready status: [build helper svc-0]"
WARNING: Failed to pull image with policy "Always": image pull failed: Back-off pulling image "some-image:1.0.0"
ERROR: Job failed: prepare environment: waiting for pod running: pulling image "some-image:1.0.0": image pull failed: Back-off pulling image 
```

There are no retries from Gitlab jobs by default. I need to define a `retry` block in each project's gitlab-ci file to get it to retry on failure, ie:
```
default:
  retry:
    max: 2
    when:
      - script_failure
      - runner_system_failure
```

since we have 100s of projects, It would be much simpler to increase pull limit from a provisioner configuration item, than to update every project with the above block.

**Comment by ellistarn** [comment]
> There are no retries from Gitlab jobs by default. 

I mean pod retry by the kubelet. It should be recoverable since it's a retriable error.

**Comment by hscheib** [comment]
> It should be recoverable since it's a retriable error.

I expected the same thing with that error too. 

We can launch a deployment with 1000 replicas and eventually all 1000 pods are running on the many m5.8xlarges, even if it takes it some time to retry on the QPS threshold. The only thing I could come up with is the Gitlab job is launched as a single pod and is not following the retry logic that it would get if deployed as part of a deployment/replicaset and just fails and Gitlab reports as full job failure. So this request might be more specific to the way these pods are launched?

**Comment by ellistarn** [comment]
Can you provide a full pod spec for a failed pod?

**Comment by hscheib** [comment]
I redacted some env vars
```

  spec:
    affinity: {}
    containers:
    - command:
      - sh
      - -c
      - "if [ -x /usr/local/bin/bash ]; then\n\texec /usr/local/bin/bash \nelif [
        -x /usr/bin/bash ]; then\n\texec /usr/bin/bash \nelif [ -x /bin/bash ]; then\n\texec
        /bin/bash \nelif [ -x /usr/local/bin/sh ]; then\n\texec /usr/local/bin/sh
        \nelif [ -x /usr/bin/sh ]; then\n\texec /usr/bin/sh \nelif [ -x /bin/sh ];
        then\n\texec /bin/sh \nelif [ -x /busybox/sh ]; then\n\texec /busybox/sh \nelse\n\techo
        shell not found\n\texit 1\nfi\n\n"
      env:
      - name: FF_CMD_DISABLE_DELAYED_ERROR_LEVEL_EXPANSION
        value: "false"
      - name: FF_NETWORK_PER_BUILD
        value: "false"
      - name: FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY
        value: "false"
      - name: FF_USE_DIRECT_DOWNLOAD
        value: "true"
      - name: FF_SKIP_NOOP_BUILD_STAGES
        value: "true"
      - name: FF_USE_FASTZIP
        value: "false"
      - name: FF_GITLAB_REGISTRY_HELPER_IMAGE
        value: "true"
      - name: FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR
        value: "false"
      - name: FF_ENABLE_BASH_EXIT_CODE_CHECK
        value: "false"
      - name: FF_USE_WINDOWS_LEGACY_PROCESS_STRATEGY
        value: "true"
      - name: FF_USE_NEW_BASH_EVAL_STRATEGY
        value: "false"
      - name: FF_USE_POWERSHELL_PATH_RESOLVER
        value: "false"
      - name: FF_USE_DYNAMIC_TRACE_FORCE_SEND_INTERVAL
        value: "false"
      - name: FF_SCRIPT_SECTIONS
        value: "false"
      - name: FF_USE_NEW_SHELL_ESCAPE
        value: "false"
      - name: FF_ENABLE_JOB_CLEANUP
        value: "false"
      - name: AWS_DEFAULT_REGION
        value: us-west-2
      - name: AWS_REGION
        value: us-west-2
      - name: AWS_ROLE_ARN
        value: arn:aws:iam::123456789:role/role-name
      - name: AWS_WEB_IDENTITY_TOKEN_FILE
        value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
      image: some-image:some-version
      imagePullPolicy: Always
      name: build
      resources:
        limits:
          cpu: "5"
        requests:
          cpu: "1"
      securityContext:
        capabilities:
          drop:
          - NET_RAW
        privileged: true
      stdin: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /scripts-4-2983904
        name: scripts
      - mountPath: /logs-4-2983904
        name: logs
      - mountPath: /builds
        name: repo
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-8w24n
        readOnly: true
      - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
        name: aws-iam-token
        readOnly: true
    - command:
      - sh
      - -c
      - "if [ -x /usr/local/bin/bash ]; then\n\texec /usr/local/bin/bash \nelif [
        -x /usr/bin/bash ]; then\n\texec /usr/bin/bash \nelif [ -x /bin/bash ]; then\n\texec
        /bin/bash \nelif [ -x /usr/local/bin/sh ]; then\n\texec /usr/local/bin/sh
        \nelif [ -x /usr/bin/sh ]; then\n\texec /usr/bin/sh \nelif [ -x /bin/sh ];
        then\n\texec /bin/sh \nelif [ -x /busybox/sh ]; then\n\texec /busybox/sh \nelse\n\techo
        shell not found\n\texit 1\nfi\n\n"
      env:
      - name: FF_CMD_DISABLE_DELAYED_ERROR_LEVEL_EXPANSION
        value: "false"
      - name: FF_NETWORK_PER_BUILD
        value: "false"
      - name: FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY
        value: "false"
      - name: FF_USE_DIRECT_DOWNLOAD
        value: "true"
      - name: FF_SKIP_NOOP_BUILD_STAGES
        value: "true"
      - name: FF_USE_FASTZIP
        value: "false"
      - name: FF_GITLAB_REGISTRY_HELPER_IMAGE
        value: "true"
      - name: FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR
        value: "false"
      - name: FF_ENABLE_BASH_EXIT_CODE_CHECK
        value: "false"
      - name: FF_USE_WINDOWS_LEGACY_PROCESS_STRATEGY
        value: "true"
      - name: FF_USE_NEW_BASH_EVAL_STRATEGY
        value: "false"
      - name: FF_USE_POWERSHELL_PATH_RESOLVER
        value: "false"
      - name: FF_USE_DYNAMIC_TRACE_FORCE_SEND_INTERVAL
        value: "false"
      - name: FF_SCRIPT_SECTIONS
        value: "false"
      - name: FF_USE_NEW_SHELL_ESCAPE
        value: "false"
      - name: FF_ENABLE_JOB_CLEANUP
        value: "false"
      - name: AWS_DEFAULT_REGION
        value: us-west-2
      - name: AWS_REGION
        value: us-west-2
      - name: AWS_ROLE_ARN
        value: arn:aws:iam::123456789:role/role-name
      - name: AWS_WEB_IDENTITY_TOKEN_FILE
        value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
      image: registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-e0218c92
      imagePullPolicy: Always
      name: helper
      resources:
        limits:
          cpu: "1"
        requests:
          cpu: "1"
      securityContext:
        capabilities:
          drop:
          - NET_RAW
        privileged: true
      stdin: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /scripts-4-2983904
        name: scripts
      - mountPath: /logs-4-2983904
        name: logs
      - mountPath: /builds
        name: repo
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-8w24n
        readOnly: true
      - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
        name: aws-iam-token
        readOnly: true
    - env:
      - name: FF_CMD_DISABLE_DELAYED_ERROR_LEVEL_EXPANSION
        value: "false"
      - name: FF_NETWORK_PER_BUILD
        value: "false"
      - name: FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY
        value: "false"
      - name: FF_USE_DIRECT_DOWNLOAD
        value: "true"
      - name: FF_SKIP_NOOP_BUILD_STAGES
        value: "true"
      - name: FF_USE_FASTZIP
        value: "false"
      - name: FF_GITLAB_REGISTRY_HELPER_IMAGE
        value: "true"
      - name: FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR
        value: "false"
      - name: FF_ENABLE_BASH_EXIT_CODE_CHECK
        value: "false"
      - name: FF_USE_WINDOWS_LEGACY_PROCESS_STRATEGY
        value: "true"
      - name: FF_USE_NEW_BASH_EVAL_STRATEGY
        value: "false"
      - name: FF_USE_POWERSHELL_PATH_RESOLVER
        value: "false"
      - name: FF_USE_DYNAMIC_TRACE_FORCE_SEND_INTERVAL
        value: "false"
      - name: FF_SCRIPT_SECTIONS
        value: "false"
      - name: FF_USE_NEW_SHELL_ESCAPE
        value: "false"
      - name: FF_ENABLE_JOB_CLEANUP
        value: "false"
      - name: AWS_DEFAULT_REGION
        value: us-west-2
      - name: AWS_REGION
        value: us-west-2
      - name: AWS_ROLE_ARN
        value: arn:aws:iam::123456789:role/role-name
      - name: AWS_WEB_IDENTITY_TOKEN_FILE
        value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
      image: some-test-image:2.7.0
      imagePullPolicy: Always
      name: svc-0
      resources:
        limits:
          cpu: "2"
        requests:
          cpu: "1"
      securityContext:
        capabilities:
          drop:
          - NET_RAW
        privileged: true
      stdin: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /scripts-4-2983904
        name: scripts
      - mountPath: /logs-4-2983904
        name: logs
      - mountPath: /builds
        name: repo
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-8w24n
        readOnly: true
      - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
        name: aws-iam-token
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostAliases:
    - hostnames:
      - postgres
      ip: 127.0.0.1
    imagePullSecrets:
    - name: docker-hub-creds
    - name: runner-1aigsdtr-project-4-concurrent-9jkfm9
    initContainers:
    - command:
      - sh
      - -c
      - touch /logs-4-2983904/output.log && (chmod 777 /logs-4-2983904/output.log
        || exit 0)
      env:
      - name: AWS_DEFAULT_REGION
        value: us-west-2
      - name: AWS_REGION
        value: us-west-2
      - name: AWS_ROLE_ARN
        value: arn:aws:iam::123456789:role/role-name
      - name: AWS_WEB_IDENTITY_TOKEN_FILE
        value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
      image: registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-e0218c92
      imagePullPolicy: Always
      name: init-permissions
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /scripts-4-2983904
        name: scripts
      - mountPath: /logs-4-2983904
        name: logs
      - mountPath: /builds
        name: repo
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-8w24n
        readOnly: true
      - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
        name: aws-iam-token
        readOnly: true
    nodeName: ec2IP.region.compute.internal
    nodeSelector:
      gitlab-runner: "true"
      kubernetes.io/arch: amd64
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: gitlab-runner-karpenter-gitlab-runner
    serviceAccountName: gitlab-runner-karpenter-gitlab-runner
    terminationGracePeriodSeconds: 0
    tolerations:
    - effect: NoExecute
      key: gitlab-runner
      operator: Equal
      value: "true"
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: aws-iam-token
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            audience: sts.amazonaws.com
            expirationSeconds: 86400
            path: token
    - emptyDir: {}
      name: repo
    - configMap:
        defaultMode: 511
        name: runner-1aigsdtr-project-4-concurrent-9-scriptsltgps
        optional: false
      name: scripts
    - emptyDir: {}
      name: logs
    - name: kube-api-access-8w24n
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  ```

**Comment by tzneal** [comment]
It looks like GitLab may not be waiting for the image to pull. Perhaps increasing the  GitLab [poll_timeout](https://docs.gitlab.com/runner/executors/kubernetes.html#:~:text=status%20(default%20%3D%203).-,poll_timeout,-The%20amount%20of) would solve it?

> The amount of time, in seconds, that needs to pass before the runner will time out attempting to connect to the container it has just created. Useful for queueing more builds that the cluster can handle at a time (default = 180).

From what I can tell, by default, if the pod takes more than 180 seconds to reach running status, GitLab will declare the job failed with the same error message you received `waiting for pod running`

You can see this in the GitLab K8s runner code [here](https://gitlab.com/gitlab-org/gitlab-runner/-/blob/main/executors/kubernetes/kubernetes.go)

**Comment by vasylenko** [comment]
We faced the same issue, and I can confirm it is the `registryPullQPS` parameter. Unfortunately, kubelet has deprecated its setting as the CLI arg, so there is a workaround by appending that option to the existing `kubelet-config.json`. Still, it's a kind of hotfix rather than a solution.

**Comment by tzneal** [comment]
You can modify this value with custom userdata currently:

```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: kubelet-config-example
spec:
  subnetSelector:
    karpenter.sh/discovery: my-cluster
  securityGroupSelector:
    karpenter.sh/discovery: my-cluster
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"

    --BOUNDARY
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash
    echo "$(jq '.registryPullQPS=50' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json

    --BOUNDARY--
```

**Comment by aaronborden-rivian** [comment]
For GitLab Kubernetes executor, there's an additional workaround to set retries by setting [multiple image pull policies](https://docs.gitlab.com/runner/executors/kubernetes.html#using-pull-policies) e.g. `pull_policy = ["always", "always", "always"]`. Adjusting the registryPullQPS is still the desired fix.

**Comment by tzneal** [comment]
Closing as this can be modified via userdata for both BottleRocket and AL2.  We are trying to minimize the amount of kubelet configuration in the provisioner, limiting it to data that we need for scheduling purposes.

**Comment by tan-wei-xin-alez** [comment]
For those not specifically using karpenter, it's also possible for `eks_managed_node_groups` (the example below is for the case when `ami_id` is not provided)
```
module "eks" {
  source = "terraform-aws-modules/eks/aws"
  version = "19.15.3"
  cluster_name = "my-cluster"
  cluster_version = "0.0.1"
  ...
  eks_managed_node_groups = {
    ...
    gitlab-runners = {
      min_size = 0
      max_size = 10
      desired_size = 1
      instance_types = ["t3.large"]
      labels = {
        Type = "gitlab-runners"
      }
      // https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/user_data.md#eks-managed-node-group
      // https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-user-data
      // set registryPullQPS to zero (i.e. no limit) to prevent "WARNING: Failed to pull image with policy "Always": image pull failed: pull QPS exceeded" error
      pre_bootstrap_user_data = <<-EOF
        MIME-Version: 1.0
        Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="
        --==MYBOUNDARY==
        Content-Type: text/x-shellscript; charset="us-ascii"
        #!/bin/bash
        echo "$(jq '.registryPullQPS=0' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json
        --==MYBOUNDARY==--
      EOF
    }
  }
}
```
you can then check whether the change has taken effect with
```
kubectl proxy & disown && sleep 1; curl -s "http://localhost:8001/api/v1/nodes/<node_name>/proxy/configz" | jq '.kubeletconfig | to_entries[] | select(.key == "registryPullQPS") | "\(.key): \(.value)"'; kill $(ps aux | grep 'kubectl proxy' | head -1 | awk '{print $2}')
```

**Comment by dex4er** [comment]
FYI: for `terraform-aws-modules/eks/aws` it might be stripped to the single line (I guess Karpenter still needs full userdata):

```tf
module "eks" {
  source = "terraform-aws-modules/eks/aws"
  eks_managed_node_groups = {
    gitlab-runners = {
      pre_bootstrap_user_data = <<-EOF
        echo "$(jq '.registryPullQPS=0' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json
        --==MYBOUNDARY==--
      EOF
    }
  }
}
```

**Comment by hjeffries94** [comment]
> You can modify this value with custom userdata currently:
> 
> ```yaml
> apiVersion: karpenter.k8s.aws/v1alpha1
> kind: AWSNodeTemplate
> metadata:
>   name: kubelet-config-example
> spec:
>   subnetSelector:
>     karpenter.sh/discovery: my-cluster
>   securityGroupSelector:
>     karpenter.sh/discovery: my-cluster
>   userData: |
>     MIME-Version: 1.0
>     Content-Type: multipart/mixed; boundary="BOUNDARY"
> 
>     --BOUNDARY
>     Content-Type: text/x-shellscript; charset="us-ascii"
> 
>     #!/bin/bash
>     echo "$(jq '.registryPullQPS=50' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json
> 
>     --BOUNDARY--
> ```

Does anyone know what the formatting of this would be like in TOML for Bottlerocket?

**Comment by dex4er** [comment]
> @hjeffries94 
> Does anyone know what the formatting of this would be like in TOML for Bottlerocket?

Ie.

```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: test
spec:
  amiFamily: Bottlerocket
  userData: |-
    [settings.kubernetes]
    event-qps = 75
    event-burst = 150
    kube-api-qps = 75
    kube-api-burst = 150
    registry-qps = 75
    registry-burst = 150
    [settings.host-containers.admin]
    enabled = true
```

**Comment by flavono123** [comment]
no way for windows node?

**Comment by forsberg** [comment]
For anyone else late to the game, on AL2023 it's pretty simple:

```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: kubelet-config-example
spec:
  ...
  amiFamily: AL2023
  userData: |
    apiVersion: node.eks.aws/v1alpha1
    kind: NodeConfig
    spec:
      kubelet:
        config:
          registryPullQPS: 50
```
