### ISSUE TITLE
Support for topology.kubernetes.io/region

### ISSUE THREAD

**Issue by nonoswz** [aws/karpenter#1298]
## Version

**Karpenter**: v0.6.1

**Kubernetes**: v1.20+

Not sure if this is really a bug or not, but we are hit by this and can't find how to solve this. 

## Expected Behavior

Karpenter is able to use our `default` provisioner to schedule our statefulset as the requested region by the PV is correct (matching the given cluster and available subnets). 

## Actual Behavior

One of our statefulset uses a PVC. The bound PV is having nodeAffinity based on the region (using [failure-domain.beta.kubernetes.io/region](http://failure-domain.beta.kubernetes.io/region)) , we updated Karpenter to 0.6.1 to get it working (after seeing PR #1271) but we bumped into the following issue:
`tried provisioner/default: incompatible requirements, invalid value: require values for key topology.kubernetes.io/region but is not defined`

In order to define a value for the region, I tried to add the following to our `default` provisioner as it should support the [Well Known Labels](https://karpenter.sh/v0.6.1/provisioner/#specrequirements). The provisioner is saved but discards the region block. 
````
  - key: topology.kubernetes.io/region
    operator: In
    values:
    - us-east-1
````
We saw [here](https://karpenter.sh/v0.6.1/tasks/scheduling/) that region might not be supported. Is there a config change I can do to get it working? If not and If it is due to the non-support of region, is it possible to get a fix to support the region? 

## Steps to Reproduce the Problem

1. Create a statefulset with a PV (we are using zookeeper)
2. The PV should have a nodeAffinity with `failure-domain.beta.kubernetes.io/region`
3. Get Karpenter to schedule this statefulset 

## Resource Specs and Logs

Logs
````
2022-02-08T20:05:35.263Z	DEBUG	controller.selection	Could not schedule pod, matched 0/3 provisioners, tried provisioner/default: incompatible requirements, invalid value: require values for key topology.kubernetes.io/region but is not defined: requirements[6].key; tried provisioner/prometheus: did not tolerate dedicated=prometheus:NoSchedule; tried provisioner/tidb: did not tolerate dedicated=tidb:NoSchedule	{"commit": "xxxxx", "pod": "zk-regional/zk-regional-3"}
````

Pod Spec (relevant part)
````
spec:
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: zk-regional-3
  nodeSelector:
    group: default
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  serviceAccount: default
  serviceAccountName: default
  subdomain: zk-regional
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  topologySpreadConstraints:
  - labelSelector:
      matchExpressions:
      - key: app
        operator: In
        values:
        - zk-regional
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
  - labelSelector:
      matchExpressions:
      - key: app
        operator: In
        values:
        - zk-regional
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
  volumes:
  - name: datadir
    persistentVolumeClaim:
      claimName: *************
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-02-08T00:02:58Z"
    message: '0/17 nodes are available: 1 node(s) had taint {dedicated: ******},
      that the pod didn''t tolerate, 10 Insufficient cpu, 6 node(s) were unschedulable.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable
````

PV spec
````
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: *******
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: *******
    namespace: ******
    resourceVersion: "48950"
    uid: ********
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - us-east-1
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - us-east-1b
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2-encrypted
  volumeMode: Filesystem
status:
  phase: Bound
````

Provisioner spec (I replaced few values by <prefix_name>)
````
spec:
  kubeletConfiguration: {}
  labels:
    group: default
  limits: {}
  provider:
    apiVersion: extensions.karpenter.sh/v1alpha1
    instanceProfile: <our_instance_profile_name>
    kind: AWS
    launchTemplate: <our_launch_template_name>
    securityGroupSelector:
      kubernetes.io/cluster/<cluster_name>: '*'
    subnetSelector:
      Name: '*private*'
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - m5.4xlarge
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - us-east-1a
    - us-east-1b
    - us-east-1c
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 86400
````

Thanks
