### ISSUE TITLE
(request): Pausing and resuming provisioners feature

### ISSUE THREAD

**Issue by robertd** [aws/karpenter#1315]
**Tell us about your request**

Is it possible to pause provisioners? i.e. Have them created but in a state that is not being picked up by Karpenter?

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

If we're having a cluster that is being used by different groups. We would like to tailor Provisioners according to group's needs. It would be great if cluster admin could "pause" provisioners (rather than destroying them and re-applying them) so that user's only option would be to use whatever `default` provisioner is set for until cluster admin re-enables their dedicated provisioner (if there is `default` provisioner at all).

It could be in a form of an annotation flag or something.

Hope this makes sense. 😄 

**Are you currently working around this issue?**

N/A

**Additional context**

N/A

**Attachments**

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by robertd** [comment]
@felix-zhe-huang  After reading the docs... Is this maybe doable using `taints`?

```
  # Provisioned nodes will have these taints
  # Taints may prevent pods from scheduling if they are not tolerated
  taints:
    - key: example.com/special-taint
      effect: NoSchedule
```
