### ISSUE TITLE
Bare metal instance type is not supported

### ISSUE THREAD

**Issue by khoa-hatch** [aws/karpenter#1336]
## Version

**Karpenter**: v0.6.1

**Kubernetes**: v1.21.5 (EKS)

## Expected Behavior

Karpenter should support provision bare metal ec2 instances.
We need bare metal instance in order to use `/dev/kvm` to create virtual machine.
Kubernetes run perfectly fine with bare metal instances not sure why they are filtered out here: 
https://github.com/aws/karpenter/blob/main/pkg/cloudprovider/aws/instancetypes.go#L166

## Actual Behavior

Karpenter doesn't support bare metal instances

## Steps to Reproduce the Problem

1. Create a provisioner with spec
```
spec:
  kubeletConfiguration: {}
  limits: {}
  provider:
    apiVersion: extensions.karpenter.sh/v1alpha1
    instanceProfile: ""
    kind: AWS
    securityGroupSelector:
      kubernetes.io/cluster/******: owned
    subnetSelector:
      kubernetes.io/cluster/*********: shared
  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - m6g.metal
    - c6g.metal
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: kubernetes.io/arch
    operator: In
    values:
    - arm64
  ttlSecondsAfterEmpty: 3
```
2. Create a pod with nodeSelector:
```
  nodeSelector:
    kubernetes.io/arch: arm64
    node.kubernetes.io/instance-type: m6g.metal
```

3. No `m6g.metal` or `c6g.metal` instances provisioned and Karpenter controller errors:
```
ERROR   controller.controller.provisioning        Reconciler error        {"commit": "df57892", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner", "name": "stream", "namespace": "", "error": "validating requirements, invalid value: no feasible value for node.kubernetes.io/instance-type: values"}
```
