### ISSUE TITLE
MountVolume.SetUp failed for volume "docker-sock"

### ISSUE THREAD

**Issue by Izvi-digibank** [aws/karpenter#1337]
Karpenter is not able to mount volume. Fails with the following error:

```
MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed │
│ : /var/run/docker.sock is not a socket file
```

New nodes are coming up, on Ready state but pod are failed when they use volumes.

Is there a possibility to define container runtime through the provisioner?

**Comment by suket22** [comment]
> Is there a possibility to define container runtime through the provisioner?

Not yet. If I'm [reading this right](https://github.com/aws/karpenter/blob/main/pkg/cloudprovider/aws/launchtemplate.go#L320) Karpenter always uses containerd unless there were GPU requirements. 

Could you give me your provisionerSpec and what your podSpec look like so I can reproduce?

**Comment by Izvi-digibank** [comment]
@suket22 Thanks, I'm not using docker in docker. Here is my provisioner:

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: workflows-provisioner
spec:
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["m5.xlarge"]
  provider:
    subnetSelector: 
      Name: dev01-eks-private
    securityGroupSelector: 
      aws:eks:cluster-name: workflows
  ttlSecondsAfterEmpty: 600
```

Pod Spec: (Note the volume.hostPath , it is `/var/run/docker.sock`)

```
spec:
  containers:
  - command:
    - argoexec
    - wait
    - --loglevel
    - info
    env:
    - name: ARGO_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: ARGO_CONTAINER_RUNTIME_EXECUTOR
    - name: GODEBUG
      value: x509ignoreCN=0
    - name: ARGO_CONTAINER_NAME
      value: wait
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    image: argoproj/argoexec:v3.1.13
    imagePullPolicy: IfNotPresent
    name: wait
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /argo/podmetadata
      name: podmetadata
    - mountPath: /var/run/docker.sock
      name: docker-sock
      readOnly: true
    - mountPath: /argo/secret/github-rs
      name: github-rs
      readOnly: true
    - mountPath: /mainctrfs/apps
      name: input-artifacts
      subPath: apps
    - mountPath: /mainctrfs/argo/staging
      name: argo-staging
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-fvfxp
      readOnly: true
  - args:
    - /argo/staging/script
    command:
    - bash
    env:
    - name: GIT_USER
      valueFrom:
        secretKeyRef:
          key: username
          name: github-rs
    - name: GIT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: github-rs
    - name: ARGO_CONTAINER_NAME
      value: main
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    image: ghcr.io/digibank-il/argo-ubuntu
    imagePullPolicy: Always
    name: main
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /apps
      name: input-artifacts
      subPath: apps
    - mountPath: /argo/staging
      name: argo-staging
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-fvfxp
      readOnly: true
    workingDir: /apps
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: ghcr-secret
  - name: fdb-dockerhub-pullsecret
  initContainers:
  - command:
    - argoexec
    - init
    - --loglevel
    - info
    env:
    - name: ARGO_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: ARGO_CONTAINER_RUNTIME_EXECUTOR
    - name: GODEBUG
      value: x509ignoreCN=0
    - name: ARGO_CONTAINER_NAME
      value: init
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    image: argoproj/argoexec:v3.1.13
    imagePullPolicy: IfNotPresent
    name: init
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /argo/podmetadata
      name: podmetadata
    - mountPath: /argo/secret/github-rs
      name: github-rs
      readOnly: true
    - mountPath: /argo/inputs/artifacts
      name: input-artifacts
    - mountPath: /argo/staging
      name: argo-staging
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-fvfxp
      readOnly: true
  nodeName: ip-172-31-11-204.eu-west-1.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: podmetadata
  - hostPath:
      path: /var/run/docker.sock
      type: Socket
    name: docker-sock
  - name: github-rs
    secret:
      defaultMode: 420
      items:
      - key: username
        path: username
      - key: password
        path: password
      secretName: github-rs
  - emptyDir: {}
    name: input-artifacts
  - emptyDir: {}
    name: argo-staging
  - name: kube-api-access-fvfxp
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
```



@ellistarn 
Is Karpenter using `containerd://x.x.x` as default for container runtime? if yes then why?
Is creating and defining a launch template the only way to set the value `docker` in `container runtime`?
Is there a way to define AMI version from the provisioner?

**Comment by suket22** [comment]
> Is Karpenter using containerd://x.x.x as default for container runtime? if yes then why?

Yes. This is the general direction in the Kubernetes community so we're adopting it as well. If you're looking to use Docker, you'd need to use a custom launch template. Karpenter will only support containerd by default. 

> Is there a way to define AMI version from the provisioner?

Currently Karpenter always picks up the latest AMI ID, but we do intend to have this inlined in the provisioner one day. For your podSpec you're likely going to need a launch template in any case (to select the container runtime) so you can set the AMI Id in the launch template.

**Comment by Izvi-digibank** [comment]
@suket22 Thanks again, I created a launch template with AMI version which used to be on my node group before I involved Karpenter- ami-06efe6b9d402e8674 (1.21.5-20211206)

Now the following is happening: 

`2022-02-15T16:51:03.113Z	DEBUG	controller.selection	Could not schedule pod, matched 0/1 provisioners, tried provisioner/workflows-provisioner: invalid nodeSelector "topology.kubernetes.io/region", [eu-west-1] not in []{"commit": "2346ed5", "pod": "argo-events/my-pod-097da59b7j68-3484880711"}`

provisioner:

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: workflows-provisioner
spec:
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["m5.xlarge"]
  limits:
    resources:
      cpu: 1000
  provider:
    launchTemplate: my-launch-template
    subnetSelector: 
      Name: dev01-eks-private
    securityGroupSelector: 
      aws:eks:cluster-name: workflows
  ttlSecondsAfterEmpty: 600
```

Also, now even DaemonSet pods are failing to schedule:

` Warning  FailedScheduling  11s (x2 over 13s)  default-scheduler  0/17 nodes are available: 10 node(s) were unschedulable, 2 node(s) had taint {tools: basictools}, that the pod didn't tolerate, 5 node(s) had taint {workflowType: e2eTests}, that the pod didn't tolerate.`
