### ISSUE TITLE
Created nodes are missing Karpenter label karpenter.sh/provisioner-name

### ISSUE THREAD

**Issue by nonoswz** [aws/karpenter#1380]
## Version

**Karpenter**: v0.6.3

**Kubernetes**: v1.20

## Expected Behavior

All nodes created by Karpenter should have the Karpenter label `karpenter.sh/provisioner-name` to be managed by Karpenter.

## Actual Behavior

Couple of nodes created by one of our provisioner are missing following Karpenter labels:
````
karpenter.sh/capacity-type: on-demand
karpenter.sh/provisioner-name: prometheus 
````

As they are missing the `karpenter.sh/provisioner-name` label, they are not managed by Karpenter later on. We can see from the AWS console that those nodes were created by Karpenter. 

We believe what happened is that Karpenter pod (controller/webhook) got killed at the same time (or just after) it was creating those nodes, and when Karpenter got running again, it then lost the information that those nodes were created. We were performing the switch from ASG node groups to Karpenter node groups in one environment and Karpenter was not yet placed on a dedicated node, so it got killed when we brought all the ASG to 0.  

It would be great if Karpenter would be able to label those nodes later on. Let's say if every 5/10 minutes, Karpenter would lookup in AWS if there is any node that ended up in that situation, and if it is the case, Karpenter would label them again. 

## Steps to Reproduce the Problem

- Scale a workload to make Karpenter create new nodes
- Kill Karpenter pod after Karpenter launched the new instances, but the nodes are not yet `Ready`
- When nodes get `Ready`, they will not be labeled by Karpenter

## Resource Specs and Logs

Node labels 
````
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    projectcalico.org/IPv4Address: 10.146.41.35/21
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2022-02-17T21:45:42Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: r5.16xlarge
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: us-west-2
    failure-domain.beta.kubernetes.io/zone: us-west-2b
    group: prometheus
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: ip-10-146-41-35.us-west-2.compute.internal
    kubernetes.io/os: linux
    node.kubernetes.io/instance-type: r5.16xlarge
    topology.kubernetes.io/region: us-west-2
    topology.kubernetes.io/zone: us-west-2b
````

Provisioner spec
````
spec:
  kubeletConfiguration: {}
  labels:
    group: prometheus
  limits: {}
  provider:
    apiVersion: extensions.karpenter.sh/v1alpha1
    kind: AWS
    launchTemplate: ****************
    subnetSelector:
      Name: ********
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - r5.16xlarge
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - us-west-2a
    - us-west-2b
    - us-west-2c
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  taints:
  - effect: NoSchedule
    key: dedicated
    value: prometheus
  ttlSecondsAfterEmpty: 30
````

AWS Console with the given node
![image](https://user-images.githubusercontent.com/58952992/154724921-5f868d58-8154-4182-b9de-542c0175b04b.png)
