### ISSUE TITLE
Auto ALB Target Group registration

### ISSUE THREAD

**Issue by albertjunkim** [aws/karpenter#1381]
**Tell us about your request**
What do you want us to build?

- When a Karpenter node is provisioned, the controller will register a node to the given Target group ARNs in the provisioned.
- This is to support NGINX Ingress Controller on Karpenter nodes.

```
labels:
  ...
providers: 
  targetGroupARNs: ["arn:aws:elasticloadbalancing:us-east-1:...:targetgroup/..."]

```

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

- While ASG can register its nodes to the ELB Target groups automatically by given Target Group ARN (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#target_group_arns), 
Karpenter nodes do not have this capability.  It does not make sense to manually register them since these nodes are dynamic. 

**Are you currently working around this issue?**
How are you currently solving this problem?

- We guide users to use the ALB Controller instead of NGINX. However, there are still use cases for using NGINX ingress instead of ALB Controller 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Karpenter is intentionally not aware of load balancer solutions. I'd recommend using another controller that watches for nodes to come online and registers them with the load balancer.

**Comment by mikestef9** [comment]
This is worth looking at 

https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/targetgroupbinding/targetgroupbinding/

**Comment by ellistarn** [comment]
This should work beautifully!

**Comment by adiii717** [comment]
> This is worth looking at
> 
> https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/targetgroupbinding/targetgroupbinding/

facing a similar issue with the Nginx ingress controller, is there any workaround for the Nginx ingress controller? The above only works for ALB controllers.

**Comment by mballoni** [comment]
@adiii717 whats your issue specifically? I'm facing some inter node communication with nginx controller and I suspect I may have the same problem.

**Comment by adiii717** [comment]
@mballoni Actually  Nginx ingress controller does not work with karpenter, Karpenter uses group less autoscaling (note a node group actually), to resolve this we just moved to ALB controllers with `ingress-group` which is new feature of v2, so that we can use single load balancer as an entry-point as we have ingress controller 
This is how my initial ingress look like

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: {{ quote .Values.scheme }}
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-path: "/healthz"
    alb.ingress.kubernetes.io/group.name: alb-ingress-{{ .Values.scheme }}
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: {{ quote .Values.certificate_arn }}
    alb.ingress.kubernetes.io/success-codes: "200,404"
    alb.ingress.kubernetes.io/load-balancer-name: {{ quote .Values.load_balancer_name }}
    alb.ingress.kubernetes.io/tags: Environment={{ .Values.environment }},ManagedBy=alb-controllers
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ quote .Values.wafv2_acl_arn }}
  labels:
    {{- include "initial-ingress.labels" . | nindent 4 }}
  name:  {{ include "initial-ingress.fullname" . }}
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: {{ include "initial-ingress.fullname" . }}-default-svc
      port:
        number: {{ .Values.service.port }}
```
