### ISSUE TITLE
Discuss defaulting behavior

### ISSUE THREAD

**Issue by ellistarn** [aws/karpenter#1449]
**Tell us about your request**

I created a simple provisioner:
```
  spec:
    provider:
      securityGroupSelector:
        kubernetes.io/cluster/etarn: '*'
      subnetSelector:
        kubernetes.io/cluster/etarn: '*'
    ttlSecondsAfterEmpty: 360
```
Here's what I got:
```
  spec:
    kubeletConfiguration: {}
    provider:
      amiFamily: AL2
      apiVersion: extensions.karpenter.sh/v1alpha1
      kind: AWS
      securityGroupSelector:
        kubernetes.io/cluster/etarn: '*'
      subnetSelector:
        kubernetes.io/cluster/etarn: '*'
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.sh/capacity-type
      operator: In
      values:
      - on-demand
    ttlSecondsAfterEmpty: 360
```
Here's what I'm not sure about:
- `amiFamily: AL2`should probably default in memory, rather than defaulting into the spec. This allows the user to be unaware of Karpenter's default, should it change over time. By not specifying AMIFamily, I'm really saying that I don't care.
- `kubeletConfiguration: {}` should be omitted, since we use `omitempty`. It's not clear why this is persisted. 
- `apiVersion: extensions.karpenter.sh/v1alpha1, kind: AWS`. This feels really crufty. It would be great if we modeled this with a separate vendor specific CRD. This is a breaking change and a good candidate for https://github.com/aws/karpenter/issues/1327

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
