### ISSUE TITLE
Pod Antiaffinity Feature

### ISSUE THREAD

**Issue by amitdrana** [aws/karpenter#1481]
Hi Team, 
 IS Karpenter supports the Pod anti-affinity feature as we are using it for our application deployment.
 also, we are using nodeAffinity with the following match expression.
 Not able to set  `node.kubernetes.io/role` label on the pod. any other way I can use this?
```
 nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/role
                operator: In
                values:
                - ToolsOnDemand
```
