### ISSUE TITLE
grafana and prometheus-values broken for v0.6.5

### ISSUE THREAD

**Issue by cryptomacma** [aws/karpenter#1502]
## Version

**Karpenter**: v0.6.5

**Kubernetes**: v1.21

## Expected Behavior

the grafana dashboard can display pod and node metrics correctly
## Actual Behavior

the metrics don't display
## Steps to Reproduce the Problem

follow all steps from the get started page
## solution:
grafana-values.yaml: update last 4 lines:
```
    pod-dashboard:
      url: https://karpenter.sh/preview/getting-started/getting-started-with-eksctl/karpenter-pod-metrics.json
    node-dashboard:
      url: https://karpenter.sh/preview/getting-started/getting-started-with-eksctl/karpenter-node-metrics.json
```
prometheus-values.yaml: update last one line:
```
        - karpenter.karpenter:8080
 ```
