### ISSUE TITLE
Make templates/deployment.yaml env variables to be optional

### ISSUE THREAD

**Issue by psidza** [aws/karpenter#1539]
**Tell us about your request**
Make templates/deployment.yaml env variables for controller and webhook containers optional, like you already did for AWS_DEFAULT_INSTANCE_PROFILE.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'm using Terraform to create my EKS cluster, and ArgoCD to deploy Karpenter. 
CLUSTER_NAME and CLUSTER_ENDPOINT values needs to be passed somehow to ArgoCD, so i decided pulling them from config map created by terraform.
I've added this to values.yaml in for both containers, and it's pulling these values correctly.
```
  env:
    - name: CLUSTER_NAME
      valueFrom:
        configMapKeyRef:
          name: karpenter-aws-parameters
          key: CLUSTER_NAME
    - name: CLUSTER_ENDPOINT
      valueFrom:
        configMapKeyRef:
          name: karpenter-aws-parameters
          key: CLUSTER_ENDPOINT
    - name: AWS_DEFAULT_INSTANCE_PROFILE
      valueFrom:
        configMapKeyRef:
          name: karpenter-aws-parameters
          key: AWS_DEFAULT_INSTANCE_PROFILE
```

Since CLUSTER_NAME and CLUSTER_ENDPOINT are already defined in deployment.yaml, i'm getting a conflict.
`The order in patch list: [map[name:CLUSTER_NAME value:<nil>] map[name:CLUSTER_NAME valueFrom:map[configMapKeyRef:map[key:CLUSTER_NAME name:karpenter-aws-parameters]]] map[name:CLUSTER_ENDPOINT value:<nil>] map[name:CLUSTER_ENDPOINT valueFrom:map[configMapKeyRef:map[key:CLUSTER_ENDPOINT name:karpenter-aws-parameters]]]] doesn't match $setElementOrder list: [map[name:CLUSTER_NAME] map[name:KUBERNETES_MIN_VERSION] map[name:CLUSTER_ENDPOINT] map[name:KARPENTER_SERVICE] map[name:SYSTEM_NAMESPACE] map[name:CLUSTER_NAME] map[name:CLUSTER_ENDPOINT] map[name:AWS_DEFAULT_INSTANCE_PROFILE]]`

I found a solution for it, but it requires a template modification. 
In order to make chart updates easier, it would be nice to get some solution implemented in your future release.

**Are you currently working around this issue?**
By adding if statements within deployment.yaml template around env variables that i'd like to override. 
```
env:
  {{- if .Values.clusterName }}
  - name: CLUSTER_NAME
    value: {{ .Values.clusterName }}
  {{- end }}
  {{- if .Values.clusterEndpoint }}
  - name: CLUSTER_ENDPOINT
    value: {{ .Values.clusterEndpoint }}
  {{- end }}
```
**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
