### ISSUE TITLE
Provisioner is creating some arm64 nodes even with kubernetes.io/arch in  ["amd64"] requirement

### ISSUE THREAD

**Issue by armujahid** [aws/karpenter#1540]
## Version

**Karpenter**: v0.7.1

**Kubernetes**: v1.2.1
Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

## Expected Behavior
karpenter should only provision amd64 nodes since it's mentioned in provisioner requirements.

## Actual Behavior
karpenter is adding some arm64 nodes that are causing "standard_init_linux.go:228: exec user process caused: exec format error" for some pods because of architecture incompatibility.
Also 
`k get nodes -l kubernetes.io/arch=arm64` is returning some nodes created by karpenter 

## Steps to Reproduce the Problem
1) create eks cluster using https://karpenter.sh/v0.7.1/getting-started/getting-started-with-eksctl/
2) apply this provisioner
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
  limits:
    resources:
      cpu: 1000
  provider:
    subnetSelector:
      karpenter.sh/discovery: ${CLUSTER_NAME}
    securityGroupSelector:
      # karpenter.sh/discovery returns multiple security groups which cause conflict with ingress controller
      # karpenter.sh/discovery: ${CLUSTER_NAME}
      kubernetes.io/cluster/${CLUSTER_NAME}: owned
  ttlSecondsAfterEmpty: 30
```
3) Run some pods to force karpenter to add nodes. 

## Resource Specs and Logs
Will add later. Provisioner spec is already provided.

**Comment by dewjam** [comment]
Hey @armujahid I'm trying to reproduce this now.  In the meantime, can you share some details about your cluster?  

Is this a new cluster you've built just for testing out Karpenter?  Or is this an existing cluster with other workloads?

Can you enable debug logging and supply some logs showing this?

**Comment by dewjam** [comment]
Hey @armujahid I am able to reproduce the problem in my test cluster.  From what we can tell v0.7.1 is not filtering out instance types based on architecture when identifying feasible instance type options.  

Here's an example log from v0.6.5 showing instance type options:
```
2022-03-18T19:49:16.111Z	INFO	controller.provisioning	Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [m1.small m1.medium m3.medium c1.medium t3a.small t3.small c4.large c3.large c6a.large c5.large t3a.medium c5d.large t3.medium c5ad.large c6i.large c5a.large c5n.large m3.large]	{"commit": "7b5afee", "provisioner": "default"}

```

Here's an example log from v0.7.1 with same workload and provisioner spec:
```
2022-03-18T19:33:45.888Z	INFO	controller.provisioning	Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [m1.small c6g.medium a1.medium c6gd.medium c6gn.medium m1.medium m3.medium m6g.medium m6gd.medium r6g.medium r6gd.medium c1.medium t3a.small t3.small t4g.small c4.large c3.large]	{"commit": "4b14787", "provisioner": "default"}
```
(notice the graviton instances are in the list)

We are working on a fix for this now.  Thank you for bringing this issue to our attention!

**Comment by dewjam** [comment]
As a note, you can temporarily work around this by manually specifying instance types in the Provider spec.  Such as:
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  ttlSecondsAfterEmpty: 60
  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values: ["c5.large", "c5.xlarge"]
```
