### ISSUE TITLE
Support for capacity-type as TopologyKey in TopologySpreadConstraint

### ISSUE THREAD

**Issue by cdharma** [aws/karpenter#1557]
**Tell us about your request**
Support for capacity-type as TopologyKey in TopologySpreadConstraint

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
It would be great if deployments could spread across capacity type (spot, on-demand) using topology constraint. It will allow to deployment accross capacity types evenly. It will also help in avoiding any interruptions because of SPOT. For example, a deployment with 10 replicas will run 5 pods on spot and 5 pods on on-demand nodes. 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 10
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "karpenter.sh/capacity-type"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: inflate
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 1 
```

**Are you currently working around this issue?**
No work around.

**Additional context**

**Attachments**
Error message from karpenter controller log : 
```
2022-03-22T10:37:11.149Z	ERROR	controller.selection	Ignoring pod, unsupported topology key, karpenter.sh/capacity-type not in map[kubernetes.io/hostname:{} topology.kubernetes.io/zone:{}]	{"commit": "c9e015e", "pod": "default/inflate-859f896c66-swdpm"}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
We've talked about something similar here. https://github.com/aws/karpenter/issues/331. The latest thinking is that we want to do a KEP that enables 
```
topologySpreadConstraints:
- maxSkew: 1
  topologyKey: "karpenter.sh/capacity-type"
  domains:
    "Spot": 5
    "Ondemand": 1
```

This would enable arbitrary weighting.
