### ISSUE TITLE
containerd by default doesn't work

### ISSUE THREAD

**Issue by pymag09** [aws/karpenter#1585]
## Version

**Karpenter**: v0.7.3

**Kubernetes**: v1.21.0

## Expected Behavior

I expect karpenter uses containerd as a default CRI. 
## Actual Behavior

For some reason it creates docker node instead of containerd.
## Steps to Reproduce the Problem

I have no idea how to reproduce the issue. I definitely do not want to use custom launch Template. I just want to know under what circumstances karpenter make a decission to use docker instaed of containerd
## Resource Specs and Logs

Provisioner:

```
spec:
  kubeletConfiguration: {}
  labels:
    purpose: monitoring
  limits:
    resources:
      cpu: 10k
  provider:
    amiFamily: AL2
    apiVersion: extensions.karpenter.sh/v1alpha1
    kind: AWS
    securityGroupSelector:
      Name: bla-bla
    subnetSelector:
      karpenter.sh/discovery: bla-bla
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - c5a.4xlarge
        - c5a.2xlarge
        - c5a.xlarge
        - c5a.large
        - t3a.2xlarge
        - t3a.xlarge
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
  taints:
    - effect: NoSchedule
      key: monitoring
  ttlSecondsAfterEmpty: 30
```
