### ISSUE TITLE
Karpenter exceeding memory limits

### ISSUE THREAD

**Issue by bwmetcalf** [aws/karpenter#1730]
## Version
**Karpenter**: v0.7.2
**Kubernetes**: v1.22

## Expected Behavior
Karpenter would refuse to provision a new node based on memory limit of 50Gi

## Actual Behavior
Karpenter exceeds memory limit
```
spec:
  kubeletConfiguration: {}
  limits:
    resources:
      memory: 50Gi
...
status:
  resources:
    cpu: "18"
    memory: 70537628Ki
```
