### ISSUE TITLE
taints dont work as expected

### ISSUE THREAD

**Issue by trondhindenes** [aws/karpenter#1735]
## Version
**Karpenter**: v0.90.0
**Kubernetes**: v1.21.0

## Expected Behavior
the example should work

## Actual Behavior
Using the example from the doc does not work:

provisioner:
```
  taints:
  - key: nvidia.com/gpu
    value: "true"  # value is a string and not a bool like the doc indicates
    effect: "NoSchedule"
```
deployment:
```
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
```

## Steps to Reproduce the Problem
Use the example for the documentation, karpenter controller logs:
```
Could not schedule pod, matched 0/1 provisioners, tried provisioner/default: did not tolerate nvidia.com/gpu=true:NoSchedule
```

it looks to me like only taints without `value` set will work, which is just a subset of the taint/toleration spec in Kubernetes
This combination of provisioner and toleration works:
provisioner:
```
  taints:
  - key: nvidia.com/gpu
    effect: "NoSchedule"
```
deployment:
```
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
```

**Comment by tzneal** [comment]
I can't reproduce this locally.  Using a provisioner with this taint:

```
  taints:
  - effect: NoSchedule
    key: nvidia.com/gpu
    value: "true"
```

Scaling this deployment caused a node to be launched:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate-nvidia
spec:
  replicas: 0
  selector:
    matchLabels:
      app: inflate-nvidia
  template:
    metadata:
      labels:
        app: inflate-nvidia
    spec:
      terminationGracePeriodSeconds: 0
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: "true"
      containers:
        - name: inflate-nvidia
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 1
            limits:
              nvidia.com/gpu: 1
```

I tested separately with an alternate toleration, which worked as well:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate-nvidia
spec:
  replicas: 0
  selector:
    matchLabels:
      app: inflate-nvidia
  template:
    metadata:
      labels:
        app: inflate-nvidia
    spec:
      terminationGracePeriodSeconds: 0
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      containers:
        - name: inflate-nvidia
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 1
            limits:
              nvidia.com/gpu: 1
```
I submitted a PR to fix the docs issue.

Can you provide the provisioner spec and deployment YAML that you expect to work, but which aren't?
