### ISSUE TITLE
Provisioner name not showing in EC2 instance tags

### ISSUE THREAD

**Issue by evandam** [aws/karpenter#1766]
## Version

**Karpenter**: v0.9.1

**Kubernetes**: v1.22 (EKS)

## Expected Behavior
EC2 Instances provisioned with Karpenter are created with the tags as documented in https://karpenter.sh/v0.9.1/aws/provisioning/#tags. Same goes for the EBS volumes created.

Hoping I'm just missing something obvious in the docs but it doesn't seem like it.

```
Name: karpenter.sh/provisioner/test
karpenter.sh/provisioner-name: test
```

## Actual Behavior

EC2 Instance tags:

```
Name: karpenter.sh/provisioner/
karpenter.sh/provisioner-name: ""
```

## Steps to Reproduce the Problem

Installed Karpenter Helm chart via Terraform:

```hcl
resource "helm_release" "karpenter" {
  name       = "karpenter"
  repository = "https://charts.karpenter.sh"
  chart      = "karpenter"
  version    = "0.9.1"

  namespace        = "karpenter"
  create_namespace = true

  reuse_values = false
  reset_values = false
  force_update = false
  recreate_pods = false

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${var.cluster_name}_eks_karpenter"
  }

  set {
    name  = "clusterName"
    value = var.cluster_name
  }

  set {
    name  = "clusterEndpoint"
    value = data.aws_eks_cluster.test.endpoint
  }

  set {
    name  = "aws.defaultInstanceProfile"
    value = "test_eks_karpenter"
  }

  set {
    name  = "logLevel"
    value = "info"
  }
}
```

## Resource Specs and Logs

Provisioner is almost exactly as seen in https://karpenter.sh/v0.9.1/provisioner/

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: test
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: topology.kubernetes.io/zone
      operator: In
      values: ["us-west-2a", "us-west-2b", "us-west-2c"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["t3.medium", "t3a.medium"]
  limits:
    resources:
      memory: 10Gi
  provider:
    subnetSelector:
      karpenter.sh/discovery: test
    securityGroupSelector:
      karpenter.sh/discovery: test
    tags:
      karpenter.sh/discovery: test
      terraform: "false"
  ttlSecondsAfterEmpty: 30
```

No errors in controller logs:

```
2022-05-05T00:52:01.045Z	INFO	controller	Batched 1 pod(s) in 1.000648877s	{"commit": "a7e26e6"}
2022-05-05T00:52:04.110Z	INFO	controller	Launched instance: i-0c3162a914f0e04b6, hostname: ip-10-62-37-98.us-west-2.compute.internal, type: t3.medium, zone: us-west-2c, capacityType: spot	{"commit": "a7e26e6", "provisioner": "test"}
2022-05-05T00:52:04.147Z	INFO	controller	Created node with 1 pods requesting {"cpu":"1155m","memory":"622880Ki","pods":"6"} from types t3.medium, t3a.medium	{"commit": "a7e26e6", "provisioner": "test"}
2022-05-05T00:52:04.180Z	INFO	controller	Waiting for unschedulable pods	{"commit": "a7e26e6"}
```
