### ISSUE TITLE
Karpenter 0.9.1 not assigning value for tag "karpenter.sh/provisioner-name"

### ISSUE THREAD

**Issue by ssro** [aws/karpenter#1778]
## Version

**Karpenter**: v0.9.1

**Kubernetes**: v1.22.6-eks

## Expected Behavior
Karpenter should assing the default provisioner's name for `karpenter.sh/provisioner-name` tag

In version 0.9.1 this tag is empty
## Actual Behavior
In karpenter 0.9.0 after configuring and applying any provisioner, the tag `karpenter.sh/provisioner-name`, which was applied to the instances after launch had the value of the provisoner name, for example `karpenter.sh/provisioner-name: default`.

## Steps to Reproduce the Problem
Downgrade karpenter to version 0.9.0, create a provisioner (named default in this case) and launch a deployment which in turn will trigger the provisioner. The tag `karpenter.sh/provisioner-name` is set and has the value of the provisioner's name

Upgrade to 0.9.1 and trigger an instance launch (using the same provisioner which was applied above). The tag `karpenter.sh/provisioner-name` will have no value

## Resource Specs and Logs

karpenter provisioner yaml:

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  taints:
    - key: example.com/reserved
      effect: NoSchedule
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["c5a.xlarge"] # 4cpu
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["ap-southeast-1a", "ap-southeast-1b", "ap-southeast-1c"]
    - key: "example.com/reserved"
      operator: In
      values: ["true"]
  limits:
    resources:
      cpu: 10
  provider:
    subnetSelector:
      karpenter.sh/discovery: dev
    securityGroupSelector:
      karpenter.sh/discovery: dev
    tags:
      karpenter.sh/discovery: dev
  ttlSecondsAfterEmpty: 30
```

Pod yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: inflate
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: inflate
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: example.com/reserved
                operator: In
                values:
                - "true"
      containers:
      - image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
        imagePullPolicy: IfNotPresent
        name: inflate
        resources:
          requests:
            cpu: "3"
      tolerations:
      - effect: NoSchedule
        key: exaqmple.com/reserved
        operator: Exists
```

<img width="835" alt="v0 9 0" src="https://user-images.githubusercontent.com/13402690/167303052-43500742-0f25-42a3-a358-7ffd2ea800b7.png">
<img width="830" alt="v0 9 1" src="https://user-images.githubusercontent.com/13402690/167303056-ed84ecae-b62f-43b3-b586-81f1fdf4f12e.png">

Karpenter logs for v0.9.0 and v0.9.1

[v0.9.0.txt](https://github.com/aws/karpenter/files/8647232/v0.9.0.txt)

[v0.9.1.txt](https://github.com/aws/karpenter/files/8647233/v0.9.1.txt)
