### ISSUE TITLE
Incorrect resource provisioning using podAntiAffinity

### ISSUE THREAD

**Issue by edijsdrezovs** [aws/karpenter#1794]
## Version
**Karpenter**:v0.10.0
**Kubernetes**: v1.0.0

## Expected Behavior
When using `podAntiAffinity` with topologyKey `kubernetes.io/hostname` when I'm adding let's say 3 additional replicas carpenter provisions node with resources to fit for all 3 new pods instead of provisioning 3 additional nodes
```
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: test
          topologyKey: kubernetes.io/hostname
```

```
    resources:
      limits:
        cpu: "16"
        memory: 32Gi
      requests:
        cpu: "15"
        memory: 30Gi
```

## Actual Behavior
Provisioning 3 additional nodes instead with resources to fit all pending pods

## Resource Specs and Logs
```
2022-05-11T09:27:19.103Z	INFO	controller	Created node with 3 pods requesting {"cpu":"45125m","memory":"90Gi","pods":"5"} from types c5a.16xlarge, c6a.16xlarge, c5.18xlarge, c5ad.16xlarge, c5d.18xlarge and 89 other(s)	{"commit": "00661aa", "provisioner": "ondemand"}
```

**Comment by tzneal** [comment]
Can you provide the entire deployment that you are using?

**Comment by tzneal** [comment]
I'm having trouble reproducing this. I'm running v0.10.0 and applied your deployment, I then scaled it to 3 and then 6 replicas before the first three nodes were ready.  I waited till those six nodes were ready and scaled again to 10 replicas.  It launched a new node each time.


I left the invalid image name in the deployment which caused the image pull errors: 
```log
test-65f9594fd5-77hrw   0/1     ErrImagePull       0          2m52s   192.168.145.160   ip-192-168-141-238.us-west-2.compute.internal   <none>           <none>
test-65f9594fd5-7fdxh   0/1     ImagePullBackOff   0          84s     192.168.33.230    ip-192-168-39-11.us-west-2.compute.internal     <none>           <none>
test-65f9594fd5-fbp2k   0/1     ImagePullBackOff   0          2m52s   192.168.132.11    ip-192-168-130-29.us-west-2.compute.internal    <none>           <none>
test-65f9594fd5-glrmj   0/1     ImagePullBackOff   0          2m43s   192.168.145.161   ip-192-168-151-87.us-west-2.compute.internal    <none>           <none>
test-65f9594fd5-hhxbf   0/1     ImagePullBackOff   0          84s     192.168.35.165    ip-192-168-53-109.us-west-2.compute.internal    <none>           <none>
test-65f9594fd5-krtq6   0/1     ImagePullBackOff   0          84s     192.168.57.122    ip-192-168-54-146.us-west-2.compute.internal    <none>           <none>
test-65f9594fd5-lnfmk   0/1     ImagePullBackOff   0          3m4s    192.168.102.225   ip-192-168-111-189.us-west-2.compute.internal   <none>           <none>
test-65f9594fd5-sh7z7   0/1     ImagePullBackOff   0          84s     192.168.22.45     ip-192-168-13-244.us-west-2.compute.internal    <none>           <none>
test-65f9594fd5-sqzpc   0/1     ImagePullBackOff   0          2m43s   192.168.71.35     ip-192-168-73-225.us-west-2.compute.internal    <none>           <none>
test-65f9594fd5-sxvlk   0/1     ImagePullBackOff   0          2m43s   192.168.131.241   ip-192-168-133-128.us-west-2.compute.internal   <none>           <none>
```

**Comment by edijsdrezovs** [comment]
Can you share your provisioner config @tzneal ?

**Comment by tzneal** [comment]
Sure, it's:

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
spec:
  limits:
    resources:
      cpu: 5k
  provider:
    amiFamily: AL2
    apiVersion: extensions.karpenter.sh/v1alpha1
    kind: AWS
    securityGroupSelector:
      karpenter.sh/discovery: tnealt-karpenter-demo
    subnetSelector:
      karpenter.sh/discovery: tnealt-karpenter-demo
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - us-west-2a
    - us-west-2b
    - us-west-2c
    - us-west-2d
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  ttlSecondsAfterEmpty: 30
```
