### ISSUE TITLE
label domain node.kubernetes.io not permitted

### ISSUE THREAD

**Issue by universam1** [aws/karpenter#1802]
## Version

**Karpenter**: v0.10.0

**Kubernetes**: v1.21.9-eks-14c7a48

## Expected Behavior
We need to set the label `node.kubernetes.io/node-group` on nodes to mark pod affinity. We have other node labels in use such as `node.kubernetes.io/lifecycle`or `node.kubernetes.io/class` as well.
For now we are setting those labels in user-data of the launch-template, however we cannot migrate to Karpenter since this part is taken over but not supported.

It is not logical to restrict such labels to be used in Karpenter - where else should they be set then?

## Actual Behavior
This label domain is restricted, erroring out:
```
ERROR webhook Failed the resource specific validation {"commit": "00661aa", "knative.dev/kind": "karpenter.sh/v1alpha5, Kind=Provisioner", "knative.dev/namespace": "", "knative.dev/name": "default-spot", "knative.dev/operation": "CREATE", "knative.dev/resource": "karpenter.sh/v1alpha5, Resource=provisioners", "knative.dev/subresource": "", "error": "invalid key name \"node.kubernetes.io/node-group\": spec.labels\nlabel domain not allowed, node.kubernetes.io"} 
```

## Steps to Reproduce the Problem
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  labels:
    node.kubernetes.io/node-group: primary
```
