### ISSUE TITLE
Can the Provisioner ignore a deployment pod and terminate nodes with the correct labels?

### ISSUE THREAD

**Issue by patricktalmeida** [aws/karpenter#1824]
My situation is:

I want the Provisioner to ignore a given Deployment when **deprovisioning** nodes. 
Just like it ignores DaemonSets I want to tell it to ignore pods from a Deployment when **deprovisioning** nodes and just kill the node.

Is this possible in any version right now? 
If it is, could someone help me with examples?

**Comment by suket22** [comment]
Are you looking for this to speed up the scale down times? That's not something you can do today so I'm curious what your use case is

**Comment by patricktalmeida** [comment]
> Are you looking for this to speed up the scale down times? That's not something you can do today so I'm curious what your use case is

I can say that would be something like speeding up scale down. 
But in my case I have to deal with an application (badly architected) that is a deployment (because it receives and processes requests) which has this `podAntiAffinity`:

```
affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - '{{.Values.APP_NAME}}'
            topologyKey: kubernetes.io/hostname
```
            
 So, the deployment gets updated according to the amount of nodes that the cluster has. 
 
In this case, if somehow the cluster scales up because of any other reason and after sometime it should scale down, it just won't because pods of this Deployment will be there even if not needed.
 
 I know I could just set a lower `ttlSecondsUntilExpired` and the pods are going to rearrange themselves inside the existing nodes, but I don't want to be rotating nodes so frequently (right now `ttlSecondsUntilExpired` is set to 15 days).
 
 Thanks for the answer on not being possible to just "ignore" a Deployment, I'll probably need to wait the nodes rotation for a proper scale down or find another way to solve this issue with this badly architected application.
