### ISSUE TITLE
Unable to use pod affinity with architecture topology key "kubernetes.io/arch"

### ISSUE THREAD

**Issue by jbouricius** [aws/karpenter#1863]
## Version

**Karpenter**: v0.10.1

**Kubernetes**: v1.19

## Expected Behavior

I am trying to use pod affinity to enforce all pods in a given namespace run in the same AWS Availability Zone and on the same Architecture. In practice my pods are a Spark driver and executors, so inter-AZ transfer costs are prohibitive, and Spark has some low-level memory optimizations which means mixing architectures among the pods will cause jobs to fail. The key here is that to maximize VM availability, I do not care which zone or architecture is used, only that all pods have the same ones.

## Actual Behavior

When I configure a podSpec with an affinity using the topologyKey "kubernetes.io/arch" Karpenter does not launch any nodes, or even recognize the pods. There are no logs in the controller. With the topologyKey "topology.kubernetes.io/zone" the pods are launched successfully.

## Steps to Reproduce the Problem

This is my deployment spec:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "inflate-deployment"
  namespace: "inflate-ns"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "TESTING-KARPENTER"
  template:
    metadata:
      labels:
        app: "TESTING-KARPENTER"
      name: "inflate"
      namespace: "inflate-ns"
    spec:
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 1
      schedulerName: "my-scheduler"
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: "TESTING-KARPENTER"
              topologyKey: "topology.kubernetes.io/zone"
            # - labelSelector:
            #     matchLabels:
            #       app: "TESTING-KARPENTER"
            #   topologyKey: "kubernetes.io/arch"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: "TESTING-KARPENTER"
              topologyKey: "kubernetes.io/hostname"
```

Note the commented out section using the arch key "kubernetes.io/arch". With that section commented out, the Karpenter controller finds pods and schedules them, and because of the pod affinity using key "topology.kubernetes.io/zone", the pods are in the same zone as expected/desired. When the section containing the arch key is uncommented, the Karpenter controller will not recognize the pods as unschedulable, in fact it produces no logs at all.

## Resource Specs and Logs

This is my provisioner spec, of course with dummy values for my other cloud resources like the node profile and security groups.

```
cat <<EOF | kubectl apply -f -
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64", "arm64"]
    - key: topology.kubernetes.io/zone
      operator: In
      values: ["us-east-1a", "us-east-1b", "us-east-1c", "us-east-1d", "us-east-1f"]
  limits:
    resources:
      cpu: 1000
  provider:
    instanceProfile: my-karpenter-profile
    subnetSelector:
      karpenter.sh/discovery: my-cluster
    securityGroupSelector:
      karpenter.sh/discovery: my-cluster
  ttlSecondsAfterEmpty: 30
EOF
```

Thanks in advance for any help looking into this!
