### ISSUE TITLE
Question: quickstarting GPU workers?

### ISSUE THREAD

**Issue by BrewedCoffee** [aws/karpenter#1895]
Hello! Apologies if this is a trivial question, but I was wondering if it would be possible to add a GPU provider/deployment example, having some trouble getting off the ground. 

I want to deploy something capable of [this](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html), eventually moving on past testing to serve custom Docker applications (that require GPUs).

Uncertain if I need to supply a custom launch template or how to configure new nodes to come pre-installed with NVIDIA plug-ins.

Here is the relevant snippet of my (Terraform) configuration (I've skipped using different providers w/ taints at the moment):

```
resource "kubectl_manifest" "karpenter_provisioner" {
  yaml_body = <<-YAML
  apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: default
  spec:
    requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot"]
      - key: node.kubernetes.io/instance-type
        operator: In
        values: ["p3.8xlarge", "p3.16xlarge", "t3.2xlarge"]
    limits:
      resources:
        # nvidia.com/gpu: 10 #currently not supported
        cpu: 1000
    provider:
      subnetSelector:
        karpenter.sh/discovery: ${local.name}
      securityGroupSelector:
        karpenter.sh/discovery: ${local.name}
      tags:
        karpenter.sh/discovery: ${local.name}
    ttlSecondsAfterEmpty: 30
  YAML

  depends_on = [
    helm_release.karpenter
  ]
}

# Example deployment based off of [this PR](https://github.com/aws/karpenter/pull/1476) (I see there are some comments about not having the nvidia plugin pre-installed?)
# and starts with zero replicas
resource "kubectl_manifest" "gpu_deploy" {
  yaml_body = <<-YAML
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: gpu-test
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: gpu-test
    template:
      metadata:
        labels:
          app: gpu-test
      spec:
        containers:
          - name: gpu-test
            image: nvcr.io/nvidia/cuda:10.1-base-ubuntu18.04
            command: [ "/bin/bash", "-c", "--" ]
            args: [ "while true; do nvidia-smi; sleep 5; done;" ]
            resources:
              limits:
                nvidia.com/gpu: 1
  YAML

  depends_on = [
    helm_release.karpenter
  ]
}

# Example deployment using the [pause image](https://www.ianlewis.org/en/almighty-pause-container)
# and starts with zero replicas
resource "kubectl_manifest" "cpu_deploy" {
  yaml_body = <<-YAML
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: inflate
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: inflate
    template:
      metadata:
        labels:
          app: inflate
      spec:
        # nodeSelector:
        #   node.kubernetes.io/instance-type: m5.large
        terminationGracePeriodSeconds: 0
        containers:
          - name: inflate
            image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
            resources:
              requests:
                cpu: 1
  YAML

  depends_on = [
    helm_release.karpenter
  ]
}
```

When attempting to deploy `inflate` or `gpu-test` containers with
`kubectl scale deployment gpu-test --replicas 1`,

this returns the error 
```
2022-06-03T20:44:40.840Z        ERROR   controller.provisioning Launching node, creating cloud provider machine, with fleet error(s), UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.   {"commit": "c115db3", "provisioner": "default"}
```

This is not a spot instance availability issue, as our service quota is set well above our 0 usage.

I see there is a workload manifest example at the bottom of [this page](https://karpenter.sh/v0.6.1/aws/provisioning/#accelerators-gpu), but nothing for the provider/making sure they come with prerequisite device plugins.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
