### ISSUE TITLE
c5.18xlarge is not being created

### ISSUE THREAD

**Issue by aabed** [aws/karpenter#1898]
## Expected Behavior
A new node is created

## Actual Behavior
controller 2022-06-04T23:46:15.075Z      ERROR   controller      no instance type satisfied resources {"cpu":"60","memory":"125Gi","pods":"1"} and requirements topology.kubernetes.io/zone In [us-west-2a us-west-2b], kubernetes.io/hostname In [hostname-placeholder-4354], kubernetes.io/os In [linux], karpenter.sh/capacity-type In [on-demand spot], kubernetes.io/arch In [amd64], node.kubernetes.io/instance-type In [c5.18xlarge c5.xlarge t3a.large], karpenter.sh/provisioner-name In [default]  

## Steps to Reproduce the Problem

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3a.large", "c5.xlarge", "c5.18xlarge"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot","on-demand"]
  limits:
    resources:
      cpu: 1000
  provider:
    securityGroupSelector:
      Name: k8s-0-node
    subnetSelector:
      Name: k8s-0-private
  ttlSecondsAfterEmpty: 30
```

Regardless of the fact that the pods can fit on c5.18xlarge, I still get the above error

**Comment by dewjam** [comment]
Hello @aabed ,
Just to be thorough, can you provide the resource requests/limits for the DaemonSets we expect to be running on this node?

```
k get ds -A --output=jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.spec.template.spec.containers[].resources}{"\n"}'
```

**Comment by BrewedCoffee** [comment]
I have a similar issue with a slightly different message, here is my output for the above command:

```
aws-node        {"requests":{"cpu":"25m"}}
kube-proxy      {"requests":{"cpu":"100m"}}
nvidia-device-plugin-daemonset  {}
```

ERROR:
```
no instance type satisfied resources {"cpu":"1","pods":"1"} and requirements kubernetes.io/os In [linux], karpenter.sh/capacity-type DoesNotExist [], karpenter.sh/provisioner-name In [default], kubernetes.io/hostname In [hostname-placeholder-0705], node.kubernetes.io/instance-type In [a1.2xlarge a1.4xlarge a1.large a1.medium a1.metal and 534 others], topology.kubernetes.io/zone In [us-west-2a us-west-2b us-west-2c], kubernetes.io/arch In [amd64]   {"commit": "10fc37b", "pod": "default/inflate-6b88c9fb68-89tx6"}
```
PROVIDER:
```
apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: default
  spec:
    requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["t3.medium", "g5.xlarge", "g5.2xlarge", "p3.2xlarge", "p3.4xlarge", "p3.8xlarge"]
    limits:
      resources:
        cpu: 1000
        memory: 1000Gi
    provider:
      subnetSelector:
        karpenter.sh/discovery: ${local.name}
      securityGroupSelector:
        karpenter.sh/discovery: ${local.name}
      tags:
        karpenter.sh/discovery: ${local.name}
    ttlSecondsAfterEmpty: 10
```
