### ISSUE TITLE
draining karpenter-provisioned node resulted in another karpenter-provisioned node while capacity is available in a managed eks nodegroup

### ISSUE THREAD

**Issue by dmitry-mightydevops** [aws/karpenter#1950]
## Version

**Karpenter**: v0.10.0

**Kubernetes**: Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

## Expected Behavior

I have spot eks managed node group "apps" with label "apps=true"
AWS terminates spot node
AWS node termination handler makes immediate node drain and all pods targeted with nodeSelector apps=true get pending status
AWS Karpenter Kicks in
5m later spot eks managed node group "apps"  gets new node in READY state
I want to stop manually the karpenter provisioner node and do this:
`k drain --delete-emptydir-data --ignore-daemonsets -l karpenter.sh/provisioner-name=apps`

I expect the node to be drained all pods relocated to eks managed node group "apps"

## Actual Behavior
Another karpenter node started with provisioner, however I have available capacity in a new node added by eks managed node group.

## Steps to Reproduce the Problem
**provisioner:**
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: apps
spec:
  labels:
    apps: "true"
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["m5.large", "t3.large"]
    - key: topology.kubernetes.io/zone
      operator: In
      values: ["us-east-1a", "us-east-1b", "us-east-1c"]
  limits:
    resources:
      cpu: '5'
  provider:
    subnetSelector:
      karpenter.sh/discovery: prod-eks
    securityGroupSelector:
      karpenter.sh/discovery: prod-eks
    tags:
      karpenter.sh/discovery: prod-eks
      terraform: "false"
      karpenter: "true"
      managed_by: "karpenter"
      environment: "prod"
      karpenter.sh/cluster/prod-eks: owned
      kubernetes.io/cluster/prod-eks: owned
  ttlSecondsAfterEmpty: 300
```
