### ISSUE TITLE
Calculated available memory does not fit

### ISSUE THREAD

**Issue by mKeRix** [aws/karpenter#1959]
## Version

**Karpenter**: v0.11.1

**Kubernetes**: v1.22.9-eks-a64ea69

## Expected Behavior

Karpenter scales up an EC2 instance that can fit the pod requests into its allocatable memory.

## Actual Behavior

Karpenter spins up an EC2 instance without enough allocatable memory, leading the pod to be in Pending state forever. This will also cause some node churn, as Karpenter keeps spinning up new nodes when the in-flight capacity does not work out. This seems to happen when the memory requests are close to a certain edge, such as in the example deployment below. In our case this led to Karpenter provisioning a c5n.xlarge instance over and over, with the affected pod never coming up.

The allocatable memory of the node after it is spun up is reported as `8739468Ki` (`8949215232` bytes), while Karpenter is scheduling for a workload of `9037933121` bytes.

We think this might be an issue related to how Karpenter calculates the allocatable memory when scheduling without ENI based pod density (i.e. 110 max pods for all instance types), as it looks like the overhead is always calculated based on the ENI numbers currently.

## Steps to Reproduce the Problem

1. Run Karpenter with `AWS_ENI_LIMITED_POD_DENSITY` set to `false`.
2. Configure the provisoner as shown below.
3. Create the deployment.
4. Observe Karpenter trying to spin up c5n.xlarge. (The mismatch between calculated and real allocatable memory should be present on all node types though.)

## Resource Specs and Logs

Note that I included our full provisioner spec - it may not be reproducible as is on a fresh cluster as we use IPv6 and Cilium.

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  kubeletConfiguration:
    clusterDNS:
      - fdac:2175:8016::a
  limits:
    resources:
      cpu: 1k
  provider:
    amiFamily: Bottlerocket
    blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          deleteOnTermination: true
          encrypted: true
          volumeSize: 2G
          volumeType: gp3
      - deviceName: /dev/xvdb
        ebs:
          deleteOnTermination: true
          encrypted: true
          volumeSize: 25G
          volumeType: gp3
    securityGroupSelector:
      karpenter.sh/discovery: terratest-u1q5gG
    subnetSelector:
      karpenter.sh/discovery: terratest-u1q5gG
      kubernetes.io/role/internal-elb: '1'
    tags:
      karpenter.sh/discovery: terratest-u1q5gG
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - spot
        - on-demand
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
        - arm64
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - a1.2xlarge
        - a1.4xlarge
        - a1.xlarge
        - c5.12xlarge
        - c5.18xlarge
        - c5.24xlarge
        - c5.2xlarge
        - c5.4xlarge
        - c5.9xlarge
        - c5.xlarge
        - c5a.12xlarge
        - c5a.16xlarge
        - c5a.24xlarge
        - c5a.2xlarge
        - c5a.4xlarge
        - c5a.8xlarge
        - c5a.xlarge
        - c5ad.12xlarge
        - c5ad.16xlarge
        - c5ad.24xlarge
        - c5ad.2xlarge
        - c5ad.4xlarge
        - c5ad.8xlarge
        - c5ad.xlarge
        - c5d.12xlarge
        - c5d.18xlarge
        - c5d.24xlarge
        - c5d.2xlarge
        - c5d.4xlarge
        - c5d.9xlarge
        - c5d.xlarge
        - c5n.18xlarge
        - c5n.2xlarge
        - c5n.4xlarge
        - c5n.9xlarge
        - c5n.xlarge
        - c6a.12xlarge
        - c6a.16xlarge
        - c6a.24xlarge
        - c6a.2xlarge
        - c6a.32xlarge
        - c6a.4xlarge
        - c6a.8xlarge
        - c6a.xlarge
        - c6g.12xlarge
        - c6g.16xlarge
        - c6g.2xlarge
        - c6g.4xlarge
        - c6g.8xlarge
        - c6g.xlarge
        - c6gd.12xlarge
        - c6gd.16xlarge
        - c6gd.2xlarge
        - c6gd.4xlarge
        - c6gd.8xlarge
        - c6gd.xlarge
        - c6gn.12xlarge
        - c6gn.16xlarge
        - c6gn.2xlarge
        - c6gn.4xlarge
        - c6gn.8xlarge
        - c6gn.xlarge
        - c6i.12xlarge
        - c6i.16xlarge
        - c6i.24xlarge
        - c6i.2xlarge
        - c6i.32xlarge
        - c6i.4xlarge
        - c6i.8xlarge
        - c6i.xlarge
        - d3.2xlarge
        - d3.4xlarge
        - d3.8xlarge
        - d3.xlarge
        - g4ad.16xlarge
        - g4ad.2xlarge
        - g4ad.4xlarge
        - g4ad.8xlarge
        - g4ad.xlarge
        - g4dn.12xlarge
        - g4dn.16xlarge
        - g4dn.2xlarge
        - g4dn.4xlarge
        - g4dn.8xlarge
        - g4dn.xlarge
        - i3en.12xlarge
        - i3en.24xlarge
        - i3en.2xlarge
        - i3en.3xlarge
        - i3en.6xlarge
        - i3en.xlarge
        - inf1.24xlarge
        - inf1.2xlarge
        - inf1.6xlarge
        - inf1.xlarge
        - m5.12xlarge
        - m5.16xlarge
        - m5.24xlarge
        - m5.2xlarge
        - m5.4xlarge
        - m5.8xlarge
        - m5.xlarge
        - m5a.12xlarge
        - m5a.16xlarge
        - m5a.24xlarge
        - m5a.2xlarge
        - m5a.4xlarge
        - m5a.8xlarge
        - m5a.xlarge
        - m5ad.12xlarge
        - m5ad.16xlarge
        - m5ad.24xlarge
        - m5ad.2xlarge
        - m5ad.4xlarge
        - m5ad.8xlarge
        - m5ad.xlarge
        - m5d.12xlarge
        - m5d.16xlarge
        - m5d.24xlarge
        - m5d.2xlarge
        - m5d.4xlarge
        - m5d.8xlarge
        - m5d.xlarge
        - m5dn.12xlarge
        - m5dn.16xlarge
        - m5dn.24xlarge
        - m5dn.2xlarge
        - m5dn.4xlarge
        - m5dn.8xlarge
        - m5dn.xlarge
        - m5n.12xlarge
        - m5n.16xlarge
        - m5n.24xlarge
        - m5n.2xlarge
        - m5n.4xlarge
        - m5n.8xlarge
        - m5n.xlarge
        - m5zn.12xlarge
        - m5zn.2xlarge
        - m5zn.3xlarge
        - m5zn.6xlarge
        - m5zn.xlarge
        - m6a.12xlarge
        - m6a.16xlarge
        - m6a.24xlarge
        - m6a.2xlarge
        - m6a.32xlarge
        - m6a.4xlarge
        - m6a.8xlarge
        - m6a.xlarge
        - m6g.12xlarge
        - m6g.16xlarge
        - m6g.2xlarge
        - m6g.4xlarge
        - m6g.8xlarge
        - m6g.xlarge
        - m6gd.12xlarge
        - m6gd.16xlarge
        - m6gd.2xlarge
        - m6gd.4xlarge
        - m6gd.8xlarge
        - m6gd.xlarge
        - m6i.12xlarge
        - m6i.16xlarge
        - m6i.24xlarge
        - m6i.2xlarge
        - m6i.32xlarge
        - m6i.4xlarge
        - m6i.8xlarge
        - m6i.xlarge
        - p4d.24xlarge
        - r5.12xlarge
        - r5.16xlarge
        - r5.24xlarge
        - r5.2xlarge
        - r5.4xlarge
        - r5.8xlarge
        - r5.xlarge
        - r5a.12xlarge
        - r5a.16xlarge
        - r5a.24xlarge
        - r5a.2xlarge
        - r5a.4xlarge
        - r5a.8xlarge
        - r5a.xlarge
        - r5ad.12xlarge
        - r5ad.16xlarge
        - r5ad.24xlarge
        - r5ad.2xlarge
        - r5ad.4xlarge
        - r5ad.8xlarge
        - r5ad.xlarge
        - r5b.12xlarge
        - r5b.16xlarge
        - r5b.24xlarge
        - r5b.2xlarge
        - r5b.4xlarge
        - r5b.8xlarge
        - r5b.xlarge
        - r5d.12xlarge
        - r5d.16xlarge
        - r5d.24xlarge
        - r5d.2xlarge
        - r5d.4xlarge
        - r5d.8xlarge
        - r5d.xlarge
        - r5dn.12xlarge
        - r5dn.16xlarge
        - r5dn.24xlarge
        - r5dn.2xlarge
        - r5dn.4xlarge
        - r5dn.8xlarge
        - r5dn.xlarge
        - r5n.12xlarge
        - r5n.16xlarge
        - r5n.24xlarge
        - r5n.2xlarge
        - r5n.4xlarge
        - r5n.8xlarge
        - r5n.xlarge
        - r6g.12xlarge
        - r6g.16xlarge
        - r6g.2xlarge
        - r6g.4xlarge
        - r6g.8xlarge
        - r6g.xlarge
        - r6gd.12xlarge
        - r6gd.16xlarge
        - r6gd.2xlarge
        - r6gd.4xlarge
        - r6gd.8xlarge
        - r6gd.xlarge
        - t3.2xlarge
        - t3.xlarge
        - t3a.2xlarge
        - t3a.xlarge
        - t4g.2xlarge
        - t4g.xlarge
        - x2idn.16xlarge
        - x2idn.24xlarge
        - x2idn.32xlarge
        - x2iedn.16xlarge
        - x2iedn.24xlarge
        - x2iedn.2xlarge
        - x2iedn.32xlarge
        - x2iedn.4xlarge
        - x2iedn.8xlarge
        - x2iedn.xlarge
        - z1d.12xlarge
        - z1d.2xlarge
        - z1d.3xlarge
        - z1d.6xlarge
        - z1d.xlarge
  startupTaints:
    - effect: NoExecute
      key: node.cilium.io/agent-not-ready
      value: 'true'
  ttlSecondsAfterEmpty: 60
  ttlSecondsUntilExpired: 604800
```

The `nodeSelector` here helps make it reproducible, the same issue can happen without it depending on availability of instance types.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
  namespace: inflate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        node.kubernetes.io/instance-type: c5n.xlarge
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 224m
              memory: 8791517761
            limits:
              cpu: 1120m
              memory: 17403035522
```

```console
2022-06-21T06:39:33.966Z	INFO	controller.provisioning	Computed 1 new node(s) will fit 1 pod(s)	{"commit": "eb05b1e"}
2022-06-21T06:39:33.966Z	INFO	controller.provisioning	Computed 1 unready node(s) will fit 1 pod(s)	{"commit": "eb05b1e"}
2022-06-21T06:39:35.864Z	INFO	controller.provisioning.cloudprovider	Launched instance: i-0964f0c8513910555, hostname: ip-172-16-61-152.eu-central-1.compute.internal, type: c5n.xlarge, zone: eu-central-1a, capacityType: spot	{"commit": "eb05b1e", "provisioner": "default"}
2022-06-21T06:39:35.890Z	INFO	controller.provisioning	Created node with 1 pods requesting {"cpu":"559m","memory":"9037933121","pods":"8"} from types c5n.xlarge	{"commit": "eb05b1e", "provisioner": "default"}
2022-06-21T06:39:35.890Z	INFO	controller.provisioning	Waiting for unschedulable pods	{"commit": "eb05b1e"}
```
