### ISSUE TITLE
Pod Affinity impacts Karpenter tracking in-flight nodes

### ISSUE THREAD

**Issue by jbouricius** [aws/karpenter#1975]
## Version

**Karpenter**: v0.12.0 (actively working on upgrading from 0.10)

**Kubernetes**: v1.19.15

## Expected Behavior
As of Karpenter 0.11, pods are no longer pre-bound to nodes. However, per https://github.com/aws/karpenter/pull/1727 , Karpenter is supposed to track newly launched nodes and not launch new nodes for unbound pods.

## Actual Behavior
I have a business reason to require certain pods to be in the same availability zone. When I include PodAffinity in my spec, Karpenter launches nodes, then continues to launch nodes while the first ones become ready. Eventually the first ones become ready, the pods schedule, and Karpenter deletes the extraneous nodes.

## Steps to Reproduce the Problem
Here is an anonymized version of my podSpec. I've picked resource and instance class so that each pod gets its own node, I don't think they're important otherwise.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "inflate-deployment"
  namespace: "inflate-ns"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "TESTING-KARPENTER"
  template:
    metadata:
      labels:
        app: "TESTING-KARPENTER"
      name: "inflate"
      namespace: "inflate-ns"
    spec:
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 800m
              memory: 8000M
      nodeSelector:
        node.kubernetes.io/instance-type: "r5a.large"
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "topology.kubernetes.io/zone"
              labelSelector:
                matchLabels:
                  app: "TESTING-KARPENTER"
```

If I remove the podAffinity block, everything behaves as I expect. Or, it behaves in a superficially similar way to 0.10 - Karpenter launches exactly the right number of nodes. With the podAffinity block, Karpenter launches nodes, then continues to launch more nodes until the pods schedule. I am fairly certain that the node has the right label `topology.kubernetes.io/zone: us-east-1d` before it becomes Ready in the cluster.

As a workaround, I've tried increasing the global setting `batchMaxDuration` . The longer the interval, the less time for Karpenter to launch extra nodes, but also the more time it takes to launch the first node and get the pod scheduled.
