### ISSUE TITLE
GPU node provisioned without specifying instance-type

### ISSUE THREAD

**Issue by gjkamstra** [aws/karpenter#2027]
## Version

**Karpenter**: v0.13.0

**Kubernetes**: v1.22.9-eks

## Expected Behavior
No GPU nodes shall be provisioned when not specifying a instance-type requirement.

## Actual Behavior
GPU node (g3s.xlarge) is provisioned

## Steps to Reproduce the Problem
Create a provisioner without instance-type requirement

Create a Job that requires a GPU (nbody)

When the nbody job is deployed, the default provisoner creates an instance of type `g3s.xlarge` that has a GPU.

The [documentation](https://karpenter.sh/v0.13.1/provisioner/#instance-types) states:

> The default value includes all instance types with the exclusion of metal (non-virtualized), [non-HVM](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/virtualization_types.html), and GPU instances.

Since I didn't specify an explicit instance-type, I expected that no GPU node was created, as the documentation says.
I expect this is is a mistake in the implementation, and not the documentation, considering the examples on GPU with a taint to prevent regular workloads from running on a GPU node.

## Resource Specs and Logs

Provisioner

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
spec:
  labels:
    intent: apps
  limits:
    resources:
      cpu: 1k
      memory: 100Gi
  provider:
    blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          deleteOnTermination: true
          encrypted: true
          iops: 1000
          throughput: 150
          volumeSize: 100Gi
          volumeType: gp3
    instanceProfile: swat-ops-karpenter-profile
    metadataOptions:
      httpEndpoint: enabled
      httpProtocolIPv6: disabled
      httpPutResponseHopLimit: 1
      httpTokens: required
    securityGroupSelector:
      karpenter.sh/discovery/swat-ops-cluster: swat-ops-cluster
    subnetSelector:
      karpenter.sh/discovery/swat-ops-cluster: swat-ops-cluster
    tags:
      Name: swat-ops-karpenter-default
      karpenter.sh/discovery/swat-ops-cluster: swat-ops-cluster
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
        - spot
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
  ttlSecondsAfterEmpty: 30
```

GPU Job

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: nbody
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: gpuapp
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
              nvidia.com/gpu: 1
            limits:
              cpu: 250m
              memory: 256Mi
              nvidia.com/gpu: 1
          image: nvidia/samples@sha256:a2117f5b8eb3012076448968fd1790c6b63975c6b094a8bd51411dee0c08440d
          command: ["/tmp/nbody", "-benchmark", "-numbodies=25600"]
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      restartPolicy: Never
  backoffLimit: 4
```

Karpenter Log

```
2022-06-30T11:56:24.754Z	INFO	controller.provisioning	Created node with 1 pods requesting {"cpu":"435m","memory":"368Mi","nvidia.com/gpu":"1","pods":"7"} from types g4dn.xlarge, g3s.xlarge, g4dn.2xlarge, p2.xlarge, g5.xlarge and 4 other(s)	{"commit": "37c8653", "provisioner": "default"}
```

**Comment by tzneal** [comment]
Sorry, the doc is incorrect, I'll correct it.  If you want to prevent GPU instances from being launched you can exclude them by name or family or you can use limits to prevent instance types with those resources from being launched:

```
  limits:
    resources:
      cpu: 2k
      nvidia.com/gpu: "0"
      aws.amazon.com/neuron: "0"
      amd.com/gpu: "0"
```
