### ISSUE TITLE
Missing network interface for custom launch template?

### ISSUE THREAD

**Issue by BrewedCoffee** [aws/karpenter#2041]
Hello! I have been following the instructions here https://karpenter.sh/v0.13.1/aws/launch-templates/ to use a custom AMI, and have run into an issue where spawned nodes remain in status `Unknown`, reason `NodeStatusNeverUpdated`, message `Kubelet never posted node status.`.

I did a side by side comparison with a default Karpenter provisioned node and discovered that while my node matches the same subnet, security groups, tags, and IAM profile, it seems to be missing an additional network interface that grants it some more private IPv4 addresses and is tagged `aws-K8S-i-<removed string of chars>`.

Where is this coming from, and how can I resolve this issue? There is a block for additional `network_interfaces` in the [LT Terraform resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#network-interfaces) but I am not sure if that will override the existing interface/what values and networking rules are required. I also see that we are told not to in the docs: https://karpenter.sh/v0.13.1/aws/launch-templates/#network-interfaces.

I am using Karpenter version 0.13.1, Terraform 1.2.2, and Kubernetes/EKS version 1.22.

Launch template:
```

resource "aws_launch_template" "test" {
  name = "test"
  image_id = "<removed>"

  user_data = filebase64("${path.module}/resources/bootstrap.sh")

  iam_instance_profile {
    arn = "<removed>"
  }

  vpc_security_group_ids = [
    module.eks.cluster_primary_security_group_id,
    module.eks.cluster_security_group_id,
    module.eks.node_security_group_id
  ]

  tag_specifications {
    resource_type = "instance"

    tags = merge(local.tags, {
    "karpenter.sh/discovery" = local.name,
    "kubernetes.io/cluster/${local.name}" = "owned",
    })
  }

  tags = merge(local.tags, {
    "karpenter.sh/discovery" = local.name
  })
}
```

bootstrap.sh
```
#!/bin/bash
/etc/eks/bootstrap.sh '<removed>' \
--kubelet-extra-args '--node-labels=node.k8s.aws/capacity-type=spot'
--b64-cluster-ca '<removed>'\
--apiserver-endpoint '<removed>' \
```

Provisioner
```
resource "kubectl_manifest" "gpu_provisioner" {
  yaml_body = <<-YAML
  apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: gpu-only
  spec:
    requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot"]
    limits:
      resources:
        cpu: 1000
        memory: 1000Gi
    taints:
    - effect: NoSchedule
      key: nvidia.com/gpu
      value: "true"
    provider:
      launchTemplate: test
      subnetSelector:
        karpenter.sh/discovery: ${local.name}
      tags:
        karpenter.sh/discovery: ${local.name}
    ttlSecondsAfterEmpty: 30
  YAML

  depends_on = [
    helm_release.karpenter
  ]
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
