### ISSUE TITLE
Karpenter ignoring parts of Bottlerocket userData in AWSNodeTemplate

### ISSUE THREAD

**Issue by resnikb** [aws/karpenter#2059]
## Version

**Karpenter**: v0.13.1

**Kubernetes**: v1.22.9

## Expected Behavior

Karpenter merges all Bottlerocket sections found in `userData` in `AWSNodeTemplate` resource into the generated launch template.

## Actual Behavior

Karpenter is ignoring certain configuration options in `userData`, in particular `[settings.network]` section. They are left out from the generated launch template.

## Steps to Reproduce the Problem

Given the following configuration:
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]

  limits:
    resources:
      cpu: 100

  # Scale down if the node is empty
  ttlSecondsAfterEmpty: 30

  # Reference our node template that configures proxy usage
  providerRef:
    name: bottlerocket-proxy
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: bottlerocket-proxy
spec:
  amiFamily: Bottlerocket

  subnetSelector:
    karpenter.sh/discovery: mycluster

  securityGroupSelector:
    karpenter.sh/discovery: mycluster

  userData: |
    [settings.network]
    https-proxy = "http://my-proxy"
    no-proxy = ["localhost", "127.0.0.1"]
```
I would expect the generated launch template to contain the `[settings.network]` section with proxy configuration. However, this does not happen - the section is missing from the configuration.

Other sections, eg `[settings.kubernetes]`, are correctly merged into the launch template.
