### ISSUE TITLE
Karpenter subnet selection preference

### ISSUE THREAD

**Issue by pavlospt** [aws/karpenter#2144]
## Version
**Karpenter**: v0.13.2
**Kubernetes**: v1.22.0

## Expected Behavior
Karpenter should pick subnets in a round-robin balanced fashion.

## Actual Behavior
We recently had to migrate our development VPC to bigger subnets since we were running out of IPs. We have our development EKS cluster and its nodes spread across all of 3 private subnets of the development VPC and for some reason Karpenter seems to be preferring 1b in order to spawn nodes, which creates a huge gap in IP allocation between subnets (1subnet per AZ). 

The numbers look like these:

```
1a -> 3974
1b -> 3436
1c -> 3904
```

As you can understand there is a diff of ~500 IPs between subnets. 

We have checked Karpenter controller logs and it indeed shows that it finds all of subnets but for some reason it chooses 1b most of the time, creating an unbalanced situation. 

Is there a way to find if there is a bug behind this situation? 

Let me know if you need me to provide you with more insights around our setup! 

## Steps to Reproduce the Problem
Check the specs below.

## Resource Specs and Logs
```yaml
apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: spot-workers
  spec:
    requirements:
      - key: "node.kubernetes.io/instance-type"
        operator: In
        values: ["t2.xlarge", "t3.xlarge", "m5.xlarge"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot"]
      - key: "kubernetes.io/arch"
        operator: In
        values: ["amd64"]
      - key: "topology.kubernetes.io/zone"
        operator: In
        values: ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
    labels:
      managed-by: karpenter
      purpose: spot-workers
    provider:
      launchTemplate: spot-workers-lt
      subnetSelector:
        karpenter.sh/discovery: <our_cluster_name>
      tags:
        karpenter.sh/discovery: <our_cluster_name>
    ttlSecondsAfterEmpty: 30
```
