### ISSUE TITLE
[Bug]: false value cant be quoted

### ISSUE THREAD

**Issue by FernandoMiguel** [aws/karpenter#2162]
## Version

**Karpenter**: 0.13.2

**Kubernetes**: v1.22
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

## Expected Behavior
trying to enable AWS_ENI_LIMITED_POD_DENSITY via env var

## Actual Behavior
issue with quoting
```hcl
module.base_system.module.karpenter[0].module.eks_blueprints_kubernetes_addons_karpenter.module.helm_addon.helm_release.addon[0]: Still modifying... [id=karpenter, 20s elapsed]

Error: failed to replace object: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found f, error found in #10 byte of ...|,"value":false}],"im|..., bigger context ...|}},{"name":"AWS_ENI_LIMITED_POD_DENSITY","value":false}],"image":"public.ecr.aws/karpenter/controlle|...

  with module.base_system.module.karpenter[0].module.eks_blueprints_kubernetes_addons_karpenter.module.helm_addon.helm_release.addon[0],
  on .terraform/modules/base_system.karpenter.eks_blueprints_kubernetes_addons_karpenter/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
   1: resource "helm_release" "addon" {
```

## Steps to Reproduce the Problem
```hcl
module "eks_blueprints_kubernetes_addons_karpenter" {
  source = "git::ssh://git@github.com/aws-ia/terraform-aws-eks-blueprints.git//modules/kubernetes-addons/karpenter?ref=v4.5.0"
  # source = "git::ssh://git@github.com/aws-ia/terraform-aws-eks-blueprints.git//modules/kubernetes-addons/karpenter?ref=main"

  # enable_aws_node_termination_handler = true
  helm_config = {
    cleanup_on_fail = true
    force_update    = true
    replace         = true
    version         = var.karpenter_helm_config_version
    set = [
      # {
      #   name  = "logLevel"
      #   value = "debug"
      # },
      {
        name  = "hostNetwork"
        value = "true"
      },
      {
        name  = "controller.env[0].name"
        value = "AWS_ENI_LIMITED_POD_DENSITY"
      },
      {
        name  = "controller.env[0].value"
        value = "false"
        type  = "string"
      },
    ]
  }
  addon_context = var.addon_context
}
```

tried a few combinations to quote and escape `false` but it either fails or when it works, leaves the wrong value in the `Deployment`

```hcl
      {
        name  = "controller.env[0].value"
        value = "\"false\""
        type  = "string"
      },
```
this applies

but then looks like this:
```yaml
    spec:
      containers:
      - name: controller
        image: public.ecr.aws/karpenter/controller:v0.13.2@sha256:af463b2ab0a9b7b1fdf0991ee733dd8bcf5eabf80907f69ceddda28556aead31
        ports:
        - name: http-metrics
          containerPort: 8080
          protocol: TCP
        - name: http
          containerPort: 8081
          protocol: TCP
        env:
        - name: CLUSTER_NAME
          value: fernando-rare-anchovy
        - name: CLUSTER_ENDPOINT
          value: https://8F0612BE376069E8F02961CDADE488AF.gr7.us-east-1.eks.amazonaws.com
        - name: KARPENTER_SERVICE
          value: karpenter
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: AWS_ENI_LIMITED_POD_DENSITY
          value: '"false"'
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
```
