### ISSUE TITLE
Karpenter dose not delete nodes after the downscale

### ISSUE THREAD

**Issue by ermiaqasemi** [aws/karpenter#2166]
Hey team,

I am using Karpenter version v0.13.2 and EKS version 1.22. When I am testing Karpenter in a fresh cluster after I scaled down the node will stay up and never be deleted. 

I reported this issue in the slack channel and folks provided me with this snapshot to have better logs and info. `public.ecr.aws/karpenter/controller:08bc074ccc5631ab6a81d10c444411e1ba799477` 

I also upload karpenter logs file [here](https://drive.google.com/file/d/1DumduVSAl6G1iyd6YbnglHI0e0h6OWJO/view?usp=sharing) so you guys can better understand what happened during the scaling up and down. FYI, my nodes were completely ready and pods were able to schedule but Karpenter continuously said they are not ready.

How I bring up the Karpenter: 

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.26.3"


  cluster_name    = var.name
  cluster_version = var.cluster_version

  vpc_id     = var.vpc_id
  subnet_ids = var.vpc_private_subnets

  enable_irsa                          = true
  cluster_endpoint_private_access      = true
  cluster_endpoint_public_access       = true
  cluster_endpoint_public_access_cidrs = var.endpoint_access_cidrs

  # Self managed node groups will not automatically create the aws-auth configmap so we need to
  create_aws_auth_configmap = true
  manage_aws_auth_configmap = true

  cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
      addon_version     = "v1.8.7-eksbuild.1"
    }
    kube-proxy = {
      addon_version = "v1.22.6-eksbuild.1"
    }
    vpc-cni = {
      resolve_conflicts = "OVERWRITE"
      addon_version     = "v1.11.2-eksbuild.1"
    }
  }

  cluster_encryption_config = [{
    provider_key_arn = aws_kms_key.eks.arn
    resources        = ["secrets"]
  }]

  # Extend node-to-node security group rules
  node_security_group_additional_rules = {
    # Control plane invoke Karpenter webhook
    ingress_karpenter_webhook_tcp = {
      description                   = "Control plane invoke Karpenter webhook"
      protocol                      = "tcp"
      from_port                     = 8443
      to_port                       = 8443
      type                          = "ingress"
      source_cluster_security_group = true
    }
  }

  eks_managed_node_group_defaults = {
    launch_template_name = "core"
    iam_role_name        = "CoreEKS${data.aws_region.current.name}"
    labels = {
      "eks.example.so/node-role" = "core"
    }
  }

  eks_managed_node_groups = {
    core = {
      name           = var.name
      instance_types = var.core_instance_type

      min_size     = var.core_min_size
      max_size     = var.core_max_size
      desired_size = var.core_min_size

      iam_role_additional_policies = [
        # Required by Karpenter
        "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore",
        # Required by NTH
        "arn:aws:iam::aws:policy/AmazonSQSFullAccess"
      ]
    }
  }

  tags = merge(var.tags, {
    "eks.example.so/node-role" = "core"
    "karpenter.sh/discovery" = var.name
  })
}
```

Service Account IAM policy:

```
resource "aws_iam_role_policy" "oidc_policy" {
  name = "${var.name}-OIDCPolicy"
  role = module.iam_assumable_oidc_role.iam_role_name

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = [
          "ec2:CreateLaunchTemplate",
          "ec2:CreateFleet",
          "ec2:RunInstances",
          "ec2:CreateTags",
          "iam:PassRole",
          "ec2:TerminateInstances",
          "ec2:DescribeLaunchTemplates",
          "ec2:DeleteLaunchTemplate",
          "ec2:DescribeInstances",
          "ec2:DescribeSecurityGroups",
          "ec2:DescribeSubnets",
          "ec2:DescribeInstanceTypes",
          "ec2:DescribeInstanceTypeOfferings",
          "ec2:DescribeAvailabilityZones",
          "ec2:DescribeSpotPriceHistory",
          "ssm:GetParameter",
          "pricing:GetProducts"
        ]
        Effect   = "Allow"
        Resource = "*"
      },
    ]
  })
}
```

```
resource "helm_release" "karpenter" {
  namespace = "karpenter"
  wait      = true

  name       = "karpenter"
  repository = "https://charts.karpenter.sh"
  chart      = "karpenter"
  version    = "v0.13.2"

  cleanup_on_fail = true
  force_update    = true


  values = [jsonencode(
    {
      "controller" = {
        "env" = [
          {
            "name"  = "AWS_ENABLE_POD_ENI"
            "value" = "true"
          },
          {
            "name"  = "AWS_ENI_LIMITED_POD_DENSITY"
            "value" = "true"
          }
        ]
      }
    }
  )]

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = var.cluster_oidc_role_arn
  }

  set {
    name  = "clusterName"
    value = var.cluster_name
  }

  set {
    name  = "clusterEndpoint"
    value = var.cluster_endpoint
  }

  set {
    name  = "aws.defaultInstanceProfile"
    value = var.cluster_node_instance_profile_name
  }
}
```

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: worker
spec:
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [c5n, m5n]
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values: [nano, micro, small, large]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand", "spot"]
  provider:
    subnetSelector:
      karpenter.sh/discovery: "development-us-east-1-neo"
    securityGroupSelector:
      karpenter.sh/discovery: "development-us-east-1-neo"
    tags:
      karpenter.sh/discovery: "development-us-east-1-neo"
  limits:
    resources:
      cpu: 1000
  ttlSecondsAfterEmpty: 120
  ttlSecondsUntilExpired: 2592000
  labels:
    eks.example.so/node-role: worker

```
