### ISSUE TITLE
Instance type g5 family is not support.

### ISSUE THREAD

**Issue by zorrofox** [aws/karpenter#2177]
## Version

**Karpenter**: v0.13.2

**Kubernetes**: v1.21

## Expected Behavior

Support g5 instance type as the [document](https://karpenter.sh/v0.13.2/aws/instance-types/#g5-family) mentioned.
## Actual Behavior

The karpenter controller will report:
```
2022-07-25T02:43:03.697Z        ERROR   controller.provisioning Provisioning failed, launching node, creating cloud provider instance, with fleet error(s), Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.       {"commit": "062a029"}
```

## Steps to Reproduce the Problem

Add a Provisioner as follow:
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
 name: gpu
spec:
 requirements:
   - key: karpenter.sh/capacity-type
     operator: In
     values: ["spot", "on-demand"] 
   - key: node.kubernetes.io/instance-type
     operator: In
     values: ["g5.xlarge", "g5.2xlarge"]
 taints:
   - key: nvidia.com/gpu
     effect: "NoSchedule"
 limits:
   resources:
     gpu: 100
 provider:
   blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          volumeSize: 200Gi
 ttlSecondsAfterEmpty: 30
```
