### ISSUE TITLE
Karpenter is not aware of the Custom Networking VPC CNI pod limit per node

### ISSUE THREAD

**Issue by zahodi** [aws/karpenter#2273]
## Version

**Karpenter**: public.ecr.aws/karpenter/controller:v0.13.2@sha256:af463b2ab0a9b7b1fdf0991ee733dd8bcf5eabf80907f69ceddda28556aead31

**Kubernetes**: Server Version: v1.21.14-eks-18ef993

## Expected Behavior
Karpenter is expected to not exceed the maximum amount of pods that can be scheduled on the node. 

## Actual Behavior
More pods get scheduled unto a node then is supported by the: https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/pkg/aws/vpc/limits.go#L509
<img width="814" alt="Screen Shot 2022-08-09 at 3 45 44 PM" src="https://user-images.githubusercontent.com/5876685/183774587-529adaf2-7f74-47d3-8600-d126286bf2c8.png">

It's possible that this is due to the fact that we run two CIDRs for EKS. Separate CIDR for nodes and another one for workload/pods.  

## Steps to Reproduce the Problem
* Setup dual cidr range in your eks cluster: https://aws.amazon.com/premiumsupport/knowledge-center/eks-multiple-cidr-ranges/
* deploy karpenter
* deploy and scale a sample service which should bring up a node which will have over-provisioned pods. 

## Resource Specs and Logs
No relevant logs are observed in Karpenter.
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  labels:
    app: reviews
    version: v1
spec:
  replicas: 100
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.4
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        securityContext:
          runAsUser: 1000
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
        ```
      
```
Warning  FailedCreatePodSandBox  3m53s (x1089 over 23m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "a2a5a5df3f2010b2e03c0f45ae2129fcfa5b3965d2f5107558a4c7dcefb450b9" network for pod "reviews-v3-7886dd86b9-kk46x": networkPlugin cni failed to set up pod "reviews-v3-7886dd86b9-kk46x_default" network: add cmd: failed to assign an IP address to container
```

```
spec:
  kubeletConfiguration:
    containerRuntime: dockerd
  labels:
    billing: blah
    limits: {}
  providerRef:
    name: al2
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000
status:
  resources:
    attachable-volumes-aws-ebs: "64"
    cpu: "10"
    ephemeral-storage: 484417496Ki
    memory: 32820628Ki
    pods: "126"
   
```

Node Information:

```
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: t3a.small
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: us-east-1
    failure-domain.beta.kubernetes.io/zone: us-east-1c
    karpenter.k8s.aws/instance-cpu: "2"
    karpenter.k8s.aws/instance-family: t3a
    karpenter.k8s.aws/instance-hypervisor: nitro
    karpenter.k8s.aws/instance-memory: "2048"
    karpenter.k8s.aws/instance-pods: "8"
```
