### ISSUE TITLE
Adding Dynamic Taints to Nodes based on Tolerations

### ISSUE THREAD

**Issue by VishDev12** [aws/karpenter#2290]
**Tell us about your request**

Using this [scheduling technique](https://karpenter.sh/v0.14.0/tasks/scheduling/#exists-operator), it's possible to add a custom label to a node based on a corresponding key/value pair specified in the node-selector or node-affinity. This allows us to have nodes from a single provisioner that have differing custom labels based on the workloads that get scheduled on them, and ultimately, this allows for workload isolation at the node level.

But this is only true if every pod using that provisioner specifies that custom label in the node-selector or node-affinity. If a workload doesn't specify it, it can now be scheduled on any node launched by the provisioner and isolation is no longer a guarantee.

It seems that in addition to dynamic labelling, a mechanism to dynamically taint the nodes would help guarantee workload isolation at the node level. This would be critical for multi-tenant scenarios where it's one thing to say that isolation is 'possible', but with this feature, isolation would be inviolable.

@ellistarn had the suggestion of defining taints in the provisioner with an empty or '*' value and then specifying the corresponding tolerations in the workload.

Taint specified in the provisioner:

```yaml
- key: company.com/team
  value: "*"
  effect: NoSchedule
```

Toleration:

```yaml
- key: company.com/team
  value: datascience
  effect: NoSchedule
```

If the corresponding toleration is not specified in the workload, the understanding is that the node on which it will be scheduled never gets a taint. This allows both isolated and non-isolated workloads to use the same provisioner.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

In a multi-tenant scenario, we prefer to have workloads cleanly segregated by nodes. Currently this is achievable by creating a new provisioner where the clear expectation is that everyone using it is expected to either have the custom label specified in the node-selector or node-affinity, and this would be what determines the workload isolation because their workloads would always be scheduled on nodes with matching labels. But what would be more ideal is to be able to do this directly from the default provisioner where both isolated and non-isolated workloads are able to coexist with it being impossible for the non-isolated pods to be scheduled on the isolated nodes.

**Me being greedy**

The above would be more than cool enough already. But if it's possible to do away with the necessity of specifying the custom labels or taints on the provisioner, that would be the ultimate level of flexibility. Unlimited node groups controlled by nothing but the workloads. Perhaps something along these lines:

```yaml
nodeSelector:
  customLabel/company.com/team: datascience

tolerations:
  - key: customLabel/company.com/team
    value: datascience
    effect: NoSchedule
```

The expectation being that when Karpenter sees 'customLabel/' in the nodeSelector, it understands that it needs to generate a corresponding node label (after stripping away 'customLabel/'). The same would apply for generating taints when it sees the 'customLabel/' prefix in the tolerations.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
> Me being greedy

Part of the Provisioner's design is that the Provisioner defines a bounded universe for pods. This enables a separation of concerns between operators and developers, who may have different permissions in the cluster. Any taint (or node property, for that matter) that exists in the cluster must be defined by *some* provisioner.

**Comment by VishDev12** [comment]
Okay, that makes a lot of sense, I can see how not having the provisioner at least define the labels/taints will collapse that boundary. It was definitely a stretch in any case.

What are your thoughts on the taints though? Does this part still hold up from our earlier chat?

Taint specified in the provisioner:
```yaml
- key: company.com/team
  value: "*"
  effect: NoSchedule
```

Toleration:
```yaml
- key: company.com/team
  value: datascience
  effect: NoSchedule
```

**Comment by jonathan-innis** [comment]
Value is not a required field. Do we even need to specify the taint value in this case? Can we just assume the taint should inherit the toleration value if the workload needs it when the taint in the provisioner looks like this?

```
- key: company.com/team
  effect: NoSchedule
```

**Comment by jonathan-innis** [comment]
I'd prefer to go with empty since it would make more semantic sense as specifying that a label exists is also "not specifying a value"

```yaml
- key: company.com/team
  effect: NoSchedule
```

**Comment by ellistarn** [comment]
I'm a fan of:

Taint specified in the provisioner (value is undefined):
```
- key: company.com/team 
  effect: NoSchedule
```
Toleration:
```
- key: company.com/team
  value: datascience
  effect: NoSchedule
```

**Comment by VishDev12** [comment]
How would the coexistence of isolated and non-isolated workloads work in this scenario?

Looking at a few cases:

## Taint specified with undefined value, but toleration isn't specified at all (no key, no value)

Provisioner taint
```yaml
- key: company.com/team 
  effect: NoSchedule
```

**No Toleration**

Taint generated on node
```yaml
- key: company.com/team
  effect: NoSchedule
```

Taint gets created on node, but without a value. Which perfectly syncs up with the current behaviour of what happens when a taint is specified in the provisioner without a value. We expect only pods with a matching toleration (only key needs to match) to be scheduled on the node.

## Taint specified with wildcard value, but toleration isn't specified at all (no key, no value)

The "*" value is just an indicator to differentiate the empty value case above from this case. As long as we have that differentiation in some form, we should be good. Let's call this the `generated-taints` use case.

Provisioner taint
```yaml
- key: company.com/team
  value: "*"
  effect: NoSchedule
```

**No toleration**

**No taint is generated**

The provisioner now allows generic, non-isolated workloads with no tolerations to run on nodes that have no taints specified.

### Note:
If we conflate this `generated-taints` case with with the empty value case above, we're saying that every node launched by the provisioner, at the very least, will have the taint specified without the value. Which means that generic workloads can only be scheduled if they have a matching toleration.

## Taint specified with wildcard value, toleration specified with value

Provisioner
```yaml
- key: company.com/team
  value: "*"
  effect: NoSchedule
```

Toleration
```yaml
- key: company.com/team
  value: datascience
  effect: NoSchedule
```

Taint generated on node
```yaml
- key: company.com/team
  value: datascience
  effect: NoSchedule
```

**Comment by jonathan-innis** [comment]
I'm not convinced the generated case is the behavior we want. In my opinion, if you are specifying a taint on your provisioner, even keeping wildcards in mind, your intent is that you will generate a taint on the node that is generated by the Provisioner. If you don't want this taint, you can create another Provisioner that doesn't contain taints.

> ## Taint specified with wildcard value, but toleration isn't specified at all (no key, no value)

In this case, I think that we should generate a taint without a toleration, the taint just should have an empty value.

My concern with using empty value has more with an empty value being a valid value for a taint. Meaning we are potentially conflating a user's intent to specify an empty value and a user's intent to specify a flexible value (maybe this isn't a common scenario and we can ignore it).

As it stands "*" is not a valid taint value on a node so we could use this as a wildcard value without conflating these two intents.

**Comment by VishDev12** [comment]
I agree with your concerns about empty taint values. That's it's own valid case, and shouldn't be conflated with this new feature.

> You can create another Provisioner that doesn't contain taints.

One of the points when this discussion started was to co-locate isolated and general purpose workloads within a single provisioner. And that's possible only when a node can be added without a taint so that any workload can be scheduled to it.

So any mechanism at all (doesn't have to be wildcards) that ensures that the empty value taint case and the generated taint case are separate will be perfect. Just so that there can be a subset of nodes without generated taints to schedule pods that don't have the matching tolerations.

Another point of note is that if we have this separation, we can use a single provisioner to support generated taints with different keys. Workloads can "choose" which taints should be on the nodes on which they get scheduled. For example:

1. `key: company.com/team`
2. `key: client/name`
3. `key: product/name`
4. `key: modelTraining/trialName`

The alternative would be to implement 4 provisioners in addition to the default provisioner just to support these taints. And the concept of selecting a random subset of these would just not be possible. For example, nodes dedicated to product A and client X, or team M and product B.

**Question: Why can't we just add dummy tolerations to the workloads for the tolerations that go unused? This would allow the use of a single provisioner.**
* For example, adding `product/name: general-purpose` and `client/name: general`.

**Answer:**
1. Because we'd have completely irrelevant tolerations on pods. The `modelTraining/trialName` toleration, for example, only makes sense for a highly particular use-case, and forcing all other workloads to add a generic value for that toleration just to support that use-case wouldn't make sense.
2. When we make changes to the generated taints in the provisioner, the tolerations for all workloads using the provisioner would also have to change to add a new generic value. And the existing nodes have to be recycled to allow for that new generic value.

---

I realize I'm placing a lot of weight on making a single provisioner doing all this work, but I feel that having fewer provisioners to maintain would be ideal. Without this, over time, I can see an explosion of provisioners in larger K8s clusters used by multiple teams, just to support different taints and for no other reason, which would be painful for maintenance.

This would be an amazing feature to have, and would introduce incredible versatility to workload isolation and make it quite robust.

**Comment by jonathan-innis** [comment]
@VishDev12 

> Another point of note is that if we have this separation, we can use a single provisioner to support generated taints with different keys. Workloads can "choose" which taints should be on the nodes on which they get scheduled.

Is there any reason why you can't just rely on a single very specific taint to do the workload isolation if you need more granular control over your workload isolation?

I understand that you may have to create 4 different provisioners (5 if we are including generic workloads) for these different kinds of isolation but this seems doable and maintainable and, as an added bonus, your Provisioners now represent their own world of a boundary between the types of workloads they can and can't deploy.

I'm not sure that I'm seeing the use-case for creating subsets of tolerations from a Provisioner that has a larger set of taints. For this one, could you help by giving me a more concrete use-case?

**Comment by VishDev12** [comment]
Of course @jonathan-innis, here's an example of what I was planning to use it for.

# Example

## Facts

* There are 5 different teams.
* Each team has at least 3 products.
* Each product is available in 3 different environments at the same point in time.
  * For example, dev, staging, prod.
  * It'll have even more environments if it's an API with a large team actively developing it.
* Each product is further split up into 10s of microservices.
  * A microservice can be a single deployment/statefulset.
  * Or it can be something like Airflow or Kubeflow Pipelines (KFP), which is actually further made up of 10s of microservices. Because of the vastly differing scaling patterns between something like KFP/Airflow and a simple deployment/statefulset, we give KFP its own node group.

## Requirements for Isolation

* Each team will have its own node group.
* Each environment will have its own node group.
  * But not always. While prod and staging would need to be isolated, the multiple dev environments do not need to be and can share resources to save costs.
* Each product from each team can require its own node group.
  * But not always, the products within a team can share a node group to save costs.
* Each microservice in a product can require its own node group.
  * But only in a few critical scenarios like the one laid out above for KFP/Airflow, they'll mostly share a node group.

## Karpenter Usage in a Few Different Cases

### Case I

Team: A => Isolated; needs a dedicated node group
Environment: Staging => Isolated; needs a dedicated node group
Products: [1, 2, 3, 4, 5] => Unisolated; can share a node group
Product: [6] => Isolated; needs a dedicated node group

Total node groups needed: 2

#### Karpenter Taints:
* `team: A` and `environment: staging`
* `team: A`, `environment: staging`, and `product: 6`

#### Pod tolerations

* Products 1, 2, 3, 4, and 5 will only specify `team: A` and `environment: staging`.
  * They don't need to specify a toleration for `product` at all, even a generic one, because the first node group has no product taint.
* Product 6 will specify `team: A`, `environment: staging`, and `product: 6`.

### Case II

Team: B => Isolated; needs a dedicated node group
Environment: Dev => Unisolated; can share a node group
Products: [1, 2, 3] => Unisolated; can share a node group
Microservice of product 1: KFP => Isolated; needs a dedicated node group

#### Karpenter Taints:
* `team: B`
* `team: B` and `microservice: KFP`

#### Pod tolerations
* All microservices except KFP will specify nothing but: `team: B`.
* KFP will specify both `team: B` and `microservice: KFP`.

We don't have to even consider the environment or product tolerations because the workloads are able to share nodes at those levels.

---

If we don't have the ability to let the provisioner discard generated taints based on the pod's lack of tolerations for it:

## Why can we use Provisioners that are highly specific in their taints?

There will be an explosion of provisioners with different combinations of taints. For example, in this case: `team: A`, `environment: staging`, and `product: 6`, we can't just have the product taint because a product can be in multiple environments. So we'd need a dedicated provisioner with the combination of these three taints.

## Why can't we use Provisioners that will always apply every taint specified to its nodes?

We can get a version of the above working with a provisioner whose nodes will always have all four taints: `team`, `environment`, `product`, and `microservice`. But this will necessitate us having to figure out generic values to handle the shared node group case.

Products 1, 2, and 3 can share a node group? What's the shared value of the product toleration that will let them share a set of nodes? What dummy values do we insert into the microservice and environment tolerations? And who manages this and standardizes these dummy values so there's no confusion?

This complexity would only keep growing unless there's a way to allow for taints to "disappear" if the pod doesn't need them.

I've also only covered one scenario.

There's the scenario where a specific domain comes into the picture. For example, if we have Machine Learning workloads and we wanted to track them by trialName, we could use a `trialName` taint and toleration. But then would we have to assign a dummy toleration for `trialName` to every workload that uses that provisioner?

There's the scenario where time becomes a factor. Let's say two months after creating a provisioner with all four taints: `team`, `environment`, `product`, and `microservice`, I decided to add a taint called `client`. We'd have to add a generic toleration to every existing workload on the provisioner nodes and synchronize it with the restart of every existing node in the provisioner so the new generic taint gets added to them.

There's also the argument against repetition. Except for highly specific scenarios with specific AMIs, etc, one provisoner can handle the vast majority of use cases. So is it justifiable to repeat the spec of every provisioner for nothing more than getting a new taint? And to add the task of keeping all these provisioners in sync to the cluster admin?

This, for example, is a part of my requirements, and I'd rather repeat it as few times as possible so that it doesn't become necessary to copy-paste and keep multiple provisioners in sync:

```yaml
requirements:
    # Prioritize spot, fallback to OD.
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]

    # Exclude instances in these categories.
    - key: karpenter.k8s.aws/instance-category # We prevent instances with a GPU, etc from being provisioned.
      operator: NotIn
      values:
        - g # GPUs
        - p # Large GPUs
        - inf # Inferentia acclerator
        - dl # Gaudi accelerator
        - cc # Cluster compute, for HPC.
        - d # Dense storage, for parallel data processing
        - i # Storage optimized
        - im # Storage optimized, Graviton
        - is # Storage optimized, Graviton
        - h # Storage optimized, high throughput
        - u # Absurdly high memory, for in-memory DBs
        - vt # Video transcoding
        - x # Xeon processors, high memory
        - z # High mem, high CPU, high frequency

    # Exclude instances in these families.
    - key: karpenter.k8s.aws/instance-family
      operator: NotIn
      values:
        - c1 # 1st gen
        - c3 # 3rd gen
        - c6i # Intel processors, twice the cost in Mumbai
        - c6id
        - m1 # 1st gen
        - m2 # 2nd gen
        - m3 # 3rd gen
        - m5zn # High frequency
        - m6i # Intel processors
        - m6id
        - r3 # 3rd gen
        - r6i # Intel processors
        - r6id
        - t1 # 1st gen
        - g3 # 3rd gen, old GPU
        - g3s # 3rd gen, old GPU

    # We'd rather have smaller instances to encourage aggressive deprovisioning.
    # Prevent instances with more than 50 GB of memory from being launched.
    - key: karpenter.k8s.aws/instance-memory
      operator: Lt
      values:
        - "50000"
    # Prevent instances with more than 24 CPUs from being launched.
    - key: karpenter.k8s.aws/instance-cpu
      operator: Lt
      values:
        - "25"
```

**Comment by jonathan-innis** [comment]
I'm wondering if a semantic like `optionalTaints` is more appropriate here. I'm concerned with the `*` semantic in the existing `taints` field since there is an understanding at this point that anything that appears in the `taints` or `labels` fields will always get populated onto the nodes.

If we impose something like `.spec.taints[*].optional`, we can imply that a taint value may not be applied to the node unless there is a corresponding toleration on the pod. This combined with the wildcard semantic could give you the behavior you are looking for. 

```yaml
taints:
# Only apply this taint if there is a matching toleration
  - key: example.com/taint1
     effect: NoSchedule
     value: *
     optional: true
# Apply this taint always to the node
  - key: example.com/taint1
     effect: NoSchedule
     value: *
```

### Why not just use the wildcard (*) to specify optionality?

I'm concerned that just specifying the wildcard in the `value` isn't intuitive enough for most users and may actually surprise a lot of people in practice.

As a user, I personally would find it surprising if I specifying a taint on my provisioner with a wildcard and had no taint appear on a node produced by the provisioner. Adding an `optional` parameter to the taint makes it _very_ clear that this taint will only appear if there is a toleration on the pod that can support it.

**Comment by ellistarn** [comment]
```
  - key: example.com/taint1
     effect: NoSchedule
     value: *
     optional: true
```
This is definitely an option. Do we need value: `"*"` if we also have `optional: true`? These express the same intent in my mind.
```
  - key: example.com/taint1
     effect: NoSchedule
     optional: true
```

That said, as I continue to think of this, I've been thinking about the * semantic more generally. One way to think of `*` is that it's any value, including the lack of a value. I think it might be logically reasonable for a "wildcard taint" to only be applied if a workload requests it, and that a valid value for a wildcard taint is to simply not exist. I'm weighing how (un)natural this semantic is against the cognitive burden of creating a new concept that must be understood by users. 

Tentatively, I think I'm supportive of the wildcard approach, where taints may or may not be generated, depending on the tolerations of incoming pods.

**Comment by jonathan-innis** [comment]
One thing this prevents us from doing is creating an "optional" taint with a specified value. There's no way to have optional taints and constrain the value if we choose to just go with the pure wildcard semantic. 

The other thing I was considering is if we want to extend the wildcard semantic to other things like effect, we are not able to do this without using something like `optional` since the optionality of the taint will be communicated by the `value: *` semantic.

**Comment by jonathan-innis** [comment]
@ellistarn and I discussed offline and decided based on the use-cases as you described them @VishDev12 that the wildcard semantic (which can also mean no taint if there is a pod that does not have a toleration for the matching taint key):

```yaml
- key: example.com/taint1
   effect: NoSchedule
   value: *
```

makes the most sense going forward. I'll be working on trying to get this in as a feature add into the project.

**Comment by VishDev12** [comment]
That's awesome! Thank you both!

**Comment by jonathan-innis** [comment]
@VishDev12 There's been more discussion around the PR I put up with the maintainers, specifically around the non-deterministic nature of the dynamic/generated taints proposal. Take the following example given a single provisioner with the proposal as described:

__Provisioner Taints_
```yaml
taints:
- key: team-name
   effect: NoSchedule
   value: *
```

__Pending Pods__
```yaml
metadata:
  name: pod1
spec:
  tolerations: []
```
```yaml
metadata:
  name: pod2
spec:
  tolerations:
  - key: team-name
     value: team-a
...
```

If `pod1` goes through our scheduler algorithm first, we run into an issue. We will provision a node with no taints because the taints were optional (as specified above). Then, when the second pod `pod2` comes to be scheduled, we will schedule it to the same node because it can fit on that node. This is most likely not what was intended by the user.

In the reverse case where `pod2` goes through the scheduling loop first, we will create two nodes (one with the `team-name` toleration and the other with no tolerations).

We see this as a concern since behaviors can randomly diverge depending on how pods come into the scheduler. We are wondering if the following solves your use-case of enforcing isolation

- Create generic taints for isolation "categories" when you want to isolate based on some value
- When specifying a generic taint for a category, specify the matching generic toleration on the workload pod and ensure that a `nodeSelector` or `requiredNodeAffinity` is set on that same workload pod to enforce the isolation

__Provisioner__
```yaml
requirements:
- key: "team-name"
  operator: Exists
taints:
- key: "team-name"
   effect: NoSchedule
```

__Pending Pods__
```yaml
...
nodeSelector:
  team-name: team-a
tolerations:
- key: team-name
   operator: Exists
```
```yaml
...
nodeSelector:
  team-name: team-b
tolerations:
- key: team-name
   operator: Exists
```

In this case, you would still have to do a couple things:
1. Ensure that there is relevant policy set to require that teams have to set `nodeSelectors` on their workload pods
2. Create a separate Provisioner for the each subset of taints you want to enforce the isolation boundary on (because you wouldn't have to specify the value in the above, this should hopefully be a smaller number of Provisioners)

Ideally, this would solve your isolation scenario without requiring any feature adds to the current set of controllers. 

The remaining concern from the Provisioner spec you specified above is the need to continually re-specify the same set of requirements across different Provisioners. This might be solved by an entirely different mechanism, something like a `RequirementsClass` that we could add to the API to prevent the need for re-specification of common requirements.

**Comment by VishDev12** [comment]
Thank you for the explanation, but please allow me to take a bit more of your time. I understand this concern:

> We see this as a concern since behaviors can randomly diverge depending on how pods come into the scheduler.

But this was expected behaviour — dynamic taints are only one part of the story. Just like [dynamic labels](https://karpenter.sh/v0.16.0/tasks/scheduling/#exists-operator) and node-selectors don't enforce **node isolation**, dynamic taints and tolerations won't enforce **node selection.**

In the use case I laid out, one provisioner would've been used both for the no-taints case and the generated taints case, so the expectation was always that both node-selectors and taints would be required to get the desired behaviour. 

So, if the user adds to their workload:

* Dynamic node-selectors but no corresponding tolerations — they don't expect their pods to be isolated, only that the pods will be on nodes with a particular dynamic label.
* Dynamic tolerations but no corresponding node-selectors — they don't expect their pods to be scheduled only on nodes with the taints matching the tolerations. They only expect that the nodes that do get created for the sole purpose of scheduling these pods will prevent other pods without the right tolerations from being scheduled on them.

If any of the two points above seems like it doesn't make sense (the second point certainly seems without purpose), it's because they're meant to be two opposing parts that make up a single story, one to enforce selection and one to enforce isolation, and together guarantee complete isolation. They have to be used together, just like labels/node-selectors and taints/tolerations are used in regular EKS or Spotinst Ocean node groups to guarantee isolation.

I think the users that make use of dynamic taints will have a clear understanding of this fact if they ever reach that point in their scheduling journey, especially since wildcards aren't something they could add by accident to their provisioner taints.

I should have definitely elaborated on this point, but the intent was captured in this line on the [first message](https://github.com/aws/karpenter/issues/2290#issue-1338748743) of this thread:

> It seems that in addition to dynamic labelling, a mechanism to dynamically taint the nodes would help guarantee workload isolation at the node level.

Just to complete the picture:

Provisioner
```yaml
requirements:
- key: "team-name"
  operator: Exists
taints:
- key: "team-name"
  value: *
  effect: NoSchedule
```

Pod Spec
```yaml
nodeSelector:
  team-name: team-a
tolerations:
- key: team-name
  value: team-a
```
