### ISSUE TITLE
Configurable cluster consolidation

### ISSUE THREAD

**Issue by koolwithk** [aws/karpenter#2365]
**Tell us about your request**
can we make configurable [cluster consolidation](https://github.com/aws/karpenter/pull/2123) where we can reserved some **CPU** and **Memory** for better performance and tuned cost saving?

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: provisioner
spec:
   consolidation:
     enabled: true
     reserverd:
       cpu: 1000m
       memory: 2G

##### OR in percentage % #####
     reserverd:
       cpu: 5%
       memory: 5%
```

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
After implementing [consolidation feature ](https://github.com/aws/karpenter/pull/2123)some of our pods are getting restarted due to failing **readiness** and **liveness probe** and when we increase cpu and memory it starts running.
By adding some reserved `cpu` and `memory` during calculation of consolidation it will act as soft tuning button for cost optimization and it will bring more confidence in user for using consolidation feature.

For example, If node has `10 CPU` and `20 GB RAM` and we want to reserve **10%** then consolidation feature should only consider `9 CPU` and `18GB RAM` for making consolidation decision .

**Are you currently working around this issue?**
How are you currently solving this problem?

Possible solution:
- Increase the timeout for initialDelay, readiness and liveness periodSeconds
- Increase the CPU and Memory for Deployment
- Configurable cluster consolidation which kind of act as safe tuning button

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
