### ISSUE TITLE
Allow for Single String Lists

### ISSUE THREAD

**Issue by pptb-aws** [aws/karpenter#2371]
**Tell us about your request**
What do you want us to build?

When using nodeAffinity to limit what type of instances a node will launch with or what region it will launch in Karpenter will fail to scale out if the values are all in one set of quotes, such as the instance size section below,

```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "app"
                    operator: "In"
                    values: ["app"]
                  - key: "topology.kubernetes.io/zone "
                    operator: "In"
                    values: ["us-east-1d"]
                  - key: "karpenter.k8s.aws/instance-size "
                    operator: "In"
                    values: ["xlarge, 2xlarge"]
                  - key: "karpenter.sh/capacity-type "
                    operator: "In"
                    values: ["spot"]
```

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

The purpose of this is to allow for additional formatting which is not specified as limited in any documentation I could find.

**Are you currently working around this issue?**
How are you currently solving this problem?

Using values like,
```
                  - key: "karpenter.k8s.aws/instance-size "
                    operator: "In"
                    values: ["xlarge", "2xlarge"]
```
or
```
                  - key: "karpenter.k8s.aws/instance-size "
                    operator: "In"
                    values:
                    - 'xlarge'
                    - '2xlarge'
```

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

Sample Provisioner and deployment attached.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

[sample_provisioner_and_deployment.yaml.txt](https://github.com/aws/karpenter/files/9433139/sample_provisioner_and_deployment.yaml.txt)

**Comment by bwagner5** [comment]
The examples around Node Affinity given are not within Karpenter's control. Those are Kubernetes APIs on the Pod spec:

```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "app"
                    operator: "In"
                    values: ["app"]
                  - key: "topology.kubernetes.io/zone "
                    operator: "In"
                    values: ["us-east-1d"]
                  - key: "karpenter.k8s.aws/instance-size "
                    operator: "In"
                    values: ["xlarge, 2xlarge"]
                  - key: "karpenter.sh/capacity-type "
                    operator: "In"
                    values: ["spot"]
```

Karpenter defines the labels on the node, but the way you are suggesting that a single entry with a comma-delimited list would mean that Kubernetes would expect the node to have the exact string `xlarge, 2xlarge` as the label value which wouldn't make sense on a node (it would have to be one or the other). 

Even if Karpenter parsed it the way you are suggesting, the semantic wouldn't work within Kubernetes.

I also don't think this way of specifying a comma delimit string list is clear to users since all other Kubernetes APIs are using the proper yaml list syntax.
