### ISSUE TITLE
Support blockDeviceMappings with instance store NVMe volume to provisioned nodes

### ISSUE THREAD

**Issue by maciej-ciach** [aws/karpenter#2372]
## Version

**Karpenter**: v0.16.0

**Kubernetes**: v1.20.0

## Expected Behavior
I would like to use EC2 instances with instance store volumes instead of provisioning additional EBS devices

## Actual Behavior
I tried to configure provisioner using example of blockDeviceMapping from https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html#instance-block-device-mapping 
```
    amiFamily: Bottlerocket
    blockDeviceMappings:
      - deviceName: /dev/xvdb
        virtualName: ephemeral0
```
But I'm getting provisioner errors when scheduling pods.
## Steps to Reproduce the Problem

Configure provisioner with blockDeviceMappings block above
