### ISSUE TITLE
Karpenter does not attach network interface with the launch template

### ISSUE THREAD

**Issue by munjalpatel** [aws/karpenter#2397]
## Version
**Karpenter**: v0.16.0
**Kubernetes**: v1.21

## Expected Behavior
When Karpenter creates the launch template, it should associate the network interface with it.

## Actual Behavior
When Karpenter creates the launch template, it does not associate the network interface with it.

## Steps to Reproduce the Problem
**Provisioner**

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: default
spec:
  limits:
    resources:
      cpu: 1k
  provider:
    instanceProfile: kooyal-dev-instance-profile
    securityGroupSelector:
      karpenter.sh/discovery: kooyal-dev
    subnetSelector:
      karpenter.sh/discovery: kooyal-dev
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - t3a.small
        - t3.small
        - t3a.medium
        - t3.medium
        - t3a.large
        - t3.large
        - t3a.xlarge
        - t3.xlarge
        - t3a.2xlarge
        - t3.2xlarge
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - spot
    - key: topology.kubernetes.io/zone
      operator: In
      values:
        - us-west-2a
        - us-west-2b
        - us-west-2c
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000
```

## Screenshot of correct launch template created by EKS
![image](https://user-images.githubusercontent.com/2717686/187349112-ead8ed1d-0388-42be-b996-14752c3d97d2.png)

## Screenshot of incorrect launch template created by Karpenter
![image](https://user-images.githubusercontent.com/2717686/187349148-497e3153-015c-4635-a6fb-a445eba72965.png)

**Comment by munjalpatel** [comment]
Hey folks, any help here please?

**Comment by bwagner5** [comment]
I can look into this as I'm doing some related work to attach more network interfaces at launch.  Karpenter only supplies the launch template with the bare minimum properties and the rest is supplied directly to the EC2 Fleet API.  Is there a use-case for having the network interface information in the launch template?

**Comment by munjalpatel** [comment]
Thanks @bwagner5 

Well, without the network interface, the pods on the nodes spun up by Karpenter are not able to communicate with the pod on the other nodes or the internet for that matter.

**Comment by munjalpatel** [comment]
Interesting, when I deployed Karpenter, the pods scheduled on the node were not able to communicate with the pods scheduled on the other nodes.

**Comment by bwagner5** [comment]
Were the security groups specified in your Provisioner setup to allow inter-node communication?

**Comment by munjalpatel** [comment]
@bwagner5 I did specify security group and subnets in the provisioner.

```yaml
securityGroupSelector:
      karpenter.sh/discovery: kooyal-dev
subnetSelector:
      karpenter.sh/discovery: kooyal-dev
```
