### ISSUE TITLE
Cannot launch EKS nodes using custom launch template.

### ISSUE THREAD

**Issue by garyyang6** [aws/karpenter#2412]
In the default Karpenter configuration, Karpenter uses an EKS optimized version of AL2 (Amazon Linux 2)  (https://karpenter.sh/v0.13.2/aws/launch-templates/) and passes the hostname of the Kubernetes API server, and a certificate.
Karpenter supports using custom launch templates. I created an AMI use Ubuntu 20.04 with Cuda 11.6. I use resource "aws_launch_template" to launch custom template. See the code below. After launched EKS cluster, the nodes are still Amazon Linux 2, not Ubuntu. Below is the related code. No clue why the resource "aws_launch_template" does not launch the ubuntu AMI instance.
```
resource "aws_launch_template" "ubuntu_cuda" {
  name = "ubuntu_cuda"
  image_id = "ami-009aa2e3397b12345"
  user_data = filebase64("${path.module}/resources/bootstrap.sh")

  iam_instance_profile {
    name = aws_iam_instance_profile.karpenter.name
  }

  vpc_security_group_ids = [
    module.eks.cluster_primary_security_group_id,
    module.eks.cluster_security_group_id,
    module.eks.node_security_group_id
  ]
  block_device_mappings {
    device_name = "/dev/sda1"

    ebs {
      volume_size = 200
      volume_type = "gp3"
      delete_on_termination = true
    }
  }

  tag_specifications {
    resource_type = "instance"

    tags = merge(local.tags, {
    "karpenter.sh/discovery" = local.name,
    "kubernetes.io/cluster/${local.name}" = "owned",
    })
  }

  tags = merge(local.tags, {
    "karpenter.sh/discovery" = local.name
  })

  depends_on = [
    module.eks
  ]
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.0"
  cluster_name                    = "${local.name}-${local.env}"
  cluster_version                 = local.cluster_version
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.public_subnets
  create_cloudwatch_log_group = false
  cloudwatch_log_group_retention_in_days = 3
  node_security_group_additional_rules = {
    ingress_karpenter_webhook_tcp = {
      protocol                      = "tcp"
      from_port                     = 8443
      to_port                       = 8443
      type                          = "ingress"
      source_cluster_security_group = true
    }
  }
  eks_managed_node_groups = {
    "karpenter-${var.environment}" = {
      create_security_group                 = false
      attach_cluster_primary_security_group = true

      capacity_type  = "SPOT"
      instance_types = ["t3.large"] # try to minimize

      min_size     = 1
      max_size     = 3
      desired_size = 1

      iam_role_additional_policies = [
        "arn:${local.partition}:iam::aws:policy/CloudWatchAgentServerPolicy",
        "arn:${local.partition}:iam::aws:policy/AmazonSSMManagedInstanceCore",
        "arn:${local.partition}:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly",
      ]
    }
  }

  tags = merge(local.tags, {
    "karpenter.sh/discovery" = "${local.name}-${local.env}"
  })
}
```
**Is an existing page relevant?**

**What karpenter features are relevant?**

**How should the docs be improved?**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Have you configured a launch template on the provisioner? If so, can you provide your provisioner spec?

Also in later versions of Karpenter you can use custom AMIs [without creating a launch template.](https://karpenter.sh/v0.16.0/aws/user-data/)

**Comment by garyyang6** [comment]
Here are the provisioners:

# GPU Provisioner for Karpenter-default AL2-based AMI instances.
resource "kubectl_manifest" "northstar_karpener_provisioner" {
  yaml_body = <<-YAML
  apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: northstar-${local.env}
  spec:
    requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot", "on-demand"]
      - key: node.kubernetes.io/instance-type
        operator: In
        values: ["g5.12xlarge"]
    limits:
      resources:
        cpu: 1000
        memory: 1000Gi
    taints:
    - effect: NoSchedule
      key: "nvidia.com/gpu"
      value: "true"
    provider:
      blockDeviceMappings:
        - deviceName: /dev/xvda
          ebs:
            volumeSize: 40Gi
            volumeType: gp3
            deleteOnTermination: true
      subnetSelector:
        karpenter.sh/discovery: ${local.name}-${local.env}
      securityGroupSelector:
        karpenter.sh/discovery: ${local.name}-${local.env}
      tags:
        Name: galileo-gpu-${local.env}
        karpenter.sh/discovery: ${local.name}-${local.env}
    ttlSecondsAfterEmpty: 300 # 5 minutes, comment out for indefinite
    # ttlSecondsUntilExpired: 604800 # 7 days, commented out for indefinite
  YAML

  depends_on = [
    helm_release.karpenter
  ]
}

# CPU Provisioner for Karpenter-default AL2-based AMI instances.
resource "kubectl_manifest" "cpu_karpener_provisioner" {
  yaml_body = <<-YAML
  apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: cpu-${local.env}
  spec:
    requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot", "on-demand"]
      - key: node.kubernetes.io/instance-type
        operator: In
        values: ["t2.micro", "t3.medium", "t3.large"]
    limits:
      resources:
        cpu: 1000
        memory: 1000Gi
    provider:
      subnetSelector:
        karpenter.sh/discovery: ${local.name}-${local.env}
      securityGroupSelector:
        karpenter.sh/discovery: ${local.name}-${local.env}
      tags:
        Name: galileo-cpu-${local.env}
        karpenter.sh/discovery: ${local.name}-${local.env}
    ttlSecondsAfterEmpty: 300 # 5 minutes
    # ttlSecondsUntilExpired: 604800 # 7 days, commented out for indefinite
  YAML

  depends_on = [
    helm_release.karpenter
  ]
}
resource "kubectl_manifest" "converter_75_provisioner" {
  yaml_body = <<-YAML
  apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: nebula-converter-75-v2
  spec:
    requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot", "on-demand"]
      - key: node.kubernetes.io/instance-type
        operator: In
        values: ["g4dn.xlarge", "g4dn.2xlarge", "g4dn.4xlarge"]
    limits:
      resources:
        cpu: 1000
        memory: 1000Gi
    taints:
    - effect: NoSchedule
      key: "nvidia.com/gpu"
      value: "true"
    labels:
        architecture: "7.5"
    provider:
      blockDeviceMappings:
        - deviceName: /dev/xvda
          ebs:
            volumeSize: 20Gi
            volumeType: gp3
            deleteOnTermination: true
      subnetSelector:
        karpenter.sh/discovery: ${local.name}
      securityGroupSelector:
        karpenter.sh/discovery: ${local.name}
      tags:
        Name: converter-7.5
        karpenter.sh/discovery: ${local.name}
    ttlSecondsAfterEmpty: 60
    ttlSecondsUntilExpired: 7200 # 2 hours
  YAML

  depends_on = [
    helm_release.karpenter
  ]
}
resource "kubectl_manifest" "converter_86_provisioner" {
  yaml_body = <<-YAML
  apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: nebula-converter-86-v2
  spec:
    requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot", "on-demand"]
      - key: node.kubernetes.io/instance-type
        operator: In
        values: ["g5.xlarge", "g5.2xlarge", "g5.4xlarge"]
    limits:
      resources:
        cpu: 1000
        memory: 1000Gi
    taints:
    - effect: NoSchedule
      key: "nvidia.com/gpu"
      value: "true"
    labels:
        architecture: "8.6"
    provider:
      blockDeviceMappings:
        - deviceName: /dev/xvda
          ebs:
            volumeSize: 20Gi
            volumeType: gp3
            deleteOnTermination: true
      subnetSelector:
        karpenter.sh/discovery: ${local.name}
      securityGroupSelector:
        karpenter.sh/discovery: ${local.name}
      tags:
        Name: converter-8.6
        karpenter.sh/discovery: ${local.name}
    ttlSecondsAfterEmpty: 60
    ttlSecondsUntilExpired: 7200 # 2 hours
  YAML

  depends_on = [
    helm_release.karpenter
  ]
}

resource "helm_release" "karpenter" {
  namespace        = "karpenter"
  create_namespace = true

  name       = "karpenter"
  repository = "https://charts.karpenter.sh"
  chart      = "karpenter"
  version    = "v0.13.2"

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = module.karpenter_irsa.iam_role_arn
  }

  set {
    name  = "clusterName"
    value = module.eks.cluster_id
  }

  set {
    name  = "clusterEndpoint"
    value = module.eks.cluster_endpoint
  }

  set {
    name  = "aws.defaultInstanceProfile"
    value = aws_iam_instance_profile.karpenter.name
  }
}

**Comment by garyyang6** [comment]
You asked "Have you configured a launch template on the provisioner? ". I do not understand your question. Based on my launch template, resource "aws_launch_template" (See my code above), How do I configure launch template on the provisioner?

**Comment by garyyang6** [comment]
I guess I did not configure provisioner correctly. The provisioner is not using the template. Or my template is wrong?
Please shed a light. Thank you.

**Comment by garyyang6** [comment]
I think the problem is Provisioner. I have four provisioners. See above code. 
resource "kubectl_manifest" "northstar_karpener_provisioner" {
yaml_body = <<-YAML
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner

resource "kubectl_manifest" "cpu_karpener_provisioner" {
yaml_body = <<-YAML
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner

resource "kubectl_manifest" "converter_75_provisioner" {
yaml_body = <<-YAML
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner

resource "kubectl_manifest" "converter_86_provisioner" {
yaml_body = <<-YAML
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner

And one launch template. But, I have no clue how to make provisioner use the launch template below? Any parameters, values I need to add in those four provisioners?

resource "aws_launch_template" "ubuntu_cuda" {
name = "ubuntu_cuda"

**Comment by garyyang6** [comment]
I guess I find out the root cause. But, I have no clue how to fix it. The provisioner is defined in yaml format. See below:

```
resource "kubectl_manifest" "northstar_karpener_provisioner" {
  yaml_body = <<-YAML
  apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: northstar-${local.env}
  spec:
    requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot", "on-demand"]
      - key: node.kubernetes.io/instance-type
        operator: In
        values: ["g5.12xlarge"]
    limits:
      resources:
        cpu: 1000
        memory: 1000Gi
    taints:
    - effect: NoSchedule
      key: "nvidia.com/gpu"
      value: "true"
    provider:
      blockDeviceMappings:
        - deviceName: /dev/xvda
          ebs:
            volumeSize: 40Gi
            volumeType: gp3
            deleteOnTermination: true
      subnetSelector:
        karpenter.sh/discovery: ${local.name}-${local.env}
      securityGroupSelector:
        karpenter.sh/discovery: ${local.name}-${local.env}
      tags:
        Name: galileo-gpu-${local.env}
        karpenter.sh/discovery: ${local.name}-${local.env}
    ttlSecondsAfterEmpty: 300 # 5 minutes, comment out for indefinite
    # ttlSecondsUntilExpired: 604800 # 7 days, commented out for indefinite
  YAML

  depends_on = [
    helm_release.karpenter
  ]
}
```

The launch template is defined in Terraform format. See below:
```
 resource "aws_launch_template" "ubuntu_cuda" {
   name = "ubuntu_cuda"
   image_id = "ami-009aa2e3397b1qwer"

   user_data = filebase64("${path.module}/resources/bootstrap.sh")

   iam_instance_profile {
     name = aws_iam_instance_profile.karpenter.name
   }

   vpc_security_group_ids = [
     module.eks.cluster_primary_security_group_id,
     module.eks.cluster_security_group_id,
     module.eks.node_security_group_id
   ]

   monitoring {
     enabled = true
   }

   block_device_mappings {
     device_name = "/dev/sda1"

     ebs {
       volume_size = 200
       volume_type = "gp3"
       delete_on_termination = true
     }
   }

   tag_specifications {
     resource_type = "instance"

     tags = merge(local.tags, {
     "karpenter.sh/discovery" = local.name,
     "kubernetes.io/cluster/${local.name}" = "owned",
     })
   }

   tags = merge(local.tags, {
     "karpenter.sh/discovery" = local.name
   })
 }
```
At the provider section inside Provisioner, I need to specify the launch template, something like the code below in Terraform format,
```
      "provider" = {
        "launchTemplate"  = aws_launch_template.ubuntu_cuda.name
        "subnetSelector"  = {
          format("kubernetes.io/cluster/%s", var.cluster_name) = "true"
        }
```

 However, inside Provisioner, the provider is written in yaml format. 
```
    provider:
      blockDeviceMappings:
        - deviceName: /dev/xvda
          ebs:
            volumeSize: 40Gi
            volumeType: gp3
            deleteOnTermination: true
      subnetSelector:
        karpenter.sh/discovery: ${local.name}-${local.env}
      securityGroupSelector:
        karpenter.sh/discovery: ${local.name}-${local.env}
      tags:
        Name: galileo-gpu-${local.env}
        karpenter.sh/discovery: ${local.name}-${local.env}
    ttlSecondsAfterEmpty: 300 # 5 minutes, comment out for indefinite
```

How to add "launchTemplate"  = aws_launch_template.ubuntu_cuda.name into it?
