### ISSUE TITLE
Failed to fetch resource from kubernetes: context deadline exceeded

### ISSUE THREAD

**Issue by garyyang6** [aws/karpenter#2437]
I got, "Error: overprovision/overprovision failed to fetch resource from kubernetes: context deadline exceeded". Below is the related code. Is there anything wrong with the code?

```
resource "kubectl_manifest" "northstar_overprovision" {
  yaml_body = <<-YAML
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: overprovision
    namespace: overprovision
  spec:
    replicas: ${local.overprovision}
    selector:
      matchLabels:
        app: overprovision
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        namespace: overprovision
        labels:
          app: overprovision
      spec:
        terminationGracePeriodSeconds: 0
        priorityClassName: northstar-overprovision
        containers:
        - image: ${local.image}
          name: run
          imagePullPolicy: IfNotPresent
          args:
          - sleep
          - 1d
          resources:
            requests:
              nvidia.com/gpu: 4
              cpu: 32
            limits:
              nvidia.com/gpu: 4
        tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
  YAML

  depends_on = [
    helm_release.karpenter,
    kubectl_manifest.northstar_overprovision_priority
  ]
}
```

**Is an existing page relevant?**

**What karpenter features are relevant?**

**How should the docs be improved?**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
