### ISSUE TITLE
Make it possible to override just an image repo in helm chart

### ISSUE THREAD

**Issue by olfway** [aws/karpenter#2465]
**Tell us about your request**
Split controller.image and webhook.image to repository and version

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'm trying to use local images and right now I have to hardcode version in helm values:
```
controller:
  image: 1234567890.dkr.ecr.eu-west-1.amazonaws.com/mirror/public.ecr.aws/karpenter/controller:v0.16.1

webhook:
  image: 1234567890.dkr.ecr.eu-west-1.amazonaws.com/mirror/public.ecr.aws/karpenter/webhook:v0.16.1
```

It would be easier to override just repository, like:
```
controller:
  image:
    repository: 1234567890.dkr.ecr.eu-west-1.amazonaws.com/mirror/public.ecr.aws/karpenter/controller

webhook:
  image:
    repository: 1234567890.dkr.ecr.eu-west-1.amazonaws.com/mirror/public.ecr.aws/karpenter/webhook
```
and do not hardcode version

**Comment by spring1843** [comment]
Can you link to where you'd like to see this separation? or an example where this overriding ability is implemented?

**Comment by olfway** [comment]
Sure, you can look here

https://github.com/helm/examples/blob/main/charts/hello-world/values.yaml#L7
```
image:
  repository: nginx
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
```

https://github.com/helm/examples/blob/main/charts/hello-world/templates/deployment.yaml#L20
```
image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
```
