### ISSUE TITLE
Allow bringing up nodes in a tainted state

### ISSUE THREAD

**Issue by grosser** [aws/karpenter#2479]
**Tell us about your request**
I want to start my nodes with a taint set and then remove the taint when the node is ready.
This does not work, because I get `Could not schedule pod, incompatible with provisioner \"test\", did not tolerate some-taint"`

nodes are created with taints set, so I cannot use the kubelet option `--register-with-taints`
but what I want is that the node gets added when kubelet starts, so it comes up with the taint and then when https://github.com/kubernetes/node-problem-detector thinks it's healthy we remove the taint.

**Are you currently working around this issue?**
Taint the node from inside the ami startup.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
This should be solved by configuring `startupTaints` in your provisioner:

```yaml
  # Provisioned nodes will have these taints, but pods do not need to tolerate these taints to be provisioned by this
  # provisioner. These taints are expected to be temporary and some other entity (e.g. a DaemonSet) is responsible for
  # removing the taint after it has finished initializing the node.
  startupTaints:
    - key: example.com/another-taint
      effect: NoSchedule
```
