### ISSUE TITLE
Controlled distribution of pods between spot and on-demand nodes

### ISSUE THREAD

**Issue by Adityashar** [aws/karpenter#2508]
### Tell us about your request

As a user, I want my application's pods to get distributed between the spot and on-demand nodes in a controlled ratio, and the ratio should be configurable at an application's level i.e, it could be different for different applications.

Eg. If my workload has 10 pods and I want a 60% spot and 40% on-demand split, then 6 of these pods should go to the spot nodes and the rest to the on-demand nodes.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

We want the workloads to be split across on-demand / spot which can be configured on a per-application/workload level. Current [Documentation](https://karpenter.sh/v0.16.1/tasks/scheduling/#on-demandspot-ratio-split) provides to configure the split on a cluster level altogether. When we tried even the cluster level approach suggested in the documentation, we observed that the splits are no way near the ratios that we want to achieve

### Are you currently working around this issue?

No. 

But we can think of solution involving annotations and custom webhooks with a very high-level perspective. We can provide a split percentage (say 20) to the deployment (say with 20 pods) as an annotation and the custom webhook would inject a nodeSelector / nodeAffinity field within our pod spec. Eg. here 4 (20% of 20) pods would be getting the following spec injected and will get scheduled over the spot nodes- 

```yaml
nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
        - matchExpressions:
        - key: "karpenter.sh/capacity-type"
            operator: "In"
            values: ["spot"]
```

### Additional Context

Adding some results from my experiments with the [on-demand / spot ratio split](https://karpenter.sh/v0.16.1/tasks/scheduling/#on-demandspot-ratio-split) method. 

Created two provisioners, one for spot and the other for on-demand node provisioning and configured capacity-spread label on the two provisioners for a 60% spot (capacity-spread can be 1, 2 or 3) and 40% on-demand (capacity-spread can be 4 or 5) distribution of workload pods.
```yaml
  # spot-provisioner
  requirements:
  - key: "karpenter.sh/capacity-type"
    operator: In
    values: [ "spot"]
  - key: capacity-spread
    operator: In
    values:
    - "2"
    - "3"
    - "1"
    
  # on-demand provisioner
  requirements:
  - key: "karpenter.sh/capacity-type"
    operator: In
    values: [ "on-demand"]
  - key: capacity-spread
    operator: In
    values:
    - "4"
    - "5"

```
Took two scenarios, 

1. Number of topologies = 5
A node exists in each of the 5 topologies created by the capacity-spread label (topologies corresponding to the values - 1, 2, 3, 4 and 5). Deploying an application with X pod count and noting down how many pods are getting scheduled in a specific topology. 

|S. no.|Pod Count|T1     |T2     |T3     |T4          |T5          |Ratio achieved                 |Action performed|
|------|---------|-------|-------|-------|------------|------------|-------------------------------|----------------|
|1     |5        |1      |1      |1      |1           |1           |60:40                          |new deployment  |
|2     |10       |2      |2      |2      |2           |2           |60:40                          |rescaling 1     |
|3     |10       |2      |3      |3      |2           |0           |80:20                          |restarting 2    |
|4     |7        |1      |2      |2      |1           |1           |71:29                          |new             |
|5     |8        |2      |2      |2      |1           |1           |75:25                          |new             |
|6     |8        |2      |1      |2      |2           |1           |62:38                          |restarting 5    |

Ti - Topology created by label `capacity-spread: i`
T1, T2, T3 - Spot 
T4, T5 - on-demand
Ratio - Spot to On-demand 

2. Number of topologies < 5 

|S. no.|Pod Count|T1     |T2     |T3     |T4          |T5          |Ratio achieved                 |Action performed               |
|------|---------|-------|-------|-------|------------|------------|-------------------------------|-------------------------------|
|1     |10       |X      |4      |3      |3           |X           |70:30                          |new deployment                 |
|2     |20       |X      |6      |7      |7           |X           |65:35                          |rescaling 1                    |
|3     |30       |X      |10     |10     |9           |1           |66:34                          |rescaling 2                    |
|4     |40       |X      |14     |X      |13          |13          |35:65                          |new deployment                 |

X - no node exist in this topology

Results in both the situations are uneven, and could vary by large margins from the desired 60-40 split and we should be looking for an absolute solution to this distribution issue.

**Comment by FernandoMiguel** [comment]
is there a reason you want a ration of OD?
karpenter is capable of falling back to OD if there are no Spot available.
you still keep your SLA and QoS.

**Comment by ra-grover** [comment]
@FernandoMiguel Our team has multiple big clusters of the order of 900-1K nodes. If any spot mass termination occurs then that would greatly affect the stability of the clusters. 
Thus we want the split at application level, so that application owners can decide their split.

**Comment by JamesWojewoda** [comment]
I have the same issue right now. It seems the consolidation has brought my cluster to be almost 100% OD, which costs a fortune. It would be nice to have the option to control the max % of OD nodes even at the cost of interruption due to the potential for the cluster to be filled up with OD rather than spot. Setting low expiration TTLs can cause interruptions otherwise.

**Comment by tzneal** [comment]
@Adityashar  Sorry, I'm not following.  Are you setting the `whenUnsatisfiable: DoNotSchedule` on the deployment?  If so, kube-scheduler will not violate the topology spread modulo a few conditions:
- It's only aware of the labels via existing nodes, so if nodes aren't already in your cluster with those labels it may violate your spread.  There is a `minDomains` property in K8s 1.25 that [fixes](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#spread-constraint-definition) this.
- There's no guarantee that the constraints remain satisfied when Pods are removed. For example, scaling down a Deployment may result in imbalanced Pods distribution, see K8s [docs](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#known-limitations).

Something like [descheduler](https://github.com/kubernetes-sigs/descheduler) can help with the second problem.

**Comment by tzneal** [comment]
@JamesWojewoda Since v0.16.1 consolidation actively tries to replace on-demand nodes with spot nodes, are your provisioner and workloads both open to spot and on-demand?

**Comment by JamesWojewoda** [comment]
@tzneal Yes, can confirm I'm on v0.16.1 and the spread has been about 90% on demand/10% Spot since yesterday. I applied the upgrade 2 days ago, along with the fall back of introducing on demand nodes in the config:

```    
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
```

**Comment by tzneal** [comment]
@ra-grover You should be able to support multiple ratio splits with only two provisioners.

Provisioners:
```yaml
  # spot-provisioner
  requirements:
  - key: "karpenter.sh/capacity-type"
    operator: In
    values: [ "spot"]
  - key: capacity-spread
    operator: In
    values:
    - "1-s"
    - "2-s"
    - "3-s"
    - "4-s"
    - "5-s"
    
  # on-demand provisioner
  requirements:
  - key: "karpenter.sh/capacity-type"
    operator: In
    values: [ "on-demand"]
  - key: capacity-spread
    operator: In
    values:
    - "1-od"
    - "2-od"
    - "3-od"
    - "4-od"
    - "5-od"
```

Topology spreads interact with [node selectors and required node affinities](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#interaction-with-node-affinity-and-node-selectors), which you can use:


* 50/50 OD to Spot split
```yaml
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: capacity-spread
        whenUnsatisfiable: DoNotSchedule
```

* 33/66 OD to Spot split:
```yaml
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: capacity-spread
        whenUnsatisfiable: DoNotSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: capacity-spread
            operator: In
            values:
            - 1-s
            - 2-s
            - 1-od
```

* 80/20 OD to Spot split:
```yaml
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: capacity-spread
        whenUnsatisfiable: DoNotSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: capacity-spread
            operator: In
            values:
            - 1-od
            - 2-od
            - 3-od
            - 4-od
            - 1-s
```

**Comment by JamesWojewoda** [comment]
@tzneal Before I do that, we recently increased the TTL for expiry/emptiness to a large amount to prevent interruptions (Node expiry was set to 2 days, emptiness set to 30 seconds) -> (Now at 30 days expiry, emptiness 2 days). Does Karpenter require these values for this consolidation, or should it be automatically handled?

**Comment by tzneal** [comment]
> @tzneal Before I do that, we recently increased the TTL for expiry/emptiness to a large amount to prevent interruptions (Node expiry was set to 2 days, emptiness set to 30 seconds) -> (Now at 30 days expiry, emptiness 2 days). Does Karpenter require these values for this consolidation, or should it be automatically handled?

Emptiness and consolidation are currently mutually exclusive.  Have you turned off emptiness and turned on consolidation by adding to your provisioner spec:
```
  consolidation:
    enabled: true
```

To be aware, consolidation will be deleting your empty nodes faster if you turn it on.

**Comment by JamesWojewoda** [comment]
@tzneal Thanks so much for the recommendations! I will use that and your other suggestion to try and smooth out our Spot vs. OD dilemma

**Comment by Adityashar** [comment]
@tzneal Yes, i am using `DoNotSchedule` in my constraints.
```yaml
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: capacity-spread
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app: pod-x
``` 
<blockquote>
If so, kube-scheduler will not violate the topology spread modulo a few conditions:

- It's only aware of the labels via existing nodes, so if nodes aren't already in your cluster with those labels it may violate your spread. There is a minDomains property in K8s 1.25 that [fixes](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#spread-constraint-definition) this.
- There's no guarantee that the constraints remain satisfied when Pods are removed. For example, scaling down a Deployment may result in imbalanced Pods distribution, see K8s [docs](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#known-limitations).
</blockquote>

Also, I agree with the conditions that you have specified here for topologySpreadConstraints.

1. The large variation in ratio [here](https://github.com/aws/karpenter/issues/2508#:~:text=0-,80%3A20,-restarting%202) during restarts could be controlled through the use of a descheduler.
2. I'm not much sure about this minDomains feature, I'll have to test it first and determine whether this could indeed improve the results for the [second type](https://github.com/aws/karpenter/issues/2508#:~:text=to%20On%2Ddemand-,Number%20of%20topologies,-%3C%205) of my experiments where the nodes are not present in all of the required topologies. Although, this won't be much useful to us since we are currently using the EKS 1.21 and the latest EKS version is itself 1.23.
