### ISSUE TITLE
Support topologySpreadConstraints for multiarch.

### ISSUE THREAD

**Issue by lherring-tii** [aws/karpenter#2513]
### Tell us about your request

```
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: my-app
        maxSkew: 1
        topologyKey: kubernetes.io/arch
        whenUnsatisfiable: DoNotSchedule
```

I have a pod that wants to deploy 50/50 to arm64 and amd64 nodes. I imagine the solution would be to do something like this, so karpenter knows i'm wanting to make sure my app is spread between architectures evenly and spin up an arm64 node for this pod.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

My cluster currently has the ability to spin up arm64 nodes by applying only this to my pod, therefore there is no choice but to spin up an arm64 node and deploy my pod to it.

``` 
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
```

If I were to start afresh, (removing the arm64 node from the cluster) and add in `-amd64` to this example so we have both architectures,  all pods become deployed to amd64 nodes, karpenter does not show interest in spinning up any `arm64` nodes. 

### Are you currently working around this issue?

Yes, I must tell Karpenter to always have at least 1 arm64 node running in the meantime. Though this is not efficient use of funds.

### Additional Context

I may be missing something from my pod spec that supports what I'm trying to do

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment]
take a look at `virtual domains` https://karpenter.sh/preview/tasks/scheduling/#on-demandspot-ratio-split

**Comment by jonathan-innis** [comment]
@lherring-turnitin This issue seems inherent to `topologySpreadConstraints` in general and should hopefully be solved with the [`minDomains` field](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#spread-constraint-definition). 

The work to add `minDomains` to the scheduling considerations is planned work but is currently not implemented in Karpenter.

**Comment by lherring-turnitin** [comment]
@FernandoMiguel it looks like I already had tried this without realising.

provisioner requirements:
```
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
```

And my topologySpreadConstraints as above and didn't get the functionality I was expecting.

I'm trying now with a non well-known key to see if that's the issue.

**Comment by lherring-turnitin** [comment]
Okay, trying with a custom key had interesting results.

It first spun up a new amd64 node with the expected label, then both pods deployed there.

deployment
```
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: my-app
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchLabels:
            app: my-app
        maxSkew: 1
        topologyKey: arch-spread
        whenUnsatisfiable: DoNotSchedule
```

arm64 provisioner (requirements)
```
...
  - key: kubernetes.io/arch
    operator: In
    values:
    - arm64
  - key: arch-spread
    operator: In
    values:
    - arm64
...
```

**Comment by jonathan-innis** [comment]
I would expect the result with virtual domains and just using the `kubernetes.io/arch` label would be the same. The only advantage of virtual domains compared to using the standard key/values is you can increase the number of values (virtual domains) that fall under an actual domain which means you can get percentage based spreads i.e. 20/80 vs a 50/50 spread like you have above. 

I'll open a feature add for `minDomains`. Adding this feature to the scheduler should satisfy this requirement.

**Comment by lherring-turnitin** [comment]
Hm, I managed to get `arch-spread` working, just needed to kick the deployment! I re-tested using `kubernetes.io/arch` and `beta.kubernetes.io/arch` incase the `beta.` was necessary but neither of those worked unfortunately.

**Comment by jonathan-innis** [comment]
Yeah, the more I was thinking about it, I think it should work for topology spread out of the box. Karpenter will consider all possible values for a topology spread to be the ones it is aware of from instance types and from the provisioner requirements. 

In this case, `kubernetes.io/arch` is a well-known label, so Karpenter should know to spread across the two domains `arm64` and `amd64`. I'll do some validation on my side as well but if you are able to get `arch-spread` working, I would expect that `kubernetes.io/arch` should also work...

**Comment by lherring-turnitin** [comment]
Yeah, I would be interested to see if you can re-create what I've been experiencing. It's awkward to create a label that seems to be duplicate values of the `kubernetes.io/arch`

**Comment by xAzigo** [comment]
So the other difference that was in mine is that I have 2 provisioners, with an arch each. Maybe that could be the factor given im sure when I last tested, the only changes I made were swapping between `arch-spread` and `kubernetes.io/arch`. I didn't change `whenUnsatisfiable` and it only worked for the `arch-spread`.

I will give this another check making sure we are set to `DoNotSchedule` and see what happens.

**Comment by lherring-turnitin** [comment]
[So when I last tested](https://github.com/aws/karpenter/issues/2513#issuecomment-1249173835), the only variable I changed was the `topologyKey` and `whenUnsatisfiable` was set to `DoNotSchedule`.  The difference that was in my example to yours is that I have 2 provisioners, with an arch each. Maybe that could be the factor.

I'm testing agains just to be sure.

**Comment by lherring-turnitin** [comment]
one additional note is this problem specifically involves karpenter not spinning up arm nodes for tis.

if the arm node already is running, it spreads between them fine.

**Comment by jonathan-innis** [comment]
To clarify, you have one provisioner that looks like this

```yaml
requirements:
 - key: "karpenter.sh/capacity-type"
    operator: In
    values: ["spot", "on-demand"]
 - key: "kubernetes.io/arch"
    operator: In
    values: ["arm64"]
```

And another that looks like this

```yaml
```yaml
requirements:
 - key: "karpenter.sh/capacity-type"
    operator: In
    values: ["spot", "on-demand"]
 - key: "kubernetes.io/arch"
    operator: In
    values: ["amd64"]
```

While having a Deployment that has the following `topologySpreadConstraints`

```yaml
topologySpreadConstraints:
  - maxSkew: 1
     topologyKey: kubernetes.io/arch
     whenUnsatisfiable: DoNotSchedule
     labelSelector:
       matchLabels:
         app: my-app
```

Is this correct?
