### ISSUE TITLE
web requests to nginx pods are coming as IPv6 when cluster is set as IPv4 single stack

### ISSUE THREAD

**Issue by innovia** [aws/karpenter#2551]
### Version

__Karpenter Version:__ v0.16.2

__Kubernetes Version:__ v1.22.12-eks-ba74326

node tamplate
```yaml

apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  amiFamily: AL2
  instanceProfile: "KarpenterNodeInstanceProfile-{{ .Values.karpenter.clusterName }}"
  metadataOptions:
    httpProtocolIPv6: "disabled"
    httpPutResponseHopLimit: 2
    httpTokens: "optional"
  blockDeviceMappings:
    - deviceName: "/dev/xvda"
      ebs:
        deleteOnTermination: true
        encrypted: true
        iops: {{ .Values.karpenter.nodeTemplates.default.volumeIops }}
        throughput: {{ .Values.karpenter.nodeTemplates.default.volumeThroughput }}
        volumeSize: {{ .Values.karpenter.nodeTemplates.default.volumeSize }}
        volumeType: {{ .Values.karpenter.nodeTemplates.default.volumeType }}
  subnetSelector:
    kubernetes.io/cluster/{{ .Values.karpenter.clusterName }}: shared
  securityGroupSelector:
    karpenter.sh/discovery/{{ .Values.karpenter.clusterName }}: {{ .Values.karpenter.clusterName }}
  tags:
    karpenter.sh/discovery/{{ .Values.karpenter.clusterName }}: {{ .Values.karpenter.clusterName }}
    kubernetes-cluster: {{ .Values.karpenter.clusterName }}
    environment: {{ .Values.environment }}
    aws-node-termination-handler/managed: "true"
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"

    --BOUNDARY
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash
    # Workaround for dd-agent which fails to check disk usage if binfmt_misc isn't mounted before Kubelet comes up
    mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc || true
    echo 1 > /proc/sys/fs/binfmt_misc/status

    # This installs the System Manager agent
    yum install -y amazon-ssm-agent
    systemctl start amazon-ssm-agent
    systemctl enable amazon-ssm-agent
    yum clean all

    TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"`
    LIFE_CYCLE=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/instance-life-cycle)
      KUBELET_EXTRA_ARGS="--node-labels=node.kubernetes.io/lifecycle=${LIFE_CYCLE}"
      # End of script used as a separator for concatenating other scripts

     # Tweak Kubelet Configuration
     echo "$(jq '.registryPullQPS=500' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json
     echo "$(jq '.registryBurst=100' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json
     echo "$(jq '.evictionHard."memory.available"="10%"' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json
--BOUNDARY--
```

provisioner

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: on-demand-provisioner
spec:
  consolidation:
    enabled: {{ .Values.consolidate }}
  weight: 1
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    # Look for instances with memory larger than 2GB
    - key: "karpenter.k8s.aws/instance-memory"
      operator: NotIn
      values:
        - "512"
        - "1024"
        - "2048"
        - "4096"
    # Look for instances with cpus greater than 4
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: NotIn
      values:
        - "1"
        - "2"
        - "4"
    # Exclude burstable families
    - key: "karpenter.k8s.aws/instance-family"
      operator: NotIn
      values:
        - "t1"
        - "t2"
        - "t3"
        - "t3a"
        - "t4"
        - "t4g"
        - "c5a"
        - "c6a"
        - "m5a"
        - "m6a"
        - "r5a"
        - "r6a"
    # Exclude Graviton Instances
    - key: "kubernetes.io/arch"
      operator: In
      values:
        - "amd64"
    # taints requirements
    - key: "node.kubernetes.io/lifecycle"
      operator: In
      values: ["on-demand"]
  # Limits prevent Karpenter from creating new instances once the limit is exceeded.
  limits:
    resources:
      cpu: 1000
  # name of node template to reference
  providerRef:
    name: default
  {{- if not .Values.consolidate }}
  ttlSecondsAfterEmpty: 5  # scale down nodes after 15 seconds without workloads (excluding daemons)
  {{- end }}
  # Setting a value here enables node expiry. After nodes reach the defined age in seconds, they will be deleted, even if in use.
  # This enables nodes to effectively be periodically “upgraded” by replacing them with newly provisioned instances.
  ttlSecondsUntilExpired: {{ .Values.ttlSecondsUntilExpired }}

```

we experience lots of connection refused like so

```
2022/09/23 20:57:48 [error] 7#7: *3994 connect() failed (111: Connection refused) while connecting to upstream, client: 54.203.69.179, server: _, request: "GET /api/v2/deployments/?cluster_id=1&multi_tenant=true&page_number=1&page_size=200 HTTP/1.1", upstream: "http://[::1]:8080/api-internal/v2/deployments/?cluster_id=1&multi_tenant=true&page_number=1&page_size=200", host: "xyz.app-domain.com"
```

this doesn't happen on non karpenter nodes - we reverted the karpneter setup and the errors stopped

its using the same AMI for both karpenter and asg self managed nodes: 
`amazon-eks-node-1.22-v20220914`
`ami-0f2b7c6874eb8414f`

We can not find any difference in karpenter and the self managed nodes, the only thing I can think of is the bootstrap script that somehow does enable ipv6 even though the cluster is single stack ipv4

### Expected Behavior

no errors, calls should be `127.0.0.1:8080` and not `[::1]:8080`

### Actual Behavior

requests err on nginx detecting ipv6

### Steps to Reproduce the Problem

run nginx with proxy pass to gunicorn and use the same setup as above for karpenter 

### Resource Specs and Logs

```
2022/09/23 20:57:48 [error] 7#7: *3994 connect() failed (111: Connection refused) while connecting to upstream, client: 54.203.69.179, server: _, request: "GET /api/v2/deployments/?cluster_id=1&multi_tenant=true&page_number=1&page_size=200 HTTP/1.1", upstream: "http://[::1]:8080/api-internal/v2/deployments/?cluster_id=1&multi_tenant=true&page_number=1&page_size=200", host: "server.domain.com"

```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
