### ISSUE TITLE
Improve docs on topology spread across zones

### ISSUE THREAD

**Issue by chrisnegus** [aws/karpenter#2572]
### Is an existing page relevant?

https://karpenter.sh/v0.16.3/tasks/scheduling/#topology-spread

### What karpenter features are relevant?

Using topologySpreadConstraints in pod scheduling to balance pods across multiple zones.

### How should the docs be improved?

Until a pod has been scheduled to a zone, the Kubernetes scheduler doesn't know that the zone exists. So if, for example, you wanted to use topologySpreadConstraints to spread pods across zone-a, zone-b, and zone-c, if the Kubernetes scheduler has scheduled pods to zone-a and zone-b, but not zone-c, it would only spread pods across nodes in zone-a and zone-b and never create nodes on zone-c.

I'm proposing to update the documentation to describe workarounds to this problem in the [Topology Spread](https://karpenter.sh/v0.16.3/tasks/scheduling/#topology-spread) documentation. This could include doing things like launching a pause container to each zone you want the scheduler to use before launching the pods you want to spread across those zones.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by hawkesn** [comment]
I did a bit of a dive into this topic because I was running into this issue. I was able to solve this by what you suggested @chrisnegus using the following pause pods:

```
---
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: az-headroom
value: -1
globalDefault: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-headroom
  labels:
    app: az-headroom
spec:
  replicas: 3 # As many AZs as you have
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: az-headroom
  template:
    metadata:
      labels:
        app: az-headroom
      annotations: 
    spec:
      priorityClassName: az-headroom
      containers:
        - image: k8s.gcr.io/pause
          imagePullPolicy: IfNotPresent
          name: az-headroom
          resources:
            requests:
              cpu: 4 # Set to whatever
              memory: 4 Gi # Set to whatever
      nodeSelector:
        nodegroup: myNodeGroupIWantAcrossAZs
      tolerations:
      - operator: Exists
        effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
                matchLabels:
                  app: az-headroom
            topologyKey: topology.kubernetes.io/zone
```

This is a similar approach to how the `cluster-proportional-autoscaler` works for overprovisioning.

However, if you're on Kubernetes 1.25, you may be able to use the new `minDomains` feature:
https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#spread-constraint-definition

```
minDomains indicates a minimum number of eligible domains. This field is optional. A domain is a particular instance of a topology. An eligible domain is a domain whose nodes match the node selector.
```
Which would let you use `topologySpreadConstraints` instead of `podAntiAffinity`.

**Comment by FernandoMiguel** [comment]
we been using this with success, assuming there are pre-existing karpenter nodes in all AZs
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
  labels:
    app: inflate
spec:
  selector:
    matchLabels:
      app: inflate
  replicas: 2
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.5
          resources:
            requests:
              cpu: 3
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: inflate
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
        - labelSelector:
            matchLabels:
              app: inflate
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
```

we use this deployment, one per AZ in the ENIConfig to force karpenter to create one node in each AZ
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate-${az}
  labels:
    app: inflate
spec:
  selector:
    matchLabels:
      app: inflate
  replicas: 1
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.5
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: inflate
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
        topology.kubernetes.io/zone: ${az}
```
