### ISSUE TITLE
Getting `invariant violated: spec.provider is not defined` when using `providerRef`

### ISSUE THREAD

**Issue by apamildner** [aws/karpenter#2585]
### Version

__Karpenter Version:__ v0.16.3

__Kubernetes Version:__ v1.22.0

### Expected Behavior

I ran the following terraform code, trying to install karpenter into my EKS cluster, trying to install a default provisioner and
a default `AWSNodeTemplate`. I expected this to work, and that when there are unschedulable pods karpenter would spin up new nodes. 

### Actual Behavior

When I look at the logs I get the following error
```bash
k get pods | grep karpenter                                                                                                                                                                  х 
karpenter-77bb58dc6c-7j44z   2/2     Running   0          25m
karpenter-77bb58dc6c-brpbc   2/2     Running   0          25m
```
And then, for example, `k logs karpenter-77bb58dc6c-7j44z` gives me
```
...
2022-10-03T09:41:42.303Z	INFO	controller	Starting workers	{"commit": "5d4ae35-dirty", "controller": "provisioner-state", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "worker count": 10}
2022-10-03T09:41:42.303Z	INFO	controller	Starting workers	{"commit": "5d4ae35-dirty", "controller": "node", "controllerGroup": "", "controllerKind": "Node", "worker count": 10}
2022-10-03T09:41:42.303Z	INFO	controller	Starting workers	{"commit": "5d4ae35-dirty", "controller": "termination", "controllerGroup": "", "controllerKind": "Node", "worker count": 10}
2022-10-03T09:41:42.304Z	INFO	controller	Starting workers	{"commit": "5d4ae35-dirty", "controller": "counter", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "worker count": 10}
2022-10-03T09:41:42.306Z	INFO	controller	Starting workers	{"commit": "5d4ae35-dirty", "controller": "provisionermetrics", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "worker count": 1}
2022-10-03T09:41:52.509Z	ERROR	controller.consolidation	consolidating cluster, determining candidate nodes, listing instance types for default, invariant violated: spec.provider is not defined. Is the validating webhook installed?	{"commit": "5d4ae35-dirty"}
2022-10-03T09:42:02.510Z	ERROR	controller.consolidation	consolidating cluster, determining candidate nodes, listing instance types for default, invariant violated: spec.provider is not defined. Is the validating webhook installed?	{"commit": "5d4ae35-dirty"}
2022-10-03T09:42:12.511Z	ERROR	controller.consolidation	consolidating cluster, determining candidate nodes, listing instance types for default, invariant violated: spec.provider is not defined. Is the validating webhook installed?	{"commit": "5d4ae35-dirty"}
```

### Steps to Reproduce the Problem

My terraform code is as follows, where I have tried to follow the docs (aws provisioning docs)[https://karpenter.sh/v0.16.3/aws/provisioning/]. Also, I am confused since the "get started with terraform docs" (get started with terraform)[https://karpenter.sh/v0.16.3/getting-started/getting-started-with-terraform/) deviates from what is described in the aws provisioning docs. This terraform code is based on the `aws provisioning docs` since it felt more up to date, but this may be the root of the issues I'm facing.

### Resource Specs and Logs

```hcl
locals {
  karpenter_discovery_tag = "karpenter.sh/discovery/${var.cluster_name}"
}
module "karpenter_irsa" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "~> v5.5.0"

  role_name                          = "karpenter-controller-${var.cluster_name}"
  attach_karpenter_controller_policy = true

  karpenter_controller_cluster_id = module.eks.cluster_id
  karpenter_controller_ssm_parameter_arns = [
    "arn:${local.partition}:ssm:*:*:parameter/aws/service/*"
  ]
  karpenter_controller_node_iam_role_arns = [
    module.eks.eks_managed_node_groups["karpenter"].iam_role_arn
  ]
  oidc_providers = {
    main = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["karpenter:karpenter"]
    }
  }
}

resource "aws_iam_instance_profile" "karpenter" {
  name = "KarpenterNodeInstanceProfile-${var.cluster_name}"
  role = module.eks.eks_managed_node_groups["karpenter"].iam_role_name
}

resource "helm_release" "karpenter" {
  namespace        = "karpenter"
  create_namespace = true
  force_update     = true

  name       = "karpenter"
  repository = "https://charts.karpenter.sh"
  chart      = "karpenter"
  version    = "0.16.3"

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = module.karpenter_irsa.iam_role_arn
  }

  set {
    name  = "clusterName"
    value = module.eks.cluster_id
  }

  set {
    name  = "clusterEndpoint"
    value = module.eks.cluster_endpoint
  }

  set {
    name  = "aws.defaultInstanceProfile"
    value = aws_iam_instance_profile.karpenter.name
  }
}

# Workaround - https://github.com/hashicorp/terraform-provider-kubernetes/issues/1380#issuecomment-967022975
resource "kubectl_manifest" "karpenter_provisioner" {
  yaml_body = <<-YAML
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type         # optional, set to on-demand by default, spot if both are listed
      operator: In
      values: ["spot"]
  limits:
    resources:
      cpu: 1000                               # optional, recommended to limit total provisioned CPUs
      memory: 1000Gi
  providerRef:                                # optional, recommended to use instead of `provider`
    name: default
  ttlSecondsAfterEmpty: 30                    # optional, but never scales down if not set
  ttlSecondsUntilExpired: 2592000             # optional, but never expires if not set
  YAML

  depends_on = [
    helm_release.karpenter
  ]
}
resource "kubectl_manifest" "karpenter_aws_node_template" {
  yaml_body = <<-YAML
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:                             # required
    ${local.karpenter_discovery_tag}: ${var.cluster_name}
  securityGroupSelector:                      # required
   ${local.karpenter_discovery_tag}: ${var.cluster_name}
  YAML

  depends_on = [
    helm_release.karpenter
  ]
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Hi @apamildner, the terraform documentation on the [terraform guide[(https://karpenter.sh/v0.16.3/getting-started/getting-started-with-terraform/) is not maintained by the Karpenter team. 

For this issue, can you get the webhook logs of your pods to make sure the webhook is running?  You can do that with`kubectl logs $pod_name -n karpenter -c webhook`

**Comment by apamildner** [comment]
I realized my provisioner was not recreated when I re-applied my terraform, or something along those lines. So everything works now when I use the provider spec as this (and as described by the docs..):
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type         # optional, set to on-demand by default, spot if both are listed
      operator: In
      values: ["spot"]
  limits:
    resources:
      cpu: 1000                               # optional, recommended to limit total provisioned CPUs
      memory: 1000Gi
  providerRef:                                # optional, recommended to use instead of `provider`
    name: default
  ttlSecondsAfterEmpty: 30                    # optional, but never scales down if not set
  ttlSecondsUntilExpired: 2592000             # optional, but never expires if not set
```
And node template:
```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:                             # required
    ${local.karpenter_discovery_tag}: ${var.cluster_name}
  securityGroupSelector:                      # required
   ${local.karpenter_discovery_tag}: ${var.cluster_name}
  tags:
    ${local.karpenter_discovery_tag}: ${var.cluster_name}
```
For anyone struggling like me with this, I have two other hints that may help and I'll just leave them here:
1. Remember to properly tag launch templates created elsewhere with the proper karpenter discovery tag if you want karpenter to use them
2. When you create an [IRSA]( "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"), remember that you may need to explicitly pass the parameter 
``` hcl 
# This karpenter_tag_key is important if we want to use a custom discovery tag per cluster.
  karpenter_tag_key               = local.karpenter_discovery_tag
  ```
  Closing this, as the original issue wasn't really a bug. Thanks nonetheless for the answer!
