### ISSUE TITLE
blockDeviceMapping for ebs volumeSize doesn't follow unit correctly.

### ISSUE THREAD

**Issue by ROunofF** [aws/karpenter#2593]
### Version

__Karpenter Version:__ v0.16.2

__Kubernetes Version:__ v1.23.10

### Expected Behavior

When using a blockDeviceMapping
```
 blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 200Gi
```

I expect an EBS volume of 200GiB

### Actual Behavior

I'm getting a volume of 215GiB (and I get 200GiB if I put 200G while I should get ~187GiB)

### Steps to Reproduce the Problem

Override the EBS volume in a blockDeviceMapping and validate the size provision from the console/node.

### Resource Specs and Logs

```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: node-storage
spec:
  instanceProfile: karpenter-tf2-managed-ondemand
  securityGroupSelector:
    karpenter.sh/discovery/karpenter-tf2: karpenter-tf2
  subnetSelector:
    Name: karpenter-tf2-private*
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 200Gi
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
