### ISSUE TITLE
Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:karpenter:karpenter" cannot list resource "namespaces" in API group "" at the cluster scope

### ISSUE THREAD

**Issue by ishworg** [aws/karpenter#2702]
### Version

__Karpenter Version:__ v0.16.2

__Kubernetes Version:__ v1.23.10-eks-15b7512

### Expected Behavior

Karpenter by default is able to scale out nodes and more importantly the RBAC is correct.

Open to better ways of doing this :) 

### Actual Behavior

Cluster admins _do_ need to modify RBAC to fix it to list namespace at *cluster* scope.
```
E0729 01:51:55.864520       1 reflector.go:138] k8s.io/client-go@v0.21.4/tools/cache/reflector.go:167: Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:karpenter:karpenter" cannot list resource "namespaces" in API group "" at the cluster scope
```

### Steps to Reproduce the Problem

Helm install (clean room) a Karpenter chart v0.16.2
```
helm -n karpenter list                                       
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
karpenter       karpenter       19              2022-10-18 05:37:18.790623665 +0000 UTC deployed        karpenter-0.16.2        0.16.2    
```

inflate and test.

### Resource Specs and Logs

```
helm -n karpenter get values karpenter  
USER-SUPPLIED VALUES:
aws:
  defaultInstanceProfile: KarpenterNodeInstanceProfile-xxxx
clusterEndpoint: https://xxxx.gr7.ap-southeast-2.eks.amazonaws.com
clusterName: xxxx
logEncoding: json
logLevel: info
replicas: 3
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xx:role/karpenter-xxxx
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
