### ISSUE TITLE
Karpenter 0.18.1 not in https://charts.karpenter.sh/

### ISSUE THREAD

**Issue by funes79** [aws/karpenter#2729]
### What karpenter features are relevant?

Deployment

### How should the docs be improved?

The latest available version is 0.16.1 in https://charts.karpenter.sh/ and according to the docs (https://karpenter.sh/v0.18.1/getting-started/getting-started-with-terraform/) the OCI url should be used. However in ArgoCD the OCI url is not recognized:
```
rpc error: code = Unknown desc = `helm pull --destination /tmp/5c46eac2-2448-48e2-bbe0-814efae2f904 --version 0.18.1 --repo oci://public.ecr.aws/karpenter karpenter` failed exit status 1: Error: looks like "oci://public.ecr.aws/karpenter" is not a valid chart repository or cannot be reached: object required
```

So what should I use in the Helm chart definition for Karpenter?

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-eks
  namespace: argocd
spec:
  destination:
    namespace: karpenter
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: karpenter
    repoURL: oci://public.ecr.aws/karpenter
    # #https://charts.karpenter.sh/
    targetRevision: v0.18.1
```

It would be good to have a clear docs about how to proceed with these changes when the Karpenter is deployed via Helm in Argo. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by spring1843** [comment]
Are you able to share the helm version? helm started working with OCI since v3.8.0+ as per notes [here](https://karpenter.sh/v0.18.1/upgrade-guide/#upgrading-to-v0170).

**Comment by funes79** [comment]
I am using ArgoCD v2.4.6+a48bca0 with Helm v3.8.1+g5cb9af4. But the repo url: `oci://public.ecr.aws/karpenter` does not work.

**Comment by spring1843** [comment]
I noticed that
`helm pull --destination /tmp/5c46eac2-2448-48e2-bbe0-814efae2f904 --version v0.18.1 --repo oci://public.ecr.aws/karpenter/ karpenter` doesn't work but

`helm pull --destination /tmp/5c46eac2-2448-48e2-bbe0-814efae2f904 --version v0.18.1 oci://public.ecr.aws/karpenter/karpenter`

Works. Somehow you got to get rid of that --repo flag.

This maybe a good question to ask ArgoCD, e.g. how do you consume OCI images in ArgoCD.

**Comment by funes79** [comment]
Tried the URL without `oci` but it seems not working.

With:
```
spec:
  destination:
    namespace: karpenter
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: karpenter
    repoURL: public.ecr.aws
```
the error is:
```
rpc error: code = Unknown desc = `helm pull oci://public.ecr.aws/karpenter --version 0.18.1 --destination /tmp/cd5f0caf-4507-4a3b-875c-4653f3dd870d` failed exit status 1: Error: public.ecr.aws/karpenter:0.18.1: not found
```
```
spec:
  destination:
    namespace: karpenter
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: karpenter
    repoURL: public.ecr.aws/karpenter
    # oci://public.ecr.aws/karpenter/karpenter 
    targetRevision: 0.18.1
```

Another attempt:

```
rpc error: code = Unknown desc = `helm pull oci://public.ecr.aws/karpenter/karpenter --version 0.18.1 --destination /tmp/517a6ff7-5b73-4cc5-8d2d-a5a43be304e2` failed exit status 1: Error: public.ecr.aws/karpenter/karpenter:0.18.1: not found
```

also tried 
```
spec:
  destination:
    namespace: karpenter
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: karpenter
    repoURL: public.ecr.aws/karpenter/karpenter
    # oci://public.ecr.aws/karpenter/karpenter 
    targetRevision: 0.18.1
```
similar error
```
ComparisonError: rpc error: code = Unknown desc = `helm pull oci://public.ecr.aws/karpenter/karpenter --version 0.18.1 --destination /tmp/3250ec2d-cc14-4ed7-8f2d-2447aa470026` failed exit status 1: Error: public.ecr.aws/karpenter/karpenter:0.18.1: not found/tmp/6b65e11a-4259-4b13-a175-dae1e573a1b1` failed exit status 1: Error: public.ecr.aws/karpenter/karpenter/karpenter:0.18.1: not found
```

**Comment by bwagner5** [comment]
You'll need the `v` in the version (`v0.18.1`) as described here: https://karpenter.sh/preview/upgrade-guide/#:~:text=If%20you%20were%20not%20prepending%20a%20v%20to%20the%20version%20(i.e.%200.17.0)%2C%20you%20will%20need%20to%20do%20so%20with%20the%20OCI%20chart%2C%20v0.17.0.

**Comment by spring1843** [comment]
That should resolve it @funes79 please feel free to reopen otherwise.

**Comment by funes79** [comment]
Yes thanks, so the correct yaml is
```
    chart: karpenter
    repoURL: public.ecr.aws/karpenter
    targetRevision: v0.18.1
```

**Comment by totogtr** [comment]
Hi @funes79 , out of interest how to you declare clusterName and clusterEndpoint in the Application manifest ? I'm trying to do that in a declarative way but since this value will change from cluster to cluster I haven't found an easy solution.

**Comment by funes79** [comment]
@totogtr the cluster name for the given manifest file is fixed, as the manifest is to deploy the Karpenter to the given EKS. (we do not change EKS so often).
And the cluster endpoint is also defined by the EKS, so unless we recreate the EKS we do not need to change it.
Here is the full yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-eks1
  namespace: argocd
spec:
  destination:
    namespace: karpenter
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: karpenter
    repoURL: public.ecr.aws/karpenter
    targetRevision: v0.18.1
    helm:
      releaseName: karpenter
      parameters:
        - name: clusterName
          value: 'eks1'
        - name:  'aws.defaultInstanceProfile'
          value: 'KarpenterNodeInstanceProfile-eks1'
        - name: clusterEndpoint
          value: 'https://xxxxxxxxxxxxxxxxxxxxxx.gr7.eu-west-1.eks.amazonaws.com'
        - name: 'serviceAccount.annotations.eks\.amazonaws\.com/role-arn'
          value: arn:aws:iam::xxxxxxxxxxxxxxxxxxx:role/karpenter-controller-eks1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}       
  ignoreDifferences:
  - group: '*'
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
    jqPathExpressions:  
    - .data
  - group: '*'
    kind: MutatingWebhookConfiguration
    name: defaulting.webhook.provisioners.karpenter.sh
    jqPathExpressions:  
    - .webhooks[0].rules[]
  - group: '*'
    kind: ValidatingWebhookConfiguration
    name: validation.webhook.provisioners.karpenter.sh
    jqPathExpressions:  
    - .webhooks[0].rules[]
```
