### ISSUE TITLE
Karpenter Provisioner doesn't respect pod's upper memory limit

### ISSUE THREAD

**Issue by disparo13** [aws/karpenter#2743]
### Version

__Karpenter Version:__ v0.18.1

__Kubernetes Version:__ v1.23.10

### Expected Behavior

Karpenter should check the "Pending" pod's memory upper limit and create a node with the needed amount of RAM.

### Actual Behavior

Even if in the Deployment set the limit to 6 gigs of RAM - Karpenter will create a node with a lower amount of RAM, so that limit can never be reached.

### Steps to Reproduce the Problem

Deploy Karpenter with such provisioner configuration:
```
  apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: karpenter-provisioner
  spec:
    consolidation:
      enabled: true
    requirements:
      - key: "karpenter.k8s.aws/instance-category"
        operator: In
        values: ["c", "m"]
      - key: "karpenter.k8s.aws/instance-cpu"
        operator: In
        values: ["2", "4", "8"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand"]
    limits:
      resources:
        cpu: 100
    providerRef:
      name: karpenter-template
```

Create deployment setting upper limit to 6 gigabytes of RAM:
```
resources:
    limits:
       memory: 6Gi
    requests:
       cpu: 800m
       memory: 256Mi
```

Scale your deployment, and Karpenter will always create a "c6a.large" type of node with 4 Gb RAM in any case.

### Resource Specs and Logs

Karpenter provisioner configuration:
```
  apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: karpenter-provisioner
  spec:
    consolidation:
      enabled: true
    requirements:
      - key: "karpenter.k8s.aws/instance-category"
        operator: In
        values: ["c", "m"]
      - key: "karpenter.k8s.aws/instance-cpu"
        operator: In
        values: ["2", "4", "8"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand"]
    limits:
      resources:
        cpu: 100
    providerRef:
      name: karpenter-template
```

Resources configuration for the Deployment:
```
resources:
    limits:
       memory: 6Gi
    requests:
       cpu: 800m
       memory: 256Mi
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
