### ISSUE TITLE
Karpenter not respecting daemonsets resources

### ISSUE THREAD

**Issue by JoseAlvarezSonos** [aws/karpenter#2751]
### Version

__Karpenter Version:__ v0.18.1

__Kubernetes Version:__ v1.23.9 (EKS)

### Expected Behavior

When scaling up, Karpenter should calculate the "reserved" CPU needs for all DaemonSets from all namespaces and from there calculate the amount of instances needed for the "non-scheduled" pods. The expected behaviour in the end should be that for all new nodes all DaemonSets should always be up and running without any resources issues.

### Actual Behavior

From time to time, we have scales up where multiple pods are created at the same time, it can go from 15 to 4k Pods. In this situations, there are some Pods from DaemonSets that won't get scheduled with the error " 0/X nodes are available: 1 Insufficient cpu, X node(s) didn't match Pod's node affinity/selector.". 

We have tried adding priorityClass and nothing has really improved. All of the DaemonSets have proper resource definitions. Plus, this error seems random, so not really a deterministic way to find other reasons.

It's worth mentioning that I found some old similar issues which where technically solved in older versions. Also, this happens in Provisioners regardless of the feature "consolidation".

### Steps to Reproduce the Problem

Install multiple DaemonSets like:
- aws-node
- ebs-csi-node
- efs-csi-node
- fluentd
- kube-proxy
- node-local-dns
- aws-otel-agent
- falco
- falco-exporter
- prometheus-prometheus-node-exporter

Install Karpenter and then try to autoscale thousands or hundreds Pods multiple times and the error should appear.

### Resource Specs and Logs

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: example
  namespace: karpenter
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: karpenter
    helm.sh/chart: karpenter-1.0.0
    helm.sh/release: "karpenter"
    helm.sh/heritage: "Helm"
spec:
  ttlSecondsAfterEmpty: 300
  weight: 100
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: karpenter.k8s.aws/instance-hypervisor
      operator: In
      values: ["nitro"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values:
      - m6i.xlarge
      - m6i.2xlarge
      - m6i.4xlarge
      - m6i.8xlarge
      - m6i.12xlarge
  limits:
    resources:
      cpu: "5k"
  providerRef:
    name: default
  ttlSecondsUntilExpired: 10080
  taints:
    - effect: NoSchedule
      key: key_name
      value: value_name
  labels:
    key_name: value_name
```

There aren't any warnings, nor errors in the log's controller.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by spring1843** [comment]
>It's worth mentioning that I found some old similar issues which where technically solved in older versions.

Can you link to those issues?

**Comment by spring1843** [comment]
Karpenter looks at pending pods and reacts on that by launching new nodes so this behavior is expected but maybe it's a feature request?

**Comment by ellistarn** [comment]
We check the schedulability of daemonsets and include it in simulations. Sometimes, daemonsets with specific scheduling constraints can cause us to not know whether or not they will schedule, so they don't get included in the node sizing decision. However, if you use a high priority on your daemonset, then some of your workload pods will fail to schedule, and will simply get caught/healed in the next provisioning loop (and potentially later consolidated).

**Comment by mqsoh** [comment]
Ah, you're right. The priority class name works fine for me. My secondary issue was actually that I was adding another daemon set but my managed node group had nodes that were too small to accommodate anything else.

**Comment by JoseAlvarezSonos** [comment]
> > It's worth mentioning that I found some old similar issues which where technically solved in older versions.
> 
> Can you link to those issues?

Hello @spring1843 , sure, here are the ones I found related to this issue:
- https://github.com/aws/karpenter/issues/2309
- https://github.com/aws/karpenter/issues/2250
- https://github.com/aws/karpenter/issues/1649

Regarding the priority class, yeah, most of our DaemonSets have system-node-critical or system-cluster-critical, but personally I feel that it shouldn't matter, if a Pod either from a DaemonSet or Deployment is meant to run in one node ... Karpenter should proactively respect that and not wait for kube to evict some other Pods and then wait for Karpenter to spawn another node. 
For example, in our particular situation, some of these workloads are ML related, and they have a long grace period time due to some cleanup they do and push results to different places, plus when they start ... oh boy, they start all-in so even if kube tries to evict them ... they won't, and we designed them like this because we needed to make sure that the Pod did always certain things that could take some time to finish.
So when we added the high priority classes I do have to admit that frequency of the issue was reduced but it still happens from time to time, whenever the "Pod surge" is small is way less likely, but when the "Pod surge" is big it will for certain happen at least for 1 Pod and again it would be nice that Karpenter calculates the proper "deamonset reserved CPU" and took it into account, or it could be a configuration where you could explicitly say "always remove X% CPU and Y% memory when calculating the required CPU", not sure if it makes sense but just throwing random ideas.

Thanks for the follow up btw 👍

**Comment by tzneal** [comment]
Are you using VPA on your daemonsets?  We do calculate the sum of all of the daemonset resources to ensure that there is enough space.  If a DS is modified after that, it could lead to pods not scheduling.

**Comment by cdenneen** [comment]
Running 0.19.0 still issue.
Currently I'm having it with DaemonSet for `newrelic-bundle-nrk8s-kubelet`:

```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-11-18T02:06:16Z"
    message: '0/7 nodes are available: 1 Insufficient cpu. preemption: 0/7 nodes are
      available: 7 No preemption victims found for incoming pod.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable
```

if I change the `spec.template.spec.priorityClassName: system-node-critical` on the DS it actually schedules but it booted another pod from another DS off that node. I don't think it's likely that every DS will be setting a priorityClassName and therefore Karpenter should scale and rebalance.

**Comment by JoseAlvarezSonos** [comment]
Hello @tzneal , no we don't use VPA at all, so the resources are pretty fixed.

**Comment by ellistarn** [comment]
Interesting. Looks like our scheduler doesn't think that the daemonset can schedule. I see your provisioner has
```
  taints:
    - effect: NoSchedule
      key: key_name
      value: value_name
```
Does your daemonset tolerate this? Can you share the pod spec?

**Comment by JoseAlvarezSonos** [comment]
@ellistarn yes, all of our daemonsets have:
```
tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Exists
```

**Comment by ellistarn** [comment]
From the snippit you shared, you'd need 
```
tolerations:
    - effect: NoSchedule
      key: key_name
      operator: Exists
```
