### ISSUE TITLE
Pods with ephemeral storage requests don't fit on valid instance type

### ISSUE THREAD

**Issue by anthropic-eli** [aws/karpenter#2797]
### Version

__Karpenter Version:__ 0.13.2

__Kubernetes Version:__ v1.21.14-eks-6d3986b

### Expected Behavior

Re-raising #1563

Karpenter should be able to schedule pods to nodes when ephemeral-storage requests are defined in the pod spec.

### Actual Behavior

Karpenter claims it can't find an instance type that satisfies the resource requests and fails to provision nodes for the pods. This is despite the ephemeral-storage request for 17Gi on an r5d.24xlarge or i3.metal, both of which have ample ephemeral-storage capacity. Requesting 1Gi works, though...

### Steps to Reproduce the Problem

1. Deploy Karpenter on a cluster
2. Apply the provisioner manifest outlined below
3. Apply the deployment manifest outlined below

### Resource Specs and Logs

Provisioner spec:
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  providerRef:
    name: default
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
    - on-demand
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - i4i.metal
    - i3.metal
    - m5d.24xlarge
    - r5d.24xlarge
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  ttlSecondsAfterEmpty: 30
```

Pod spec:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                      - r5d.24xlarge
                      - i3.metal
                  - key: node.kubernetes.io/instance-type
                    operator: NotIn
                    values:
                      - p4d.24xlarge
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 93
                ephemeral-storage: 17Gi
```

Karpenter controller logs:
```
karpenter-99769fc7d-4fpmz controller 2022-11-03T23:23:30.908Z   ERROR   controller.provisioning Could not schedule pod, incompatible with provisioner "default", no instance type satisfied resources {"cpu":"93","ephemeral-storage":"17Gi","pods":"1"} and requirements karpenter.sh/capacity-type In [on-demand spot], karpenter.sh/provisioner-name In [default], node.kubernetes.io/instance-type In [i3.metal r5d.24xlarge], kubernetes.io/arch In [amd64]      {"commit": "062a029", "pod": "default/inflate-58c99b8b6f-zzb4s"}

karpenter-99769fc7d-4fpmz controller 2022-11-03T23:23:30.908Z   DEBUG   controller.events       Warning {"commit": "062a029", "object": {"kind":"Pod","namespace":"default","name":"inflate-58c99b8b6f-zzb4s","uid":"d5577f0f-e94a-4346-bfb6-d7e92748366c","apiVersion":"v1","resourceVersion":"159895296"}, "reason": "FailedProvisioning", "message": "Failed to provision new node, incompatible with provisioner \"default\", no instance type satisfied resources {\"cpu\":\"93\",\"ephemeral-storage\":\"17Gi\",\"pods\":\"1\"} and requirements karpenter.sh/capacity-type In [on-demand spot], karpenter.sh/provisioner-name In [default], node.kubernetes.io/instance-type In [i3.metal r5d.24xlarge], kubernetes.io/arch In [amd64]"}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
