### ISSUE TITLE
 karpenter.sh/initialized: true does not get applied to any Node

### ISSUE THREAD

**Issue by rwilliams-r7** [aws/karpenter#2833]
### Version

__Karpenter Version:__ v0.18.1

__Kubernetes Version:__ v1.23 (AWS EKS)

### Expected Behavior

Karpenter should bring nodes up as requested and when initialized should label the instance with `karpenter.sh/initialized: true`

On version v0.18.1 the label `karpenter.sh/initialized: true` is not set on ANY new instance. 

This leads to such behaviour problems as deleting and consolidation not working as expected, in this case not removing or consolidating any nodes.

This has a huge cost hit.

Note this nodes have been used correctly by pods.

### Actual Behavior

New nodes are correctly bought up and when ready should be labeled with `karpenter.sh/initialized: true`.

This then allows the behaviours to work as expected such as deletion and consolidation.

### Steps to Reproduce the Problem

Bring up any node with version v0.18.1 and look at the labels you will see they are not labeled correctly.

To see the nodes are not labeled correctly we ran `kubectl get node -L karpenter.sh/initialized` see below for command output.

### Resource Specs and Logs

`kubectl get node -L karpenter.sh/initialized`

```
NAME                           STATUS     ROLES    AGE     VERSION               INITIALIZED
ip-xxx.ec2.internal    Ready      <none>   36m     v1.23.9-eks-ba74326
ip-xxx.ec2.internal    Ready      <none>   37m     v1.23.9-eks-ba74326
ip-xxx.ec2.internal    Ready      <none>   37m     v1.23.9-eks-ba74326
ip-xxx.ec2.internal   Ready      <none>   14m     v1.23.9-eks-ba74326
ip-xxx.ec2.internal    Ready      <none>   3h14m   v1.23.9-eks-ba74326
ip-xxx.ec2.internal    Ready      <none>   14m     v1.23.9-eks-ba74326
ip-xxx.ec2.internal    Ready      <none>   37m     v1.23.9-eks-ba74326
ip-xxx.ec2.internal   Ready      <none>   14m     v1.23.9-eks-ba74326
ip-xxx.ec2.internal   Ready      <none>   37m     v1.23.9-eks-ba74326
ip-xxx.ec2.internal   Ready      <none>   14m     v1.23.9-eks-ba74326
ip-xxx.ec2.internal   Ready      <none>   3h14m   v1.23.9-eks-ba74326
ip-xxx.ec2.internal    Ready      <none>   37m     v1.23.9-eks-ba74326
ip-xxx.ec2.internal    Ready      <none>   37m     v1.23.9-eks-ba74326
ip-xxx.ec2.internal   Ready      <none>   37m     v1.23.9-eks-ba74326
ip-xxx.ec2.internal   Ready      <none>   4m26s   v1.23.9-eks-ba74326
ip-xxx.ec2.internal   Ready      <none>   37m     v1.23.9-eks-ba74326
ip-xxx.ec2.internal   Ready      <none>   37m     v1.23.9-eks-ba74326
ip-xxx.ec2.internal   Ready      <none>   37m     v1.23.9-eks-ba74326
ip-xxx.ec2.internal   Ready      <none>   3h18m   v1.23.9-eks-ba74326
ip-xxx.ec2.internal   Ready      <none>   14m     v1.23.9-eks-ba74326
ip-xxx.ec2.internal   Ready      <none>   19m     v1.23.9-eks-ba74326
ip-xxx.ec2.internal    Ready      <none>   4m27s   v1.23.9-eks-ba74326
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
This is normally caused by extended resources not registering or startup taints not being removed.  

Are you using extended resources (e.g. GPUs or have AWS_ENABLE_POD_ENI turned on?) or startup taints?

**Comment by bwagner5** [comment]
👋  Are you using GPU instances by chance?  

I just tried this w/ Karpenter v0.18.1 on an EKS cluster running K8s v1.23.9:

```
> kubectl scale deploy/inflate --replicas=10
> sleep 60
> kubectl get node -l karpenter.sh/initialized=true
```

**Comment by snorlaX-sleeps** [comment]
Can confirm @tzneal and @bwagner5 - we found we had set `AWS_ENABLE_POD_ENI` in these 2 clusters.
Removing that ENV var meant the nodes immediately got labeled and removed.

This was a misconfiguration where the provisioner didn't have `vpc.amazonaws.com/has-trunk-attached: "false"`
I assume this label is required for this functionality to correctly work?

If this setting is enabled and the provisioner is not correctly labelled, should Karpenter not be able to behave normally?
Is there a way to use this setting for pod-security-groups but still have normal provisioners?
Or are the two currently incompatible?

**Comment by rwilliams-r7** [comment]
Thank you for your help here we needed it. @tzneal comment was key.

**Comment by snorlaX-sleeps** [comment]
When using pod-sgs without these settings, it was taking 30mins+ for a node to become ready for use. (attaching the ENI)
I would have assumed with this environment variable, but without the label it would have taken 30mins+ for a node to become ready, rather than the several days we had seen?

**Comment by bwagner5** [comment]
The `AWS_ENABLE_POD_ENI` is required, but the `vpc.amazonaws.com/has-trunk-attached: "false"` label shouldn't be required on the provisioner, it should be added by the [VPC Resource Controller](https://github.com/aws/amazon-vpc-resource-controller-k8s) which runs transparently on your EKS cluster.

Here are some more details on how security groups for pods work w/ Karpenter: https://karpenter.sh/v0.19.1/aws/provisioning/#pod-eni-security-groups-for-pods

**Comment by rkirk-r7** [comment]
I am seeing the same issue when using instance types with GPU, e.g. g5 instance type. Where the `karpenter.sh/initialized: true` label is not being set on these instance types.  Is there any additional configuration required to allow these types to be properly initialized?

**Comment by tzneal** [comment]
Are you running the NVidia device plugin daemonset? https://github.com/NVIDIA/k8s-device-plugin It's responsible for registering the GPU resources.

**Comment by rkirk-r7** [comment]
@tzneal I was not thanks. If this daemonset is not configured should karpenter be attempting to use these instance types? For my use case I was not making use of the GPU resource, just karpenter happened to pick some of these instance types as I had not explicitly excluded them

**Comment by ellistarn** [comment]
This shouldn't happen unless you restrict your provisioner significantly. Can you provide a provisioner and pod spec?

**Comment by rkirk-r7** [comment]
Provisioner
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  annotations:
    meta.helm.sh/release-name: karpenter-worker-default-provisioner-chart
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  name: default-karpenter-provisioner
spec:
  consolidation:
    enabled: true
  labels:
    env: karpenter-on-demand
  provider:
    launchTemplate: launch-template-karpenter-default20220408
    subnetSelector:
      Service: Private
      kubernetes.io/cluster/my-cluster: '*'
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: karpenter.k8s.aws/instance-size
    operator: In
    values:
    - 16xlarge
    - 24xlarge
    - 32xlarge
    - 48xlarge
    - metal
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
status:
  resources:
    attachable-volumes-aws-ebs: "1365"
    cpu: "3456"
    ephemeral-storage: 2201578820Ki
    memory: 27576652336Ki
    pods: "24286"
```

And pod spec
```
selector:
    matchLabels:
      app: my-service
  template:
    metadata:
      annotations:
        app: my-service
      creationTimestamp: null
      labels:
        app: my-service
        app.kubernetes.io/instance: my-service
        app.kubernetes.io/managed-by: spinnaker
        app.kubernetes.io/name: my-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - my-service
              topologyKey: kubernetes.io/hostname
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - my-service
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
      containers:
      - command:
        - java
        - -server
        - -jar
        - app.war
        env:
        - name: EC2_NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: <uri-to-image>/my-service:123
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /health/liveness
            port: 8083
            scheme: HTTP
          initialDelaySeconds: 210
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: my-service
        ports:
        - containerPort: 8083
          protocol: TCP
        readinessProbe:
          failureThreshold: 12
          httpGet:
            path: /health/readiness
            port: 8083
            scheme: HTTP
          initialDelaySeconds: 200
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 8G
          requests:
            cpu: "2"
            memory: 8G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        env: karpenter-on-demand
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: my-service-sa
      serviceAccountName: my-service-sa
      terminationGracePeriodSeconds: 30
```

@ellistarn let me know if there is anything else you need me to provide, thanks

**Comment by rkirk-r7** [comment]
Unfortunately I don't have any logs going back that far i'm afraid

**Comment by kenny-monster** [comment]
I'm trying to utilise `inf1` instances for regular workloads that have no need for special resources because the spot pricing is generally really good. Where it's not working is that the label in question isn't being applied because the neuron device plugin isn't running on the node. We can make sure to get that running on the node but then we have the problem that:

1. Bottlerocket doesn't support neuron instance types such as inf1 (unrelated and out of scope here but mentioned just for context)
2. The daemonset pod is using resources when we don't really care for the special resources.

Is there any resolution here?

**Comment by ellistarn** [comment]
>Is there any resolution here?

@jonathan-innis was thinking about changing initialization to only require the resources requested by pods (e.g. if pods didn't request the resources, we wouldn't include it in initialization)

> The daemonset pod is using resources when we don't really care for the special resources.

You should

**Comment by kenny-monster** [comment]
In my specific case (Bottlerocket), it doesn't help but I can imagine that being workable if we weren't.

**Comment by jonathan-innis** [comment]
> Reopening for his comment

This should solve your case, as long as we didn't do a scheduling simulation that required pods that requested the `neuron` resource to be on the node, we would assume that the node is initialized once it launches normally.

**Comment by kenny-monster** [comment]
I don't think I quite understand. I've tried setting the resources for the daemonset to 0. I wasn't sure if it's only `aws.amazon.com/neuron: "0"` that I should've set (as seen below) but I also tried setting `cpu` and `memory` to 0.
```
spec:
  template:
    spec:
      containers:
      - ...
        image: 790709498068.dkr.ecr.us-west-2.amazonaws.com/neuron-device-plugin:latest
        imagePullPolicy: Always
        name: neuron-device-plugin
        resources:
          limits:
            aws.amazon.com/neuron: "0"
          requests:
            aws.amazon.com/neuron: "0"
        ...
      - ...
        image: public.ecr.aws/neuron/neuron-device-plugin:1.5.3.0
        imagePullPolicy: Always
        name: k8s-neuron-device-plugin-ctr
        resources:
          limits:
            aws.amazon.com/neuron: "0"
          requests:
            aws.amazon.com/neuron: "0"
        ...
```

The `karpenter.sh/initialized` label is never set.
