### ISSUE TITLE
Vault sidecar container blocks Karpenter scale up

### ISSUE THREAD

**Issue by barth12** [aws/karpenter#2882]
### Version

__Karpenter Version:__ v0.16.3

__Kubernetes Version:__ v1.24

### Expected Behavior

Should trigger extra node for new set of pods

### Actual Behavior

I'm testing this on nginx pod. When nginx (without sidecar of Vault) is scaled up to 30 replicas Karpenter correctly starts up new node. However when Vault annotations are added to deployment so in turn to pod Karpenter errors and does not add another node. 

### Steps to Reproduce the Problem

If you are using Vault sidecar injector then you can create a deployment as such:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/role: "xxx"
        vault.hashicorp.com/agent-inject-secret-.env: "secrets/data/xxx"
        vault.hashicorp.com/agent-inject-template-.env: |
          {{- with secret (print "secrets/data/xxx") -}}{{- range $k, $v := .Data.data -}}
          export {{ $k }}={{ $v }}
          {{ end }}{{- end -}}
      labels:
        app: nginx
    spec:
      serviceAccountName: xxx
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

This in turn generates pod like so:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
    vault.hashicorp.com/agent-init-first: "true"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-.env: secrets/data/xxx
    vault.hashicorp.com/agent-inject-status: injected
    vault.hashicorp.com/agent-inject-template-.env: |
      {{- with secret (print "secrets/data/xxx") -}}{{- range $k, $v := .Data.data -}}
      export {{ $k }}={{ $v }}
      {{ end }}{{- end -}}
    vault.hashicorp.com/role: xxx
    vault.hashicorp.com/tls-skip-verify: "true"
  labels:
    app: nginx
    pod-template-hash: 7d56bcdf6d
  name: nginx-deployment-7d56bcdf6d-jclmf
spec:
  containers:
    - image: nginx:1.14.2
      name: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-l95x2
          readOnly: true
        - mountPath: /vault/secrets
          name: vault-secrets
    - args:
        - echo ${VAULT_CONFIG?} | base64 -d > /home/vault/config.json && vault agent -config=/home/vault/config.json
      command:
        - /bin/sh
        - -ec
      env:
        - name: VAULT_LOG_LEVEL
          value: info
        - name: VAULT_LOG_FORMAT
          value: standard
        - name: VAULT_CONFIG
          value: xxx
      image: hashicorp/vault:1.11.3
      name: vault-agent
      resources:
        limits:
          cpu: 500m
          ephemeral-storage: 128Mi
          memory: 128Mi
        requests:
          cpu: 250m
          ephemeral-storage: 64Mi
          memory: 64Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 100
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-r93x2
          readOnly: true
        - mountPath: /home/vault
          name: home-sidecar
        - mountPath: /vault/secrets
          name: vault-secrets
  initContainers:
    - args:
        - echo ${VAULT_CONFIG?} | base64 -d > /home/vault/config.json && vault agent -config=/home/vault/config.json
      command:
        - /bin/sh
        - -ec
      env:
        - name: VAULT_LOG_LEVEL
          value: info
        - name: VAULT_LOG_FORMAT
          value: standard
        - name: VAULT_CONFIG
          value: xxx
      image: hashicorp/vault:1.11.3
      name: vault-agent-init
      resources:
        limits:
          cpu: 500m
          ephemeral-storage: 128Mi
          memory: 128Mi
        requests:
          cpu: 250m
          ephemeral-storage: 64Mi
          memory: 64Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 100
      volumeMounts:
        - mountPath: /home/vault
          name: home-init
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-r93x2
          readOnly: true
        - mountPath: /vault/secrets
          name: vault-secrets
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  serviceAccountName: xxx
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: kube-api-access-l95x2
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    fieldPath: metadata.namespace
                  path: namespace
    - emptyDir:
        medium: Memory
      name: home-init
    - emptyDir:
        medium: Memory
      name: home-sidecar
    - emptyDir:
        medium: Memory
      name: vault-secrets
```

Provisioner config I'm using:

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: general
  namespace: karpenter
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
  provider:
    instanceProfile: "KarpenterNodeInstanceProfile"
    subnetSelector:
      Name: eks-private-*
    securityGroupSelector:
      Name: sg_name
    tags:
      "eks/cluster-name": my_cluster_name
      "eksctl.cluster.k8s.io/v1alpha1/cluster-name": my_cluster_name
      "kubernetes.io/cluster/my_cluster_name: "owned"
  ttlSecondsAfterEmpty: 30
```

### Resource Specs and Logs

Corrsponding Karpenter controller logs (debug level enabled):

`2022-11-17T21:19:55.792Z        ERROR   controller.provisioning Failed to compute packing, pod(s) [test/nginx-deployment-7d56bcdf6d-xcgf5 test/nginx-deployment-7d56bcdf6d-v6r8t test/nginx-deployment-7d56bcdf6d-lm5z7] did not fit in instance type option(s) [m1.small m1.medium m3.medium t3a.micro t3.micro c1.medium t3a.small t3.small c3.large c4.large c6a.large c5d.large c5a.large c5.large c6id.large t3a.medium c6i.large t3.medium c5ad.large c5n.large m3.large m1.large m5.large m4.large m5ad.large m6id.large m6a.large t3.large m5n.large t3a.large m5d.large m5a.large m5zn.large m5dn.large m6i.large r3.large i3.large r4.large r6i.large i3en.large r5.large r5d.large r5b.large r5n.large r5ad.large r5a.large r6a.large r5dn.large r6id.large m2.xlarge c4.xlarge c3.xlarge c6id.xlarge c6a.xlarge c5d.xlarge c5a.xlarge c5ad.xlarge c6i.xlarge c5.xlarge c5n.xlarge m1.xlarge m3.xlarge m6i.xlarge t3a.xlarge m5d.xlarge m6id.xlarge m5dn.xlarge t3.xlarge m6a.xlarge m5ad.xlarge m5.xlarge m5a.xlarge m5n.xlarge m4.xlarge m5zn.xlarge r4.xlarge r3.xlarge i3.xlarge r5b.xlarge r5.xlarge r5ad.xlarge r6a.xlarge r5d.xlarge r5dn.xlarge i3en.xlarge r6id.xlarge r5a.xlarge r5n.xlarge r6i.xlarge m2.2xlarge c1.xlarge c4.2xlarge c3.2xlarge c6a.2xlarge c5d.2xlarge c6i.2xlarge c5a.2xlarge c5.2xlarge c5ad.2xlarge c6id.2xlarge c5n.2xlarge m3.2xlarge t3a.2xlarge m6i.2xlarge m5a.2xlarge m5zn.2xlarge m5d.2xlarge m5n.2xlarge m5.2xlarge m5dn.2xlarge m4.2xlarge t3.2xlarge m5ad.2xlarge m6id.2xlarge m6a.2xlarge i3.2xlarge r4.2xlarge r3.2xlarge i3en.2xlarge r5a.2xlarge r5n.2xlarge r5dn.2xlarge r5ad.2xlarge r6a.2xlarge r6id.2xlarge r6i.2xlarge r5b.2xlarge r5d.2xlarge r5.2xlarge m2.4xlarge m5zn.3xlarge i3en.3xlarge c4.4xlarge c3.4xlarge c6a.4xlarge c6id.4xlarge c5.4xlarge c5ad.4xlarge c5a.4xlarge c6i.4xlarge c5d.4xlarge c5n.4xlarge m6a.4xlarge m5d.4xlarge m4.4xlarge m5n.4xlarge m5.4xlarge m5dn.4xlarge m5a.4xlarge m5ad.4xlarge m6id.4xlarge m6i.4xlarge i3.4xlarge r4.4xlarge r3.4xlarge r5b.4xlarge r6i.4xlarge r5.4xlarge r5d.4xlarge r5n.4xlarge r5dn.4xlarge r6a.4xlarge r5a.4xlarge r6id.4xlarge r5ad.4xlarge m5zn.6xlarge i3en.6xlarge c3.8xlarge cc2.8xlarge c6id.8xlarge c6i.8xlarge c5ad.8xlarge c6a.8xlarge c5a.8xlarge m6i.8xlarge m5a.8xlarge m6id.8xlarge m5dn.8xlarge m5n.8xlarge m5d.8xlarge m5.8xlarge m6a.8xlarge m5ad.8xlarge r4.8xlarge r3.8xlarge i3.8xlarge r5n.8xlarge r6i.8xlarge r6a.8xlarge r5b.8xlarge r5d.8xlarge r5.8xlarge r5dn.8xlarge r6id.8xlarge r5a.8xlarge r5ad.8xlarge c4.8xlarge c5d.9xlarge c5.9xlarge c5n.9xlarge m4.10xlarge c5.12xlarge c6id.12xlarge c5a.12xlarge c6i.12xlarge c6a.12xlarge c5d.12xlarge c5ad.12xlarge m6i.12xlarge m6a.12xlarge m5ad.12xlarge m5.12xlarge m5d.12xlarge m5zn.12xlarge m5a.12xlarge m5n.12xlarge m6id.12xlarge m5dn.12xlarge r5b.12xlarge r6i.12xlarge r5dn.12xlarge r5a.12xlarge i3en.12xlarge r6a.12xlarge r5.12xlarge r5ad.12xlarge r5n.12xlarge r6id.12xlarge r5d.12xlarge c6a.16xlarge c6id.16xlarge c5ad.16xlarge c5a.16xlarge c6i.16xlarge m5dn.16xlarge m5.16xlarge m6a.16xlarge m5d.16xlarge m4.16xlarge m6i.16xlarge m5a.16xlarge m5n.16xlarge m6id.16xlarge m5ad.16xlarge i3.16xlarge r4.16xlarge r6a.16xlarge r6id.16xlarge r5a.16xlarge r5ad.16xlarge r6i.16xlarge r5n.16xlarge r5b.16xlarge r5dn.16xlarge r5d.16xlarge r5.16xlarge c5d.18xlarge c5.18xlarge c5n.18xlarge c5ad.24xlarge c6id.24xlarge c5a.24xlarge c6i.24xlarge c5.24xlarge c5d.24xlarge c6a.24xlarge m5ad.24xlarge m6a.24xlarge m5a.24xlarge m5dn.24xlarge m6i.24xlarge m5d.24xlarge m5n.24xlarge m6id.24xlarge m5.24xlarge r5a.24xlarge r5n.24xlarge r5ad.24xlarge r5d.24xlarge r5b.24xlarge r6id.24xlarge r5.24xlarge i3en.24xlarge r6i.24xlarge r6a.24xlarge r5dn.24xlarge c6i.32xlarge c6a.32xlarge c6id.32xlarge m6id.32xlarge m6a.32xlarge m6i.32xlarge r6id.32xlarge r6i.32xlarge r6a.32xlarge c6a.48xlarge m6a.48xlarge r6a.48xlarge]        {"commit": "df57892", "provisioner": "general"}`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
