### ISSUE TITLE
Karpenter ignores eviction-soft argument in Bottlerocket userData in AWSNodeTemplate

### ISSUE THREAD

**Issue by alejandraRamos** [aws/karpenter#2890]
### Version

__Karpenter Version:__ v0.18.1

__Kubernetes Version:__ v1.23.0

### Expected Behavior

Karpenter must merge all Bottlerocket sections delivered in the userData into the AWSNodeTemplate resource in the generated launch template.

### Actual Behavior

Karpenter is ignoring the configuration argument in userData `eviction-soft` and `eviction-soft-grace-period` and this causes them to be omitted in the generated launch template.

### Steps to Reproduce the Problem

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["c6i.2xlarge", "c5.2xlarge","c6i.4xlarge", "c5.4xlarge"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-east-1a", "us-east-1b"]
    - key: "eks.amazonaws.com/compute-type"
      operator: In
      values: ["ec2"]
  limits:
    resources:
      cpu: 125000m
      memory: 170Gi
  providerRef:
    name: default
  labels:
    type: karpenter
    provisioner: default
  consolidation:
    enabled: true
  ttlSecondsUntilExpired: 604800

---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  amiFamily: Bottlerocket
  subnetSelector:
    karpenter.sh/discovery: mycluster

  securityGroupSelector:
    karpenter.sh/discovery: mycluster
  
  userData: |
    [settings.kubernetes]
    registry-qps = 50
    [settings.kubernetes.eviction-soft]
    "imagefs.available" = "4Gi"
    [settings.kubernetes.eviction-soft-grace-period]
    "imagefs.available" = "1m"
```

I would expect the generated launch template to contain the `eviction-soft` and `eviction-sot-grace-period` arguments. However, this doesn't happen, the arguments are missing in the configuration.

The `registry-qps` and ` eviction-hard` arguments are merged correctly in the launch template. You should add these arguments which are important for the termination of the graceful nodes.

## Reference

https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#eviction-signals

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
