### ISSUE TITLE
Support maintenance windows for expired node

### ISSUE THREAD

**Issue by yuyuvn** [aws/karpenter#2949]
### Tell us about your request

We are using kubernetes cluster with statefulset resources, which will have some downtime when those pods are moved to another node. We can use Pod Disruption Budget to avoid pods being disrupted, but this will lead to nodes never being updated.
It would be good if we can have a mechanism to automate upgrading nodes.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Add extra setting for expire via maintenanceWindows fields:
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  expire:
    ttlSecondsUntilExpired: 100ms
    maintenanceWindows:
      timeInWeek:
      - day: Monday
        hourSlots:
        - 1
        - 2
```
Or we can crease CRD for the maintenance window setting.
When a node expired, it will wait for maintenanceWindow before remove it.

Note: I refered maintenance window setting from aks's planned maintenance
https://learn.microsoft.com/en-us/azure/aks/planned-maintenance

### Are you currently working around this issue?

We are using a custom tool that runs cronjob to remove nodes in the maintenance window, but would be better if karpenter supports it natively.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
