### ISSUE TITLE
Do not use old instances in case of ipv6 setup

### ISSUE THREAD

**Issue by runningman84** [aws/karpenter#2975]
### Tell us about your request

2022-12-02T15:09:53.931Z    ERROR    controller.deprovisioning    processing cluster, deprovisioning nodes, launching replacement node, launching node, creating cloud provider instance, with fleet error(s), Unsupport │
│ edOperation: IPv6 addresses are not supported on m3.medium    {"commit": "470aa83"}

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Would not it make sense to discover that ipv6 is used and exclude old instance types by default instead of throwing errors like that?

### Are you currently working around this issue?

na

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
It's possible that we could do that by implicitly filtering the instance types when we discover that Ipv6 is being used. We've been moving away from in-memory, implicit filtering like that though because it can be surprising in certain cases.  There may not be surprising behavior for IPv6, since it isn't a very intuitive filter currently ("current-gen" which maps to 4th gen+ in addition to c3, r3, and i2). 

A path forward in the mean-time, is to add an instance-category and instance-generation requirements in your provisioner like this:
 
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "karpenter.k8s.aws/instance-category"
      operator: In
      values: ["c", "m", "r"]
    - key: "karpenter.k8s.aws/instance-generation"
      operator: Gt
      values: ["3"]
```

If you'd like to use c3, r3, and/or i2, then you'd need to use the instance-family requirement and list all the families since requirements are AND'd instead of OR'd. The requirements above also do not include t2's and t3's which should also support ipv6 but have an offset generation (i..e t2 is 4th gen and t3's are 5th gen, but Karpenter uses the actual number in the instance type and doesn't try to normalize to the actual generation...). 

I think we can pretty trivially add an `instance-ipv6` requirements label and then potentially implicitly filter based on the ip-family discovery, but at very least you can add the `instance-ipv6` label to the requirements and not have to compromise on instance type flexibility (reaching down into the few 3rd gen instance types) or knowing what generations it supports.
