### ISSUE TITLE
Node launched via karpenter are in NotReady status for more than 10 minutes before becoming Ready

### ISSUE THREAD

**Issue by zeagord** [aws/karpenter#3033]
### Version

__Karpenter Version:__ v0.20.0

__Kubernetes Version:__ v0.20.0

### Expected Behavior

The node should become available sooner than 10 minutes. 

### Actual Behavior

The node takes more 10 minutes to become `Ready`. Using BottleRocket OS with LaunchTemplate for the provisioning. 

* Checked the vpc-cni and kube-proxy pods both of which are in pending state during the NotReady status. 
* Unable to ssh in to the node to check the kubelet logs immediately. But there are no obvious error or issues there. 

Note:  All the necessary VPC Endpoints are available

### Steps to Reproduce the Problem

* Launch new pods via Karpenter provisioner in a Private EKS Cluster with no internet access
* Observe the node status

### Resource Specs and Logs

Initially the kube-proxy and aws-node (CNI) pods are stuck like below 

```
Warning  FailedScheduling  7m33s (x2 over 8m35s)  default-scheduler  0/5 nodes are available: 1 Insufficient cpu, 1 Too many pods, 4 node(s) didn't match Pod's node affinity/selector.
Warning  FailedScheduling  3s (x6 over 6m3s)      default-scheduler  0/6 nodes are available: 1 Insufficient cpu, 1 Too many pods, 5 node(s) didn't match Pod's node affinity/selector.
```

After 10 minutes, I can see the below events.

```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  17m (x2 over 18m)    default-scheduler  0/5 nodes are available: 1 Insufficient cpu, 1 Too many pods, 4 node(s) didn't match Pod's node affinity/selector.
  Warning  FailedScheduling  8m27s (x7 over 15m)  default-scheduler  0/6 nodes are available: 1 Insufficient cpu, 1 Too many pods, 5 node(s) didn't match Pod's node affinity/selector.
  Normal   Scheduled         8m11s                default-scheduler  Successfully assigned kube-system/kube-proxy-f49xk to ip-10-58-1-172.ap-southeast-1.compute.internal
  Normal   Pulling           8m10s                kubelet            Pulling image "[XXXXXXXXX.dkr.ecr.ap-southeast-1.amazonaws.com/eks/kube-proxy:v1.23.7-minimal-eksbuild.1](http://XXXXXXXXXX.dkr.ecr.ap-southeast-1.amazonaws.com/eks/kube-proxy:v1.23.7-minimal-eksbuild.1)"
  Normal   Pulled            8m8s                 kubelet            Successfully pulled image "[XXXXXXXX.dkr.ecr.ap-southeast-1.amazonaws.com/eks/kube-proxy:v1.23.7-minimal-eksbuild.1](http://XXXXXXXX.dkr.ecr.ap-southeast-1.amazonaws.com/eks/kube-proxy:v1.23.7-minimal-eksbuild.1)" in 2.430576831s
  Normal   Created           8m8s                 kubelet            Created container kube-proxy
  Normal   Started           8m8s                 kubelet            Started container kube-proxy
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by spring1843** [comment]
@zeagord can you some provisioner details?

**Comment by zeagord** [comment]
Sure, here we go. 

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: test
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["ap-southeast-1a", "ap-southeast-1b", "ap-southeast-1c"]                             #Update the correct region and zones
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
    - key: "node.kubernetes.io/instance-type"              #If not included, all instance types are considered
      operator: In
      values: ["m5.large", "m6i.large"]
    - key: "kubernetes.io/arch"                            #If not included, all architectures are considered
      operator: In
      values: ["amd64"]
  limits:
    resources:
      cpu: 1000
  providerRef:
    name: "test"     # Used by Karpenter Nodes
  labels:
    type: karpenter
    provisioner: test
  ttlSecondsAfterEmpty: 120
  # Limits prevent Karpenter from creating new instances once the limit is exceeded.
  limits:
    resources:
      cpu: "100"
      memory: 100Gi

```

**Comment by ellistarn** [comment]
Can you include the AWSNodeTemplate?

**Comment by zeagord** [comment]
The launch template is created using Terraform. The configuration is same as this - https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/launch-templates

```
    bottlerocket = {
      ami                    = "ami-00acb198bcce355d2" #data.aws_ami.bottlerocket.id
      launch_template_os     = "bottlerocket"
      launch_template_prefix = "bottlerocket"
      iam_instance_profile   = module.aws_eks_managed_node_groups["mng_lt"].managed_nodegroup_iam_instance_profile_id[0] 
      vpc_security_group_ids = [module.eks.node_security_group_id]
      block_device_mappings = [
        {
          device_name = "/dev/xvda"
          volume_type = "gp3"
          volume_size = 100
        }
      ]
    }

```

Also tested with AWSNodeTemplate now and can confirm the behaviour is same.

```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: br-lt
spec:
  amiFamily: Bottlerocket
  subnetSelector:
    karpenter.sh/discovery: k8s-sandbox
  securityGroupSelector:
    karpenter.sh/discovery: k8s-sandbox
```
