### ISSUE TITLE
Karpenter doesn't create new nodes with AWS_ENABLE_POD_ENI enabled 

### ISSUE THREAD

**Issue by janavenkat** [aws/karpenter#3034]
### Version

__Karpenter Version:__ v0.20.0

__Kubernetes Version:__ v1.20.15

### Expected Behavior

Am using security groups for pods so I have to enable `AWS_ENABLE_POD_ENI` and It should create new nodes for pending pods when 

### Actual Behavior

It doesn't create nodes and here is the logs 

`
ERROR controller.provisioner Could not schedule pod, incompatible with provisioner "xxx", no instance type satisfied resources {"cpu":"90m","memory":"210M","pods":"1","vpc.amazonaws.com/pod-eni":"1"} and requirements karpenter.k8s.aws/instance-category In [c m r], karpenter.k8s.aws/instance-generation Exists >2, karpenter.sh/capacity-type In [spot], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], karpenter.sh/provisioner-name In [xxx] {"commit": "f60dacd", "pod": "xxxx"}
`

### Steps to Reproduce the Problem

Deploy Karapetner with helm chart version 0.20.0 and here is the provisoner config 

```

apiVersion: karpenter.sh/v1alpha5  
kind: Provisioner  
metadata:  
   name: xxx 
spec:  
  ttlSecondsAfterEmpty: 30  
  labels:  
    vpc.amazonaws.com/has-trunk-attached: "false"  
  
  requirements:  
    - key: karpenter.sh/capacity-type  
      operator: In  
      values: ["spot"]  
    - key: "kubernetes.io/arch"  
      operator: In  
      values: ["amd64"]  
  kubeletConfiguration:  
    clusterDNS: [ "xxx" ]  
  limits:  
    resources:  
      cpu: 50  
xxxxx
```

### Resource Specs and Logs

`
ERROR controller.provisioner Could not schedule pod, incompatible with provisioner "xxx", no instance type satisfied resources {"cpu":"90m","memory":"210M","pods":"1","vpc.amazonaws.com/pod-eni":"1"} and requirements karpenter.k8s.aws/instance-category In [c m r], karpenter.k8s.aws/instance-generation Exists >2, karpenter.sh/capacity-type In [spot], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], karpenter.sh/provisioner-name In [xxx] {"commit": "f60dacd", "pod": "xxxx"}
`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by spring1843** [comment]
The `AWS_ENABLE_POD_ENI` is part of a config map since v0.19.0. PTAL https://karpenter.sh/v0.20.0/upgrade-guide/#upgrading-to-v0190

Reading the ticket it seems like you may still be using an env variable.   Can you double check that `aws.enablePodENI` is set to `true` when you run:

`k get configmaps -n karpenter karpenter-global-settings -o yaml`

I was able to see nodes being scheduled with this provisioner on v0.20.0:

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  labels:
    vpc.amazonaws.com/has-trunk-attached: "false"
  limits:
    resources:
      cpu: 1k
  providerRef:
    name: default
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  ttlSecondsAfterEmpty: 30
```
