### ISSUE TITLE
Cluster price increase with consolidation

### ISSUE THREAD

**Issue by TapTap21** [aws/karpenter#3035]
### Version

__Karpenter Version:__ v0.20.0

__Kubernetes Version:__ v1.24.0

### Expected Behavior

The price of the cluster to decrease with the use of consolidation

### Actual Behavior

The price increased with 78% compared to a before.

### Steps to Reproduce the Problem

i upgraded from v0.13.0 to v0.20.0, with the goal using consolidation. I used eks-node-viewer to get a quick overview of the cluster before everything. 
![image](https://user-images.githubusercontent.com/31740134/207636363-e310e067-5243-46c3-8dc3-68b412e2d82c.png)

I upgraded, loosened the node selection restrictions and started to play around with scaling up and down workloads. After scaling back down to the original load, the cluster cost had increased by 78%, which is a very significant increase.
![image](https://user-images.githubusercontent.com/31740134/207636930-dc08548b-a4ae-47ae-b3bf-f5c37027d1c2.png)

### Resource Specs and Logs

Provisioner spec before:
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: karpenter-provisioner
  namespace: karpenter
spec:
  limits:
    resources:
      cpu: 100
      memory: 100Gi
  provider:
    tags:
      karpenter.sh/discovery: cluster-name
    subnetSelector:
      karpenter.sh/discovery: cluster-name
    securityGroupSelector:
      Name: security-group-name
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: topology.kubernetes.io/zone
      operator: In
      values: ["eu-central-1a", "eu-central-1b"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        ["t3a.large", "t3a.medium", "t3a.xlarge", "m6a.large", "m6a.xlarge"]
    - key: node.kubernetes.io/instance-type
      operator: Exists
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 864000
  labels:
    provisioner: karpenter

```

Provisioner spec after:
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: karpenter-provisioner
spec:
  consolidation:
    enabled: true
  labels:
    provisioner: karpenter
  limits:
    resources:
      cpu: '500'
      memory: 5000Gi
  provider:
    securityGroupSelector:
      Name: security-group-name
    subnetSelector:
      karpenter.sh/discovery: cluster-name
    tags:
      karpenter.sh/discovery: cluster-name
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
    - key: topology.kubernetes.io/zone
      operator: In
      values:
        - eu-central-1a
        - eu-central-1b
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values:
        - c
        - m
        - r
        - t
    - key: node.kubernetes.io/instance-type
      operator: Exists
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
  ttlSecondsUntilExpired: 864000

```
The workloads i run on karpenter are all about 0.5CPU requests and 0.5-1GB memory. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Can you look at the pods on those nodes, particularly 38-16 to see why it can't be consolidated? There's not enough information here to determine that.  Do you have label selectors that request particular instance types

**Comment by TapTap21** [comment]
@tzneal The workloads I'm running are all very similar, without any instance type selectors. Here is an example:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-deployment
  namespace: some-namespace
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 1
  selector:
    matchLabels:
      app: some-app
  template:
    metadata:
      labels:
        app: some-app
    spec:
      restartPolicy: Always
      nodeSelector:
        "karpenter.sh/provisioner-name": "karpenter-provisioner"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: some-app
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: some-app
      containers:
        - name: hopper
          image: some-nodejs-container:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 512m
              memory: 512Mi
            limits:
              memory: 512Mi
          ports:
            - name: server
              containerPort: 3333
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 5
            httpGet:
              path: /health
              port: 3333
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 5
            httpGet:
              path: /health
              port: 3333

```
```yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: some-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: some-deployment
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

```
```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb
  namespace: some-namespace
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      app: some-app

```

I have since gone back to my strict node-selectors on the provisioner to save on cluster costs. Please let me know if there is any other info I can provide, as I'm a very big supporter of the Karpenter project!
