### ISSUE TITLE
Controller container is bind to 8080 port

### ISSUE THREAD

**Issue by chandrakanthkannam** [aws/karpenter#3040]
### Version

__Karpenter Version:__ v0.20.0

__Kubernetes Version:__ v1.22.15-eks-fb459a0

### Expected Behavior

upon modifying the `containerPort` for the controller container service able to run on the new port

```
spec:
  template:
    spec:
      containers:
        ports:
        - containerPort: 8088
          name: http-metrics
          protocol: TCP
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https-webhook
          protocol: TCP
```

### Actual Behavior

instead of honoring the new `containerPort` service is binding to port `8080`
```
panic: failed to setup manager: error listening on :8080: listen tcp :8080: bind: address already in use

goroutine 1 [running]:
github.com/samber/lo.must({0x233b3c0, 0xc0002fe700}, {0xc000a3f9e0, 0x1, 0x1})
	github.com/samber/lo@v1.36.0/errors.go:51 +0x1cd
github.com/samber/lo.Must[...]({0x0?, 0x0}, {0x233b3c0, 0xc0002fe700?}, {0xc000a3f9e0?, 0x1?, 0x274e2e0?})
	github.com/samber/lo@v1.36.0/errors.go:65 +0x45
github.com/aws/karpenter-core/pkg/operator.NewOperator()
	github.com/aws/karpenter-core@v0.0.2-0.20221205173459-064a52f2f9e1/pkg/operator/operator.go:127 +0x999
main.main()
	github.com/aws/karpenter/cmd/controller/main.go:34 +0x2e
```

### Steps to Reproduce the Problem

Modify the karpenter deployment file , it can be any other port
```
spec:
  template:
    spec:
      containers:
        ports:
        - containerPort: 8088
          name: http-metrics
          protocol: TCP
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https-webhook
          protocol: TCP
```

### Resource Specs and Logs

here is the log showing service trying to bind `8080` irrespective of the custom port which was passed in

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by toscott** [comment]
Sounds like you are expecting the kubernetes deployment configuration to automatically change the port that the application is starting up on? If I'm following, I think the current behavior is expected.

It looks like karpenter-core does have environment variable support for swapping the metrics port from 8080 to another port: https://github.com/aws/karpenter-core/blob/main/pkg/operator/options/options.go#L59

Maybe try setting the environment variable METRICS_PORT=8088 in addition to your changes to the deployment spec.

**Comment by chandrakanthkannam** [comment]
I was able to get around this with couple of changes, added the below things to helm chart values
```
controller:
  env:
  - name: METRICS_PORT
    value: "8088"
  - name: HEALTH_PROBE_PORT
    value: "8089"
```

and for the `containerPort` is mapped to these values using kustomize. can we have the imputs available for the chart similar to what we have for `webhook.port`?, so dont have to use the post-rendering of the chart
