### ISSUE TITLE
Karpenter not falling back to lower priority GPU provisioner when reaching capacity limits

### ISSUE THREAD

**Issue by gmalkov** [aws/karpenter#3043]
### Version

__Karpenter Version:__ v0.19.0

__Kubernetes Version:__ v1.21.14-eks-fb459a0

### Expected Behavior

We use a lot of GPU instances in very bursty workloads. I have configured Karpenter with 3 provisioners, one for each different type of GPU instance we use. I gave them different priorities corresponding to the order we want to attempt to scale them up. We often run into AWS capacity limits, and I was hoping that Karpenter would fail over to the next-highest priority provisioner when it encounters `InsufficientInstanceCapacity` errors for all the possible instance/zone combinations for a given provisioner.

### Actual Behavior

What I observe happening when we schedule a bunch of pods with above tolerations:
- P2s are scaled up until we are constantly hitting `InsufficientInstanceCapacity` and no new nodes are being added even though tons of pods are still pending:
`InsufficientInstanceCapacity for offering { instanceType: p2.xlarge, zone: us-east-1a, capacityType: on-demand }, avoiding for 3m0s`
- If I then go and edit the priorities of the provisioners such that the P3 or G4DN provisioner is the highest-priority one, new nodes of that type immediately start to come up.

My initial thought is that maybe I need to increase the 3 minute avoidance window? Maybe there are enough different permutations of instances/zones that it takes 3 mins to try them all and it never gets around to falling back to another provisioner? Unfortunately it's tough to justify massively scaling up until we hit capacity errors just to test solutions to this, so I'll have to wait until the next time we require such scale. In the meantime I'd love to hear any other suggestions.

I guess another approach would be to define a separate provisioner+taint for workloads that don't care what type of GPU they get. We have some workloads that are GPU-specific, and ideally they would still be able to hop on nodes that were originally scaled up for GPU-agnostic workloads, so this approach is not ideal.

### Steps to Reproduce the Problem

- Configure provisioners similarly to as described
- Try to scale up enough that falling back to a lower-priority provisioner is needed

### Resource Specs and Logs

Relevant parts of provisioner configurations:
```yaml
# Common spec to all 3:
spec:
  labels:
    gpu: 'yes'
    role: worker
  providerRef:
    name: worker-default
  requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
    - key: karpenter.k8s.aws/instance-cpu
      operator: In
      values:
        - '4'
        - '8'
        - '16'
        - '32'
        - '48'
        - '64'
        - '96'
    - key: topology.kubernetes.io/zone
      operator: In
      values:
        - us-east-1a
        - us-east-1b
        - us-east-1c
        - us-east-1d
        - us-east-1f
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
  taints:
    - effect: NoSchedule
      key: workload-type
      value: gpu
  ttlSecondsAfterEmpty: 600
  ttlSecondsUntilExpired: 2592000
---
# Provisioner-specific config
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: worker-p2
spec:
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values:
        - p2
  taints:
    - effect: NoSchedule
      key: gpu-type
      value: tesla-k80
  weight: 50
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: worker-g4dn
spec:
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values:
        - g4dn
  taints:
    - effect: NoSchedule
      key: gpu-type
      value: tesla-t4
  weight: 40
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: worker-p3
spec:
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values:
        - p3
  taints:
    - effect: NoSchedule
      key: gpu-type
      value: v100
  weight: 30
```

Example tolerations of a pod that should result in attempts to scale up P2s, G4DNs, and then P3s, in that order:
```yaml
spec:
  tolerations:
    - key: "workload-type"
      operator: "Equal"
      value: "gpu"
      effect: "NoSchedule"
    - key: "gpu-type"
      operator: "Equal"
      value: "tesla-k80"
      effect: "NoSchedule"
    - key: "gpu-type"
      operator: "Equal"
      value: "tesla-t4"
      effect: "NoSchedule"
    - key: "gpu-type"
      operator: "Equal"
      value: "v100"
      effect: "NoSchedule"
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
