### ISSUE TITLE
incompatible with provisioner. No instance type satisfied resources

### ISSUE THREAD

**Issue by ben5556** [aws/karpenter#3075]
### Version

__Karpenter Version:__ v0.20.0

__Kubectl Version:__

`Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:"clean", BuildDate:"2022-10-24T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`

### Expected Behavior

karpenter launches a new node and the pod is scheduled 

### Actual Behavior

karpenter is unable to launch an instance with the below error

`Warning  FailedScheduling  1s               karpenter          Failed to schedule pod, incompatible with provisioner "useast1-infrastructure", incompatible requirements, key node-type, node-type In [StatefulSet] not in node-type In [Infrastructure]; incompatible with provisioner "useast1-stateful", no instance type satisfied resources {"cpu":"1","memory":"1Gi","pods":"1"} and requirements node-type In [StatefulSet], topology.kubernetes.io/zone In [us-east-1a], kubernetes.io/arch In [amd64], karpenter.k8s.aws/instance-generation Exists >2, topology.kubernetes.io/region In [us-east-1], karpenter.sh/capacity-type In [spot], karpenter.k8s.aws/instance-category In [c m r], kubernetes.io/os In [linux], karpenter.sh/provisioner-name In [useast1-stateful]`

### Steps to Reproduce the Problem

Apply the attached specs and deploy a pod with the node selector `node-type: StatefulSet`

### Resource Specs and Logs

[specs.zip](https://github.com/aws/karpenter/files/10267932/specs.zip)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by pyromaniac3010** [comment]
@ben5556 
I think your provisioner is faulty. 
There is no `requirements node-type In [StatefulSet],` available as a "requirement" I think.
https://karpenter.sh/v0.18.1/provisioner/#specrequirements
You might have tried to use a provisioner requirement as a taint.

**Comment by ben5556** [comment]
@pyromaniac3010 thanks for looking into this.  I am not sure I understand, can you please elaborate ?

`incompatible with provisioner "useast1-stateful", no instance type satisfied resources {"cpu":"1","memory":"1Gi","pods":"1"} and requirements node-type In [StatefulSet],`

My pods have a nodeSelector config to be scheduled on nodes with label `node-type: StatefulSet`

**Comment by pyromaniac3010** [comment]
@ben5556 
Karpenter starts new nodes according to the "requirements" you define in the provisioner.
You cannot add your own labels as a provisioner requirement.
I think what you want to to is:
add this to your pods instead of `node-type: StatefulSet` to force them to only schedule on nodes provisioned by your desired provisioner name
```
  nodeSelector:
    karpenter.sh/provisioner-name: "useast1-stateful"

```
to get karpenter working, you need to remove these lines from your provisioner:
```
  requirements:
    - key: node-type
      operator: In
      values: ["StatefulSet"]
```

**Comment by ben5556** [comment]
My statefulset has this affinity

```
affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - StatefulSet
```

My provisioner manifest for reference (FYI I have attached the specs as a zip file), it doesn't have the requirement that you are referring to

`apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: useast1-stateful
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-east-1a", "us-east-1b"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot"]
  providerRef:
    name: useast1-stateful
  #ttlSecondsAfterEmpty: 60
  consolidation:
    enabled: true
  kubeletConfiguration:
    containerRuntime: dockerd
    clusterDNS: ["172.20.0.10"]
  labels:
    node-type: StatefulSet
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: useast1-stateful
spec:
  amiSelector:
    aws-ids: "ami-03cda5ec8e5da6650"
  subnetSelector:
    karpenter.sh/discovery: useast1
  securityGroupSelector:
    karpenter.sh/discovery: useast1
  instanceProfile: KarpenterInstanceProfile
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        deleteOnTermination: true
  tags:
    karpenter.sh/discovery: useast1
    Name: karpenter-useast1-Stateful
`

**Comment by ben5556** [comment]
I am merely expecting karpenter to launch a node with a label and I would use this label in my statefulset as node selector so the pod can be scheduled on this node

**Comment by FernandoMiguel** [comment]
just FYI `containerRuntime: dockerd` wont work on eks 1.24. 
you may want to plan to upgrade that

**Comment by ben5556** [comment]
karpenter provisioner [doc](https://karpenter.sh/v0.20.0/concepts/scheduling/#supported-labels) says the below which is exactly what I am doing.

`You can also define your own custom labels by specifying requirements or labels on your Provisioner and select them using nodeAffinity or nodeSelectors on your Pods.`

**Comment by jonathan-innis** [comment]
This is the expected behavior of the Provisioner. The Provisioner is "deny all" by default for unknown labels. This means if you don't tell the Provisioner to support a label, it won't schedule that pod. To fix it, you should use the `Exists` operator:

```
requirements:
- key: node-type
   operator: Exists
```

**Comment by jonathan-innis** [comment]
We updated the [docs](https://karpenter.sh/preview/concepts/scheduling/#user-defined-labels) to give more details on this one.

**Comment by ben5556** [comment]
@jonathan-innis  thanks for looking into this. I tried your suggestion but no joy

```
2022-12-21T03:49:57.539Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "useast1-stateful", no instance type satisfied resources {"cpu":"3","memory":"20Gi","pods":"1"} and requirements kubernetes.io/os In [linux], kubernetes.io/arch In [amd64], karpenter.sh/provisioner-name In [useast1-stateful], node-type In [StatefulSet], karpenter.k8s.aws/instance-generation Exists >2, topology.kubernetes.io/zone In [us-east-1a], karpenter.k8s.aws/instance-category In [c m r], karpenter.sh/capacity-type In [spot], topology.kubernetes.io/region In [us-east-1]; incompatible with provisioner "useast1-infrastructure", incompatible requirements, key node-type, node-type In [StatefulSet] not in node-type In [Infrastructure]	{"commit": "f60dacd", "pod": "infrastructure/apm-es-cluster-1"}

2022-12-21T03:49:57.544Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "useast1-stateful", no instance type satisfied resources {"cpu":"3","memory":"20Gi","pods":"1"} and requirements node-type In [StatefulSet], kubernetes.io/arch In [amd64], topology.kubernetes.io/zone In [us-east-1a], karpenter.sh/capacity-type In [spot], karpenter.k8s.aws/instance-category In [c m r], karpenter.k8s.aws/instance-generation Exists >2, kubernetes.io/os In [linux], topology.kubernetes.io/region In [us-east-1], karpenter.sh/provisioner-name In [useast1-stateful]; incompatible with provisioner "useast1-infrastructure", incompatible requirements, key node-type, node-type In [StatefulSet] not in node-type In [Infrastructure]	{"commit": "f60dacd", "pod": "infrastructure/apm-es-cluster-3"}
```

This is how my provisioner looks now after adding your change. I tried the `node-type` key with and without quotes and same behaviour.

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: useast1-stateful
spec:
  requirements:
    - key: "node-type"
      operator: Exists
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-east-1a"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot"]
  providerRef:
    name: useast1-stateful
  #ttlSecondsAfterEmpty: 60
  limits:
    resources:
      cpu: 100
      memory: 200Gi
  consolidation:
    enabled: true
  kubeletConfiguration:
    containerRuntime: dockerd
    clusterDNS: ["172.20.0.10"]
  labels:
    node-type: StatefulSet
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: useast1-stateful
spec:
  amiSelector:
    aws-ids: "ami-03cda5ec8e5da6650"
  subnetSelector:
    karpenter.sh/discovery: useast1
  securityGroupSelector:
    karpenter.sh/discovery: useast1
  instanceProfile: KarpenterInstanceProfile
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        deleteOnTermination: true
  tags:
    karpenter.sh/discovery: useast1
    Name: karpenter-useast1-Stateful
```

**Comment by ben5556** [comment]
Please re-open thanks

**Comment by ben5556** [comment]
@jonathan-innis any thoughts on this please ? It is stopping our ability to move our clusters scaling under karpenter

**Comment by jonathan-innis** [comment]
> `incompatible with provisioner "useast1-infrastructure", incompatible requirements, key node-type, node-type In [StatefulSet] not in node-type In [Infrastructure]	{"commit": "f60dacd", "pod": "infrastructure/apm-es-cluster-3"}`

From the error above, it looks like the workload that you are trying to schedule has an affinity or a nodeSelector with the value `Infrastructure` in the `node-type`. If that's the case, you need to remove this section from your provisioner since it's restricting the labels that your Provisioner can add to the node for `node-type`

```
...
  labels:
    node-type: StatefulSet
...
```

**Comment by ben5556** [comment]
@jonathan-innis the `apm-es-cluster-3` pod has an affinity with the value `StatefulSet` in the `node-type`.

What I believe the above message you highlighted is saying is that the pod is incompatible with the infrastructure provisioner as the affinity does not match.

We’ve had karpenter version `v0.16.x` on an other cluster deployed about 6-7 months ago and that didn’t have the issue I am seeing here as we’ve had custom labels that worked just fine. What changed in `v0.20.0` ?

**Comment by jonathan-innis** [comment]
> What I believe the above message you highlighted is saying is that the pod is incompatible with the infrastructure provisioner as the affinity does not match.

From what I can tell, it looks like the pod has an affinity with Infrastructure. That's what the second error message above is saying, since it was compared against the statefulset provisioner.

Can you share the rest of the statefulset manifest to look at what the pod is requesting?

**Comment by ben5556** [comment]
This is the affinity and anti-affinity configuration on the `apm-es-cluster` Statefulset manifest

```
spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - StatefulSet
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - es-logging
                  - ct-es-master
                  - cassandra
                  - postgresql
                  - db-rs
                  - kafka
                  - mongodb-replicaset
                  - zookeeper
                  - ctredis
                  - apm-es-cluster
              topologyKey: kubernetes.io/hostname
            weight: 1
```

**Comment by ben5556** [comment]
I have 2 provisioners currently configured. One is `infrastructure` and the other is `stateful`. so when the pod is being scheduled it checks both provisioners. If we break down the error in 2 parts. The first one says, it could not satisfy any instance type. The second one outright says the provisioner is incompatible as the node-type label does not match. Did I get that right ?

`Could not schedule pod, incompatible with provisioner "useast1-stateful", no instance type satisfied resources {"cpu":"3","memory":"20Gi","pods":"1"} and requirements node-type In [StatefulSet], kubernetes.io/arch In [amd64], topology.kubernetes.io/zone In [us-east-1a], karpenter.sh/capacity-type In [spot], karpenter.k8s.aws/instance-category In [c m r], karpenter.k8s.aws/instance-generation Exists >2, kubernetes.io/os In [linux], topology.kubernetes.io/region In [us-east-1], karpenter.sh/provisioner-name In [useast1-stateful];`

`incompatible with provisioner "useast1-infrastructure", incompatible requirements, key node-type, node-type In [StatefulSet] not in node-type In [Infrastructure]`

**Comment by jonathan-innis** [comment]
Do you have any topology spread on the statefulset?

**Comment by ben5556** [comment]
We have the affinity and anti affinity requirements that I pasted above. No topology spread constraints. Let me attach the full manifest 1 sec

**Comment by ben5556** [comment]
[apm.yaml.txt](https://github.com/aws/karpenter/files/10283387/apm.yaml.txt)

attached.. please rename it .yaml

**Comment by ben5556** [comment]
@jonathan-innis please advise how to proceed on this issue. Do you think we should just use the older version of karpenter v0.16.x ?

**Comment by jonathan-innis** [comment]
I doubt this is an issue with the version. You could try installing an older version and see if it resolves your issue. I'm not able to repro this on my cluster given the two provisioners you provided and your statefulset workload.

Can you double-checck that the provisioners and the statefulset that actually appear from the yaml on the cluster matches what you have shown above? I'm thinking you may have some mutating webhook on either that might be updating the data before it hits the api-server.

**Comment by ben5556** [comment]
Which version of k8s did you test this on please ? I am positive the yaml on the cluster matches what I gave you. I copied them over from the cluster. I don't have a local copy.

How can I check and confirm the below is the culprit ? What is a mutating webhook ?

_I'm thinking you may have some mutating webhook on either that might be updating the data before it hits the api-server._

**Comment by ben5556** [comment]
Did you have to use the below to get it to work as expected on your end ?

```
requirements:
- key: node-type
  operator: Exists
```

**Comment by ben5556** [comment]
Can you share the provisioners and statefulset you used and I will test with that on a new cluster ?

**Comment by jonathan-innis** [comment]
> Did you have to use the below to get it to work as expected on your end ?

No, I missed that you had the `labels` field at the bottom of the Provisioner spec which should be sufficient to set the known values for user-defined labels

```
spec:
...
  labels:
    node-type: StatefulSet
...
```

With that `label` field set, you shouldn't need to set the `Exists` requirement.

**Comment by jonathan-innis** [comment]
> Can you please share the provisioners and statefulset you used and I will test with that on a new cluster ?

I tried to capture the gist of it by creating a StatefulSet with affinity and anti-affinity on a fresh cluster along with a Provisioner with your scheduling requirements as a baseline.

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  consolidation:
    enabled: true
  providerRef:
    name: default
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-west-2a"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot"]
  labels:
    node-type: StatefulSet
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:                             
    karpenter.sh/discovery: ${CLUSTER_NAME}
  securityGroupSelector:                      
    karpenter.sh/discovery: ${CLUSTER_NAME}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apm-es-cluster
spec:
  podManagementPolicy: Parallel
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test
  serviceName: apm-es-cluster
  template:
    metadata:
      labels:
        app: test
      namespace: ct-infrastructure
    spec:
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 1
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - StatefulSet
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - es-logging
                  - ct-es-master
                  - cassandra
                  - postgresql
                  - db-rs
                  - kafka
                  - mongodb-replicaset
                  - zookeeper
                  - ctredis
                  - apm-es-cluster
              topologyKey: kubernetes.io/hostname
            weight: 1
```
