### ISSUE TITLE
Add `imageGCThresholdPercent` support to `kubeletConfiguration`

### ISSUE THREAD

**Issue by Swalloow** [aws/karpenter#3110]
### Tell us about your request

- Adds `imageGCHighThresholdPercent`, `imageGCLowThresholdPercent` support into kubeletConfiguration
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  ...
  kubeletConfiguration:
    imageGCHighThresholdPercent: 80
    imageGCLowThresholdPercent: 60
```

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

I'm trying to configure Amazon EKS worker nodes to clean up the image cache at a specified percent of disk usage.
Ref: https://aws.amazon.com/premiumsupport/knowledge-center/eks-worker-nodes-image-cache/

### Are you currently working around this issue?

Currently I'm solving it with the userdata script.
Ref: https://aws.amazon.com/premiumsupport/knowledge-center/eks-worker-nodes-image-cache/

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
