### ISSUE TITLE
Add support for Elastic Fabric Adapter (EFA) to Karpenter

### ISSUE THREAD

**Issue by iankouls-aws** [aws/karpenter#3127]
Problem Statement:

Some workloads [distributed training, simulations, HPC applications] require high performance networking on AWS provided by instances that are enabled with [Elastic Fabric Adapter](https://aws.amazon.com/hpc/efa/). The specific instance types are documented [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa.html#efa-instance-types). Currently Karpenter does not recognize EFA resource requests or limits specified in Kubernetes manifests as described below.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              vpc.amazonaws.com/efa: 1
            limits:
              vpc.amazonaws.com/efa: 1
```

When such a manifest is applied to a Karpenter-enabled cluster, the Karpenter controller produces an error like the following:

```log
ERROR   controller.provisioning Could not schedule pod, incompatible with provisioner "default", no instance type satisfied resources {"pods":"1","vpc.amazonaws.com/efa":"1"} and requirements karpenter.k8s.aws/instance-generation Exists >2, karpenter.sh/provisioner-name In [default], karpenter.sh/capacity-type In [on-demand spot], kubernetes.io/os In [linux], kubernetes.io/arch In [amd64], karpenter.k8s.aws/instance-category In [c m r]   {"commit": "f290d37-dirty", "pod": "default/inflate-fd9bc9f9b-xmkq2"}
```

Feature Request:

Add capability in Karpenter to recognize resource `vpc.amazonaws.com/efa`, identify, and provision a suitable EC2 instance type with EFA enabled.
