### ISSUE TITLE
Add support for Host Resource Groups

### ISSUE THREAD

**Issue by cspargo** [aws/karpenter#3182]
### Tell us about your request

We use Dedicated Hosts provisioned with Host Resource Groups (a.k.a "host" tenancy).  These require some additional settings in the launch template data  to set the tenancy, the ARN of the host resource group and the ARN of the license configuration. These settings are mentioned [here](https://docs.aws.amazon.com/autoscaling/ec2/userguide/create-launch-template.html#advanced-settings-for-your-launch-template). 

In cloudformation, it would look like this
```
   Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: foo
      LaunchTemplateData:
        Placement:
          Tenancy: host
          HostResourceGroupArn: arn:aws:resource-groups:us-east-1:123456789012:group/my-hrg-name
        LicenseSpecifications:
          - LicenseConfigurationArn: arn:aws:license-manager:eu-east-1:123456789012:license-configuration:lic-edf7f9e241f5e16f29996c842111f448
```

It would mean adding full or partial support for these to the aws node template

- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-placement.html (only need "Tenancy" and "HostResourceGroupArn" for this use case)
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-licensespecification.html

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

We would like to be able to provision instances onto our dedicated hosts with Karpenter. This blocks us from using it.

There was a previous issue regarding dedicated hosts https://github.com/aws/karpenter/issues/2556. The recommendation there was to use custom launch templates, however I believe support for these is or will be removed.

### Are you currently working around this issue?

we don't have any workaround

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
