### ISSUE TITLE
Missing SQS permission in starter cloudformation

### ISSUE THREAD

**Issue by sansmoraxz** [aws/karpenter#3185]
### Version

__Karpenter Version:__ v0.22.0

__Kubernetes Version:__ v1.23.14-eks-ffeb93d

### Expected Behavior

Successfully join SQL queue

### Actual Behavior

Failure to join SQS due to missing permission

### Steps to Reproduce the Problem

Follow the steps provided in the guide at https://karpenter.sh/v0.22.0/getting-started/getting-started-with-eksctl/

```bash
curl -fsSL https://karpenter.sh/"${KARPENTER_VERSION}"/getting-started/getting-started-with-eksctl/cloudformation.yaml  > $TEMPOUT \
&& aws cloudformation deploy \
  --stack-name "Karpenter-${CLUSTER_NAME}" \
  --template-file "${TEMPOUT}" \
  --capabilities CAPABILITY_NAMED_IAM \
  --parameter-overrides "ClusterName=${CLUSTER_NAME}"
```

Can be fixed by attaching SQS permissions to the created role

### Resource Specs and Logs

[error.log](https://github.com/aws/karpenter/files/10376106/err_.log)
[expect.log](https://github.com/aws/karpenter/files/10376108/expect.log)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Can you describe your environment a little more? We haven't observed other users hitting this issue. I'm wondering if this has to do with adding permissions to the role in IAM and needing the container to be restarted to pick up the new config and permissions.

**Comment by sansmoraxz** [comment]
I tried to reproduce this a couple of times on fresh clusters but I seem to be out of luck. It may possibly be an one off thing unless I messed up the configuration somewhere.

I was following the getting started guide without any modifications if that helps.

**Comment by njtran** [comment]
@sansmoraxz I just installed fresh from the getting-started guide without any modifications and hadn't seen any issues. 

Can you show which IAM permission it needs? The default policy only allows it on specific queues, so maybe you've inputted a queue that is different than the one allowed in the IAM document?

Here's the IAM snippet used
```
          - Effect: Allow
            Action:
              # Write Operations
              - sqs:DeleteMessage
              # Read Operations
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ReceiveMessage
            Resource: !GetAtt KarpenterInterruptionQueue.Arn
```
