### ISSUE TITLE
Tags fail to propagate to resources

### ISSUE THREAD

**Issue by sidewinder12s** [aws/karpenter#3198]
### Version

__Karpenter Version:__ v0.22.0

__Kubernetes Version:__ v1.22

### Expected Behavior

AWSNodeTemplate and global `settings.aws.tags` tags should propagate to all resources. Karpenter Default tags should propagate as well

### Actual Behavior

Tags are applied to the launch template itself and in the Resource Tags configuration of the generated launch template, but the tags are not set to propagate to everything (Instance, Volumes, etc). Even the default Karpenter tags are not set to propagate.

### Steps to Reproduce the Problem

Run without tags or set tags.

### Resource Specs and Logs

```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    # karpenter.sh/discovery: '{{ .Values.clusterName }}'
    aws-ids: "subnet-ids"
  securityGroupSelector:
    karpenter.sh/discovery: '{{ .Values.karpenter.settings.aws.clusterName }}'
  amiSelector:
    aws-ids: '{{ .Values.clusterWorkerAmiId }}'
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: optional
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        deleteOnTermination: true
  tags:
    my-tag/project: {{ .Values.clusterName }}
    my-tag/contact: contact
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
