### ISSUE TITLE
Architecture mismatch when requesting arm64 EC2 instance with GPU

### ISSUE THREAD

**Issue by pcolmer** [aws/karpenter#3217]
### Version

__Karpenter Version:__ v0.22.1

__Kubernetes Version:__ v1.24.0

### Expected Behavior

A Pod specification for `arm64` architecture and 1 NVIDIA GPU should launch an instance from the g5g family.

### Actual Behavior

Karpenter says it is going to launch the instance:
```
2023-01-13T14:25:33.030Z        INFO    controller.provisioner  launching node with 1 pods requesting {"cpu":"2610m","memory":"4008650Ki","nvidia.com/gpu":"1","pods":"5"} from types g5g.metal, g5g.16xlarge, g5g.4xlarge, g5g.2xlarge, g5g.xlarge and 1 other(s)        {"commit": "c4a4efd-dirty", "provisioner": "gpu-default"}
```
but an error is then reported:
```
2023-01-13T14:25:28.412Z        ERROR   controller.provisioner  launching machine, creating cloud provider instance, creating instance, with fleet error(s), InvalidParameterValue: The architecture 'arm64' of the specified instance type does not match the architecture 'x86_64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type or AMI.  {"commit": "c4a4efd-dirty"}
```

### Steps to Reproduce the Problem

Try to launch a Pod that requires `arm64` architecture and a NVIDIA GPU.

Provisioner & provider:

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: gpu-default
spec:
  weight: 99
  ttlSecondsAfterEmpty: 5
  labels:
    clo/gpu-type: nvidia
  providerRef:
    name: default
  requirements:
    - key: "kubernetes.io/arch"
      operator: In
      values: ["arm64", "amd64"]
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: ["g"]
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: ci-cluster
  securityGroupSelector:
    karpenter.sh/discovery: ci-cluster
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"

    --BOUNDARY
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash -xe
    exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
    TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"`
    AWS_AVAIL_ZONE=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -S http://169.254.169.254/latest/meta-data/placement/availability-zone)
    AWS_REGION="`echo \"$AWS_AVAIL_ZONE\" | sed 's/[a-z]$//'`"
    AWS_INSTANCE_ID=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -S http://169.254.169.254/latest/meta-data/instance-id)
    ROOT_VOLUME_IDS=$(aws ec2 describe-instances --region $AWS_REGION --instance-id $AWS_INSTANCE_ID --output text --query Reservations[0].Instances[0].BlockDeviceMappings[0].Ebs.VolumeId)
    aws ec2 create-tags --resources $ROOT_VOLUME_IDS --region $AWS_REGION --tags Key="InstanceID",Value="$AWS_INSTANCE_ID"

    --BOUNDARY--
```

### Resource Specs and Logs

See logs under "Actual behaviour".

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
