### ISSUE TITLE
Pending pods when using topology spread constrains

### ISSUE THREAD

**Issue by abirsigron** [aws/karpenter#3239]
### Version

__Karpenter Version:__ v0.21.1

__Kubernetes Version:__ v1.23.13

### Expected Behavior

When scaling up the number of pods, karpenter should scale up the number of nodes accordingly.
Even if the deployment has the following topology:
```yaml
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: abir-test
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
```

### Actual Behavior

Karpenter is only creating 3 nodes, 1 for each zone in the cluster and it is unable to create more nodes after that.

When the deployment replicas is set to 3, karpenter successfully scale 3 nodes in 3 zones (that we have).
**But** when the replicas are set to a larger number and the existing nodes doesn't have more capacity, the new pods are stuck on pending.
I can see errors in karpenter logs that hints that karpenter is unable to schedule the new pod due to the topology spread constrains 
The expected behavior is for karpenter to create new nodes for the new pods to schedule on.

### Steps to Reproduce the Problem

1. Create a simple deployment with 3 replicas and with the specified topology.
2. Scale up the deployment to larger number so new node creation will be needed.
3. New pods won't have capacity but karpenter will not scale new nodes for them.

### Resource Specs and Logs

Deployment with topology spread constrains:
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: abir-test
  template:
    metadata:
      labels:
        app: abir-test
    spec:
      containers:
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: abir-test
        ports:
        - containerPort: 80
          name: default-port
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: "2"
            memory: 256Mi
      nodeSelector:
        intent: abir-test
        project: abir-test
      restartPolicy: Always
      schedulerName: default-scheduler
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: abir-test
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
```

Provisioners:
```yaml
provisioners:
  abir-test:
    intent: abir-test
    project: abir-test
```

Unable to schedule log:
```2023-01-19T16:03:00.337Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "abir-test", unsatisfiable topology constraint for topology spread, key=topology.kubernetes.io/zone	{"commit": "06cb81f-dirty", "pod": "devops-apps/abir-test-7574467bdc-tt52m"}```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Can you provide your entire provisioner?

**Comment by abirsigron** [comment]
Hi @tzneal here is the entire provisioner:

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"karpenter.sh/v1alpha5","kind":"Provisioner","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/instance":"karpenter-resources"},"name":"abir-test"},"spec":{"consolidation":{"enabled":true},"labels":{"intent":"abir-test","nodegroup-name":"abir-test","project":"abir-test"},"providerRef":{"name":"abir-test"},"requirements":[{"key":"topology.kubernetes.io/zone","operator":"In","values":["us-east-1b","us-east-1d","us-east-1e"]},{"key":"karpenter.sh/capacity-type","operator":"In","values":["spot","on-demand"]},{"key":"karpenter.k8s.aws/instance-size","operator":"NotIn","values":["nano","micro","small","large","16xlarge","18xlarge","24xlarge","32xlarge","48xlarge","metal"]},{"key":"karpenter.k8s.aws/instance-family","operator":"In","values":["c5","c5d","c5n","c6i","c6id","c6a","m5","m5d","m5n","m5dn","m5zn","m6i","m6id","m6a","r5","r5d","r5n","r5dn","r6i","r6id","r6a"]},{"key":"kubernetes.io/arch","operator":"In","values":["amd64"]},{"key":"kubernetes.io/os","operator":"In","values":["linux"]}]}}
  creationTimestamp: "2023-01-18T14:55:22Z"
  generation: 1
  labels:
    argocd.argoproj.io/instance: karpenter-resources
  name: abir-test
  resourceVersion: "192649683"
  uid: 877c3e16-12e0-4843-9db6-4d3422869b24
spec:
  consolidation:
    enabled: true
  labels:
    intent: abir-test
    nodegroup-name: abir-test
    project: abir-test
  providerRef:
    name: abir-test
  requirements:
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - us-east-1b
    - us-east-1d
    - us-east-1e
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
    - on-demand
  - key: karpenter.k8s.aws/instance-size
    operator: NotIn
    values:
    - nano
    - micro
    - small
    - large
    - 16xlarge
    - 18xlarge
    - 24xlarge
    - 32xlarge
    - 48xlarge
    - metal
  - key: karpenter.k8s.aws/instance-family
    operator: In
    values:
    - c5
    - c5d
    - c5n
    - c6i
    - c6id
    - c6a
    - m5
    - m5d
    - m5n
    - m5dn
    - m5zn
    - m6i
    - m6id
    - m6a
    - r5
    - r5d
    - r5n
    - r5dn
    - r6i
    - r6id
    - r6a
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
status: {}

```

**Comment by kwarunek** [comment]
We're facing the same problem (but with different different constraint). In our setup we have 2 provsioner: 
- spot only
- on-demand

with an addtional requirement `capacity-spread` and all deployments are enforcing that requirement. And at some point during the rollout many pods stuck in Pending without a reason why karpenter does not to scale new nodes.

**Comment by tzneal** [comment]
@abirsigron I tried to reproduce it this morning, but the deployment spec you provided isn't valid.  Containers is a list in the YAML, and a map in yours.  I fixed that, but then ran into another error.  To ensure I'm testing your setup and not something else, can you provide a working deployment spec that reproduces this issue?

**Comment by abirsigron** [comment]
@tzneal Sorry for the bad deployment, I tested this one and its working:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abir-nginx-deployment
  namespace: devops-apps
spec:
  selector:
    matchLabels:
      app: abir-nginx
  replicas: 9
  template:
    metadata:
      labels:
        app: abir-nginx
    spec:
      containers:
      - name: abir-nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 256Mi
            cpu: "2"
          requests:
            cpu: "2"
            memory: 256Mi
      nodeSelector:
        intent: abir-test
        project: abir-test
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: abir-nginx
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule

```

**Comment by abirsigron** [comment]
@tzneal try to deploy it first with 3 replicas and then scale it up to 9, in our cluster 6 pods are remaining in pending mode.

**Comment by alex-berger** [comment]
Similar problem here, Karpenter assumes Pod (from a StatefulSet) fits on a specific node, but the Kubernetes Scheduler seems to not agree. And I suspect that this could be caused by topologySpreadConstraints (but cannot proof it yet). Karpenter keeps on saying things like:

```
Pod should schedule on ip-10-176-4-92.eu-central-1.compute.internal
```

While Kubernetes Scheduler continuously complains:

```
0/42 nodes are available: 
1 node(s) didn't match pod topology spread constraints, 
1 node(s) were unschedulable, 
11 node(s) didn't match Pod's node affinity/selector, 
2 node(s) had taint {eks.amazonaws.com/compute-type: fargate}, that the pod didn't tolerate, 
26 Insufficient memory, 
6 Insufficient cpu.
```
Could it be that the Kubernetes Scheduler also considers resource (e.g. CPU) limits (not just resource requests) when scheduling Pods, while Karpenter only consider resource requests?

**Comment by tzneal** [comment]
@abirsigron Can you try removing the zone requirement from your provisioner, Karpenter will detect these automatically. If they are incorrect, it can cause this problem:

```
 - key: topology.kubernetes.io/zone
    operator: In
    values:
    - us-east-1b
    - us-east-1d
    - us-east-1e
``

**Comment by tzneal** [comment]
@alex-berger Can you file a new issue and include provisioner/statefulset information as well as logs?  kube-scheduler schedules based on requests as well, so it shouldn't cause an issue.

**Comment by alex-berger** [comment]
@tzneal I filed https://github.com/aws/karpenter/issues/3262.

**Comment by abirsigron** [comment]
@tzneal I think we are on to something.

What you said about removing the zones got me thinking.
In our cluster we have 4 zones, but 1 of them is used only for egress traffic.
All of our provisioners are currently deploying only to the 3 other zones by choice (I think this a common case)

Maybe karpenter auto-detection of zones when using topology-spread is detecting all 4 zones but in the provisioner configurations we are selecting only 3 zones and that is causing unexpected behavior from karpenter side.

Can you try adding only part of the zones in your testing cluster and see if you can reproduce the issue?

**Comment by abirsigron** [comment]
Hey @tzneal 
unfortunately, upgrading to karpenter version v0.23.0 didn't solve our issue.
Pods are still pending when using topology spread constrains with "zone" key.

Were you able to reproduce the issue in your enviroment?
Did the code change fixed it for you?

thanks!

**Comment by kwarunek** [comment]
@tzneal In our case we wasn't able to reproduce our issues on isolated env, so I will delay any ticket here until it appears and will be able to add logs. Worth mention is that we have 1k nodes and about 50 provisioners and workload deployed via fluxcd/helmcontroller rollout, so we presume either 1) cluster is too large, 2) flux intervals /timeouts introduce too much noise during rolllout and then rollbacks or both.

**Comment by tzneal** [comment]
@abirsigron  I was able to reproduce it and fixed it with https://github.com/aws/karpenter-core/pull/173. Does it still fail with the deployment you provided above?  I tested locally with that.

**Comment by abirsigron** [comment]
@tzneal yes, I tested it with the deployment I sent you.
We are using this image and chart: 
```
image:
public.ecr.aws/karpenter/controller:v0.23.0@sha256:40aea3b25a33ff2cb44bdecf0417a2642e2a785b4fd30067634ef8f1bd48383c

chart: 0.23.0
```

Is that the correct version that include the fix?
What additional info you need?

**Comment by abirsigron** [comment]
@tzneal 
I found something interesting! 

When I deployed only 1 deployment with 9 replicas the pods and nodes looked like this:
It looked like this:
![image](https://user-images.githubusercontent.com/23218171/216069555-e26f7c02-daa3-47bf-81cc-f84688c65d86.png)
![image](https://user-images.githubusercontent.com/23218171/216069658-1b2f7c1e-b123-454f-b532-874ed3481e85.png)

But when I deployed another test app with 5 replicas the situation looked better, but there was still 1 pending pod though:
![image](https://user-images.githubusercontent.com/23218171/216071746-6d71f846-f02d-4666-ae23-b48f88a49f0a.png)
![image](https://user-images.githubusercontent.com/23218171/216071855-38679edc-7ce9-420d-800a-2af9a7097753.png)


Maybe you can't reproduce this issue because you already have multiple deployments running on the same provisioner.
Can you try reproduce it with only 1 deployment running on the provisioner?

**Comment by tzneal** [comment]
The only way I can reproduce this now (even with a single deployment) is by specifying an incorrect zone in my provisioner.  Are you sure that you have subnets in your cluster VPC that are selected for all of:

```
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - us-east-1b
    - us-east-1d
    - us-east-1e
```

**Comment by tzneal** [comment]
@abirsigron Can you try out a snapshot Karpenter on a non-prod cluster?

```
kubectl set image deployment/karpenter -n karpenter controller=public.ecr.aws/karpenter/controller:7e81233cd040d6efd16c67e45d785e400c7a6464
```

This version has some extra logging in the unsatisfied topology constraint case that will hopefully provide some insight into what's occurring.

**Comment by abirsigron** [comment]
hey @tzneal 
here are the output logs, I do see additional errors:
[karpenter_debug.log](https://github.com/aws/karpenter/files/10610656/karpenter_debug.log)

**Comment by tzneal** [comment]
@abirsigron Do you have the topology requirement on all of your provisioners, or is there possible one that is missing it?

```
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - us-east-1b
    - us-east-1d
    - us-east-1e
```
