### ISSUE TITLE
Is "karpenter.sh/do-not-evict" documented correctly?

### ISSUE THREAD

**Issue by cep21** [aws/karpenter#3251]
### Is an existing page relevant?

https://karpenter.sh/v0.22.1/concepts/deprovisioning/#consolidation

### What karpenter features are relevant?

Pod Eviction.

### How should the docs be improved?

I see this text under "Pod Eviction".

```yaml
spec:
  template:
    metadata:
      labels:
        karpenter.sh/do-not-evict: ""
```

The go code, [scheduling.go](https://github.com/aws/karpenter-core/blob/c38b8b0a9d7ae309f21e49b649543b1d01fd6231/pkg/utils/pod/scheduling.go#L86), has this:
```go
func HasDoNotEvict(pod *v1.Pod) bool {
	if pod.Annotations == nil {
		return false
	}
	return pod.Annotations[v1alpha5.DoNotEvictPodAnnotationKey] == "true"
}
```

Should the documented annotation be
```
spec:
  template:
    metadata:
      labels:
        karpenter.sh/do-not-evict: true
```

?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
