### ISSUE TITLE
Unschedulable Pods as Karpenter and Kubernetes Scheduler disagree 

### ISSUE THREAD

**Issue by alex-berger** [aws/karpenter#3262]
### Version

__Karpenter Version:__ [v0.22.1](https://github.com/aws/karpenter/releases/tag/v0.22.1)

__Kubernetes Version:__ v1.22.15 (v1.22.15-eks-fb459a0)

### Expected Behavior

There should be no unschedulable Pods. Whenever the *Kubernetes Scheduler* fails to schedule a Pod, *Karpenter* should kick-in and provision new nodes to enable the *Kubernetes Scheduler* to schedule the affected Pod.

### Actual Behavior

From time to time, some Pods are stuck in `Pending` state as they cannot be assigned to a node by the *Kubernetes Scheduler*, while *Karpenter* is confident  that those Pods will fit onto existing nodes. It looks like *Karpenter* and *Kubernetes Scheduler* disagree resp. do not use the same algorithms to schedule Pods.

On the affected cluster we are running *Karpenter* and *Cluster Autoscaler*, each responsible for a disjunct set of Pods/Nodes (enforced with Taints/Tolerations and `nodeAffinity`). Some information from the *Cluster Autoscaler*, that we can see in below table, might be helpful to understand which system is acting wrong (*Karpenter* vs *Kubernetes Scheduler*).

On affected Pods we are observing events like the ones outline in below table:

|Type|Reason|Age|From|Message|
|---|---|---|---|---|
|Warning|FailedScheduling|5m11s (x352 over 119m)|default-scheduler|0/31 nodes are available: 1 node(s) had taint {node.cilium.io/agent-not-ready: true}, that the pod didn't tolerate, 1 node(s) had volume node affinity conflict, 11 node(s) didn't match Pod's node affinity/selector, 15 Insufficient memory, 2 node(s) had taint {eks.amazonaws.com/compute-type: fargate}, that the pod didn't tolerate, 6 Insufficient cpu.|
|Normal|Nominated|4m36s (x404 over 11h)|karpenter|(combined from similar events): Pod should schedule on ip-10-176-5-232.eu-central-1.compute.internal|
|Normal|NotTriggerScaleUp|50s (x4289 over 12h)|cluster-autoscaler|pod didn't trigger scale-up: 3 node(s) didn't match Pod's node affinity/selector|
|Warning|FailedScheduling|13s (x174 over 118m)|default-scheduler|0/31 nodes are available: 11 node(s) didn't match Pod's node affinity/selector, 15 Insufficient memory, 2 node(s) had taint {eks.amazonaws.com/compute-type: fargate}, that the pod didn't tolerate, 2 node(s) had volume node affinity conflict, 6 Insufficient cpu.|

From those events, we can see that:

- *Karpenter* is confident that the Pod will fit on node `ip-10-176-5-232.eu-central-1.compute.internal` and thus does not bring-up any new nodes for that Pod.
- *Kubernetes Scheduler* refuses to schedule the Pod to any existing node.
- *Cluster Autoscaler* also indicates that the Pod will not fit on any existing nodes (altough it is not responsible anyway, `didn't match Pod's node affinity/selector`).

Naively, it looks like two systems (*Kubernetes Scheduler* and *Cluster Autoscaler*) agree that the Pod cannot be scheduled onto any existing node, while one system (*Karpenter*) is confident that it should fit onto a specific existing node.

### Steps to Reproduce the Problem

We cannot yet reliably reproduce this, but it happens from time to time. Once this happens the affected Pods are stuck in `Pending` state for days or weeks. 

It might also be worth mentioning, that (so far) the affected Pods all had the following kind of scheduling constraints (see attached files for more detailed information on this):

- `nodeAffinity`
- `taints/tolerations`
- `topologySpreadConstraints`
- `PersistentVolumes`

### Resource Specs and Logs

Here some detailed information about one specific occurrence of this problem, with a Pod called `cortex-ingester-2`, which belongs to a *StatefulSet* called `cortex-ingester`. 

[provisioners.txt](https://github.com/aws/karpenter/files/10487698/provisioners.txt)
[awsnodetemplates.txt](https://github.com/aws/karpenter/files/10487699/awsnodetemplates.txt)
[cortex-ingester.sts.txt](https://github.com/aws/karpenter/files/10487700/cortex-ingester.sts.txt)
[cortex-ingester-2.pod.txt](https://github.com/aws/karpenter/files/10487702/cortex-ingester-2.pod.txt)
[cortex-ingester-2.pod.describe.txt](https://github.com/aws/karpenter/files/10487703/cortex-ingester-2.pod.describe.txt)
[storage-cortex-ingester-2.pv.txt](https://github.com/aws/karpenter/files/10488067/storage-cortex-ingester-2.pv.txt)
[storage-cortex-ingester-2.pvc.txt](https://github.com/aws/karpenter/files/10488069/storage-cortex-ingester-2.pvc.txt)

[karpenter.logs.csv](https://github.com/aws/karpenter/files/10487817/karpenter.logs.csv)
[kube-scheduler.logs.csv](https://github.com/aws/karpenter/files/10487842/kube-scheduler.logs.csv)

And here an excerpt from the affected Pod for `affinity`, `tolerations`, `topologySpreadConstraints` and `volumes`. The backing *EBS Volume* for the *PersistentVolumeClaim* `storage-cortex-ingester-2` is ready and available (not bound to any EC2 instance) in *Availability Zone* `eu-central-1a`.

```yaml
metadata:
    labels: 
        nx-k8s-topology-id: f63b5ac0-408b-43cd-aba3-7cbbfe691c59
        ...
spec:
 ...
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - arm64
                  - amd64
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
              - key: node.k8s.nexxiot.com/purpose
                operator: In
                values:
                  - k8s-cluster
              - key: karpenter.k8s.aws/instance-cpu
                operator: Gt
                values:
                  - '3'
              - key: karpenter.k8s.aws/instance-category
                operator: NotIn
                values:
                  - t
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - arm64
              - key: karpenter.sh/capacity-type
                operator: In
                values:
                  - on-demand
        - weight: 50
          preference:
            matchExpressions:
              - key: karpenter.sh/capacity-type
                operator: In
                values:
                  - on-demand
  tolerations:
    - key: workload-type
      operator: Equal
      value: cluster-services
      effect: NoSchedule
    - key: kubernetes.io/arch
      operator: Equal
      value: arm64
      effect: NoSchedule
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/region
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          nx-k8s-topology-id: f63b5ac0-408b-43cd-aba3-7cbbfe691c59
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          nx-k8s-topology-id: f63b5ac0-408b-43cd-aba3-7cbbfe691c59
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          nx-k8s-topology-id: f63b5ac0-408b-43cd-aba3-7cbbfe691c59
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: storage-cortex-ingester-2
    ...
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
