### ISSUE TITLE
Volume of size 1GB is smaller than snapshot

### ISSUE THREAD

**Issue by bwmetcalf** [aws/karpenter#3302]
### Version

__Karpenter Version:__ v0.22.1

__Kubernetes Version:__ v1.24.0

### Expected Behavior

We have the following node template (relevant parts shown):
```
...
  spec:
    amiFamily: Custom
    amiSelector:
      aws-ids: ami-012cc3171fae12cba
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 2G
        volumeType: gp2
    - deviceName: /dev/xvdb
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 1T
        volumeType: gp2
...
```

and provisioner:
```
...
spec:
  consolidation:
    enabled: true
  limits:
    resources:
      memory: 240Gi
  providerRef:
    name: default-node-template
...
```

and expect a new node to spun up.

### Actual Behavior

We are getting the following in the logs:
```
2023-01-27T16:04:56.923Z	INFO	controller.provisioner	launching node with 1 pods requesting {"cpu":"1030m","memory":"3999Mi","pods":"7"} from types m5.2xlarge, m5.xlarge	{"commit": "c4a4efd-dirty", "provisioner": "karpenter-provisioner"}
2023-01-27T16:04:58.120Z	ERROR	controller.provisioner	launching machine, creating cloud provider instance, creating instance, with fleet error(s), InvalidBlockDeviceMapping: Volume of size 1GB is smaller than snapshot 'snap-090fea468f03e1c8b', expect size >= 2GB	{"commit": "c4a4efd-dirty"}
```

### Steps to Reproduce the Problem

Install karpenter 0.22.1 and create node template similar to the above.

### Resource Specs and Logs

See above.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
