### ISSUE TITLE
Node in notready status for a while and reporting Inflight check failed for node, Instance Type "" not found

### ISSUE THREAD

**Issue by scharishma-db** [aws/karpenter#3311]
### Version

__Karpenter Version:__ v0.0.0

__Kubernetes Version:__ v1.0.0

### Expected Behavior

Karpenter should be up and running and add the unschedulable pods to the nodes

### Actual Behavior

Installed Karpenter on to a existing cluster, Karpenter pods readiness probe failed and node was always in notready status. After couple of hours the Karpenter logs and Node describe shows error  ''' reporting Inflight check failed for node, Instance Type "" not found''

### Steps to Reproduce the Problem

Karpenter logs:

```
hostname": "ip-xxxxxx.us-west-2.compute.internal", "type": "t2.xlarge", "zone": "us-west-2c", "capacity-type": "on-demand"}
2023-01-27T20:38:06.200Z        DEBUG   controller.aws  deleted launch template {"commit": "f60dacd"}
2023-01-27T21:28:28.511Z        INFO    controller.inflightchecks       Inflight check failed for node, Instance Type "" not found      {"commit": "f60dacd", "node": "ip-1xxxxxxx.us-west-2.compute.internal"}
2023-01-27T21:38:28.533Z        INFO    controller.inflightchecks       Inflight check failed for node, Instance Type "" not found      {"commit": "f60dacd", "node": "xxxxxxxxxx.us-west-2.compute.internal"} 
```

### Resource Specs and Logs
```
resource "helm_release" "karpenter" {
    name  = "karpenter"
  
    repository          = "oci://public.ecr.aws/karpenter"
    chart               = "karpenter"
    #repository_username = data.aws_ecrpublic_authorization_token.token.user_name
    #repository_password = data.aws_ecrpublic_authorization_token.token.password
    version             =  "v0.22.1"
  
    namespace           = "karpenter"
    create_namespace    = true
  
    set {
      name  = "settings.aws.clusterName"
      value = "aws_eks_cluster.cluster.id"
    }
  
    set {
      name  = "settings.aws.clusterEndpoint"
      value = data.aws_eks_cluster.cluster.endpoint
    }
  
    set {
      name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
      value = data.aws_iam_role.karpenter_controller_role.arn
    }
  
    set {
      name  = "settings.aws.defaultInstanceProfile"
      value = "KarpenterNodeInstanceProfile"
    }

  }

```
-----
provisoner

```
  resource "kubectl_manifest" "karpenter_provisioner" {
  yaml_body = <<-YAML
    apiVersion: karpenter.sh/v1alpha5
    kind: Provisioner
    metadata:
      name: default
    spec:
      provider:
        subnetSelector:
         kubernetes.io/cluster/${var.project_name}: shared
        securityGroupSelector:
         kubernetes.io/cluster/${var.project_name}: owned
      requirements:
        - key: "node.kubernetes.io/instance-type" 
          operator: In
          values: ["t2.large","t2.xlarge"] 
      limits:
        resources:
          cpu: 1000
      # ttlSecondsUntilExpired: 100 # 7 Days = 7 * 24 * 60 * 60 Seconds
     ttlSecondsAfterEmpty: 30
  YAML
  depends_on = [
    helm_release.karpenter
  ]
 }
```

------
deployment.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter-test
spec:
  replicas: 0
  selector:
    matchLabels:
      app: karpenter-test
  template:
    metadata:
      labels:
        app: karpenter-test
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: karpenter-test
          image: nginx:1.16.1 
          resources:
            requests:
              cpu: 650m
          ports:
          - containerPort: 80
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
