### ISSUE TITLE
dl1.24xlrage memory resource incompatibility

### ISSUE THREAD

**Issue by DanielJuravski** [aws/karpenter#3316]
### Version

__Karpenter Version:__ v0.22.1

__Kubernetes Version:__ v1.24

### Expected Behavior

Allocate a workload with `memory` limit & request which are suitable for dl1.24xlarge `memory` (= 694632Mi) which is described here: https://karpenter.sh/v0.22.1/concepts/instance-types/#resources-148

```
resources:
  limits:
    habana.ai/gaudi: 8
    memory: 690Gi
  requests:
    habana.ai/gaudi: 8
    memory: 690Gi
```

In addition, why the memory appears in the instance type resources description (https://karpenter.sh/v0.22.1/concepts/instance-types/#resources-148) is 694632Mi, while the karpenter.k8s.aws/instance-memory is 786432Mi? How this calculation is made?

### Actual Behavior

Karpenter failed to schedule an instance type with the above resources.
`
incompatible with provisioner "gaudi", no instance type satisfied resources {"habana.ai/gaudi":"8","memory":"690Gi","pods":"1"} and requirements kubernetes.io/os In [linux], node.kubernetes.io/instance-type In [dl1.24xlarge], habana.ai/gaudi In [true], karpenter.sh/provisioner-name In [gaudi], karpenter.sh/capacity-type In [on-demand], karpenter.k8s.aws/instance-family In [dl1], kubernetes.io/arch In [amd64];
`

### Steps to Reproduce the Problem

Create Provisioner, AWSNodeTemplate and workload
``` yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "karpenter.k8s.aws/instance-category"
      operator: In
      values: ["c", "m", "r", "p", "g", "dl"]
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 10
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: my-cluster
  securityGroupSelector:
    karpenter.sh/discovery: my-cluster
```
* Apply a workload
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 4
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
      resources:
        limits:
          habana.ai/gaudi: 8
          memory: 690Gi
        requests:
          habana.ai/gaudi: 8
          memory: 690Gi
```

### Resource Specs and Logs

`
incompatible with provisioner "gaudi", no instance type satisfied resources {"habana.ai/gaudi":"8","memory":"690Gi","pods":"1"} and requirements kubernetes.io/os In [linux], node.kubernetes.io/instance-type In [dl1.24xlarge], habana.ai/gaudi In [true], karpenter.sh/provisioner-name In [gaudi], karpenter.sh/capacity-type In [on-demand], karpenter.k8s.aws/instance-family In [dl1], kubernetes.io/arch In [amd64];
`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
