### ISSUE TITLE
A more detailed error message for a Provisioner without providerRef?

### ISSUE THREAD

**Issue by rtripat** [aws/karpenter#3343]
### Version

__Karpenter Version:__ v0.23.0

__Kubernetes Version:__ v1.23.14

### Expected Behavior

I want a bare bones provisioner for non-interruptible workloads so I made edits to the one in Getting Started [guide](https://karpenter.sh/v0.22.1/getting-started/getting-started-with-eksctl/#provisioner). I mistakenly deleted the `providerRef` field as well. 

I expected Karpenter controller error message to be more descriptive about the missing field in the Provisioner. 

### Actual Behavior

I saw the following error in the controller with a generic message 

```
2023-02-02T05:44:42.424Z	ERROR	controller.provisioner	creating scheduler, getting instance types, describing subnets [], InvalidParameterValue: The filter 'null' is invalid
	status code: 400, request id: 9ca1559b-d2bd-4fd3-a447-b3e9ac65ab47	{"commit": "5a7faa0-dirty"}
```

### Steps to Reproduce the Problem

Apply the provisioner below, scale up pods and tail karpenter controller logs for errors

### Resource Specs and Logs

Provisioner
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  ttlSecondsAfterEmpty: 30
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: raghat-cluster
  securityGroupSelector:
    karpenter.sh/discovery: raghat-cluster
```

Karpenter logs
```
2023-02-02T05:44:42.424Z	ERROR	controller.provisioner	creating scheduler, getting instance types, describing subnets [], InvalidParameterValue: The filter 'null' is invalid
	status code: 400, request id: 9ca1559b-d2bd-4fd3-a447-b3e9ac65ab47	{"commit": "5a7faa0-dirty"}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
