### ISSUE TITLE
nodeAffinity causes Karpenter to use the wrong Provisioner

### ISSUE THREAD

**Issue by James-Quigley** [aws/karpenter#3355]
### Version

__Karpenter Version:__ v0.22.1

__Kubernetes Version:__ v1.22.17

### Expected Behavior

Given a provisioner with a NoSchedule taint, and a label of `Function=foobar`

And a workload that has a toleration for the taint, nodeSelector of `Function=foobar` as well as a nodeAffinities of:

preferred: `Function=foo`
required: `Function in (foo, bar, foobar)`

Karpenter should see that the workload should be schedulable on that Provisioner

### Actual Behavior

Karpenter does not see the provisioner as a match (and attempts to use our default provisioner that has no taints). The pod then can't run because it has a nodeSelector for the label from the other provisioner. When the node Affinity rules are removed, Karpenter will correctly create a node using the `foobar` provisioner. 

### Steps to Reproduce the Problem

Create two provisioners, one with a taint and labels

Create a workload with a toleration, nodeSelector AND nodeAffinity. See that Karpenter tries to use the default provisioner, but the workload will not schedule because of its nodeSelector

### Resource Specs and Logs

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  consolidation:
    enabled: true
  providerRef:
    name: al2
  requirements:
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
    - spot
  ttlSecondsUntilExpired: 1209600
```

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: foobar
spec:
  labels:
    Function: foobar
  providerRef:
    name: al2
  requirements:
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  taints:
  - effect: NoSchedule
    key: dedicated
    value: foobar
  ttlSecondsAfterEmpty: 120
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foobar
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: foobar
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: Function
                 operator: In
                 values:
                 - foo
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: Function
                 operator: In
                 values:
                 - foo
                 - bar
                 - foobar
      containers:
        image: busybox
        name: foobar-app
        resources:
          requests:
            cpu: 500m
            memory: 1000Mi
      nodeSelector:
        Function: foobar
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: foobar
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
