### ISSUE TITLE
Karpenter does not consolidate nodes that don't fit a new DaemonSet

### ISSUE THREAD

**Issue by marcofranssen** [aws/karpenter#3374]
### Version

__Karpenter Version:__ v0.22.1 *(also in previous version we have been using)*

__Kubernetes Version:__ v1.24.9

### Expected Behavior

When new DaemonSets are deployed on a existing cluster with existing Karpenter Nodes, those DaemonSets will not fit on the existing Nodes. Karpenter will automatically Consolidate those existing Nodes to replace them with bigger/multiple new Nodes so all DaemonSets will fit. 

### Actual Behavior

When new DaemonSets are deployed on a existing cluster with existing Karpenter Nodes, those DaemonSets will not fit on the existing Nodes. 

### Steps to Reproduce the Problem

- Deploy a cluster
- Deploy a couple of workloads (Deployments, StatefullSets, DaemonSets) (specify resource limits and requests)
- Wait for Karpenter to spin up those new Nodes and wait for the deployments to be ready.
- Now install another Helm chart that adds a couple of workloads including daemonsets (specify resource limits and requests). e.g. https://artifacthub.io/packages/helm/philips-labs/spire
- Some of your existing nodes will not fit the DaemonSet

Workaround to make them fit manually (Hopefully Karpenter can automate one of these approaches):

- Check which nodes do not have the DaemonSet
- Drain those nodes one by one (easiest, lazy approach, which probably Karpenter consolidation could apply), this also requires your pods to be deployed in HA to prevent downtime of deployments that might be on this node.

More advanced/least impacting other deployments:

- Check which nodes do not have the DaemonSet
- Taint the affected nodes as NoSchedule, evict another non DaemonSet pod (That at least makes room for the resource requests and limits of the other Pod), wait for Karpenter to spin up a new node for the pod we evicted.
- and remove the taint NoSchedule so the DaemonSet will take the free space that was created.

### Resource Specs and Logs

Our clusters have 2 provisioners depending on what users of our platform choose. It can be a single one, or both of them.

**amd64 provisioner**

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: amd64
spec:
  consolidation:
    enabled: true
  labels:
    intent: apps
  limits:
    resources:
      amd.com/gpu: 0
      aws.amazon.com/neuron: 0
      cpu: 1000
      memory: 100Gi
      nvidia.com/gpu: 0
  providerRef:
    name: bottlerocket
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
        - spot
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
```

**arm64 provisioner**

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: arm64
spec:
  consolidation:
    enabled: true
  labels:
    intent: apps
  limits:
    resources:
      amd.com/gpu: 0
      aws.amazon.com/neuron: 0
      cpu: 1000
      memory: 100Gi
      nvidia.com/gpu: 0
  providerRef:
    name: bottlerocket
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
        - spot
    - key: kubernetes.io/arch
      operator: In
      values:
        - arm64
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
