### ISSUE TITLE
Karpenter does not consolidate nodes with multiple coredns pods.

### ISSUE THREAD

**Issue by zensai3805** [aws/karpenter#3406]
### Tell us about your request

Karpenter support Pod(Anti)Affinity setting and coredns deployment have PodAntiAffinity setting by default.
```
podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: k8s-app
                  operator: In
                  values:
                  - kube-dns
              topologyKey: kubernetes.io/hostname
            weight: 100
```

If multiple coredns pods are scheduled on the same node, Karpenter will respect PodAntiAffinity when determining whether a given node can be consolidated, i.e. it will assume that multiple nodes need to be started.

Karpenter will now notify me as an event why a node cannot be consolidated. For example, a node with 9 coredns pods will  show up like this:
```
Events:
  Type    Reason            Age                     From       Message
  ----    ------            ----                    ----       -------
  Normal  Unconsolidatable  6m36s (x16 over 5h53m)  karpenter  can't remove without creating 9 nodes
```

I think it's rare that multiple coredns with PodAntiAffinity are scheduled on a single node, but I use cluster-proportional-autoscaler so that coredns scales out with the number of nodes. I want coredns to spread out  the nodes as much as possible, but I don't want to start as many nodes as there are coredns pods. I think the same situation can happen without using cluster-proportional-autoscaler.

Is there a solution to consolidate the excess nodes with only coredns pods? Or could we consider adding the annotation to ignore certain pods from the consolidate evaluation?

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

I want the nodes that have a particular pods with PodAntiAffinity (coredns in this case) scheduled to be consolidated when they have excess resources.

### Are you currently working around this issue?

- Prevent coredns from being scheduled on Provisioner nodes that scale out significantly.
coredns is scheduled on other nodes, but this doesn't solve the root of the problem.

- Set the total number of coredns pods to be less than the number of nodes.
Karpenter merges nodes without coredns pods, and cluster-proportional-autoscaler reduces the number of coredns as the number of nodes decreases, so there is likely a chain of nodes merging. But this doesn't solve the problem either.

- Remove PodAntiAffinity from coredns.
This also doesn't solve the problem and causes availability issues.

### Additional Context

Related issue: #1532
This release fixes an issue that prevents karpenter from deprovisioning nodes with a coredns pod.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
