### ISSUE TITLE
[Question] Integration between Kops and Karpenter

### ISSUE THREAD

**Issue by darkgordon** [aws/karpenter#3483]
### Is an existing page relevant?

https://karpenter.sh/v0.21.1/getting-started/getting-started-with-kops/

### What karpenter features are relevant?

The integration between karpenter and Kops

### How should the docs be improved?

Nothing for the moment

### 

Hello guys, hope you are doing great
Right now, I am testing Kops and karpenter integration.
I Have made  the following steps:

1.	Installed the karpenter helm chat from  [https://github.com/aws/karpenter/tree/main/charts/karpenter using version 0.23.0](https://github.com/aws/karpenter/tree/main/charts/karpenter%20using%20version%200.23.0)

3.	Installed all the requirements  needed for karpenter via cloudformation
```
curl -fsSL https://karpenter.sh/"${KARPENTER_VERSION}"/getting-started/getting-started-with-eksctl/cloudformation.yaml > $TEMPOUT \
&& aws cloudformation deploy \
  --stack-name Karpenter-${CLUSTER_NAME} \
  --template-file ${TEMPOUT} \
  --capabilities CAPABILITY_NAMED_IAM \
  --parameter-overrides ClusterName=${CLUSTER_NAME}
```

4.	Using IRSA in  karpenter service account 

6.	Configure the provisioner and awsnodetemplate and  adapted to our cluster  like: subnets,securitygroups, Custom AMI, custom ebs storage and custom user date to ssh the node

After those steps, I tested to set up a big pod called inflate used by the demo of aws https://ec2spotworkshops.com/karpenter/050_karpenter/automatic_node_provisioning.html

7.	The pods stays in pending as intended and I could see a new node provisioned by karpenter 
 
![image](https://user-images.githubusercontent.com/28151796/221910722-3489e46e-3dbf-4774-bb73-2905d2624b69.png)

8.	I ssh into my node, and try to search some logs, but I found there is no kubelet installed, no nodeup eather

 
![image](https://user-images.githubusercontent.com/28151796/221910741-f9425f23-30d0-4ec7-94a7-d67afef3df6e.png)

My question is, is there any missed Step I have to follow, because what I saw is that kops don’t provision any component in this kind of installation 
Or is better to install karpenter via the KOPS_FEATURE_FLAGS=”Karpenter” and add the manager: Karpenter and adding 

```
spec:
  karpenter:
    enabled: true
```

Thank you very much

**Comment by tzneal** [comment]
Can you provide your provisioner spec and Karpenter logs?

**Comment by darkgordon** [comment]
Hello, of course 

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  labels:
    intent: apps
    Owner: byme
    provisioned-by: karpenter
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values: [medium, large]
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000
  providerRef:
    name: default
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 60Gi
        deleteOnTermination: true
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"
    
    --BOUNDARY
    Content-Type: text/x-shellscript; charset="us-ascii"
    
    #!/bin/bash
    mkdir -p ~ubuntu/.ssh/
    touch ~ubuntu/.ssh/authorized_keys
    echo "ssh-rsa SOMEKEY" > ~ubuntu/.ssh/authorized_keys
    chmod -R go-w ~ubuntu/.ssh/authorized_keys
    chown -R ubuntu ~ubuntu/.ssh   
    --BOUNDARY--
  amiSelector:
    aws-ids: SOME_AMI_ID
  subnetSelector:
    aws-ids: "SOME_SUBNET_IDS"
  securityGroupSelector:
    aws-ids: "SOME_SG_IDS"
  tags:
    KarpenerProvisionerName: "default"
    NodeType: "karpenter-workshop"
    provisioned-by: "karpenter"
    Owner: byme



```

`2023-02-28T16:25:04.507Z        INFO    controller.provisioner.cloudprovider    launched new instance   {"commit": "3354-dirty", "provisioner": "default", "id": "i-0f676b10b1de86bd4", "hostname": "somehostname", "instance-type": "c5d.xlarge", "zone": "somezone", "capacity-type": "spot"}`

![image](https://user-images.githubusercontent.com/28151796/221916009-d3229042-5293-429b-bdc3-1dd65e01e442.png)

the node is provisioned but the kubelet from the node is not presented

**Comment by tzneal** [comment]
You're using a custom AMI ID and not an AWS provided AMI. You'll need to troubleshoot your custom AMI to deermine why kubelet isn't launching.

**Comment by darkgordon** [comment]
Thank you, one question, I see that karpenter launch an eks ami for the nodes, in that case , If I am using kops, will not work the eks ami in the nodes ? 

Because right now, I changed from using my custom ami and leave it empty to use the default ami provided by eks 

![image](https://user-images.githubusercontent.com/28151796/221921967-cb5ade45-5da4-45a9-b3c7-b99c9817c6bf.png)

![image](https://user-images.githubusercontent.com/28151796/221922800-20d8af16-76a8-4394-b31f-e42f254c754d.png)

**Comment by tzneal** [comment]
Karpenter will launch whichever AMIs you configure it to launch, regardless of the installation method.   If that's an EKS AMI and it isn't connecting to your cluster, you can run the EKS Node Log collector to gather an archive of logs that we can look at:
https://github.com/awslabs/amazon-eks-ami/tree/master/log-collector-script/linux

**Comment by darkgordon** [comment]
Nice tool by the way, I was able to ssh to my node with the AMI , I found in the var/log/messages 

I found the next error 
 TLS handshake error from <anotherworkernode>42407: no serving certificate available for the kubelet
Unable to register node with API server" err="Unauthorized" node="<workernode>"

I also execute the EKS Logs Collector 
and in the networking path I found , in the curl_api_server.txt
an issue in the ssl version
 OpenSSL/1.0.2k-fips: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

I will search more in the master version tls version I think there is the issue 

Thank you

**Comment by darkgordon** [comment]
I fix my issue, my bad was not tls or ssl related

The problem was that my kops uses a custom launchteamplate created in the ASG

So I read the crd for the provisioner and I found the provider key

```
spec:
  provider:
    launchTemplate: <my_kops_node_launch_template>
    subnetSelector:
      aws-ids: <the_subnet_ids_where_my_node_will_be_deployed>
```

I adjust those values , and delete the AWSNodeTemplate, because we will use the custom ASG Launch template from kops

Then was presented an issue regarding `UnauthorizedOperation: You are not authorized to perform this operation.`  in my karpenter pods.

I proceed to add the iam:passrole to my karpenter SA and then my node was provisioned and my pods scheduled

One last question? 

the provider.launchTemplate is deprecated ?
