### ISSUE TITLE
Nodes that fail to join cluster trigger interesting behavior

### ISSUE THREAD

**Issue by sidewinder12s** [aws/karpenter#3525]
### Version

__Karpenter Version:__ v0.25
__Kubernetes Version:__ v1.22

### Expected Behavior

I'd expect nodes that fail to join the cluster after some specified amount of time to be killed and another launch attempted.

### Actual Behavior

I updated a provisioner with a known non-EKS AMI that would fail. We have drift enabled so I'd expect it to try and replace everything.

A few seemingly strange behaviors then happened:

1. The broken node never came up
2. Karpenter appeared to evict 1-2 nodes even after this node failed to come up, leaving 2 nodes worth of pods stuck pending.

After this I confirmed that some of the provisioner metrics incremented when provisioners failed and reverted my change (was testing this: #3523).

1. Then Karpenter launched a whole pile of small nodes to get everything running again
2. I did not remove the broken node yet
3. Once everything was running it appeared to stabilize but then consolidation appeared to be stuck.
4. Once I explicitly deleted the bad node, consolidation appeared to kick back into gear.

The majority of the workloads that run on this cluster target the tainted "system" provisioner 

### Steps to Reproduce the Problem

Change a stable clusters provisioner to a non-working AMI
Let it run for a while
Reset the provisioner AMI
Wait
Then delete broken node

### Resource Specs and Logs

Provisioner
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: system
spec:
  consolidation:
    enabled: true
  kubeletConfiguration:
    containerRuntime: dockerd
  limits:
    resources:
      cpu: '200'
      memory: 200Gi
  providerRef:
    name: default
  requirements:
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values:
        - c
        - m
        - r
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values:
        - '5'
    - key: karpenter.k8s.aws/instance-cpu
      operator: Lt
      values:
        - '48'
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
  taints:
    - effect: NoSchedule
      key: node-type
      value: system
###
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: use1-test01-default
spec:
  consolidation:
    enabled: true
  kubeletConfiguration:
    containerRuntime: dockerd
  limits:
    resources:
      cpu: '200'
      memory: 200Gi
  providerRef:
    name: default
  requirements:
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values:
        - c
        - m
        - r
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values:
        - '5'
    - key: karpenter.k8s.aws/instance-cpu
      operator: Lt
      values:
        - '48'
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
# These 2 Provisioners we then have copies that are just spot but otherwise the same config
```

Controller settings
```yaml
apiVersion: v1
data:
  aws.enableENILimitedPodDensity: 'true'
  aws.enablePodENI: 'false'
  aws.isolatedVPC: 'false'
  aws.nodeNameConvention: ip-name
  aws.tags: >-
    {"Cluster":"use1-test01","Contact":"gwebster@aurora.tech","Environment":"test","Project":"use1-test01","karpenter.sh/discovery":"use1-test01"}
  aws.vmMemoryOverheadPercent: '0.075'
  batchIdleDuration: 1s
  batchMaxDuration: 10s
  featureGates.driftEnabled: 'true'
kind: ConfigMap
```

I can share logs in a Support case/other non-public forum

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
