### ISSUE TITLE
Document default Bottlerocket blockDeviceMappings

### ISSUE THREAD

**Issue by James-Quigley** [aws/karpenter#3528]
### Is an existing page relevant?

https://karpenter.sh/v0.26.1/concepts/node-templates/#specblockdevicemappings

### What karpenter features are relevant?

blockDeviceMappings

### How should the docs be improved?

The docs mention that by default there are two mappings for Bottlerocket nodes, but doesn't show what those mappings are. If a user wanted to expand the default volumes in order to make room for more ephemeral-storage, there isn't an easy way to find the defaults. I believe [this is the code for it](https://github.com/aws/karpenter/blob/main/pkg/providers/amifamily/bottlerocket.go#L70-L84)

Which yaml-ified should look something like:
```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
spec:
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 4Gi
        volumeType: gp3
        encrypted: true
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        encrypted: true
```

If you omit one of these, bottlerocket nodes still function though

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
