### ISSUE TITLE
Simple scale-up test not working due to: no instance type satisfied resources

### ISSUE THREAD

**Issue by thelabdude** [aws/karpenter#3534]
### Version

__Karpenter Version:__ 0.26.1

__Kubernetes Version:__ v1.23.14-eks-ffeb93d

### Expected Behavior

Expected Behavior: Provision a new instance to schedule the pods on.

I can't get Karpenter to scale-up any nodes for a test pod and logging around this is not helpful in troubleshooting.

The only thing I can think of is there's a problem with using a `launchTemplate` in the AWSNodeTemplate?

```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: karp-prov5
spec:
  detailedMonitoring: false
  launchTemplate: karp-prov5-node-group-44dcbf4
  subnetSelector:
    Name: private-subnet-a-1,private-subnet-b-1,private-subnet-c-1
```

and my provisioner looks like:
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: karp-prov5-provisioner
spec:
  providerRef:
    name: karp-prov5
  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - r6i.2xlarge
    - r6i.4xlarge
    - m5.2xlarge
    - r5.2xlarge
    - m5.xlarge
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
```

The reason I'm using the `LaunchTemplate` approach is we have a very complicated UserData section (cloud-init) for our worker nodes and the current `userData` field taking a string in `AWSNodeTemplate` wasn't going to work without me duplicating lots of complicated logic to produce the "stringified" user data section.

### Actual Behavior

No nodes are provisioned.

```
2023-03-03T20:11:16.357Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "karp-prov5-provisioner", no instance type satisfied resources {"cpu":"200m","memory":"128Mi","pods":"1"} and requirements kubernetes.io/arch In [amd64], karpenter.sh/provisioner-name In [karp-prov5-provisioner], karpenter.sh/capacity-type In [on-demand], node.kubernetes.io/instance-type In [m5.2xlarge m5.xlarge r5.2xlarge r6i.2xlarge r6i.4xlarge], kubernetes.io/os In [linux]
```

### Steps to Reproduce the Problem

There's no other logging in the controller log related to this issue. 

For an area that's so critical to Karpenter, I'm surprised to see how little logging there is around the Machine#Add func (from karpenter-core), even when debug is enabled.

My test deployment looks like:
```
apiVersion: apps/v1
kind: Deployment
metadata:
 name: php-apache
 namespace: default
spec:
 selector:
   matchLabels:
     run: php-apache
 replicas: 2
 template:
   metadata:
     labels:
       run: php-apache
   spec:
     containers:
     - name: php-apache
       image: ... REDACTED ...
       ports:
       - containerPort: 8080
       resources:
         limits:
           cpu: 500m
           memory: 256Mi
         requests:
           cpu: 200m
           memory: 128Mi
```
Nothing special there ^^ I verified the pods can be scheduled w/o Karpenter involved.

Also, I used the AWS Console to manually create an instance from my LaunchTemplate, to verify it works.

### Resource Specs and Logs

there are no errors in the log other than ^^

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Can you provide your full karpenter logs?  I used the same requirements in my provisioner and the same deployment and nodes launched with no issue.

**Comment by thelabdude** [comment]
Ok, thanks for trying to reproduce. Here's a clean log I just re-run through a test:
[karpenter.log](https://github.com/aws/karpenter/files/10886250/karpenter.log)

**Comment by tzneal** [comment]
I don't see anything in the logs. Can you try it without the launch template to see if theirs a bug related to that? 

I can build a snapshot release on Monday with more logging.

**Comment by thelabdude** [comment]
I'll try without the LT but I can't really do this without a LaunchTemplate in practice, our userData requirements are pretty complex. I'll wait for some more logging though, that would be very helpful.

**Comment by tzneal** [comment]
Yes, I'm not suggesting it permanently. I just wanted to see if the launch template was causing the issue to help guide the new logs I'm going to add.

**Comment by thelabdude** [comment]
hmmm ... so I switched to the following def and same error:

```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: karp-prov5
spec:
  detailedMonitoring: false
#  launchTemplate: karp-prov5-node-group-44dcbf4
  instanceProfile: "karpenter-instance-profile"
  amiSelector:
    aws-ids: "ami-REDACTED"
  securityGroupSelector:
    aws-ids: "REDACTED"
  subnetSelector:
    Name: private-subnet-a-1,private-subnet-b-1,private-subnet-c-1
  blockDeviceMappings:
    - deviceName: "/dev/xvda"
      ebs:
        volumeType: "gp3"
        volumeSize: 100G
```

The controller definitely reconciled my changes:
```
2023-03-03T23:18:25.319Z	DEBUG	controller.awsnodetemplate	discovered subnets	{"commit": "982c35f", "awsnodetemplate": "karp-prov5", "subnets": [ CORRECT VALUES HERE ;-) ]}
2023-03-03T23:18:25.449Z	DEBUG	controller.awsnodetemplate	discovered security groups	{"commit": "982c35f", "awsnodetemplate": "karp-prov5", "security-groups": [ CORRECT VALUES HERE ]}
2023-03-03T23:18:26.173Z	DEBUG	controller.deprovisioning	discovered EC2 instance types	{"commit": "982c35f", "instance-type-count": 621}
2023-03-03T23:18:26.352Z	DEBUG	controller.deprovisioning	discovered EC2 instance types zonal offerings for subnets	{"commit": "982c35f", "subnet-selector": "{\"Name\":\"private-subnet-a-1,private-subnet-b-1,private-subnet-c-1\"}"}
```

But same result once I try to deploy:
```
2023-03-03T23:17:02.531Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "karp-prov5-provisioner", no instance type satisfied resources {"cpu":"200m","memory":"128Mi","pods":"1"} and requirements karpenter.sh/capacity-type In [on-demand], node.kubernetes.io/instance-type In [m5.2xlarge m5.xlarge r5.2xlarge r6i.2xlarge r6i.4xlarge], kubernetes.io/os In [linux], kubernetes.io/arch In [amd64], karpenter.sh/provisioner-name In [karp-prov5-provisioner]	{"commit": "982c35f", "pod": "default/php-apache-5d79cb74c-kz6sg"}
```
