### ISSUE TITLE
Unable to set `settings.kubernetes.image-gc-high-threshold-percent` userdata due to incorrect type

### ISSUE THREAD

**Issue by mrparkers** [aws/karpenter#3563]
### Version

__Karpenter Version:__ v0.26.1

__Kubernetes Version:__ `Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.10-eks-48e63af", GitCommit:"9176fb99b52f8d5ff73d67fea27f3a638f679f8a", GitTreeState:"clean", BuildDate:"2023-01-24T19:17:48Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}`

### Expected Behavior

I'm unable to set `settings.kubernetes.image-gc-high-threshold-percent` within the userdata of a `AWSNodeTemplate`.

Here is my `AWSNodeTemplate`:

```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: high-disk
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
  - deviceName: /dev/xvdb
    ebs:
      deleteOnTermination: true
      encrypted: true
      volumeSize: 300Gi
      volumeType: gp3
  securityGroupSelector:
    aws:eks:cluster-name: my-cluster
  subnetSelector:
    karpenter.sh/discovery: my-cluster
  tags:
    karpenter.sh/discovery: my-cluster
  userData: |-
    [settings.kubernetes]
    registry-qps = 100

    image-gc-high-threshold-percent = 75 # this is the problem

    [settings.kubernetes.system-reserved]
    ephemeral-storage= "2Gi"

    [settings.kubernetes.kube-reserved]
    ephemeral-storage= "2Gi"
```

When I use `image-gc-high-threshold-percent = 75`, karpenter is able to spin up new nodes, but the nodes aren't able to connect to the cluster, presumably because `kubelet` fails to start.

When I use `image-gc-high-threshold-percent = "75"` (string, not integer), karpenter is unable to spin up new nodes, giving the following log message:

```
karpenter-54b4ccc5c5-w4ld4 controller {"level":"ERROR","time":"2023-03-08T21:52:30.206Z","logger":"controller.provisioner","message":"launching machine, creating cloud provider instance, creating instance, getting launch template configs, getting launch templates, creating launch template, invalid UserData toml: cannot store TOML string into a Go int32; launching machine, creating cloud provider instance, creating instance, getting launch template configs, getting launch templates, creating launch template, invalid UserData toml: cannot store TOML string into a Go int32","commit":"dc3af1a"}
```

This is because karpenter is trying to unmarshal into a struct which expects an `int32` for this value: https://github.com/aws/karpenter/blob/19a9a7c68c6897cebaea48b6aca1ae302c8b548f/pkg/providers/amifamily/bootstrap/bottlerocketsettings.go#L71

However, this value should actually be a `string`, not an `int32`.  If you connect via SSM into a bottlerocket node, you can see this using `apiclient`:

```
ssm-user@control]$ apiclient set -j '{"settings": {"kubernetes": {"image-gc-high-threshold-percent": 75}}}'
Unable to deserialize input JSON into model: invalid type: integer `75`, expected a string

[ssm-user@control]$ apiclient set -j '{"settings": {"kubernetes": {"image-gc-high-threshold-percent": "75"}}}'

[ssm-user@control]$ apiclient get settings.kubernetes.image-gc-high-threshold-percent
{
  "settings": {
    "kubernetes": {
      "image-gc-high-threshold-percent": "75"
    }
  }
}
```

### Actual Behavior

Karpenter is using the wrong data type for `settings.kubernetes.image-gc-high-threshold-percent`.

### Steps to Reproduce the Problem

Use this template to create a new node, and it will never become `Ready` and join the cluster:

```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: high-disk
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
  - deviceName: /dev/xvdb
    ebs:
      deleteOnTermination: true
      encrypted: true
      volumeSize: 300Gi
      volumeType: gp3
  securityGroupSelector:
    aws:eks:cluster-name: my-cluster
  subnetSelector:
    karpenter.sh/discovery: my-cluster
  tags:
    karpenter.sh/discovery: my-cluster
  userData: |-
    [settings.kubernetes]
    registry-qps = 100

    image-gc-high-threshold-percent = 75

    [settings.kubernetes.system-reserved]
    ephemeral-storage= "2Gi"

    [settings.kubernetes.kube-reserved]
    ephemeral-storage= "2Gi"
```

Use this template to create a new node, and a new node will never be created, and karpenter will print the same log messages as described above:

```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: high-disk
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
  - deviceName: /dev/xvdb
    ebs:
      deleteOnTermination: true
      encrypted: true
      volumeSize: 300Gi
      volumeType: gp3
  securityGroupSelector:
    aws:eks:cluster-name: my-cluster
  subnetSelector:
    karpenter.sh/discovery: my-cluster
  tags:
    karpenter.sh/discovery: my-cluster
  userData: |-
    [settings.kubernetes]
    registry-qps = 100

    image-gc-high-threshold-percent = "75"

    [settings.kubernetes.system-reserved]
    ephemeral-storage= "2Gi"

    [settings.kubernetes.kube-reserved]
    ephemeral-storage= "2Gi"
```

### Resource Specs and Logs

```
karpenter-54b4ccc5c5-w4ld4 controller {"level":"ERROR","time":"2023-03-08T21:52:30.206Z","logger":"controller.provisioner","message":"launching machine, creating cloud provider instance, creating instance, getting launch template configs, getting launch templates, creating launch template, invalid UserData toml: cannot store TOML string into a Go int32; launching machine, creating cloud provider instance, creating instance, getting launch template configs, getting launch templates, creating launch template, invalid UserData toml: cannot store TOML string into a Go int32","commit":"dc3af1a"}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
