### ISSUE TITLE
Karpenter considers only the top node selector term in node affinity when using weighted provisioners

### ISSUE THREAD

**Issue by vassilvk** [aws/karpenter#3569]
### Version

0.21.1

### Expected Behavior

When a deployment has a `nodeAffinity` with multiple items in array `nodeSelectorTerms`, Karpenter should consider all node selector terms when it attempts to determine which provisioner to use. Higher weight provisioners should take precedence regardless of the order of items in `nodeSelectorTerms`.

### Actual Behavior

When a deployment has a `nodeAffinity` with multiple items in array `nodeSelectorTerms`, and there are multiple Karpenter provisioners with different weights, Karpenter picks the provisioner that matches the first item in `nodeSelectorTerms` instead of the top-weighted provisioner that matches any of the `nodeSelectorTerms` items.
This behavior is at odds with the semantics of `nodeSelectorTerms` and Kubernetes scheduler's behavior, which, [according to Kubernetes docs](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/) is as follows:
> If you specify multiple terms in nodeSelectorTerms associated with nodeAffinity types, then the Pod can be scheduled onto a node if one of the specified terms can be satisfied (terms are ORed).

### Steps to Reproduce the Problem

Deploy two provisioners:
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default-amd64
spec:
  consolidation:
    enabled: true
  limits:
    resources:
      cpu: '250'
  requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - spot
        - on-demand
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - xxx.xxx
        - xxx.xxx
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
```

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default-arm64
spec:
  consolidation:
    enabled: true
  limits:
    resources:
      cpu: '250'
  providerRef:
    name: default-arm64
  requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
        - arm64
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - spot
        - on-demand
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - xxx.xxx
        - xxx.xxx
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
  weight: 10
```

Note `weight: 10` for provisioner `default-arm64` above.

Then deploy a deployment with the following node affinity:

```yaml
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: karpenter.sh/capacity-type
                    operator: In
                    values:
                      - on-demand
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: karpenter.sh/capacity-type
                    operator: In
                    values:
                      - on-demand
```

Scale the deployment out and observe.
Karpenter will provision `amd64` nodes for the new unschedulable pods, although the `arm64` provisioner is with a higher weight. Switching the order of the items in `nodeSelectorTerms` in the deployment's definition switches Karpenter's behavior, indicating that Karpenter might only be looking at the top item in `nodeSelectorTerms` before it tries to find a matching provisioner.

It is important to note that Karpenter does work as expected if the above match expressions are combined into one:
```yaml
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: karpenter.sh/capacity-type
                    operator: In
                    values:
                      - on-demand
```

The problem is that this collapsing of match expressions is not always possible, as there are needs to set up key value combinations which cannot be merged.

### Resource Specs and Logs

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
@vassilvk The example that you setup above shows something that can be merged? Do you mind sharing your specific use-case where you are unable to merge the semantic based on your disjoint sets of requirements for your pod workloads?

**Comment by vassilvk** [comment]
Hi @jonathan-innis,

Example: when a workload can be deployed to Linux AMD64, Linux ARM64, and Windows AMD64, but not on Windows ARM64. Then one would end up with multiple matchExpressions:

```yaml
nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - windows
```
