### ISSUE TITLE
Karpenter Consolidation constantly replaces the same node type

### ISSUE THREAD

**Issue by autarchprinceps** [aws/karpenter#3577]
### Version

0.27.0

### Expected Behavior

Some instance replacements perhaps, but certainly not permanently, and not with the same instance types.

### Actual Behavior

Replacing the same instance type over and over again.
<img width="505" alt="image" src="https://user-images.githubusercontent.com/239063/224316376-aec04085-55af-4f8a-bf63-d2aff79d7005.png">

### Steps to Reproduce the Problem

This time this was in a completely new EKS 1.25 cluster. Why this issue occurs, I cannot say, but disabling consolidation in the provisioner stops it.

### Resource Specs and Logs

```
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: arm
spec:
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values: ["on-demand","spot"]
  - key: "kubernetes.io/arch"
    operator: In
    values:
    - arm64
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values:
    - c
    - m
    - r
    - t
    - a
  - key: karpenter.k8s.aws/instance-hypervisor
    operator: In
    values: ["nitro"]
  taints:
  - key: arch
    value: arm64
    effect: NoSchedule
  limits:
    resources:
      cpu: 100
  providerRef:
    name: default
  consolidation:
    enabled: true
  ttlSecondsUntilExpired: 604800
  weight: 30
  kubeletConfiguration:
    systemReserved:
      cpu: 250m
      memory: 200Mi
      ephemeral-storage: 1Gi
    kubeReserved:
      cpu: 250m
      memory: 200Mi
      ephemeral-storage: 1Gi
    evictionHard:
      memory.available: 0.2Gi
      nodefs.available: 10%
      nodefs.inodesFree: 10%
    evictionSoft:
      memory.available: 500Mi
      nodefs.available: 15%
      nodefs.inodesFree: 15%
    evictionSoftGracePeriod:
      memory.available: 180s
      nodefs.available: 180s
      nodefs.inodesFree: 180s
    evictionMaxPodGracePeriod: 180
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: x86
spec:
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values: ["on-demand","spot"]
  - key: "kubernetes.io/arch"
    operator: In
    values:
    - amd64
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values:
    - c
    - m
    - r
  - key: karpenter.k8s.aws/instance-generation
    operator: Gt
    values:
    - "3"
  - key: karpenter.k8s.aws/instance-hypervisor
    operator: In
    values: ["nitro"]
  limits:
    resources:
      cpu: 100
  providerRef:
    name: default
  consolidation:
    enabled: true
  ttlSecondsUntilExpired: 604800
  weight: 20
  kubeletConfiguration:
    systemReserved:
      cpu: 250m
      memory: 200Mi
      ephemeral-storage: 1Gi
    kubeReserved:
      cpu: 250m
      memory: 200Mi
      ephemeral-storage: 1Gi
    evictionHard:
      memory.available: 0.2Gi
      nodefs.available: 10%
      nodefs.inodesFree: 10%
    evictionSoft:
      memory.available: 500Mi
      nodefs.available: 15%
      nodefs.inodesFree: 15%
    evictionSoftGracePeriod:
      memory.available: 180s
      nodefs.available: 180s
      nodefs.inodesFree: 180s
    evictionMaxPodGracePeriod: 180
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by albertschwarzkopf** [comment]
@tzneal here are some logs:

```2023-03-20T13:14:27.866Z	INFO	controller.deprovisioning	deprovisioning via consolidation delete, terminating 1 nodes ip-10-102-173-187.ec2.internal/m6id.xlarge/spot	{"commit": "dc3af1a"}
2023-03-20T13:14:27.887Z	INFO	controller.termination	cordoned node	{"commit": "dc3af1a", "node": "ip-10-102-173-187.ec2.internal"}
2023-03-20T13:14:28.417Z	INFO	controller.termination	deleted node	{"commit": "dc3af1a", "node": "ip-10-102-173-187.ec2.internal"}
2023-03-20T13:14:28.700Z	INFO	controller.termination	deleted node	{"commit": "dc3af1a", "node": "ip-10-102-173-187.ec2.internal"}
2023-03-20T13:16:30.128Z	INFO	controller.provisioner	found provisionable pod(s)	{"commit": "dc3af1a", "pods": 1}
2023-03-20T13:16:30.128Z	INFO	controller.provisioner	computed new node(s) to fit pod(s)	{"commit": "dc3af1a", "nodes": 1, "pods": 1}
2023-03-20T13:16:30.128Z	INFO	controller.provisioner	launching machine with 1 pods requesting {"cpu":"2240m","memory":"9106Mi","pods":"9"} from types r5ad.24xlarge, c5n.2xlarge, r5a.xlarge, m5ad.12xlarge, m5a.4xlarge and 214 other(s)	{"commit": "dc3af1a", "provisioner": "x86"}
2023-03-20T13:16:36.048Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "dc3af1a", "provisioner": "x86", "id": "i-09d2571131ecef937", "hostname": "ip-10-102-188-226.ec2.internal", "instance-type": "m6id.xlarge", "zone": "us-east-1c", "capacity-type": "spot"}
2023-03-20T13:21:47.141Z	INFO	controller.deprovisioning	deprovisioning via consolidation delete, terminating 1 nodes ip-10-102-188-226.ec2.internal/m6id.xlarge/spot	{"commit": "dc3af1a"}
2023-03-20T13:21:47.157Z	INFO	controller.termination	cordoned node	{"commit": "dc3af1a", "node": "ip-10-102-188-226.ec2.internal"}
2023-03-20T13:21:47.531Z	INFO	controller.termination	deleted node	{"commit": "dc3af1a", "node": "ip-10-102-188-226.ec2.internal"}
2023-03-20T13:21:47.847Z	INFO	controller.termination	deleted node	{"commit": "dc3af1a", "node": "ip-10-102-188-226.ec2.internal"}
2023-03-20T13:23:16.527Z	INFO	controller.provisioner	found provisionable pod(s)	{"commit": "dc3af1a", "pods": 1}
2023-03-20T13:23:16.527Z	INFO	controller.provisioner	computed new node(s) to fit pod(s)	{"commit": "dc3af1a", "nodes": 1, "pods": 1}
2023-03-20T13:23:16.528Z	INFO	controller.provisioner	launching machine with 1 pods requesting {"cpu":"2240m","memory":"9106Mi","pods":"9"} from types m5zn.6xlarge, m5d.xlarge, m5.8xlarge, m5ad.12xlarge, r6i.xlarge and 214 other(s)	{"commit": "dc3af1a", "provisioner": "x86"}
2023-03-20T13:23:23.464Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "dc3af1a", "provisioner": "x86", "id": "i-0e29e0adfcdcacd4d", "hostname": "ip-10-102-162-206.ec2.internal", "instance-type": "m6id.xlarge", "zone": "us-east-1c", "capacity-type": "spot"}
2023-03-20T13:27:31.242Z	INFO	controller.provisioner	found provisionable pod(s)	{"commit": "dc3af1a", "pods": 1}
2023-03-20T13:27:31.242Z	INFO	controller.provisioner	computed new node(s) to fit pod(s)	{"commit": "dc3af1a", "nodes": 1, "pods": 1}
2023-03-20T13:27:31.329Z	INFO	controller.provisioner	launching machine with 1 pods requesting {"cpu":"2240m","memory":"9106Mi","pods":"9"} from types c6id.8xlarge, m6id.2xlarge, m5a.16xlarge, m5d.8xlarge, r6a.xlarge and 183 other(s)	{"commit": "dc3af1a", "provisioner": "x86"}
2023-03-20T13:27:35.131Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "dc3af1a", "provisioner": "x86", "id": "i-0ebb187210c0b1f87", "hostname": "ip-10-102-133-245.ec2.internal", "instance-type": "m6id.xlarge", "zone": "us-east-1c", "capacity-type": "spot"}
2023-03-20T13:33:25.829Z	INFO	controller.provisioner	found provisionable pod(s)	{"commit": "dc3af1a", "pods": 1}
2023-03-20T13:33:25.829Z	INFO	controller.provisioner	computed new node(s) to fit pod(s)	{"commit": "dc3af1a", "nodes": 1, "pods": 1}
2023-03-20T13:33:25.829Z	INFO	controller.provisioner	launching machine with 1 pods requesting {"cpu":"2240m","memory":"9106Mi","pods":"9"} from types r6a.2xlarge, m5dn.2xlarge, m6id.2xlarge, r6in.12xlarge, c5n.2xlarge and 183 other(s)	{"commit": "dc3af1a", "provisioner": "x86"}
2023-03-20T13:33:30.628Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "dc3af1a", "provisioner": "x86", "id": "i-087059e4669d19efe", "hostname": "ip-10-102-185-248.ec2.internal", "instance-type": "m6id.xlarge", "zone": "us-east-1c", "capacity-type": "spot"}
2023-03-20T13:37:45.576Z	INFO	controller.deprovisioning	deprovisioning via consolidation delete, terminating 3 nodes ip-10-102-162-206.ec2.internal/m6id.xlarge/spot, ip-10-102-133-245.ec2.internal/m6id.xlarge/spot, ip-10-102-185-248.ec2.internal/m6id.xlarge/spot	{"commit": "dc3af1a"}
2023-03-20T13:37:45.595Z	INFO	controller.termination	cordoned node	{"commit": "dc3af1a", "node": "ip-10-102-162-206.ec2.internal"}
2023-03-20T13:37:45.605Z	INFO	controller.termination	cordoned node	{"commit": "dc3af1a", "node": "ip-10-102-133-245.ec2.internal"}
2023-03-20T13:37:45.626Z	INFO	controller.termination	cordoned node	{"commit": "dc3af1a", "node": "ip-10-102-185-248.ec2.internal"}
2023-03-20T13:37:46.270Z	INFO	controller.termination	deleted node	{"commit": "dc3af1a", "node": "ip-10-102-185-248.ec2.internal"}
2023-03-20T13:37:46.272Z	INFO	controller.termination	deleted node	{"commit": "dc3af1a", "node": "ip-10-102-133-245.ec2.internal"}
2023-03-20T13:37:46.273Z	INFO	controller.termination	deleted node	{"commit": "dc3af1a", "node": "ip-10-102-162-206.ec2.internal"}
2023-03-20T13:37:46.650Z	INFO	controller.termination	deleted node	{"commit": "dc3af1a", "node": "ip-10-102-133-245.ec2.internal"}
2023-03-20T13:37:46.652Z	INFO	controller.termination	deleted node	{"commit": "dc3af1a", "node": "ip-10-102-185-248.ec2.internal"}
2023-03-20T13:37:46.653Z	INFO	controller.termination	deleted node	{"commit": "dc3af1a", "node": "ip-10-102-162-206.ec2.internal"}
2023-03-20T13:39:41.343Z	INFO	controller.provisioner	found provisionable pod(s)	{"commit": "dc3af1a", "pods": 1}
2023-03-20T13:39:41.343Z	INFO	controller.provisioner	computed new node(s) to fit pod(s)	{"commit": "dc3af1a", "nodes": 1, "pods": 1}
2023-03-20T13:39:41.344Z	INFO	controller.provisioner	launching machine with 1 pods requesting {"cpu":"2240m","memory":"9106Mi","pods":"9"} from types r5a.2xlarge, r5.24xlarge, r6id.2xlarge, m6idn.12xlarge, r6a.2xlarge and 214 other(s)	{"commit": "dc3af1a", "provisioner": "x86"}
2023-03-20T13:39:45.865Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "dc3af1a", "provisioner": "x86", "id": "i-07343524413ea3a9e", "hostname": "ip-10-102-163-219.ec2.internal", "instance-type": "m6id.xlarge", "zone": "us-east-1c", "capacity-type": "spot"}
2023-03-20T13:44:53.136Z	INFO	controller.provisioner	found provisionable pod(s)	{"commit": "dc3af1a", "pods": 1}
2023-03-20T13:44:53.136Z	INFO	controller.provisioner	computed new node(s) to fit pod(s)	{"commit": "dc3af1a", "nodes": 1, "pods": 1}
2023-03-20T13:44:53.136Z	INFO	controller.provisioner	launching machine with 1 pods requesting {"cpu":"2240m","memory":"9106Mi","pods":"9"} from types r6i.xlarge, r6id.2xlarge, m5a.2xlarge, r6idn.2xlarge, r6a.xlarge and 183 other(s)	{"commit": "dc3af1a", "provisioner": "x86"}
2023-03-20T13:44:56.333Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "dc3af1a", "provisioner": "x86", "id": "i-0d55b96d331c7665f", "hostname": "ip-10-102-145-255.ec2.internal", "instance-type": "m6id.xlarge", "zone": "us-east-1c", "capacity-type": "spot"}
2023-03-20T13:48:53.037Z	INFO	controller.provisioner	found provisionable pod(s)	{"commit": "dc3af1a", "pods": 1}
2023-03-20T13:48:53.037Z	INFO	controller.provisioner	computed new node(s) to fit pod(s)	{"commit": "dc3af1a", "nodes": 1, "pods": 1}
2023-03-20T13:48:53.037Z	INFO	controller.provisioner	launching machine with 1 pods requesting {"cpu":"2240m","memory":"9106Mi","pods":"9"} from types r6i.xlarge, r6id.2xlarge, m5a.2xlarge, r6idn.2xlarge, r6a.xlarge and 183 other(s)	{"commit": "dc3af1a", "provisioner": "x86"}
2023-03-20T13:48:57.035Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "dc3af1a", "provisioner": "x86", "id": "i-0502f45d47ef81646", "hostname": "ip-10-102-148-221.ec2.internal", "instance-type": "m6id.xlarge", "zone": "us-east-1c", "capacity-type": "spot"}```

**Comment by albertschwarzkopf** [comment]
Happened today again. We have deployed a new version of an application (Spryker). Then Karpenter launched a new node to place the new pods there. After few minutes the same node was replaced again. I have observed it several times in the last weeks: seems to happen during a deployment, which starts new replicas.
  
Unfortunately the fix is to disable the consolidation temporary. 

Here the logs:

```2023-04-04T18:39:19.341Z	INFO	controller.provisioner	pod spryker/spryker-reward-shop-zed-7767d94844-c65sg has a preferred TopologySpreadConstraint which can prevent consolidation	{"commit": "dc3af1a"}
2023-04-04T18:39:19.341Z	INFO	controller.provisioner	pod spryker/spryker-reward-shop-glue-7bd6497558-wglvh has a preferred TopologySpreadConstraint which can prevent consolidation	{"commit": "dc3af1a"}
2023-04-04T18:39:19.341Z	INFO	controller.provisioner	pod spryker/spryker-reward-shop-yves-758596f78d-9wqjg has a preferred TopologySpreadConstraint which can prevent consolidation	{"commit": "dc3af1a"}
2023-04-04T18:39:22.355Z	INFO	controller.provisioner	found provisionable pod(s)	{"commit": "dc3af1a", "pods": 3}
2023-04-04T18:39:22.355Z	INFO	controller.provisioner	computed new node(s) to fit pod(s)	{"commit": "dc3af1a", "nodes": 1, "pods": 3}
2023-04-04T18:39:22.356Z	INFO	controller.provisioner	launching machine with 3 pods requesting {"cpu":"495m","memory":"1698Mi","pods":"9"} from types c5n.2xlarge, r6i.xlarge, r5a.xlarge, m5d.xlarge, r6id.12xlarge and 201 other(s)	{"commit": "dc3af1a", "provisioner": "x86"}
2023-04-04T18:39:25.547Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "dc3af1a", "provisioner": "x86", "id": "i-034d539613941a591", "hostname": "ip-10-18-148-58.eu-central-1.compute.internal", "instance-type": "m6i.large", "zone": "eu-central-1c", "capacity-type": "spot"}
2023-04-04T18:42:16.767Z	INFO	controller.deprovisioning	deprovisioning via consolidation delete, terminating 1 nodes ip-10-18-148-58.eu-central-1.compute.internal/m6i.large/spot	{"commit": "dc3af1a"}
2023-04-04T18:42:16.869Z	INFO	controller.termination	cordoned node	{"commit": "dc3af1a", "node": "ip-10-18-148-58.eu-central-1.compute.internal"}
2023-04-04T18:42:20.971Z	INFO	controller.provisioner	pod spryker/spryker-reward-shop-glue-54b676f9c-t76pl has a preferred TopologySpreadConstraint which can prevent consolidation	{"commit": "dc3af1a"}
2023-04-04T18:42:20.971Z	INFO	controller.provisioner	pod spryker/spryker-reward-shop-yves-6dbdcbbbc-dqd67 has a preferred TopologySpreadConstraint which can prevent consolidation	{"commit": "dc3af1a"}
2023-04-04T18:42:20.971Z	INFO	controller.provisioner	pod spryker/spryker-reward-shop-zed-77d775ff49-bz8gx has a preferred TopologySpreadConstraint which can prevent consolidation	{"commit": "dc3af1a"}
2023-04-04T18:42:21.666Z	INFO	controller.provisioner	found provisionable pod(s)	{"commit": "dc3af1a", "pods": 3}
2023-04-04T18:42:21.666Z	INFO	controller.provisioner	computed new node(s) to fit pod(s)	{"commit": "dc3af1a", "nodes": 1, "pods": 3}
2023-04-04T18:42:21.667Z	INFO	controller.provisioner	launching machine with 3 pods requesting {"cpu":"495m","memory":"1698Mi","pods":"9"} from types c5d.large, m5dn.2xlarge, m6id.xlarge, m6a.2xlarge, m5dn.12xlarge and 201 other(s)	{"commit": "dc3af1a", "provisioner": "x86"}
2023-04-04T18:42:24.179Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "dc3af1a", "provisioner": "x86", "id": "i-00dade32dccd5396a", "hostname": "ip-10-18-149-8.eu-central-1.compute.internal", "instance-type": "m6i.large", "zone": "eu-central-1c", "capacity-type": "spot"}```

**Comment by ellistarn** [comment]
> deprovisioning via consolidation delete

This bit is odd to me. We seem to think that this node is empty. 
```
	// Deprovisioning action with no replacement machines
	case actionDelete:
		return "delete"
```

Are you sure the pods are even scheduling correctly? Are you certain your pods aren't terminal with SUCCEEDED or FAILED? Can you describe events for pods and nodes?

**Comment by albertschwarzkopf** [comment]
> 



> > deprovisioning via consolidation delete
> 
> This bit is odd to me. We seem to think that this node is empty.
> 
> ```
> 	// Deprovisioning action with no replacement machines
> 	case actionDelete:
> 		return "delete"
> ```
> 
> Are you sure the pods are even scheduling correctly? Are you certain your pods aren't terminal with SUCCEEDED or FAILED? Can you describe events for pods and nodes?

Thank you for investigation! I'm sure that the pods have started successfully and were running. Also the same behaviour we have seen in other clusters with other applications. The next time I will copy the events of pods an nodes.

**Comment by autarchprinceps** [comment]
More like this: https://github.com/aws/karpenter/issues/3059

**Comment by tzneal** [comment]
Can you supply your Karpenter controller logs?

**Comment by autarchprinceps** [comment]
[karpenter.log](https://github.com/aws/karpenter/files/11294906/karpenter.log)

**Comment by tzneal** [comment]
You have preferred topology spread constraints. These can cause a situation where we launch multiple nodes to fulfill your preference, but if one node comes up slightly quicker and has enough capacity, the kube-scheduler will bind more pods to it.  This leaves an empty node that is then removed.

**Comment by runningman84** [comment]
Having these topology spread constraints seems to be best practice, can you implement some solution or slowdown in order to support topology spread constraints? We have also been using them with cluster-autoscaler without any problem.

**Comment by tzneal** [comment]
We do support topology constraints in both forms. There are some interactions with the kube-scheduler where its not aware that a new node is coming online in seconds that would meet the preferred constraint, and schedules it against an existing node that is ready.  If you use a topology spread with a `whenUnsatisfiable` set to `DoNotSchedule`, then kube-scheduler won't violate your preference and you should see this less.

**Comment by runningman84** [comment]
Changing it to noschedule will cause big problems in case of an az outage. Our topology spreads ensure that workload are on different nodes and they try to also spread on different azs. In case of an outage we could tolerate that for that moment.

**Comment by autarchprinceps** [comment]
Another person has a very similar issue with only a single pod and no topology spread constraints https://github.com/aws/karpenter/issues/3807. I don't think it can be explained away with that alone. We saw a lot of replacements nodes being the exact same instance type in the same AZ

**Comment by tzneal** [comment]
Can you supply logs that show this?  I looked at the log attached and it appears to have been caused by preferred topology spread and a race with kube-scheduler where it scheduled pods to the first nodes that went ready, leaving an empty un-needed node that was then consolidated.

**Comment by flashpaper12** [comment]
+1 I'm also experiencing this. 

<img width="1541" alt="Screenshot 2023-05-03 at 3 53 26 pm" src="https://user-images.githubusercontent.com/14196983/235841303-f3b3780e-a973-4ca4-9092-6ef1f08c3c0d.png">

The same node just keeps on getting terminated and then newly initialised

**Comment by tzneal** [comment]
@flashpaper12 Can you supply Karpenter logs and also events for the node (e.g. run `kubectl describe node node-name`)?

**Comment by dogzzdogzz** [comment]
We have similar issue recently, and found out that our pods have node affinity settings to require arm64 node, however, all of new arm64 nodes created by karpenter received the balance recommendation event and were replaced by `aws-node-termination-handler`. Just removing the node affinity settings didn't really resolve this node creation/termination loop issue because karpenter still kept creating arm64 nodes, we eventually resolve it by deploy `cluster-overprovisioner` pods for amd64 nodes to ensure there are always available capacity to avoid the spot capacity shortage in specific instance type

**Comment by borisovano** [comment]
@tzneal is it the right place to ask whether you planning to expose more controls over the consolidate logic to the user? 
such as: 
1. Weights to each of three mechanisms 
2. Ability to control the timing of the decisions such as in (batchIdleDuration)

It might help this use case, and others, such as dev cluster with dynamic workloads?

**Comment by fernandocarletti** [comment]
Was this supposed to be closed? I believe it is an ongoing issue (I still have consolidation disabled due to the issue)

**Comment by njtran** [comment]
@autarchprinceps have you still been seeing this happen? It's tough to find the issue since we don't have the way to reproduce this at the moment. We've made some bug fixes to our Consolidation/Deprovisioning logic since v0.27.0, so I think it would be worth the upgrade to the most recent version and let us know if you see it again. If you do, logs as always would be helpful.

**Comment by njtran** [comment]
@autarchprinceps re-pinging here. Any updates? Do you still see this happening?

**Comment by vipul0805** [comment]
Hi @billrayburn I am seeing this issue with karpenter v1.0.0 on EKS. I have a nodepool for AL2 AMI's and karpenter is just deleting the same instance continuously.

Resource specs:
```
---
# Source: raw/templates/resources.yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  labels:
    app: raw
    chart: raw-0.2.3
    heritage: Helm
    release: nodepool
  name: al2
spec:
  amiFamily: AL2
  role: <role>
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: <>
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: <>
---
# Source: raw/templates/resources.yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  labels:
    app: raw
    chart: raw-0.2.3
    heritage: Helm
    release: nodepool
  name: al2
spec:
  disruption:
    budgets:
    - nodes: 30%
  limits:
    cpu: "350"
    memory: 1316Gi
  template:
    metadata:
      labels:
        errors.ea.com/linux-distro: al2
    spec:
      expireAfter: 720h
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: al2
      requirements:
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - us-east-1a
        - us-east-1b
        - us-east-1c
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - c5.large
        - c5.xlarge
        - c5.2xlarge
        - c6i.large
        - c6i.xlarge
        - c6i.2xlarge
        - m5.large
        - m5.xlarge
        - m5.2xlarge
        - m6i.large
        - m6i.large
        - m6i.2xlarge
        - r5.large
        - r5.xlarge
        - r6i.large
        - r6i.xlarge
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand


```
