### ISSUE TITLE
setting system-reserved/kube-reserved based on a % instead of a static value

### ISSUE THREAD

**Issue by caviliar** [aws/karpenter#3589]
### Tell us about your request

currently `kube-reserved` and `system-reserved` is only configurable by a static value. i would like this to be more dynamic and take into account the instance-size. i would like to set a percentage like `10%`.

`cpu`/`memory`/`ephemeral-storage` are all static values.

allowing to specify both a static or percentage similar to `evictionHard` which allows both `5%` or `500Mi`

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  kubeletConfiguration:
    systemReserved:
      cpu: 1000m
  providerRef:
    name: default
  requirements:
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: ['4xlarge']
```

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

i want to specify a list of `instance-sizes` for example `2xlarge`, `4xlarge`, `9xlarge`.

different workloads require different k8s settings. our main production workload requires more `system-reserved` cpu and i have set this at `1000m`.

we would like to use more `instance-sizes` but if the machine was twice the size of another one, then there is no way to specify for it to have twice as much cpu reserved.

from what i have read, it is an anti-pattern to have multiple overlapping provisioners.

### Are you currently working around this issue?

there are a couple of options available to work around this issue
- fiddle with `userdata` to run and calculate the amount to reserve based on instance-size and use this value as a `kubelet` argument.
- update all `hpa`'s and lower the scaling target from 100% to 90%.
- own ami.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
