### ISSUE TITLE
karpenter sometimes evicting the pods even though they have the do-not-evict annotation when consolidation enabled

### ISSUE THREAD

**Issue by brainiac84** [aws/karpenter#3594]
### Version

__Karpenter Version:__ v0.27.0

__Kubernetes Version:__ v1.25.5-eks-c248520

### Expected Behavior

Do not evict the pods if `do-not-evict` annotation is set and when consolidation enabled

### Actual Behavior

karpenter sometimes evicting the pods(spawned by the job) which have the `do-not-evict` annotation _only_ when consolidation enabled

### Steps to Reproduce the Problem

Trigger around 60+ jobs to run in parallel, where is the pods have the `do-not-evict` annotation

### Resource Specs and Logs

full job spec:
```yaml
   apiVersion: batch/v1
    kind: Job
    metadata:
      generateName: placeholder # it'll be replaced with jobID
      labels:
        helm.sh/chart: workers-0.1.0
        app.kubernetes.io/name: "workers"
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      activeDeadlineSeconds: 86400
      ttlSecondsAfterFinished: 7200
      backoffLimit: 0
      template:
        metadata:
          labels:
            app.kubernetes.io/name: workers-job
            app.kubernetes.io/instance: release-name
          annotations:
            config.cordial.com/job-template: default
            app.gitlab.com/app: cordialexperiences-apps-core
            app.gitlab.com/env: staging
            karpenter.sh/do-not-evict: "true"
            linkerd.io/inject: enabled
        spec:
          terminationGracePeriodSeconds: 60
          restartPolicy: Never
          serviceAccountName: workers
          securityContext:
            sysctls:
            - name: net.ipv4.ip_local_port_range
              value: 10000 60999
          volumes:
            
            - name: vault-agent-config
              configMap:
                defaultMode: 420
                name: vault-agent-config
            - name: vault-cert
              configMap:
                defaultMode: 420
                name: vault-agent-config
                items:
                  - key: vault-ca.pem
                    path: vault-ca.pem
            - name: vault-token
              emptyDir:
                medium: Memory
            - name: consul-template
              emptyDir: {}
            - name: consul-template-out
              emptyDir: {}
            - name: cordial-data
              emptyDir: {}
            - name: temp
              emptyDir: {}
            - name: logs
              emptyDir: {}
            - name: logs-local
              emptyDir: {}
            - name: logrotate-conf
              configMap:
                defaultMode: 0644
                name: logrotate-conf
                items:
                  - key: logrotate.conf
                    path: logrotate.conf
            - name: statsd-exporter-config
              configMap:
                name: statsd-exporter-config
            - name: exit-notice
              emptyDir: {}
            - name: workers-clusters-creds
              csi:
                driver: 'secrets-store.csi.k8s.io'
                readOnly: true
                volumeAttributes:
                  secretProviderClass: 'workers-clusters-creds'
            
            - name: php-ini-settings
              configMap:
                defaultMode: 0644
                name: php-ini-settings
                items:
                - key: zz-custom.ini
                  path: zz-custom.ini
            - name: php-opcache
              emptyDir:
                medium: Memory
            - name: consul-template-secret
              csi:
                driver: 'secrets-store.csi.k8s.io'
                readOnly: true
                volumeAttributes:
                  secretProviderClass: 'workers-consul-template'
          initContainers:
            - name: config-template-copy
              image: "960048260646.dkr.ecr.us-west-2.amazonaws.com/cordial/core:cli-r-20210907.1568109017.stg"
              imagePullPolicy: IfNotPresent
              command:
                - /init
              args:
                - cp
                - /var/cordial/config.ini.tpl
                - /consul-template/config.ini.tpl
              volumeMounts:
                - mountPath: /consul-template
                  name: consul-template
              resources:
                requests:
                  memory: 10Mi
                  cpu: 10m
            - name: vault-agent-init
              args:
                - agent
                - -config=/etc/vault/vault-agent-config.hcl
                - -exit-after-auth
              env:
                - name: VAULT_ADDR
                  value: "[REDACTED]"
                - name: VAULT_CAPATH
                  value: "/etc/ssl/certs"
                - name: SKIP_SETCAP
                  value: "true"
                - name: SKIP_CHOWN
                  value: "true"
              image: "960048260646.dkr.ecr.us-west-2.amazonaws.com/vault:1.11.7"
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 100
                runAsGroup: 1000
              volumeMounts:
                - mountPath: /etc/vault
                  name: vault-agent-config
                  readOnly: true
                - mountPath: /etc/ssl/certs/vault-ca.pem
                  name: vault-cert
                  readOnly: true
                  subPath: vault-ca.pem
                - mountPath: /home/vault
                  name: vault-token
              resources:
                limits:
                  cpu: 200m
                requests:
                  cpu: 5m
                  ephemeral-storage: 300Ki
                  memory: 150Mi
            - name: consul-template-init
              image: "960048260646.dkr.ecr.us-west-2.amazonaws.com/cordial/consul-template:main-c1b25503"
              imagePullPolicy: IfNotPresent
              args:
                - /bin/bash
                - '-ec'
                - |
                  /usr/local/bin/consul-template \
                  -consul-addr=http://consul-client.consul.svc.cluster.local:8500 \
                  -vault-addr="[REDACTED]" \
                  -vault-ssl-ca-path=/etc/ssl/certs \
                  -log-level=$(LOG_LEVEL) \
                  -max-stale=10m \
                  -consul-token-file=/mnt/secret/acl-token \
                  -template "/consul-template/config.ini.tpl:/consul-template-out/config.ini" \
                  -once
              env:
                # we avoid a global value here since it is different per component
                - name: APP_NAME
                  value: "k8s-jobs"
                - name: K8S_LOGIN
                  value: "false"
                - name: HOST_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                - name: LOG_LEVEL
                  value: "info"
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
                - name: VAULT_WAIT
                  value: "false"
                - name: VAULT_K8S_AUTH_ROLE_NAME
                  value: "core-app"
                - name: VAULT_K8S_SERVICE_MOUNT_PATH
                  value: "kubernetes"
                - name: DATADOG_HOST
                  value: "127.0.0.1"
                - name: DATADOG_PORT
                  value: "9125"
                - name: "AVAILABILITY_ZONE"
                  value: "us-west-2a"
                - name: "CONSUL_AUTH_METHOD_NAME"
                  value: "kubernetes"
              volumeMounts:
                - mountPath: /consul-template
                  name: consul-template
                - mountPath: /consul-template-out
                  name: consul-template-out
                - mountPath: /home/vault
                  name: vault-token
                - mountPath: /etc/ssl/certs/vault-ca.pem
                  name: vault-cert
                  readOnly: true
                  subPath: vault-ca.pem
                - name: consul-template-secret
                  mountPath: '/mnt/secret'
                  readOnly: true
              resources:
                limits:
                  cpu: 50m
                requests:
                  cpu: 5m
                  ephemeral-storage: 300Ki
                  memory: 50Mi
          containers:
            - name: workers
              image: "960048260646.dkr.ecr.us-west-2.amazonaws.com/cordial/core:cli-r-20210907.1568109017.stg"
              imagePullPolicy: IfNotPresent
              command: ["/docker-entrypoint.sh"]
              # NOTE: always returning successful exit code to prevent triggering of additional alerts
              # as well as leave it to human judgement whether should it be retried or not.
              args:
                - su
                - -s
                - /bin/sh
                - -c
                - |
                  set -x
                  JOB_ID=$(echo "${APP_ARGO_EVENTS_POD_NAME}" | cut -d- -f1)
                  cd /var/cordial; php artisan Job:run $JOB_ID
                  code=$?
                  # shutdown statsd exporter sidecar
                  curl --retry 5 --retry-all-errors --silent -X POST 0.0.0.0:9122/-/quit
                  # shutdown linkerd-proxy sidecar
                  curl --retry 5 --retry-all-errors --silent -X POST 127.0.0.1:4191/shutdown
                  # shutdown client-log sidecar
                  touch /mnt/exit-notice/main-container-terminated
                  echo "job $JOB_ID completed with exit code $code"
                  exit 0
                - www-data
              env:
                - name: DATADOG_HOST
                  value: "127.0.0.1"
                - name: DATADOG_PORT
                  value: "9125"
                - name: DD_ENTITY_ID
                  valueFrom:
                      fieldRef:
                          fieldPath: metadata.uid
                - name: HOST_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                - name: APP_SECRETS_MOUNT_PATH
                  value: "/mnt/clusters-creds"
                - name: APP_ARGO_EVENTS_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: "APP_LOG_STREAMING"
                  value: "true"
              resources:
                limits:
                  ephemeral-storage: 5Gi
                  memory: 256Mi
                requests:
                  cpu: 200m
                  ephemeral-storage: 1Gi
                  memory: 256Mi
              volumeMounts:
                - name: vault-token
                  mountPath: /home/vault
                - name: vault-agent-config
                  mountPath: /etc/vault
                  readOnly: true
                - name: cordial-data
                  mountPath: /var/cordial/cordial_data
                - name: consul-template-out
                  mountPath: /var/cordial/cordial_data/config
                - name: logs
                  mountPath: /var/cordial/cordial_data/storage/logs
                - name: temp
                  mountPath: /tmp
                - name: logs-local
                  mountPath: /var/cordial/cordial_data/logs
                - name: exit-notice
                  mountPath: /mnt/exit-notice
                - name: workers-clusters-creds
                  mountPath: '/mnt/clusters-creds'
                  readOnly: true
                
                - name: php-ini-settings
                  mountPath: /usr/local/etc/php/conf.d/zz-custom.ini
                  subPath: zz-custom.ini
                - name: php-opcache
                  mountPath: /var/tmp/php-opcache
            - name: statsd-exporter
              image: "960048260646.dkr.ecr.us-west-2.amazonaws.com/statsd-exporter:v0.22.7"
              imagePullPolicy: IfNotPresent
              args:
                - --web.listen-address=0.0.0.0:9122
                - --statsd.listen-udp=0.0.0.0:9125
                - --statsd.listen-tcp=0.0.0.0:9125
                - --web.enable-lifecycle
                - --statsd.mapping-config=/mnt/config/mappings.yml
                - --statsd.relay.address=$(DATADOG_HOST):8125
              env:
                - name: DATADOG_HOST
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
              # the sleep keeps the exporter up while the app shuts down
              lifecycle:
                preStop:
                  exec:
                    command:
                      - /bin/sleep
                      - "30"
              ports:
                - containerPort: 9125
                  name: tcp-statsd
                  protocol: TCP
                - containerPort: 9125
                  name: udp-statsd
                  protocol: UDP
                - containerPort: 9122
                  name: metrics
                  protocol: TCP
              volumeMounts:
                - name: statsd-exporter-config
                  mountPath: /mnt/config
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /-/healthy
                  port: metrics
                  scheme: HTTP
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              livenessProbe:
                failureThreshold: 4
                httpGet:
                  path: /-/healthy
                  port: metrics
                  scheme: HTTP
                periodSeconds: 30
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  memory: 150Mi
                requests:
                  cpu: 5m
                  ephemeral-storage: 100Ki
                  memory: 25Mi
            - name: client-log
              image: "960048260646.dkr.ecr.us-west-2.amazonaws.com/busybox:latest"
              imagePullPolicy: IfNotPresent
              # note: this requires the logfiles to exist first, handled inside core container itself
              args:
                - /bin/sh
                - -c
                - |
                  trap "echo caught shutdown signal; exit" TERM INT
                  tail -n+1 -F /mnt/logs/clients/*.log &
                  CHILD_PID=$!
                  (while true; do if [[ -f "/mnt/exit-notice/main-container-terminated" ]]; then kill $CHILD_PID; fi; sleep 1; done) &
                  wait $CHILD_PID
                  if [[ -f "/mnt/exit-notice/main-container-terminated" ]]; then exit 0; fi
              lifecycle:
                preStop:
                  exec:
                    command:
                      - /bin/sleep
                      - "30"
              resources:
                requests:
                  cpu: 5m
                  memory: 25Mi
                  ephemeral-storage: 1000Mi
                limits:
                  cpu: 50m
              volumeMounts:
                - name: logs
                  mountPath: /mnt/logs
                - name: exit-notice
                  mountPath: /mnt/exit-notice
          dnsPolicy: "ClusterFirst"
          dnsConfig:
            options:
            - name: ndots
              value: "1"
            - name: single-request-reopen
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: karpenter.sh/capacity-type
                    operator: In
                    values:
                    - on-demand
```
karpenter provisioner spec:
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["arm64", "amd64"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: [ "us-west-2a"]
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values:
      - c5
      - c5d
      - c5a
      - c5ad
      - c6
      - c6a
      - c6i
      - c6id
      - c6g
      - c6gd
      - c7g
      - m5
      - m5d
      - m5a
      - m5ad
      - m6a
      - m6i
      - m6id
      - m6g
      - m6gd
      - m7g
      - r5
      - r5d
      - r5a
      - r5ad
      - r6a
      - r6i
      - r6id
      - r6g
      - r6gd
      - r7g
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values:
      - nano
      - micro
      - small
      - 8xlarge
      - 12xlarge
      - 16xlarge
      - 18xlarge
      - 24xlarge
      - 32xlarge
      - 48xlarge
      - metal
  limits:
    resources:
      cpu: "500"
      memory: 4Ti
  providerRef:
    name: cordial-bottlerocket
  consolidation:
    enabled: true
  ttlSecondsUntilExpired: 604800 # 7 days
```

**Event logs**
<img width="1765" alt="Screenshot 2023-03-15 at 16 55 50" src="https://user-images.githubusercontent.com/201724/225349225-e579c304-7653-4ac7-a2e7-07c2ebe4d7aa.png">
**Karpenter logs**
<img width="1864" alt="Screenshot 2023-03-15 at 16 58 40" src="https://user-images.githubusercontent.com/201724/225349847-a839ba05-01bc-4aea-b025-680ed77a58a9.png">

Looks only the first init container ran before pod gets evicted

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
