### ISSUE TITLE
How to increase the default ephemeral storage volume size for a node?

### ISSUE THREAD

**Issue by sebastianmontero** [aws/karpenter#3599]
### What karpenter features are relevant?

Blockdevice mappings

### How should the docs be improved?

I haven't been able to find how to can increase the default ephemeral storage volume size for a node, I'm guessing this is done through the blockdevice mappings of the  AWSNodeTemplate, but I've tried different configurations without any luck.

This is the provisioner I'm using:

```
apiVersion: karpenter.sh/v1alpha5
    kind: Provisioner
    metadata:
      name: default
    spec:
      requirements:
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["t3", "m6g"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32"]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64", "amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
      limits:
        resources:
          cpu: 1000
          memory: 1000Gi
      providerRef:
        name: default
      consolidation:
        enabled: true
 ```
And this is the AwsNodeTemplate:

```
apiVersion: karpenter.k8s.aws/v1alpha1
    kind: AWSNodeTemplate
    metadata:
      name: default
    spec:
      subnetSelector:
        karpenter.sh/discovery: ${module.eks.cluster_name}
      securityGroupSelector:
        karpenter.sh/discovery: ${module.eks.cluster_name}
      tags:
        karpenter.sh/discovery: ${module.eks.cluster_name}
      blockDeviceMappings:
      - deviceName: /dev/sdb
        ebs:
          volumeSize: 100Gi
```
Could you please provide an example on how to do this?
          

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
