### ISSUE TITLE
Bottlerocket userData not merged into launch template

### ISSUE THREAD

**Issue by leandro-loos** [aws/karpenter#3611]
### Version

__Karpenter Version:__ v0.27.0

__Kubernetes Version:__ v1.24.10-eks-48e63af

Brand new cluster created with terraform following this [example](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/v19.10.1/modules/karpenter) with Karpenter running on fargate

### Expected Behavior

I do apologise beforehand since this has to be either my misunderstanding of the documentation or my misunderstanding of how bottlerocket and userData work, otherwise there would be way more similar complaints.

I would expect that my userData defined on the cr `AWSNodeTemplate` would appear on the AWS Launch Template and therefore will then transfer to my instances.

### Actual Behavior

Not all of my defined userData reaches the Launch Template

### Steps to Reproduce the Problem

I create the following `AWSNodeTemplate` using the exact same userData provided on the example [here](https://karpenter.sh/v0.20.0/concepts/operating-systems/).
```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: sbx-core
status:
  securityGroups:
    - id: <SG_1>
    - id: <SG_2>
    - id: <SG_3>
  subnets:
    - id: <Subnet_1>
      zone: <Zone>
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
    - deviceName: /dev/xvdb
      ebs:
        deleteOnTermination: true
        encrypted: true
        kmsKeyID: <ARN>
        volumeSize: 100Gi
        volumeType: gp3
  securityGroupSelector:
    karpenter.sh/discovery: sbx2
  subnetSelector:
    karpenter.sh/discovery: sbx2
  tags:
    karpenter.sh/discovery: sbx2
  userData: |
    [settings.kubernetes]
    kube-api-qps = 30
    [settings.kubernetes.eviction-hard]
    "memory.available" = "20%"
```
Redacted the info between `<>` as it's implementation specific and those parts work fine.

The resulting Launch Template in AWS does include `kube-api-qps` but not `memory.available` (full screenshots from the template below)

It is worth mentioning that I started this super ambitiously trying to use a `bootstrap-container` and failed, decided to go more trivial adding `node-labels` which also failed, and lastly went with the same exact example from the docs and continued failing. All the time the same behaviour, whatever I define in userData was good enough to pass the TOML verification from Karpenter but will not appear on the lt, and I'm left without anywhere to look for reasons as to why this happens.

### Resource Specs and Logs

Attaching logs from karpenter for the creation of the lt, and the lt from aws console

![Screenshot 2023-03-17 at 17 08 36](https://user-images.githubusercontent.com/20324900/225967553-f72fd3ca-8406-44de-b890-ab1822b33719.png)
![Screenshot 2023-03-17 at 17 08 01](https://user-images.githubusercontent.com/20324900/225967570-e09f2a96-e2ec-4899-ac78-9ff9bff03435.png)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
