### ISSUE TITLE
Karpenter is not launching the smallest instance possible 

### ISSUE THREAD

**Issue by yuval-almog** [aws/karpenter#3617]
### Version

__Karpenter Version:__ v0.25.0

__Kubernetes Version:__ v1.21.0

### Expected Behavior

Karpenter should launch the smallest instance possible 

### Actual Behavior

since upgrading from version 0.24 to 0.25 we saw that our smallest instances have "grown" in size. Using the same pods definitions - Kaprenter 0.25 launches an instances with more cores compared to karpenter 0.24 

### Steps to Reproduce the Problem

1. install karpenter 0.24 
2. create a test provisioner 
3. create a test deployment. in my test my deployment including daemonsets my total cpu requests for all pods was 1340m and total memory request was 1754Mi 
5. kubectl apply the test deployment - see the instance launched has 2 cores 
6. upgrade karpenter to version 0.25 
7. delete the first instance   see karpenter now launched instance with 4 cores for the same spec of pods 

### Resource Specs and Logs

my test provsioner and deployment (not including daemonsets) 
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: test-provisioner
spec:
  consolidation:
    enabled: true
  kubeletConfiguration:
    containerRuntime: containerd
  labels:
    Application: test
  providerRef:
    name: default-node-template
  requirements:
  - key: karpenter.k8s.aws/instance-family
    operator: In
    values:
    - c6i
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: karpenter.k8s.aws/instance-generation
    operator: Gt
    values:
    - "4"
  - key: karpenter.k8s.aws/instance-generation
    operator: Lt
    values:
    - "7"
  - key: karpenter.k8s.aws/instance-cpu
    operator: Lt
    values:
    - "20"
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  taints:
  - effect: NoSchedule
    key: Application
    value: test
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: test-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: karpenter.k8s.aws/instance-cpu
                    operator: Lt
                    values:
                      - '5'
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 610m
            memory: 1025Mi
          limits:
            cpu: 1
            memory: 1025Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        Application: test
      tolerations:
        - key: Application
          operator: Equal
          value: test
      terminationGracePeriodSeconds: 30
```

logs 0.25:

`{"level":"INFO","time":"2023-03-19T15:36:36.247Z","logger":"controller.provisioner.cloudprovider","message":"launched new instance","commit":"beb0a64-dirty","provisioner":"test-provisioner","id":"i-xxxxxxx","hostname":"ip-xxx-xx-xxx-xxx.ec2.internal","instance-type":"c6i.xlarge","zone":"us-east-1b","capacity-type":"on-demand"}`

logs 0.24: 
`{"level":"INFO","time":"2023-03-19T16:10:22.365Z","logger":"controller.provisioner.cloudprovider","message":"launched new instance","commit":"8c27519-dirty","provisioner":"spot-c6i-test","id":"i-xxxxx","hostname":"ip-xxx-xx-xxx-xxx.ec2.internal","instance-type":"c6i.large","zone":"us-east-1a","capacity-type":"on-demand"}`

we saw this happens in multiple nodes sizes. and it made karpenter launch largest (more expensive ) instances 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
