### ISSUE TITLE
AWSNodeTemplate Control OS/amiFamily version

### ISSUE THREAD

**Issue by Raboo** [aws/karpenter#3622]
### Is an existing page relevant?

https://karpenter.sh/v0.27.0/concepts/node-templates/

### What karpenter features are relevant?

Hi,

How can I control which version of the OS/amiFamily is used?

In this case, Bottlerocket OS, I want to fix the version to Bottlerocket OS v1.13
```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  amiFamily: Bottlerocket
  subnetSelector:
    karpenter.sh/discovery: ${module.eks.cluster_name}
  securityGroupSelector:
    karpenter.sh/discovery: ${module.eks.cluster_name}
  tags:
    karpenter.sh/discovery: ${module.eks.cluster_name}
```

### How should the docs be improved?

Some example in the documentation would be nice, would be helpful for beginners.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
