### ISSUE TITLE
Spot Node not deprovisioning

### ISSUE THREAD

**Issue by Almenon** [aws/karpenter#3629]
### Version

__Karpenter Version:__ v0.23.0

__Kubernetes Version:__ v1.24.8

### Expected Behavior

Node deprovisioned. There are daemonsets, but that shouldn't count. The only non-daemonset pod has no resource requirements, so that shouldn't count either.

### Actual Behavior

Node not deprovisioned.

### Steps to Reproduce the Problem

1. Create EKS Cluster & deploy Karpenter
2. Deploy pod with no resource requirements
3. Create a daemonset
4. Create a default spot Provisioner.
5. Create a pod with resource reqs so karpenter spins up a new node
6. delete inflate pod

### Resource Specs and Logs

CPU, memory, and Pods running on node: 
<img width="796" alt="image" src="https://user-images.githubusercontent.com/13080965/226703021-b45ca11e-29a7-4fd8-86a7-7fcdb27672d2.png">
The node is using very little CPU and memory. All the pods except circleci are daemonsets. See truncated output of below command:

```
➜  ~ kubectl get pods -A -o custom-columns='NAME:.metadata.name,CONTROLLER:.metadata.ownerReferences[].kind,NAMESPACE:.metadata.namespace'
NAME                                                        CONTROLLER    NAMESPACE
aws-cloudwatch-metrics-tzqq4                                DaemonSet     amazon-cloudwatch
aws-for-fluent-bit-l7fd6                                    DaemonSet     aws-for-fluent-bit
circleci-container-agent-fbf58b8-wwzc8                      ReplicaSet    dev
aws-node-68fvk                                              DaemonSet     kube-system
datadog-ssf7p                                               DaemonSet     kube-system
ebs-csi-node-h869l                                          DaemonSet     kube-system
kube-proxy-7242n                                            DaemonSet     kube-system
```

The circleci pod does not have any resource reqs set:
```
➜  ~ k -n dev get pod/circleci-container-agent-fbf58b8-wwzc8 -o yaml | grep -i resource
  resourceVersion: "14754003"
      value: circleci-resource-tokens-test-eks1,
    resources: {}
```

Provisioner:
```yaml
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    # capacity-type, os, arch, instance-category, and instance-generation
    # MUST be specified. Otherwise we run into https://github.com/aws/karpenter/issues/2887
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: kubernetes.io/os	
      operator: In	
      values:	
        - linux	
    - key: kubernetes.io/arch	
      operator: In	
      values:	
        - amd64	
    - key: karpenter.k8s.aws/instance-category	
      operator: In	
      values:	
        - c	
        - m	
        - r	
    - key: karpenter.k8s.aws/instance-generation	
      operator: Gt	
      values:	
        - '2'
  limits:
    resources:
      cpu: "500"
      memory: 500Gi
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 30
```

Terraform:
```hcl
resource "aws_iam_instance_profile" "karpenter" {
  name = "KarpenterNodeInstanceProfile-${module.dev_main_1.eks_cluster_id}"
  role = module.dev_main_1.managed_node_group_iam_role_names[0]
}

module "dev_main_1_karpenter" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.25.0"

  providers = {
    aws        = aws.east
    helm       = helm.dev_main_1
    kubernetes = kubernetes.dev_main_1
  }
  eks_cluster_id = module.dev_main_1.eks_cluster_id

  karpenter_node_iam_instance_profile        = "KarpenterNodeInstanceProfile-${module.dev_main_1.eks_cluster_id}"
  karpenter_enable_spot_termination_handling = true
  enable_karpenter                           = true

  depends_on = [
    aws_iam_instance_profile.karpenter
  ]
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
