### ISSUE TITLE
Karpenter does not respect volume-attach-limit set for EBS volumes.

### ISSUE THREAD

**Issue by sdomme** [aws/karpenter#3647]
### Version

__Karpenter Version:__ v0.27.0

__Kubernetes Version:__ v1.24.10

### Expected Behavior

Hello. We run Karpenter on EKS and limit the attacheble EBS volumes by setting --volume-attach-limit on the ebs-csi-node.
I would expect Karpenter to create new node, if existing nodes hit the limit already attached EBS volumes.

### Actual Behavior

After the limit of attacheble EBS volumes over all nodes is hit, the PODs are stuck in pending state. No new nodes are created. All PODs show the same event:

```
0/5 nodes are available: 2 node(s) had untolerated taint {CriticalAddonsOnly: true}, 3 node(s) exceed max volume count. preemption: 0/5 nodes are available: 2 Preemption is not helpful for scheduling, 3 No preemption victims found for incoming pod.
```

### Steps to Reproduce the Problem

On a test Cluster set `--volume-attach-limit=5` on the ebs-csi-node. 3 Nodes available to run the following deployment with 20 replicas. I expect to get at least 1 additional node to run the entire workload.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: default
spec:
  replicas: 20
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - image: ealen/echo-server:latest
          imagePullPolicy: IfNotPresent
          name: echoserver
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PORT
              value: '8080'
          resources:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 128Mi
              cpu: 40m
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
          - mountPath: "/scratch"
            name: scratch-volume
      securityContext:
        fsGroup: 101
      volumes:
        - name: scratch-volume
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: my-test-volume
              spec:
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 3Gi

```

Here you can see the limitation by the ebs driver does work:

```json
kubectl get nodes -o json | jq '.items[] | {"nodeName": .metadata.name, "volumesInUse": .status.volumesInUse | length, "volumesAttached": .status.volumesAttached | length }'
{
  "nodeName": "ip-xx-xx-xx-xx.eu-central-1.compute.internal",
  "volumesInUse": 5,
  "volumesAttached": 5
}
{
  "nodeName": "ip-xx-xx-xx-xx.eu-central-1.compute.internal",
  "volumesInUse": 5,
  "volumesAttached": 5
}
{
  "nodeName": "ip-xx-xx-xx-xx.eu-central-1.compute.internal",
  "volumesInUse": 5,
  "volumesAttached": 5
}
```

Also here:

```
k get csinode ip-xx-xx-xx-xx.eu-central-1.compute.internal -o yaml
apiVersion: storage.k8s.io/v1
kind: CSINode
metadata:
  ...
spec:
  drivers:
  - allocatable:
      count: 5
    name: ebs.csi.aws.com
    nodeID: i-xxxxxxxxxxxx
    topologyKeys:
    - topology.ebs.csi.aws.com/zone
```

### Resource Specs and Logs

There is literally nothing in the carpenter controller logs after deployment was applied.

Provisioner spec:

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  consolidation:
    enabled: true
  kubeletConfiguration:
    clusterDNS:
      - xxxxxx
    maxPods: 110
  limits:
    resources:
      cpu: 1k
  providerRef:
    name: private-node
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - spot
        - on-demand
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
    - key: karpenter.k8s.aws/instance-hypervisor
      operator: In
      values:
        - nitro
    - key: karpenter.k8s.aws/instance-cpu
      operator: Gt
      values:
        - '3'
    - key: karpenter.k8s.aws/instance-cpu
      operator: Lt
      values:
        - '129'
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values:
        - c
        - m
        - r
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values:
        - '2'
  startupTaints:
    - effect: NoExecute
      key: node.cilium.io/agent-not-ready
      value: 'true'
  ttlSecondsUntilExpired: 604800
  weight: 95
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ajaykumarmandapati** [comment]
https://github.com/aws/karpenter/issues/1888 

@tzneal would this help in this regard?

**Comment by jonathan-innis** [comment]
Can you share your default `StorageClass` that is associated with the PVC that you are provisioning for this deployment

**Comment by jonathan-innis** [comment]
This looks to be a potential duplicate of https://github.com/aws/karpenter-core/issues/260. Can you confirm if you might be hitting the edge case that is described [here](https://github.com/aws/karpenter-core/issues/260#issuecomment-1494772345)

**Comment by ajaykumarmandapati** [comment]
> Can you share your default `StorageClass` that is associated with the PVC that you are provisioning for this deployment

`k get storageclasses.storage.k8s.io`

`NAME               PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ebs-sc (default)   ebs.csi.aws.com         Delete          WaitForFirstConsumer   true                   13h
gp2                kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   false                  13h`

**Comment by jonathan-innis** [comment]
Can you share the events from the pods that aren't scheduling?

**Comment by ajaykumarmandapati** [comment]
> Can you share the events from the pods that aren't scheduling? Ideally, want to see if Karpenter thinks that the pods should schedule on your current set of nodes

`0/5 nodes are available: 2 node(s) had untolerated taint {CriticalAddonsOnly: true}, 3 node(s) exceed max volume count. preemption: 0/5 nodes are available: 2 Preemption is not helpful for scheduling, 3 No preemption victims found for incoming pod.` @jonathan-innis

**Comment by jonathan-innis** [comment]
@ajaykumarmandapati Can you share the full StorageClasses, PersistentVolumes, and the PVCs that are associated with the pods that don't schedule?

**Comment by ajaykumarmandapati** [comment]
Sure, please find the requested details below : @jonathan-innis 

`pending pvc for an example-pod`
```k describe pvc echoserver-7fbddb756f-c5pdb-scratch-volume -n default
Name:          echoserver-7fbddb756f-c5pdb-scratch-volume
Namespace:     default
StorageClass:  ebs-sc
Status:        Pending
Volume:
Labels:        type=my-test-volume
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type    Reason               Age                   From                         Message
  ----    ------               ----                  ----                         -------
  Normal  WaitForPodScheduled  14s (x19 over 4m39s)  persistentvolume-controller  waiting for pod echoserver-7fbddb756f-c5pdb to be scheduled
```

`StorageClasses`
```
k get storageclasses.storage.k8s.io
NAME               PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ebs-sc (default)   ebs.csi.aws.com         Delete          WaitForFirstConsumer   true                   11h
gp2                kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   false                  12h
```

`PersistentVolumes`
```
k get pv -A
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                STORAGECLASS   REASON   AGE
pvc-038ca60f-9cec-471b-abc5-3a57c1378375   3Gi        RWO            Delete           Bound    default/echoserver-7fbddb756f-l7bcd-scratch-volume   ebs-sc                  10m
pvc-0619b02c-9c3f-47c4-a62a-972a5e61967c   3Gi        RWO            Delete           Bound    default/echoserver-7fbddb756f-ccf7w-scratch-volume   ebs-sc                  10m
pvc-0fe812ec-5bca-4b61-9054-564403b60abf   3Gi        RWO            Delete           Bound    default/echoserver-7fbddb756f-6bdp4-scratch-volume   ebs-sc                  10m
pvc-14b9eef6-e03f-4f0a-bf27-b1e979244b6a   3Gi        RWO            Delete           Bound    default/echoserver-7fbddb756f-lk7jg-scratch-volume   ebs-sc                  10m
pvc-316b6c20-5a8c-4855-a76e-bcb93e14da7c   3Gi        RWO            Delete           Bound    default/echoserver-7fbddb756f-fpl6n-scratch-volume   ebs-sc                  10m
pvc-3d98d640-67be-414e-b6f9-9f03803b2089   3Gi        RWO            Delete           Bound    default/echoserver-7fbddb756f-9xtfd-scratch-volume   ebs-sc                  10m
pvc-4ef6d7f0-bf88-425c-84c4-67ee6cce84af   32Gi       RWO            Delete           Bound    kubecost/vmsingle-kubecost                           ebs-sc                  11h
pvc-506d34ad-d41a-418f-9785-491a0c2e12ba   20Gi       RWO            Delete           Bound    victoria/vmsingle-victoria-stack                     ebs-sc                  11h
pvc-8086d8fa-25e0-49e2-a334-9f8e5b1717a6   3Gi        RWO            Delete           Bound    default/echoserver-7fbddb756f-cjtsb-scratch-volume   ebs-sc                  10m
pvc-90277e20-df0c-4018-8b52-f9d23202d651   32Gi       RWO            Delete           Bound    kubecost/kubecost-cost-analyzer                      ebs-sc                  11h
pvc-b67aa645-fbcf-4880-acab-b8187a85cfcc   3Gi        RWO            Delete           Bound    default/echoserver-7fbddb756f-9l5ll-scratch-volume   ebs-sc                  10m
pvc-d236ea08-0065-475e-8548-f97853b51fca   3Gi        RWO            Delete           Bound    default/echoserver-7fbddb756f-vkjg9-scratch-volume   ebs-sc                  10m
pvc-e029a59e-dcd6-490e-bfab-0c2bdb547884   3Gi        RWO            Delete           Bound    default/echoserver-7fbddb756f-kjfx4-scratch-volume   ebs-sc                  10m
pvc-e22db5f8-b7a5-4db3-8b23-86fe27ce0772   3Gi        RWO            Delete           Bound    default/echoserver-7fbddb756f-h8rs5-scratch-volume   ebs-sc                  10m
pvc-f8bc35cc-98d6-4234-b3c7-0e81c2121b35   3Gi        RWO            Delete           Bound    default/echoserver-7fbddb756f-z2fqk-scratch-volume   ebs-sc                  10m
pvc-feb23aaa-dbc0-4142-9395-a8515e535b6e   3Gi        RWO            Delete           Bound    default/echoserver-7fbddb756f-89579-scratch-volume   ebs-sc                  10m
```

`PVCs`
```
k get pvc
NAME                                         STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
echoserver-7fbddb756f-6bdp4-scratch-volume   Bound     pvc-0fe812ec-5bca-4b61-9054-564403b60abf   3Gi        RWO            ebs-sc         12m
echoserver-7fbddb756f-89579-scratch-volume   Bound     pvc-feb23aaa-dbc0-4142-9395-a8515e535b6e   3Gi        RWO            ebs-sc         12m
echoserver-7fbddb756f-9l5ll-scratch-volume   Bound     pvc-b67aa645-fbcf-4880-acab-b8187a85cfcc   3Gi        RWO            ebs-sc         12m
echoserver-7fbddb756f-9xtfd-scratch-volume   Bound     pvc-3d98d640-67be-414e-b6f9-9f03803b2089   3Gi        RWO            ebs-sc         12m
echoserver-7fbddb756f-c5pdb-scratch-volume   Pending                                                                        ebs-sc         12m
echoserver-7fbddb756f-ccf7w-scratch-volume   Bound     pvc-0619b02c-9c3f-47c4-a62a-972a5e61967c   3Gi        RWO            ebs-sc         12m
echoserver-7fbddb756f-cjtsb-scratch-volume   Bound     pvc-8086d8fa-25e0-49e2-a334-9f8e5b1717a6   3Gi        RWO            ebs-sc         12m
echoserver-7fbddb756f-dbk5k-scratch-volume   Pending                                                                        ebs-sc         12m
echoserver-7fbddb756f-fpl6n-scratch-volume   Bound     pvc-316b6c20-5a8c-4855-a76e-bcb93e14da7c   3Gi        RWO            ebs-sc         12m
echoserver-7fbddb756f-h8rs5-scratch-volume   Bound     pvc-e22db5f8-b7a5-4db3-8b23-86fe27ce0772   3Gi        RWO            ebs-sc         12m
echoserver-7fbddb756f-kjfx4-scratch-volume   Bound     pvc-e029a59e-dcd6-490e-bfab-0c2bdb547884   3Gi        RWO            ebs-sc         12m
echoserver-7fbddb756f-l7bcd-scratch-volume   Bound     pvc-038ca60f-9cec-471b-abc5-3a57c1378375   3Gi        RWO            ebs-sc         12m
echoserver-7fbddb756f-ldnmc-scratch-volume   Pending                                                                        ebs-sc         12m
echoserver-7fbddb756f-lk7jg-scratch-volume   Bound     pvc-14b9eef6-e03f-4f0a-bf27-b1e979244b6a   3Gi        RWO            ebs-sc         12m
echoserver-7fbddb756f-m4qhp-scratch-volume   Pending                                                                        ebs-sc         12m
echoserver-7fbddb756f-nrsp8-scratch-volume   Pending                                                                        ebs-sc         12m
echoserver-7fbddb756f-r7dqx-scratch-volume   Pending                                                                        ebs-sc         12m
echoserver-7fbddb756f-vkjg9-scratch-volume   Bound     pvc-d236ea08-0065-475e-8548-f97853b51fca   3Gi        RWO            ebs-sc         12m
echoserver-7fbddb756f-z2fqk-scratch-volume   Bound     pvc-f8bc35cc-98d6-4234-b3c7-0e81c2121b35   3Gi        RWO            ebs-sc         12m
echoserver-7fbddb756f-zqmg5-scratch-volume   Pending                                                                        ebs-sc         12m
```

**Comment by jonathan-innis** [comment]
Can you share the full output `-o yaml` from all the above. Also, getting the full output `-o yaml` from nodes that Karpenter scheduled for these PVs would be good as well. You can attach them as files in your response if they get too long.

**Comment by ajaykumarmandapati** [comment]
[output-yaml.zip](https://github.com/aws/karpenter/files/11173801/output-yaml.zip)

I've attached them 👍🏾

**Comment by jonathan-innis** [comment]
Can you share the full output of CSINodes as well?

**Comment by ajaykumarmandapati** [comment]
@jonathan-innis Please find the attachments requested.

[final-output.zip](https://github.com/aws/karpenter/files/11199544/final-output.zip)

**Comment by jonathan-innis** [comment]
If there are no logs, have you tried restarting the karpenter pods? Also, could you [enable debug logs](https://karpenter.sh/preview/troubleshooting/#enable-debug-logging) on your logging if you haven't already? It's difficult to debug this issue or figure out what's going on without the logs here.

I'm not able to repro issue when I deploy a similar configuration on my cluster running the same version of Karpenter.

**Comment by sdomme** [comment]
Hi @jonathan-innis Even enabling the debug didin't show anything. There are just no logs after createing the Deployment. We also double checked everything to make sure nothing else disturb the tests. An interesting thing also was, that you mentioned to run your test as a statefulSet. This is different from us. And yes, it worked finally with the statefulSet!

So the problem must be somewhere in the deployment spec for the volumes:

```
...
    volumes:
      - name: scratch-volume
        ephemeral:
          volumeClaimTemplate:
            metadata:
              labels:
                type: my-test-volume
            spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 3Gi
```

Is it the type ephemeral with a volumeClaimTemplate? Kubernetes wise it is correct and creates PVCs and PVs.
