### ISSUE TITLE
topologySpreadConstraints not honoured when consolidation is enabled

### ISSUE THREAD

**Issue by ctradar** [aws/karpenter#3652]
### Version

__Karpenter Version:__ v0.20.0

__Kubernetes Version:__ v1.22

### Expected Behavior

topologySpreadConstraints is honoured and pods are spread across different nodes

### Actual Behavior

topologySpreadConstraints is not honoured and pods are scheduled on the same node

### Steps to Reproduce the Problem

Run a deployment with the below topologySpreadConstraints config with consolidation set to true in the karpenter provisioner

```
topologySpreadConstraints:
      - labelSelector:
         matchLabels:
           app.kubernetes.io/name: asset-fql
         maxSkew: 1
         topologyKey: kubernetes.io/hostname
         whenUnsatisfiable: DoNotSchedule
```

### Resource Specs and Logs

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: spot
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-east-1a"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot"]
  providerRef:
    name: spot
  limits:
    resources:
      cpu: 100
      memory: 200Gi
  consolidation:
    enabled: true
  kubeletConfiguration:
    containerRuntime: dockerd
    clusterDNS: ["172.20.0.10"]
  labels:
    node-type: spot
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: spot
spec:
  amiSelector:
    aws-ids: "ami-03a30cc1dda93f173"
  subnetSelector:
    karpenter.sh/discovery: spot
  securityGroupSelector:
    karpenter.sh/discovery: spot
  instanceProfile: KarpenterInstanceProfile
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        deleteOnTermination: true
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
