### ISSUE TITLE
Setting cpuCFSQuota at kubeletConfiguration is ignored

### ISSUE THREAD

**Issue by rgeraskin** [aws/karpenter#3699]
### Version

__Karpenter Version:__ v0.27.0

__Kubernetes Version:__ v1.23.17

### Expected Behavior

Setting:
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  ...
  kubeletConfiguration:
    cpuCFSQuota: false
```

leads to kubelet setting at nodes:
```
# cat /etc/kubernetes/kubelet/kubelet-config.json | grep cpuCFSQuota
  "cpuCFSQuota": false
```

### Actual Behavior

No cpuCFSQuota setting
```
# cat /etc/kubernetes/kubelet/kubelet-config.json | grep cpuCFSQuota

```

### Steps to Reproduce the Problem

Set `cpuCFSQuota: false` at Provisioner kubeletConfiguration

### Resource Specs and Logs

n/a

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Can you provide a full launchTemplate and provisioner spec? Specifically, I need to see your amiFamily and userData.

**Comment by rgeraskin** [comment]
@ellistarn, here are my AWSNodeTemplate and Provisioner manifests:
```
extraObjects:
  - apiVersion: karpenter.k8s.aws/v1alpha1
    kind: AWSNodeTemplate
    metadata:
      name: common-nodetemplate
      namespace: karpenter
    spec:
      blockDeviceMappings:
        - deviceName: /dev/xvda
          ebs:
            deleteOnTermination: true
            volumeSize: 100Gi
            volumeType: gp2
      securityGroupSelector:
        aws-ids: >-
          xxx
      subnetSelector:
        aws-ids: >-
          xxx
      tags:
        ClusterName: xxx
  - apiVersion: karpenter.sh/v1alpha5
    kind: Provisioner
    metadata:
      name: common-provisioner
      namespace: karpenter
    spec:
      kubeletConfiguration:
        cpuCFSQuota: false
      labels:
        karpenter: "true"
      limits:
        resources:
          cpu: "80"
      providerRef:
        name: common-nodetemplate
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - c5.2xlarge
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
      taints:
        - effect: NoSchedule
          key: karpenter
          value: "true"
      ttlSecondsAfterEmpty: 60
      ttlSecondsUntilExpired: 864000
```
