### ISSUE TITLE
Drift detection is flaky

### ISSUE THREAD

**Issue by stouset** [aws/karpenter#3708]
### Version

```
__Karpenter Version:__ v0.25.0
__Kubernetes Version:__ v1.23.17
```

We are not running on the latest version of Karpenter. Reading through the CHANGELOGs, I don't believe versions through 0.27.1 address our issue, but if you have reason to believe otherwise please let me know.

We have enabled drift detection in some of our clusters via the following:

```sh
❯ kubectl --namespace karpenter \
    get configmap karpenter-global-settings \
    --output yaml \
  | yq .data \
  | grep drift

featureGates.driftEnabled: "true"
```

This feature seems extremely brittle. Sometimes it works beautifully, other times it silently does nothing. At times where it's quietly not working, even manually annotating nodes does not cause karpenter to start deprovisioning. Again, nothing relevant is in the logs.

```sh
❯ kubectl annotate node "${node}" 'karpenter.sh/voluntary-disruption=drifted'
```

The only pattern we've noticed is that in working pods, we see the following logs (with some noise removed for clarity):

```
controller.deprovisioning	controller/singleton.go:95	starting controller
controller.deprovisioning	cloudprovider/instancetypes.go:237	discovered EC2 instance types	{"instance-type-count": 626}
controller.deprovisioning	cloudprovider/instancetypes.go:198	discovered EC2 instance types zonal offerings for subnets	{"subnet-selector": "{\"aws-ids\":\"REDACTED,REDACTED,REDACTED\"}"}
...
controller.deprovisioning	deprovisioning/controller.go:145	deprovisioning via drift delete, terminating 1 nodes REDACTED/c6a.8xlarge/on-demand
# nodes continue to deprovision as expected
```

On pods that aren't deprovisioning nodes, we see:

```
controller.deprovisioning	controller/singleton.go:95	starting controller
controller.deprovisioning	cloudprovider/instancetypes.go:237	discovered EC2 instance types	{"instance-type-count": 626}
controller.node-state	cloudprovider/instancetypes.go:198	discovered EC2 instance types zonal offerings for subnets	{"node": REDACTED, "subnet-selector": "{\"aws-ids\":\"REDACTED,REDACTED,REDACTED\"}"}
...
# nothing further
```

Note that in the pod that's detecting drift successfully, discovering EC2 instance types zonal offerings is performed by the deprovisioning controller while in the pod that's stalled, it's being done by the node-state controller. They also produce slightly different log output. I have no idea if this is a clue or a red herring, but it seemed significant enough to warrant mention given the lack of other information I have about this.

Note that both of these pods are configured exactly the same, with the same `configmap/karpenter-global-settings`:

```sh
❯ kubectl --namespace karpenter \
    get configmap karpenter-global-settings \
    --output yaml \
  | yq .data

aws.clusterEndpoint: REDACTED
aws.clusterName: REDACTED
aws.defaultInstanceProfile: REDACTED
aws.enableENILimitedPodDensity: "true"
aws.enablePodENI: "false"
aws.interruptionQueueName: ""
aws.isolatedVPC: "true"
aws.nodeNameConvention: ip-name
aws.vmMemoryOverheadPercent: "0.075"
batchIdleDuration: 1s
batchMaxDuration: 10s
featureGates.driftEnabled: "true"
```

Thanks for investigating!

### Expected Behavior

Drift detection should cause nodes that have drifted to be annotated with `karpenter.sh/voluntary-disruption=drifted`, and notes with that annotation should be deprovisioned.

### Actual Behavior

Nodes that have drifted are not annotated, nor are annotated nodes deprovisioned.

### Steps to Reproduce the Problem

¯\\_(ツ)_/¯

For us, it's intermittent. Sometimes pods perform correctly right off the bat. Sometimes they don't. Sometimes they stop after awhile of working successfully.

### Resource Specs and Logs

Provider:

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: normal
spec:
  kubeletConfiguration:
    containerRuntime: dockerd
  labels:
    workload: normal
  limits:
    resources:
      cpu: "9600"
      memory: 19200Gi
  providerRef:
    name: normal
  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - c6a.8xlarge
    - c6i.8xlarge
    - c5a.8xlarge
    - c5.9xlarge
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  taints:
  - effect: NoSchedule
    key: workload
    value: normal
  ttlSecondsUntilExpired: 604800
```

AWSNodeTemplate:

```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: normal
spec:
  amiFamily: AL2
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      encrypted: true
      volumeSize: 500Gi
      volumeType: gp3
  securityGroupSelector:
    aws-ids: REDACTED
  subnetSelector:
    aws-ids: REDACTED
  userData: REDACTED
  securityGroups:
  - id: REDACTED
  - id: REDACTED
  subnets:
  - id: REDACTED
    zone: us-east-1d
  - id: REDACTED
    zone: us-east-1a
  - id: REDACTED
    zone: us-east-1c
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
