### ISSUE TITLE
Provide More Verbose AMI Compatibility Failure Error Messaging

### ISSUE THREAD

**Issue by jonathan-innis** [aws/karpenter#3849]
### Tell us about your request

When an AMI fails to be compatible with any instance types during the `cloudprovider.Create()` process, an error is fired with the following messaging

```console
2023-05-03T00:10:34.633Z	ERROR	controller.provisioner	launching machine, creating cloud provider instance, creating instance, getting launch template configs, getting launch templates, no amis exist given constraints	{"commit": "beb0a64-dirty"}
```

Though this gives information to the user that no AMIs matched the instance types, it does not give _any_ information on why the compatibility failure occurred. We should provide more verbose error logging in this console log so that the user gets more information on what they need to change in either their AMI selector or their diversity of instance types that are launched in their provisioner/pod combos.

A good place to start would be here, passing the errors back through the call from the failed compatibility checks across all AMIs: https://github.com/aws/karpenter/blob/main/pkg/providers/amifamily/resolver.go#L127

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

N/A

### Are you currently working around this issue?

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by srinchow** [comment]
would like to work on this if no one else has already picked it up

**Comment by srinchow** [comment]
The function to consider here i think is the 
`func MapInstanceTypes(amis []AMI, instanceTypes []*cloudprovider.InstanceType) map[string][]*cloudprovider.InstanceType` my idea is to also return an error from this function instead of just returning an empty map and using the len of map to determine no match. Inside this error object we can encode the more verbose error

**Comment by srinchow** [comment]
@jonathan-innis the line you pointed out already has a log which prints all the ami's i don't see that reflected in the logs statement you posted, 
as a start should we print out the possible ami names and instanceTypes incase of no match i.e `len(mappedAMIs) == 0`

**Comment by jonathan-innis** [comment]
@srinchow You're correct that we'd print out the resolved amis that we have, but the problem is that we wouldn't print out the reason why no instance types were compatible with a given AMI. I wonder if we can somehow create a summary or print out the most recent compatibility error between an AMI and an instance type if no instance types match. 

The compatibility error that I'm referring to is linked here: https://github.com/aws/karpenter/blob/main/pkg/providers/amifamily/ami.go#L106

**Comment by jonathan-innis** [comment]
@srinchow Assigned

**Comment by srinchow** [comment]
> @srinchow You're correct that we'd print out the resolved amis that we have, but the problem is that we wouldn't print out the reason why no instance types were compatible with a given AMI. I wonder if we can somehow create a summary or print out the most recent compatibility error between an AMI and an instance type if no instance types match.
> 
> The compatibility error that I'm referring to is linked here: https://github.com/aws/karpenter/blob/main/pkg/providers/amifamily/ami.go#L106

@jonathan-innis I understand that you don't print the reason when there is no compatibility match. Instead, you would like to add something to the log to help you understand the reason for the mismatch. However, if we want to add the entire summary of errors for all the AMIs, we may end up with a lot of log lines i.e N*M log lines incase of no match (N=no_of_amis M=no_of_instanceTypes as none of the ami would match to none of the instances), if these fields have high cardinality that could be an issue.

To address this issue, we can implement something that only lists a subset of these error summaries. For example, we can list only the last error summary as you mentioned

My suggestion is to let the viewer interpret the cause of the mismatch. Currently, the viewer cannot do so because they don't have the instance types with them.

so something like a 
`fmt.Errorf("no instance types %v satisfy requirements of amis %v", instanceTypes, amis)`

I came up with this solution because I was considering a straightforward situation. For instance, let's say we have an AMI that is of a GPU type, but none of the instances are of GPU type. In this case, we can easily understand why there is a compatibility issue by printing out a list of instances and AMIs.

**Comment by jonathan-innis** [comment]
I think you might have the reverse problem here, where the number of instance types might be incredibly overwhelming given the number of instance types. Is it possible that we print out the top 2-3 unique compatibility errors for the AMIs and then give the number of instance types that we are considering with some instance type examples (similar to our launch log "launching instance types from m5.large, m5.xlarge and 68 others..."

**Comment by srinchow** [comment]
@jonathan-innis makes sense i would then do 2 of the following things
1. Print a brief summary of 2-3 compatibility errors
2. add a log with a few machine types along with the total count for the same 

does this sound alright ?

**Comment by jonathan-innis** [comment]
Yep, that sounds great. We can discuss more in the PR you raise and do a little more back-and-forth there 👍

**Comment by srinchow** [comment]
@jonathan-innis made a draft pr for the same do have a look

**Comment by jonathan-innis** [comment]
Ah, I'm seeing what you were raising here originally. It looks like the user who originally reported that the error wasn't verbose enough was from a Karpenter version prior to #3700. I think with the current version on main, we are in a better situation where we are least exposing the AMI requirements back through the logs.

Based on the log that you showed that we print now, I'm wondering if we even need to provide more context. What are your thoughts on the current state and if you would be able to properly debug using the AMI info that's currently printed. Would giving info on the attempted launched instance types help with debugging here?

**Comment by srinchow** [comment]
I would say getting to know the attempted launch instance would make it easier to debug.

**Comment by jonathan-innis** [comment]
@srinchow Do you want to update the PR to just add instance type logging as values in the error message that's returned?

**Comment by srinchow** [comment]
yes will do let me update the pr for the same

**Comment by srinchow** [comment]
@jonathan-innis i had updated the pr can you have a look now

**Comment by srinchow** [comment]
@jonathan-innis any movement here this has been stale for a while

**Comment by jonathan-innis** [comment]
@srinchow Responded on the PR that you opened. Apologize for the churn. Like I mentioned in the PR, this issue got resolved separately by a different PR merge, so I'm going to close this for now.

**Comment by dcarrion87** [comment]
I am currently in hell trying to work out what the error on an issue is. What was the resolution with this on how we can determine why it's spewing incompatibility?

**Comment by tzneal** [comment]
The AMI's with requirements will be listed as part of the status on your node template. You can look here to ensure its discovering the expected AMIs:


```yaml
status:
  amis:
  - id: ami-03c71b04d72abcaba
    name: amazon-eks-node-1.26-v20230703
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: DoesNotExist
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: DoesNotExist
  - id: ami-04b16fffebdb71b44
    name: amazon-eks-gpu-node-1.26-v20230703
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: Exists
  - id: ami-04b16fffebdb71b44
    name: amazon-eks-gpu-node-1.26-v20230703
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: Exists
  - id: ami-0e1b6fa1064526fe3
    name: amazon-eks-arm64-node-1.26-v20230703
    requirements:
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: DoesNotExist
    - key: kubernetes.io/arch
      operator: In
      values:
      - arm64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: DoesNotExist
```

It will also be periodically reported as a log:

```
DEBUG	controller.awsnodetemplate	discovered amis	{"commit": "0de32b0-dirty", "awsnodetemplate": "prov-217-dockerd", "ids": "ami-03c71b04d72abcaba, ami-04b16fffebdb71b44, ami-04b16fffebdb71b44, ami-0e1b6fa1064526fe3", "count": 4}
```
