### ISSUE TITLE
How can i select private image?

### ISSUE THREAD

**Issue by belalhassan91** [aws/karpenter#3864]
### Is an existing page relevant?

https://karpenter.sh/preview/concepts/node-templates/#specamiselector

Version
Karpenter Version: v0.27.3

Kubernetes Version: v1.23

is it possible to select AMI images that it shared with me from organization accounts?
the following is my configuration
what is the possible values for aws::owners
```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  amiSelector:
     aws::name: "private"
     aws::owners: shared/account-id
```

**Comment by belalhassan91** [comment]
yes it works after add reconfigure it as following
```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  amiSelector:
     aws::name: "my-image"
     aws::owners: account-id
```
