### ISSUE TITLE
Karpenter does not provision new node base on custom key

### ISSUE THREAD

**Issue by taxidis** [aws/karpenter#3919]
### Version

__Karpenter Version: 0.27.3
__Kubernetes Version:__ v1.26

### Expected Behavior

If there is no capacity for `environment=managed`  labeled nodes on wanted AZ we expect a new node with environment=managed to be provisioned on wanted AZ and for the pod to be scheduled there.

### Actual Behavior

With the setup above, if there is no capacity on the nodes labeled as `environment=management ` on either AZ, no new node is being provisioned and logs show incompatibility.

If we change the spec.affinity of prometheus chart from 
```
          - key: environment
            operator: In
            values:
            - management
```
to 
```
          - key: environment
            operator: In
            values:
            - production
```
and there is no capacity on the nodes labeled as `environment=production ` a new node is being provisioned on wanted AZ. 

### Steps to Reproduce the Problem

Create provisioner.
Install a helm chart that has statefulset with PVs and the provided affinities, using the second value of `environment` label (management).
Upgrade said helm chart while no capacity on existing "management" nodes.

### Resource Specs and Logs

We use EKS on AWS and we have the following karpenter provisioner:
```
    apiVersion: karpenter.sh/v1alpha5
    kind: Provisioner
    metadata:
      name: gp-amd-ondemand-nodes
      namespace: karpenter
    spec:
      providerRef:
        name: bottlerocket
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["m5.xlarge"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "environment"
          operator: In
          values: ["production", "management"]
```

I have already installed a prometheus stack with 2 prometheus server pods. Servers have PVs and are spread across 2 AZs, eu-west-1a and eu-west-1b.

```
    affinity:
     nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: karpenter.sh/capacity-type
            operator: In
            values:
            - on-demand
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
          - key: environment
            operator: In
            values:
            - management
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: prometheus
```

When upgrading the helm chart of Prometheus, if no space is available on any of the two AZs, 

```
incompatible with provisioner "gp-amd-ondemand-nodes", no instance type satisfied resources {"cpu":"1200m","memory":"4146Mi","pods":"1"} and requirements 
topology.kubernetes.io/region In [eu-west-1],
topology.kubernetes.io/zone In [eu-west-1b],
karpenter.sh/capacity-type In [on-demand], 
environment In [management],
kubernetes.io/os In [linux],
kubernetes.io/arch In [amd64],
karpenter.sh/provisioner-name In [gp-amd-ondemand-nodes], 
node.kubernetes.io/instance-type In [m5.xlarge]; 
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
