### ISSUE TITLE
Karpenter - half of nodes state are not ready after simulate spot disruption with aws fis

### ISSUE THREAD

**Issue by peanutnbt** [aws/karpenter#3928]
### Version

__Karpenter Version:__ v0.27.3

__EKS Version:__ v1.24

### Expected Behavior

All spot instances get ready status

### Actual Behavior

Half of the newly provisioned instances are stuck in NotReady status.

### Steps to Reproduce the Problem

Scale inflate deployment to get 2 new nodes. Use AWS FIS to simulate spot interruption. 

### Resource Specs and Logs

I have an EKS cluster running with Karpenter provisioning. Everything worked as expected, but when I used AWS FIS to simulate spot instances interruption, I faced a weird behavior - new nodes were provisioned, but half of the new nodes were stuck in not ready forever.

As you see in the below picture, 3 in 6 nodes are stuck in NotReady status, even using the same launch template, and worked fine in normal scaling, deprovisioning cases (like manual terminate ec2 spot instances, scale up and down pod). When I had 2 new nodes provisioned, then 1 of them got stuck.

![image](https://github.com/aws/karpenter/assets/32488457/a338955f-8915-48dd-8a90-c330a611b609)

Here is my Provisioner
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  providerRef:
    name: default
  tags:
    karpenter.sh/discovery: finpath-dev

  labels:
    billing-team: my-team

  annotations:
    example.com/owner: "my-team"

  requirements:
    - key: kubernetes.io/os
      operator: In
      values: ["linux"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.small", "t3a.small", "t3.medium", "t3a.medium" ]
      # values: ["t3.medium", "t3a.medium" ]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]

  limits:
    resources:
      cpu: "100"
      memory: 100Gi

  consolidation:
    enabled: true

  ttlSecondsUntilExpired: 10800 # 3 hours

  weight: 10
```

Log of Karpenter

![image](https://github.com/aws/karpenter/assets/32488457/65fb9fad-57e8-42fc-a069-7ba5b086dcd0)

AWS FIS config
![image](https://github.com/aws/karpenter/assets/32488457/2c81c13d-72e8-46fe-864d-011cfed76530)

And one weird thing is my launch template include user data that add my ssh public key to the node then I can ssh later, but it worked (can ssh to node) only for nodes that ready, and the nodes are in NotReady status were not (Even ec2 state is running - I got Permission denied (publickey,gssapi-keyex,gssapi-with-mic))

Am I wrong in any setup step? Can someone give me a hint or any suggestions? Thank you!

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
