### ISSUE TITLE
Provisioners annotations

### ISSUE THREAD

**Issue by MauroSoli** [aws/karpenter#3963]
The annotations should be under metadata section and not under spec.

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: provisioner-test
  # Annotation to use a custom network in EKS
  # The Eniconfig name must have the name of the availability zone
  annotations:
    k8s.amazonaws.com/eniConfig: test
spec:
  # References cloud provider-specific custom resource, see your cloud provider specific documentation
  providerRef:
    name: default
```
