### ISSUE TITLE
Karpenter deprovision nodes (ttlSecondsUntilExpired) not provisioned by Karpenter

### ISSUE THREAD

**Issue by balusarakesh** [aws/karpenter#3967]
### Version

__Karpenter Version:__ v0.27.1

__Kubernetes Version:__ v1.23.17-eks-0a21954

### Expected Behavior

Karpenter should deprovision based on `ttlSecondsUntilExpired` for all nodes including the ones that are not provisioned by karpenter

### Actual Behavior

Currently deprovision happens for the nodes that are provisioned only by Karpenter. We expect the deprovision to happen to ALL nodes.

### Steps to Reproduce the Problem

NA

### Resource Specs and Logs

Our provisioner config:
```
- apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: default
  spec:
    annotations:
      karpenter.sh/do-not-consolidate: "true"
    requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand"]
      - key: node.kubernetes.io/instance-type
        operator: In
        values: [c5a.8xlarge]
    limits:
      resources:
        cpu: 2000
    providerRef:
      name: default
    ttlSecondsAfterEmpty: 30
    ttlSecondsUntilExpired: 2592000
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
