### ISSUE TITLE
Karpenter provision-node is missing "failure-domain.beta.kubernetes.io" label after upgrading EKS version to v1.26

### ISSUE THREAD

**Issue by KqLLL** [aws/karpenter#3996]
### Version

__Karpenter Version:__ v0.27.3

__Kubernetes Version:__ v1.26.4

### Expected Behavior

In EKS **1.25**, labels still exist on provision-node<img width="1388" alt="image" src="https://github.com/aws/karpenter/assets/76542414/c0a20ec5-ff7b-4502-a321-409b680ac6f3">

### Actual Behavior

In EKS **1.26** these labels are **missing**.
<img width="1402" alt="image" src="https://github.com/aws/karpenter/assets/76542414/a80d805c-a876-4790-99c6-bfc7695730c0">

### Steps to Reproduce the Problem

**Upgrade EKS version to v1.26.**

The Kapenter provision-node will be missing the "failure-domain.beta.kubernetes.io" labels, but the **CA(ASG)** creation node will have them

I'm curious why?

### Resource Specs and Logs

No error logs

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Did you use the same karpenter version for both EKS 1.25 and 1.26?

**Comment by bwagner5** [comment]
hmm odd, I just tried this on my 1.27 cluster and I'm getting the labels:

```
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: c6i.large
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: us-west-2
    failure-domain.beta.kubernetes.io/zone: us-west-2a
```

These labels have been deprecated for quite some time, so I wouldn't rely on them. Can you move to `topology.kubernetes.io/region` and `.../zone` instead?
