### ISSUE TITLE
Karpenter is incompatible with PVCs which were previously created using intree and had been automatically migrated to CSI

### ISSUE THREAD

**Issue by nadavbuc** [aws/karpenter#4003]
### Version

__Karpenter Version:__ v0.27.5
__Kubernetes Version:__ v1.26.4

### Expected Behavior

STS pod will be scheduled on a node

### Actual Behavior

Karpenter nominates pod to a node, but pod is stuck on pending.
As a workaround i created a small ASG on the same availability zones as the ebs volumes, i added affinity to the STS to use the ASG's nodes, and pods were successfully scheduled on them

_I Had not experienced this behavior until upgrading kubernetes to 1.26 (saw no issues on 1.25)_

### Steps to Reproduce the Problem

You must have an INTREE created pvc (EBS)
When you upgrade EKS it will automatically migrate the EBS to CSI and annotate it with
`pv.kubernetes.io/migrated-to: ebs.csi.aws.com`
Migrate nodes to Karpenter and recycle all nodes

### Resource Specs and Logs

LOGS:
```
2023-06-06T08:45:20.040Z	ERROR	controller.deprovisioning	PersistentVolume source 'AWSElasticBlockStore' uses an in-tree storage plugin which is unsupported by Karpenter and is deprecated by Kubernetes. Scale-ups may fail because Karpenter will not discover driver limits. Use a PersistentVolume that references the 'CSI' volume source for Karpenter auto-scaling support.	{"commit": "698f22f-dirty", "pod": "graphileon-0", "volume": "data", "persistent-volume": "pvc-e869a2d1-bdde-4c0c-93d0-c3d60ad2da90"}
```

STS:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
spec:
  template:
    spec:
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
      storageClassName: gp2
      volumeMode: Filesystem
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
