### ISSUE TITLE
topology spread multiarch

### ISSUE THREAD

**Issue by tuananh** [aws/karpenter#4011]
I have an use case where I need a deployment to spread on multiple architectures: amd64 and arm64

How should I achieve this with karpenter?

My setup is like this https://github.com/aws/karpenter/issues/2513#issuecomment-1254052045

maybe I should try to use only 1 provisioner ?

from what I observe, a new arm64 node will be provisioned but then it's getting consolidated right away.

**Comment by bwagner5** [comment]
can you post you provisioner and workload configurations?

**Comment by gtn3010** [comment]
Hi @bwagner5 , here is provisioner amd64:
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: amd64-workload
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m6i.xlarge", "m4.xlarge", "m5.xlarge", "m5n.xlarge", "m6a.xlarge"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
    - key: kubernetes.io/os	
      operator: In	
      values:	
        - linux	
    - key: kubernetes.io/arch	
      operator: In	
      values:	
        - amd64
    - key: arch-spread
      operator: In
      values:
      - "3"
      - "4"
  kubeletConfiguration:
    containerRuntime: containerd
    evictionMaxPodGracePeriod: 60
    maxPods: 30
  limits:
    resources:
      cpu: "20"
  providerRef:
    name: amd64-workload
  consolidation:
    enabled: true
  ttlSecondsUntilExpired: 604800
```

provisioner arm64:
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: arm64-workload
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m6g.xlarge", "m7g.xlarge"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
    - key: kubernetes.io/arch
      operator: In
      values:
        - arm64
    - key: arch-spread
      operator: In
      values:
      - "1"
      - "2"
  taints:
  - key: "dedicated"
    effect: NoSchedule
    value: "arm64"
  kubeletConfiguration:
    containerRuntime: containerd
    evictionMaxPodGracePeriod: 60
    maxPods: 30
  limits:
    resources:
      cpu: "20"
  providerRef:
    name: arm64-workload
  consolidation:
    enabled: true
  ttlSecondsUntilExpired: 604800
```

And the Statefulsets:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: buildkitd
    app.kubernetes.io/instance: infra-jenkins
    app.kubernetes.io/name: buildkitd
    argocd.argoproj.io/instance: infra-jenkins
    helm.sh/chart: buildkitd-0.0.1
  name: buildkitd
  namespace: infra-tools
spec:
  podManagementPolicy: Parallel
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: buildkitd
      app.kubernetes.io/instance: infra-jenkins
      app.kubernetes.io/name: buildkitd
  serviceName: buildkitd
  template:
    metadata:
      labels:
        app.kubernetes.io/component: buildkitd
        app.kubernetes.io/instance: infra-jenkins
        app.kubernetes.io/name: buildkitd
        helm.sh/chart: buildkitd-0.0.1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64
                      - amd64
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - image: moby/buildkit:v0.11.5@sha256:ca34989052fc2467dcd283d2000c2ad8c7cd6213c5ff0fcabef1a9cfb0651b3a
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          name: buildkitd
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          resources:
            limits:
              memory: 4Gi
            requests:
              cpu: 200m
              memory: 512Mi
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/buildkit
              name: buildkitd-data
            - mountPath: /etc/buildkit
              name: conf
      tolerations:
        - effect: NoSchedule
          key: dedicated
          value: arm64
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: buildkitd
              app.kubernetes.io/instance: infra-jenkins
              app.kubernetes.io/name: buildkitd
          maxSkew: 1
          minDomains: 2
          nodeTaintsPolicy: Honor
          topologyKey: arch-spread
          whenUnsatisfiable: DoNotSchedule
      volumes:
        - configMap:
            name: buildkitd-conf
          name: conf
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        labels:
          app.kubernetes.io/component: buildkitd
          app.kubernetes.io/instance: infra-jenkins
          app.kubernetes.io/name: buildkitd
          helm.sh/chart: buildkitd-0.0.1
        name: buildkitd-data
        namespace: infra-tools
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 32Gi
```
