### ISSUE TITLE
MutatingWebhookConfiguration Failing on Not Found Error

### ISSUE THREAD

**Issue by seanocca** [aws/karpenter#4016]
### Version

__Karpenter Version:__ v0.27.2

__Kubernetes Version:__ v1.24.13-eks-0a21954

### Expected Behavior

Not receiving the "not found" error in the logs for a mutatingwebhookconfiguration when it is ending with .aws instead of .io. 
Actual webhook name `defaulting.webhook.karpenter.k8s.aws`
Searching for `defaulting.webhook.karpenter.sh`

### Actual Behavior

Receiving Error in logs
`"error retrieving webhook: mutatingwebhookconfiguration.admissionregistration.k8s.io \"defaulting.webhook.karpenter.sh\" not found"`

### Steps to Reproduce the Problem

Deploy above version to AWS EKS using ArgoCD and let it populate all data

### Resource Specs and Logs

```
karpenter:
  nameOverride: ""
  fullnameOverride: ""
  additionalLabels: {}

  additionalAnnotations: {}
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  additionalClusterRoleRules: []
  serviceMonitor:
    enabled: false
    additionalLabels: {}
    endpointConfig: {}
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  podLabels: {}
  podAnnotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
    karpenter.sh/do-not-evict: "true"
  podDisruptionBudget:
    name: karpenter
    maxUnavailable: 1
  podSecurityContext:
    fsGroup: 1000
  priorityClassName: system-node-critical
  terminationGracePeriodSeconds:
  hostNetwork: false
  dnsPolicy: Default
  dnsConfig: {}
  nodeSelector:
    kubernetes.io/os: linux
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: karpenter.sh/provisioner-name
                operator: DoesNotExist
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  extraVolumes: []
  extraObjects: []

  controller:
    image:
      repository: public.ecr.aws/karpenter/controller
      tag: v0.27.2
    securityContext: {}
    env:
      - name: ENABLE_PROFILING
        value: "true"
    envFrom: []
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1Gi
    outputPaths:
      - stdout
    errorOutputPaths:
      - stderr
    logLevel: ""
    logEncoding: ""
    extraVolumeMounts: []
    sidecarContainer: []
    sidecarVolumeMounts: []
    metrics:
      port: 8080
    healthProbe:
      port: 8081
  webhook:
    logLevel: error
    port: 8443
  logLevel: debug
  logEncoding: console
  settings:
    batchMaxDuration: 10s
    batchIdleDuration: 1s
    aws:
      clusterName: "XXXXXXX"
      clusterEndpoint: ""
      defaultInstanceProfile: "XXXXXXXX"
      enablePodENI: false
      enableENILimitedPodDensity: true
      isolatedVPC: false
      nodeNameConvention: "ip-name"
      vmMemoryOverheadPercent: 0.075
      interruptionQueueName: ""
templates
      tags:
    featureGates:
      driftEnabled: false
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
