### ISSUE TITLE
Add "attribute" labels

### ISSUE THREAD

**Issue by jeremysprofile** [aws/karpenter#4043]
### Tell us about your request

I would like to be able to use
```yaml
nodeSelector:
    karpenter.k8s.aws/instance-attributes: "n"
```
to schedule a pod on a `n`etwork-optimized instance. (The "attribute" is the part after the instance category and generation, https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html#instance-type-names .)

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Most of my services are not network constrained, but some (Kafka) need a lot. I would like to schedule Kafka nodes on instances with high network bandwidth. I am not concerned about other pods being scheduled on those instances using some of that network - my other pods are not very network hungry.

### Are you currently working around this issue?

I can use 
```yaml
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node.kubernetes.io/instance-type
            operator: In
            values:
            - m5n.8xlarge
            - ...
            - r5n.8xlarge
            - r5n.16xlarge
            - r6in.8xlarge
            - ...
```
Though this requires me to list many options and look up the network bandwidth myself.

I could also use `karpenter.k8s.aws/instance-network-bandwidth`, but I can't do at-least matching, so I would have to specify every possible option that AWS has that is above my floor desired bandwidth.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jeremysprofile** [comment]
> I could also use karpenter.k8s.aws/instance-network-bandwidth, but I can't do at-least matching, so I would have to specify every possible option that AWS has that is above my floor desired bandwidth.

I was mistaken, you can do at-least matching with something like
```yaml
affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: karpenter.k8s.aws/instance-network-bandwidth
            operator: gt
            values:
            - 24999
```

This solves my issue. Apologies for not reading documentation well enough.
