### ISSUE TITLE
Upgrading CRD's with Helm Chart from non-source Chart

### ISSUE THREAD

**Issue by seanocca** [aws/karpenter#4083]
### Is an existing page relevant?

https://karpenter.sh/docs/upgrade-guide/#custom-resource-definition-crd-upgrades

### What karpenter features are relevant?

In the documentation it notes that you cannot upgrade the CRD via the source helm chart. But can you upgrade the CRD's via the CRD helm chart?
We use ArgoCD and it would be great if I could create a deployment that can upgrade the CRD's using that workflow. But there is little clarity around if that's possible because all examples just use the standard kubectl apply command

### How should the docs be improved?

Greater clarification around CRD upgrade with the CRD helm chart. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by seanocca** [comment]
We are also looking to deploy the CRD chart in ArgoCD as a secondary dependency on the same Argo chart. This creates a conflict but it looks like the CRD chart updates the CRD anyway

Chart.yaml file

```
apiVersion: v1
appVersion: "1.0"
description: "helm chart for Karpenter deployment"
name: karpenter
version: 0.27.5

dependencies:
  - name: karpenter
    version: v0.27.5
    repository: oci://public.ecr.aws/karpenter
  - name: karpenter-crd
    version: v0.27.5
    repository: oci://public.ecr.aws/karpenter
```
