### ISSUE TITLE
Missing support to pass cloud-provider via userData to Bottlerocket nodes

### ISSUE THREAD

**Issue by mrpentrexyl** [aws/karpenter#4118]
### Description

**Observed Behavior**:

Not possible to pass cloud-provider to settings.kubernetes via userData, because it is not listed in 
https://github.com/aws/karpenter/blob/main/pkg/providers/amifamily/bootstrap/bottlerocketsettings.go#L45

Why this is needed ? 
Bottlerocket nodes tend to intermittently stuck in boot due to https://github.com/bottlerocket-os/bottlerocket/pull/3214

Suggested workaround is to inject cloud-provider = "aws" to settings.kubernetes via userData.

**Expected Behavior**:

being able to inject to bottlerocket nodes cloud-provider = "aws"

**Reproduction Steps** (Please include YAML):

```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: {{ $type }}
spec:
  amiFamily: Bottlerocket
  tags:
    aws-node-termination-handler/managed/{{ $clusterName }}: "true"
  subnetSelector:
    karpenter.sh/discovery: {{ $clusterName }}
  securityGroupSelector:
    karpenter.sh/discovery: {{ $clusterName }}
  userData:  |
    [settings.kubernetes]  
    cloud-provider = "aws" <------- This is what is important to inject else bottlerocket instances intermittently get stuck in booting.
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        volumeSize: 2Gi
        iops: 3000
        throughput: 125
        deleteOnTermination: true
    - deviceName: /dev/xvdb
      ebs:
        volumeType: gp3
        volumeSize: {{ $volumeSize }}
        iops: 3000
        throughput: 125
        deleteOnTermination: true
```

**Versions**:
- Chart Version: 
- Kubernetes Version (`kubectl version`):
