### ISSUE TITLE
Could not trigger the scale up - Incompatible provisioner

### ISSUE THREAD

**Issue by npandeya** [aws/karpenter#4132]
### Description

**Observed Behavior**:  controller.provisioner	Could not schedule pod, incompatible with provisioner "default",

**Expected Behavior**: Karpenter controller would scale the node according to the provisioner and schedule the pending pods in the node

**Reproduction Steps** (Please include YAML):
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 30 # mutually exclusive with consolidation
  
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: "my-cluster"
  securityGroupSelector:
    karpenter.sh/discovery: "my cluster"
  amiFamily: Bottlerocket
```

Note: Karpenter finds all the subnets and security groups successfully and it also discovers the instance types. 
Since the EKS is private, it cannot reach the pricing api.

**Versions**: Karpenter image 0.28.0
- Chart Version: 0.28.1
- Kubernetes Version (`kubectl version`): 1.22

ERROR LOGS FROM THE TIME KARPENTER CONTROLLER 
`2023-06-26T12:59:06.175Z	DEBUG	controller.provisioner	relaxing soft constraints for pod since it previously failed to schedule, removing: spec.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0]={"weight":100,"preference":{"matchExpressions":[{"key":"hub.jupyter.org/node-purpose","operator":"In","values":["core"]}]}}	{"commit": "26e2d35-dirty", "pod": "jupyterhub/hub-58ddddcd6d-9bvv5"}
2023-06-26T12:59:06.488Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "default", daemonset overhead={"cpu":"275m","memory":"360Mi","pods":"8","vpc.amazonaws.com/pod-eni":"3"}, no instance type satisfied resources {"cpu":"275m","memory":"360Mi","pods":"9","vpc.amazonaws.com/pod-eni":"4"} and requirements kubernetes.io/arch In [amd64], karpenter.sh/capacity-type In [on-demand], karpenter.sh/provisioner-name In [default], topology.kubernetes.io/zone In [us-east-1b], karpenter.k8s.aws/instance-category In [c m r], karpenter.k8s.aws/instance-generation Exists >2, kubernetes.io/os In [linux] (no instance type has enough resources)	{"commit": "26e2d35-dirty", "pod": "jupyterhub/hub-58ddddcd6d-wdjvz"}`
