### ISSUE TITLE
Change Object Type in Docs on Disable Node Consolidation 

### ISSUE THREAD

**Issue by vinayan3** [aws/karpenter#4144]
### Description

**How can the docs be improved?**
The [docs](https://karpenter.sh/v0.28/concepts/deprovisioning/#node-consolidation) say this
```
apiVersion: karpenter.sh/v1alpha5
kind: Node
metadata:
  annotations:
    karpenter.sh/do-not-consolidate: "true"
```
The code on the other hand points to the `Machine` object type see: 

https://github.com/aws/karpenter-core/blob/1e88464e98f16955c410e9bab1f1dd2a08b2983b/pkg/controllers/deprovisioning/consolidation.go#L88

https://github.com/aws/karpenter-core/blob/main/pkg/controllers/state/statenode.go#L138-L151

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
