### ISSUE TITLE
Karpenter pods never ready with hostNetwork: true 

### ISSUE THREAD

**Issue by rarecrumb** [aws/karpenter#4145]
### Description

**Observed Behavior**: 

Updating from v0.25.0 to v0.28.0 is not successful

Setting `hostNetwork: true` makes the karpenter pods never become ready

**Expected Behavior**: Should be good

When running Calico, is `hostNetwork: true` all thats needed?

**Reproduction Steps** (Please include YAML):
```yaml
      karpenter:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: karpenter.sh/provisioner-name
                      operator: Exists
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
        controller:
          hostNetwork: true
        nodeSelector:
          kubernetes.io/arch: arm64
        tolerations:
        - key: kubernetes.io/arch
          operator: Equal
          value: arm64
          effect: NoSchedule        
        settings:
          aws:
            clusterName: mine
            clusterEndpoint: mine
            defaultInstanceProfile: mine
            interruptionQueueName: mine
          featureGates:
            driftEnabled: true
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::mine:role/karpenter-controller
```

**Versions**:
- Chart Version: 0.28.0
- Kubernetes Version (`kubectl version`): Major:"1", Minor:"24+", GitVersion:"v1.24.14-eks-c12679a", GitCommit:"05d192f0de17608d98e17761ad3cffa9a6407f2f"

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
