### ISSUE TITLE
Unschedulable pod

### ISSUE THREAD

**Issue by astropanic** [aws/karpenter#4192]
### Description

**Observed Behavior**:
```
k get pod -n xxx xxx -o yaml | yq .status

conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-07-03T13:15:10Z"
    message: '0/19 nodes are available: 1 node(s) had volume node affinity conflict, 14 Insufficient memory, 17 Insufficient cpu. preemption: 0/19 nodes are available: 1 Preemption is not helpful for scheduling, 18 No preemption victims found for incoming pod.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
phase: Pending
qosClass: Burstable

k get pod -n xxx xxx

NAME        READY   STATUS    RESTARTS   AGE
xxx         0/1     Pending   0          76m


k stern -n karpenter "karpenter*"

karpenter-f8c94f455-w6gw5 controller 2023-07-03T14:50:21.685Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "default", no instance type satisfied resources {"cpu":"2","memory":"6Gi","pods":"1"} and requirements topology.kubernetes.io/zone DoesNotExist, karpenter.k8s.aws/instance-generation Exists >2, karpenter.sh/capacity-type In [on-demand spot], karpenter.sh/provisioner-name In [default], kubernetes.io/os In [linux], kubernetes.io/arch In [amd64], karpenter.k8s.aws/instance-category In [c m r] (no instance type met the scheduling requirements or had a required offering)	{"commit": "698f22f-dirty", "pod": "xxx/xxx"}
karpenter-f8c94f455-w6gw5 controller 2023-07-03T14:50:31.686Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "default", no instance type satisfied resources {"cpu":"2","memory":"6Gi","pods":"1"} and requirements karpenter.k8s.aws/instance-category In [c m r], karpenter.k8s.aws/instance-generation Exists >2, karpenter.sh/provisioner-name In [default], karpenter.sh/capacity-type In [on-demand spot], kubernetes.io/os In [linux], topology.kubernetes.io/zone DoesNotExist, kubernetes.io/arch In [amd64] (no instance type met the scheduling requirements or had a required offering)	{"commit": "698f22f-dirty", "pod": "xxx/xxx"}
karpenter-f8c94f455-w6gw5 controller 2023-07-03T14:50:41.685Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "default", no instance type satisfied resources {"cpu":"2","memory":"6Gi","pods":"1"} and requirements kubernetes.io/arch In [amd64], karpenter.k8s.aws/instance-category In [c m r], karpenter.k8s.aws/instance-generation Exists >2, karpenter.sh/capacity-type In [on-demand spot], topology.kubernetes.io/zone DoesNotExist, karpenter.sh/provisioner-name In [default], kubernetes.io/os In [linux] (no instance type met the scheduling requirements or had a required offering)	{"commit": "698f22f-dirty", "pod": "xxx/xxx"}
karpenter-f8c94f455-w6gw5 controller 2023-07-03T14:50:51.686Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "default", no instance type satisfied resources {"cpu":"2","memory":"6Gi","pods":"1"} and requirements kubernetes.io/os In [linux], kubernetes.io/arch In [amd64], karpenter.k8s.aws/instance-category In [c m r], karpenter.k8s.aws/instance-generation Exists >2, karpenter.sh/capacity-type In [on-demand spot], topology.kubernetes.io/zone DoesNotExist, karpenter.sh/provisioner-name In [default] (no instance type met the scheduling requirements or had a required offering)	{"commit": "698f22f-dirty", "pod": "xxx/xxx"}
karpenter-f8c94f455-w6gw5 controller 2023-07-03T14:51:01.830Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "default", no instance type satisfied resources {"cpu":"2","memory":"6Gi","pods":"1"} and requirements kubernetes.io/os In [linux], karpenter.sh/provisioner-name In [default], kubernetes.io/arch In [amd64], karpenter.k8s.aws/instance-category In [c m r], karpenter.k8s.aws/instance-generation Exists >2, topology.kubernetes.io/zone DoesNotExist, karpenter.sh/capacity-type In [on-demand spot] (no instance type met the scheduling requirements or had a required offering)	{"commit": "698f22f-dirty", "pod": "xxx/xxx"}
karpenter-f8c94f455-w6gw5 controller 2023-07-03T14:51:11.686Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "default", no instance type satisfied resources {"cpu":"2","memory":"6Gi","pods":"1"} and requirements karpenter.k8s.aws/instance-generation Exists >2, topology.kubernetes.io/zone DoesNotExist, karpenter.sh/provisioner-name In [default], karpenter.sh/capacity-type In [on-demand spot], kubernetes.io/os In [linux], kubernetes.io/arch In [amd64], karpenter.k8s.aws/instance-category In [c m r] (no instance type met the scheduling requirements or had a required offering)	{"commit": "698f22f-dirty", "pod": "xxx/xxx"}


```

**Expected Behavior**:

```
k get pod -n xxx xxx

NAME        READY   STATUS    RESTARTS   AGE
xxx         1/1     Running   0          21h

```

**Reproduction Steps** (Please include YAML):

```
# pod.yaml

apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  labels:
    app: xxx
    controller-revision-hash: xxx-6bb85dbbd
    statefulset.kubernetes.io/pod-name: xxx
  name: xxx
  namespace: xxx
spec:
  containers:
  - env:
    - name: KUBERNETES_NODE
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: KUBERNETES_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: JAVA_OPTS
      value: -Djenkins.install.runSetupWizard=false -Xms2g -Xmx4g -Djava.io.tmpdir=/var/jenkins_tmp
    - name: JENKINS_OPTS
      value: --sessionTimeout=10080 --sessionEviction=43200
    image: xxx.dkr.ecr.eu-central-1.amazonaws.com/xxx:xxx
    livenessProbe:
      failureThreshold: 30
      httpGet:
        path: /login
        port: 8080
      initialDelaySeconds: 210
      timeoutSeconds: 60
    name: xxx
    ports:
    - containerPort: 8080
    readinessProbe:
      failureThreshold: 5
      httpGet:
        path: /login
        port: 8080
      initialDelaySeconds: 30
      timeoutSeconds: 10
    resources:
      limits:
        cpu: "4"
        memory: 10Gi
      requests:
        cpu: "2"
        memory: 6Gi
    securityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 1001
      runAsUser: 1001
    volumeMounts:
    - mountPath: /www/transfer
      name: transfer
    - mountPath: /var/jenkins_home
      name: jenkins-home
    - mountPath: /var/jenkins_tmp
      name: jenkins-tmp
    - mountPath: /var/cache/rakuten
      name: rakuten-feed-download-cache
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2f48m
      readOnly: true
  hostname: xxx
  imagePullSecrets:
  - name: xxx
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  securityContext:
    fsGroup: 1001
    runAsGroup: 1001
    runAsUser: 1001
  serviceAccountName: default
  subdomain: xxx
  terminationGracePeriodSeconds: 60
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: transfer
    persistentVolumeClaim:
      claimName: ftp-efs-claim
  - name: jenkins-home
    persistentVolumeClaim:
      claimName: xxx-workspace
  - name: jenkins-tmp
    persistentVolumeClaim:
      claimName: xxx-tmp
  - name: xxx-feed-download-cache
    persistentVolumeClaim:
      claimName: rakuten-feed-download-cache
  - name: kube-api-access-2f48m
    projected:
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.namespace
            path: namespace
---
#provisioner.yml

apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  limits:
    resources:
      cpu: 1k
  providerRef:
    name: default
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
    - on-demand
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values:
    - c
    - m
    - r
  - key: karpenter.k8s.aws/instance-generation
    operator: Gt
    values:
    - "2"
  ttlSecondsAfterEmpty: 30
```

**Versions**:
- Chart Version: `karpenter-v0.27.5`
- Kubernetes Version (`kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.14-eks-c12679a", GitCommit:"05d192f0de17608d98e17761ad3cffa9a6407f2f", GitTreeState:"clean", BuildDate:"2023-05-22T23:41:27Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
``` 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Can you look at the persistent volumes that are to be bound to this pod and see what the zonal affinities are on them?  I suspect one of your volumes wants to be in a zone that the provisioner can't provision to.

**Comment by astropanic** [comment]
Maybe the error messages are too generic. I have a really hard time to understand what the problem is.
Here are the volume specs regarding `nodeAffinity`:

```
k get pv -n xxx $i -o yaml | yq .spec.nodeAffinity

null
required:
  nodeSelectorTerms:
    - matchExpressions:
        - key: topology.ebs.csi.aws.com/zone
          operator: In
          values:
            - eu-central-1c
required:
  nodeSelectorTerms:
    - matchExpressions:
        - key: topology.ebs.csi.aws.com/zone
          operator: In
          values:
            - eu-central-1a
required:
  nodeSelectorTerms:
    - matchExpressions:
        - key: topology.ebs.csi.aws.com/zone
          operator: In
          values:
            - eu-central-1a
 ```
