### ISSUE TITLE
Add InstanceMetadataTags option in awsnodetemplates.karpenter.k8s.aws metadataOptions

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [aws/karpenter#4199]
### Description

**What problem are you trying to solve?**
I would like to enable querying metadata tags from aws metadata.
```
curl http://169.254.169.254/latest/meta-data/tags/instance/Name
```
To be able to do that, we need to set InstanceMetadataTags to true in ec2 instance metadataoptions.

karpenter code right now supports 4 metadataoptions:
- httpEndpoint
- httpProtocolIPv6
- httpPutResponseHopLimit
- httpTokens

Would it be possible to add instanceMetadaTags option ? Thanks

The main goal of this is to be able if a pod is running in a spot instance or on-demmand. Maybe there is an easier way to find out, but I couldn't find it.

**How important is this feature to you?**

This will allow us to define diferent stop lifecycles in our pods, based on node type [Spot|On demmand]

---
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by marcportabellaclotet-mt** [comment]
I find a really easy way to achieve this.
```
 http://169.254.169.254/latest/meta-data/instane-cycle
```
However, the requested feature may be interesting for other needs.

Thanks

**Comment by Nuru** [comment]
@marcportabellaclotet-mt I need this exact feature and your solution does not work for me. Would you please reopen this issue so I do not have to create a duplicate?

**Comment by marcportabellaclotet-mt** [comment]
@Nuru , it may not work because you need first to get the token. Here is an example lifecycle preStop which works out of the box...

``` 
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - |-
                export TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600") && \
                export INSTANCE_TYPE=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/instance-life-cycle) && \
                if [ "${INSTANCE_TYPE}" == "spot" ]; then sleep 90; else sleep 15; fi
```
