### ISSUE TITLE
Dynamic instance tagging (from node labels)

### ISSUE THREAD

**Issue by cebernardi** [aws/karpenter#4228]
### Description

**What problem are you trying to solve?**

We have a Provisioner that is configured to launch instances both in arm64 and amd64. 
We would like to dynamically tag the ec2 instances with the architecture.

Karpenter tags the instances with a default set of "dynamic" tags, described at the beginning of this documentation section: https://karpenter.sh/docs/concepts/node-templates/#spectags

```
Name: karpenter.sh/provisioner-name/<provisioner-name>
karpenter.sh/provisioner-name: <provisioner-name>
kubernetes.io/cluster/<cluster-name>: owned
```

All the rest of tagging options, are static ([here](https://karpenter.sh/docs/concepts/node-templates/#spectags) and [here](https://karpenter.sh/docs/concepts/settings/#configmap)).

We would like to have a way to specify dynamic tags, for example:
```
spec:
  tags:
    InternalAccountingTag: 1234
    dev.corp.net/app: Calculator
  tagsFromLabels:
  - kubernetes.io/arch
  - node.kubernetes.io/instance-type
```

it could be also something like:

```
spec:
  tags:
    InternalAccountingTag: 1234
    dev.corp.net/app: Calculator
    arch: "{kubernetes.io/arch}"
    instance-type: "node.kubernetes.io/instance-type"
```

while `InternalAccountingTag` and `dev.corp.net/app` are "static" tags, `kubernetes.io/arch` and `node.kubernetes.io/instance-type` are known labels, that could be used as tags as well. 

**How important is this feature to you?**
It would enable closer monitoring of costs and migrations, which are blocked now, or possible with workarounds.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
