### ISSUE TITLE
Karpenter pod keep restarting

### ISSUE THREAD

**Issue by xshot9011** [aws/karpenter#4275]
### Description

**Observed Behavior**:

Karpenter controller pod keep restarting

<img width="1127" alt="image" src="https://github.com/aws/karpenter/assets/40098197/2c28575e-8d65-43d2-a949-d0a4c5836f6e">

Role's permissions are the same in https://karpenter.sh/preview/getting-started/migrating-from-cas/

I try to change the name of cluster to non-exist one and there's nothing change from the karpenter's log
<img width="1153" alt="image" src="https://github.com/aws/karpenter/assets/40098197/79a6f844-36e2-42cb-86e8-2e87b414a8b3">

```bash
2023-07-17T03:04:02.579Z	DEBUG	Successfully created the logger.
2023-07-17T03:04:02.579Z	DEBUG	Logging level set to: debug
panic: validating settings, Key: 'Settings.ClusterName' Error:Field validation for 'ClusterName' failed on the 'required' tag

goroutine 1 [running]:
github.com/samber/lo.must({0x24f9700, 0xc00086eb20}, {0x0, 0x0, 0x0})
	github.com/samber/lo@v1.38.1/errors.go:53 +0x1f4
github.com/samber/lo.Must[...](...)
	github.com/samber/lo@v1.38.1/errors.go:65
github.com/aws/karpenter-core/pkg/operator/injection.WithSettingsOrDie({0x2e98118, 0xc00095fb60}, {0x2eb94f8, 0xc000848600}, {0xc0009df9a0, 0x2, 0x0?})
	github.com/aws/karpenter-core@v0.29.0/pkg/operator/injection/injection.go:93 +0x1b0
github.com/aws/karpenter-core/pkg/operator.NewOperator()
	github.com/aws/karpenter-core@v0.29.0/pkg/operator/operator.go:105 +0x61e
main.main()
	github.com/aws/karpenter/cmd/controller/main.go:33 +0x2e
```

**Expected Behavior**:

Karpenter application start successfully

**Reproduction Steps** (Please include YAML):

```
export HELM_EXPERIMENTAL_OCI=1
helm repo add karpenter oci://public.ecr.aws/karpenter/karpenter
helm repo update
mkdir charts
helm pull --destination charts --version "v0.29.0" oci://public.ecr.aws/karpenter/karpenter
helm upgrade --install karpenter . \
  --namespace karpenter \
  --create-namespace \
  -f values-dev.yaml
```

- Content of file `values-dev.yaml`

```yaml
# -- Overrides the chart's name.
nameOverride: ""
# -- Overrides the chart's computed fullname.
fullnameOverride: ""
# -- Additional labels to add into metadata.
additionalLabels: {}
# app: karpenter

# -- Additional annotations to add into metadata.
additionalAnnotations: {}
# -- Image pull policy for Docker images.
imagePullPolicy: IfNotPresent
# -- Image pull secrets for Docker images.
imagePullSecrets: []
serviceAccount:
  # -- Specifies if a ServiceAccount should be created.
  create: true
  # -- The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""
  # -- Additional annotations for the ServiceAccount.
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::xxx:role/xxx-controller-role"
# -- Specifies additional rules for the core ClusterRole.
additionalClusterRoleRules: []
serviceMonitor:
  # -- Specifies whether a ServiceMonitor should be created.
  enabled: false
  # -- Additional labels for the ServiceMonitor.
  additionalLabels: {}
  # -- Endpoint configuration for the ServiceMonitor.
  endpointConfig: {}
# -- Number of replicas.
replicas: 2
# -- The number of old ReplicaSets to retain to allow rollback.
revisionHistoryLimit: 10
# -- Strategy for updating the pod.
strategy:
  rollingUpdate:
    maxUnavailable: 1
# -- Additional labels for the pod.
podLabels: {}
# -- Additional annotations for the pod.
podAnnotations: {}
podDisruptionBudget:
  name: karpenter
  maxUnavailable: 1
# -- SecurityContext for the pod.
podSecurityContext:
  fsGroup: 1000
# -- PriorityClass name for the pod.
priorityClassName: system-cluster-critical
# -- Override the default termination grace period for the pod.
terminationGracePeriodSeconds:
# -- Bind the pod to the host network.
# This is required when using a custom CNI.
hostNetwork: false
# -- Configure the DNS Policy for the pod
dnsPolicy: Default
# -- Configure DNS Config for the pod
dnsConfig: {}
#  options:
#    - name: ndots
#      value: "1"
# -- Node selectors to schedule the pod to nodes with labels.
nodeSelector:
  kubernetes.io/os: linux
# -- Affinity rules for scheduling the pod. If an explicit label selector is not provided for pod affinity or pod anti-affinity one will be created from the pod selector labels.
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: karpenter.sh/provisioner-name
              operator: DoesNotExist
  #       - matchExpressions:
  #           - key: eks.amazonaws.com/nodegroup
  #             operator: In
  #             values:
  #               - xxx-private-nodegroup
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"
# -- Topology spread constraints to increase the controller resilience by distributing pods across the cluster zones. If an explicit label selector is not provided one will be created from the pod selector labels.
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
# -- Tolerations to allow the pod to be scheduled to nodes with taints.
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
# -- Additional volumes for the pod.
extraVolumes: []
# - name: aws-iam-token
#   projected:
#     defaultMode: 420
#     sources:
#     - serviceAccountToken:
#         audience: sts.amazonaws.com
#         expirationSeconds: 86400
#         path: token
controller:
  image:
    # -- Repository path to the controller image.
    repository: public.ecr.aws/karpenter/controller
    # -- Tag of the controller image.
    tag: v0.29.0
    # -- SHA256 digest of the controller image.
    digest: sha256:3009f10487d9338f77c325adee3c208513cd06c7f191653327ef3a44006bf9c8
  # -- SecurityContext for the controller container.
  securityContext: {}
  # -- Additional environment variables for the controller pod.
  env: []
  # - name: AWS_REGION
  #   value: eu-west-1
  envFrom: []
  # -- Resources for the controller pod.
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #  requests:
  #    cpu: 1
  #    memory: 1Gi
  #  limits:
  #    cpu: 1
  #    memory: 1Gi

  # -- Controller outputPaths - default to stdout only
  outputPaths:
    - stdout
  # -- Controller errorOutputPaths - default to stderr only
  errorOutputPaths:
    - stderr
  # -- Controller log level, defaults to the global log level
  logLevel: ""
  # -- Controller log encoding, defaults to the global log encoding
  logEncoding: ""
  # -- Additional volumeMounts for the controller pod.
  extraVolumeMounts: []
  # - name: aws-iam-token
  #   mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
  #   readOnly: true
  # -- Additional sidecarContainer config
  sidecarContainer: []
  # -- Additional volumeMounts for the sidecar - this will be added to the volume mounts on top of extraVolumeMounts
  sidecarVolumeMounts: []
  metrics:
    # -- The container port to use for metrics.
    port: 8000
  healthProbe:
    # -- The container port to use for http health probe.
    port: 8081
webhook:
  logLevel: error
  # -- The container port to use for the webhook.
  port: 8443
# -- Global log level
logLevel: debug
# -- Global log encoding
logEncoding: console
# -- Global Settings to configure Karpenter
settings:
  # -- The maximum length of a batch window. The longer this is, the more pods we can consider for provisioning at one
  # time which usually results in fewer but larger nodes.
  batchMaxDuration: 10s
  # -- The maximum amount of time with no new ending pods that if exceeded ends the current batching window. If pods arrive
  # faster than this time, the batching window will be extended up to the maxDuration. If they arrive slower, the pods
  # will be batched separately.
  batchIdleDuration: 1s
  # -- AWS-specific configuration values
  aws:
    # -- Cluster name.
    clusterName: xxxx-xxx-xxxxx-cluster
    # -- Cluster endpoint. If not set, will be discovered during startup (EKS only)
    clusterEndpoint: "https://abcd.efgh.ijkl.eks.amazonaws.com"
    # clusterEndpoint: ""
    # -- The default instance profile to use when launching nodes
    defaultInstanceProfile: "mkdd-karpenter-node-role"
    # -- If true then instances that support pod ENI will report a vpc.amazonaws.com/pod-eni resource
    enablePodENI: false
    # -- Indicates whether new nodes should use ENI-based pod density
    # DEPRECATED: Use `.spec.kubeletConfiguration.maxPods` to set pod density on a per-provisioner basis
    enableENILimitedPodDensity: true
    # -- If true then assume we can't reach AWS services which don't have a VPC endpoint
    # This also has the effect of disabling look-ups to the AWS pricing endpoint
    isolatedVPC: false
    # -- The VM memory overhead as a percent that will be subtracted from the total memory for all instance types
    vmMemoryOverheadPercent: 0.075
    # -- interruptionQueueName is disabled if not specified. Enabling interruption handling may
    # require additional permissions on the controller service account. Additional permissions are outlined in the docs.
    interruptionQueueName: ""
    # -- The global tags to use on all AWS infrastructure resources (launch templates, instances, etc.) across node templates
    tags:
  # -- Feature Gate configuration values. Feature Gates will follow the same graduation process and requirements as feature gates
  # in Kubernetes. More information here https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features
  featureGates:
    # -- driftEnabled is in ALPHA and is disabled by default.
    # Setting driftEnabled to true enables the drift deprovisioner to watch for drift between currently deployed nodes
    # and the desired state of nodes set in provisioners and node templates
    driftEnabled: false

```

**Versions**:
- Chart Version: v0.29.0
- Kubernetes Version (`kubectl version`): 
```bash
version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14", GitCommit:"3321ffc07d2f046afdf613796f9032f4460de093", GitTreeState:"clean", BuildDate:"2022-11-09T13:40:19Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"darwin/amd64"}
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
In the migrating guide, helm install looks like below:
```
helm template karpenter oci://public.ecr.aws/karpenter/karpenter --version ${KARPENTER_VERSION} --namespace karpenter \
    --set settings.aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${CLUSTER_NAME} \
    --set settings.aws.clusterName=${CLUSTER_NAME} \
    --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT_ID}:role/KarpenterControllerRole-${CLUSTER_NAME}" \
    --set controller.resources.requests.cpu=1 \
    --set controller.resources.requests.memory=1Gi \
    --set controller.resources.limits.cpu=1 \
    --set controller.resources.limits.memory=1Gi > karpenter.yaml
```
You need to make sure you set: ` --set settings.aws.clusterName=${CLUSTER_NAME} ` in your the helm install

**Comment by engedaam** [comment]
Actually my mistake, you are setting it in your values. Are you seeing `settings.aws.clusterName` being propagated back to you `karpenter-global-settings` ConfigMap?

**Comment by xshot9011** [comment]
Hi @engedaam , I just checked the `karpenter-global-settings` cm which no clusterName inside
<img width="797" alt="image" src="https://github.com/aws/karpenter/assets/40098197/a435e44a-f830-47a7-88bc-5f0862263d95">

**Comment by xshot9011** [comment]
@engedaam  if I use following command and check the rendered manifest, the pod start successfully
```bash
helm template karpenter oci://public.ecr.aws/karpenter/karpenter --version v0.29.0 --namespace karpenter \
    --set settings.aws.defaultInstanceProfile=mkdd-karpenter-node-role \
    --set settings.aws.clusterName=xxxx-xxx-xxxx-cluster \
    --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:aws:iam::xxx:role/xxx-xxx-xxx-xxx-karpenter-controller-role" > karpenter.yaml
kubectl apply -f karpenter.yaml
```
<img width="1246" alt="image" src="https://github.com/aws/karpenter/assets/40098197/d2b88190-52ea-4803-9213-fe3fa57fcfb0">


But if I used this command, it's failed
```bash
export HELM_EXPERIMENTAL_OCI=1
helm repo add karpenter oci://public.ecr.aws/karpenter/karpenter
helm repo update
mkdir charts
helm pull --destination charts --version "v0.29.0" oci://public.ecr.aws/karpenter/karpenter
helm upgrade --install karpenter . \
  --namespace karpenter \
  --create-namespace \
  -f values-dev.yaml
```

The configmap is empty and the karpenter will keep restarting

---

I used a dry run to obtain the manifest file from both the command line and compared the results. As expected, the outcome matches the previous one.

<img width="1503" alt="image" src="https://github.com/aws/karpenter/assets/40098197/e69584aa-b119-4f54-bdba-be99d67778da">

Could this be related to the Helm version

```bash
helm version
version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.5"}
```

**Comment by jonathan-innis** [comment]
It's possibly a helm issue but it doesn't look to be a Karpenter issue. I tried the same commands as you and wasn't able to repro what you are seeing

```console
➜  karpenter git:(main) ✗ helm version
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}

➜  karpenter git:(main) ✗ helm pull --destination charts --version "v0.29.0" oci://public.ecr.aws/karpenter/karpenter
Pulled: public.ecr.aws/karpenter/karpenter:v0.29.0
Digest: sha256:4aad65a0484f9e71519fe9c3166f3a7cb29b0b1996a115663b0026f30e828a5b

➜  karpenter git:(main) ✗ helm template karpenter charts/karpenter-v0.29.0.tgz --version v0.29.0 --namespace karpenter -f ../karpenter-testing/debug/helm-issue/values-dev.yaml | grep karpenter-global-settings -A 20
  name: karpenter-global-settings
  namespace: karpenter
  labels:
    helm.sh/chart: karpenter-v0.29.0
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/version: "0.29.0"
    app.kubernetes.io/managed-by: Helm
data:  
    "aws.clusterEndpoint": ""
    "aws.clusterName": "scale-test"
    "aws.defaultInstanceProfile": "KarpenterNodeInstanceProfile-scale-test"
    "aws.enableENILimitedPodDensity": "true"
    "aws.enablePodENI": "false"
    "aws.interruptionQueueName": ""
    "aws.isolatedVPC": "false"
    "aws.vmMemoryOverheadPercent": "0.075"
    "batchIdleDuration": "1s"
    "batchMaxDuration": "10s"
    "featureGates.driftEnabled": "false"
---
```

**Comment by xshot9011** [comment]
@jonathan-innis I ll try downgrade my helm; let's see how it's work

**Comment by jan-ludvik** [comment]
I had similar problem yesterday on fresh terraform install with helm provider. While I was setting `clusterEndpoint`, `clusterName` remained empty and pod was crashing because it is required. The only way how I made it work was to not set `clusterEndpoint` and only set `clusterName`

**Comment by njtran** [comment]
@xshot9011 any update?

**Comment by hagaimaya** [comment]
I have the same problem
I have set yaml file with
settings:
  aws:
    clusterName:  clustername
    
  but theconfigmap is empty
  apiVersion: v1
data:
  aws.assumeRoleARN: ''
  aws.assumeRoleDuration: 15m
  aws.clusterCABundle: ''
  aws.clusterEndpoint: ''
  aws.clusterName: ''

**Comment by pjastrzabek** [comment]
I just hit the same error
```
Error:Field validation for 'ClusterName' failed on
```

Indeed configmap karpenter-global-settings did not contain aws.clusterName key

But.. we are installing all internals with a gitops approach (with flux)  and we've been doing so for months now with karpenter not being touched.

In my case we deleted flux kustomization and tried to reconcile once again.
Something like this
```
flux delete helmrelease karpenter -n flux-system
flux reconcile kustomization karpenter --with-source
```
Without any other changes it worked this time.

That would indeed indicate helm bug

**Comment by edas-smith** [comment]
Running into the same issue after attempting to upgrade from version v0.32.3

**Comment by xshot9011** [comment]
I found issue that it'was related to my Chart.yaml file which I forget to create it. So when u run helm install ... something with out Chart.yaml file it won't use configured values

```sh
helm upgrade --install karpenter . \
  --namespace karpenter \
  --create-namespace \
  -f values-dev.yaml
```

Here solution::

1. Make new Chart.yaml with these following content

```yaml
apiVersion: v2
name: karpenter
description: A Helm chart for Kubernetes
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"
dependencies:
  - name: karpenter
    version: "v0.29.0"
    repository: "oci://public.ecr.aws/karpenter"
```

(2). Run `helm dependency build`; now zipped chart will get pull to chats/...

(3). Now create values files something like this `values-dev.yaml` (change ur pref name)

```yaml
provisioners:
   ... (my custom template+values)

karpenter: # THIS WILL BE MATCHED IN dependencies[0].name == "karpenter"
  # -- Overrides the chart's name.
  nameOverride: ""
  # -- Overrides the chart's computed fullname.
  fullnameOverride: ""
  # -- Additional labels to add into metadata.
  additionalLabels: {}
  # app: karpenter

  # -- Additional annotations to add into metadata.
  additionalAnnotations: {}
  # -- Image pull policy for Docker images.
  imagePullPolicy: IfNotPresent
  # -- Image pull secrets for Docker images.
  imagePullSecrets: []
  serviceAccount:
    # -- Specifies if a ServiceAccount should be created.
    create: true
    # -- The name of the ServiceAccount to use.
    # If not set and create is true, a name is generated using the fullname template.
    name: ""
    # -- Additional annotations for the ServiceAccount.
    annotations:
      eks.amazonaws.com/role-arn: "ARNANRNARNANRANRNARNARNARNARNRNARN"
  # -- Specifies additional rules for the core ClusterRole.
  additionalClusterRoleRules: []
  serviceMonitor:
    # -- Specifies whether a ServiceMonitor should be created.
    enabled: false
    # -- Additional labels for the ServiceMonitor.
    additionalLabels: {}
    # -- Endpoint configuration for the ServiceMonitor.
    endpointConfig: {}
  # -- Number of replicas.
  replicas: 2
  # -- The number of old ReplicaSets to retain to allow rollback.
  revisionHistoryLimit: 10
  # -- Strategy for updating the pod.
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  # -- Additional labels for the pod.
  podLabels: {}
  # -- Additional annotations for the pod.
  podAnnotations: {}
  podDisruptionBudget:
    name: karpenter
    maxUnavailable: 1
  # -- SecurityContext for the pod.
  podSecurityContext:
    fsGroup: 1000
  # -- PriorityClass name for the pod.
  priorityClassName: system-cluster-critical
  # -- Override the default termination grace period for the pod.
  terminationGracePeriodSeconds:
  # -- Bind the pod to the host network.
  # This is required when using a custom CNI.
  hostNetwork: false
  # -- Configure the DNS Policy for the pod
  dnsPolicy: Default
  # -- Configure DNS Config for the pod
  dnsConfig: {}
  #  options:
  #    - name: ndots
  #      value: "1"
  # -- Node selectors to schedule the pod to nodes with labels.
  nodeSelector:
    kubernetes.io/os: linux
  # -- Affinity rules for scheduling the pod. If an explicit label selector is not provided for pod affinity or pod anti-affinity one will be created from the pod selector labels.
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: karpenter.sh/provisioner-name
                operator: DoesNotExist
    #       - matchExpressions:
    #           - key: eks.amazonaws.com/nodegroup
    #             operator: In
    #             values:
    #               - ASLDKJKLSDLKASDKLASKLDKLASDJKLASDJ
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"
  # -- Topology spread constraints to increase the controller resilience by distributing pods across the cluster zones. If an explicit label selector is not provided one will be created from the pod selector labels.
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
  # -- Tolerations to allow the pod to be scheduled to nodes with taints.
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  # -- Additional volumes for the pod.
  extraVolumes: []
  # - name: aws-iam-token
  #   projected:
  #     defaultMode: 420
  #     sources:
  #     - serviceAccountToken:
  #         audience: sts.amazonaws.com
  #         expirationSeconds: 86400
  #         path: token
  controller:
    image:
      # -- Repository path to the controller image.
      repository: public.ecr.aws/karpenter/controller
      # -- Tag of the controller image.
      tag: v0.29.0
      # -- SHA256 digest of the controller image.
      digest: sha256:3009f10487d9338f77c325adee3c208513cd06c7f191653327ef3a44006bf9c8
    # -- SecurityContext for the controller container.
    securityContext: {}
    # -- Additional environment variables for the controller pod.
    env: []
    # - name: AWS_REGION
    #   value: eu-west-1
    envFrom: []
    # -- Resources for the controller pod.
    resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    #  requests:
    #    cpu: 1
    #    memory: 1Gi
    #  limits:
    #    cpu: 1
    #    memory: 1Gi

    # -- Controller outputPaths - default to stdout only
    outputPaths:
      - stdout
    # -- Controller errorOutputPaths - default to stderr only
    errorOutputPaths:
      - stderr
    # -- Controller log level, defaults to the global log level
    logLevel: ""
    # -- Controller log encoding, defaults to the global log encoding
    logEncoding: ""
    # -- Additional volumeMounts for the controller pod.
    extraVolumeMounts: []
    # - name: aws-iam-token
    #   mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
    #   readOnly: true
    # -- Additional sidecarContainer config
    sidecarContainer: []
    # -- Additional volumeMounts for the sidecar - this will be added to the volume mounts on top of extraVolumeMounts
    sidecarVolumeMounts: []
    metrics:
      # -- The container port to use for metrics.
      port: 8000
    healthProbe:
      # -- The container port to use for http health probe.
      port: 8081
  webhook:
    logLevel: error
    # -- The container port to use for the webhook.
    port: 8443
  # -- Global log level
  logLevel: debug
  # -- Global log encoding
  logEncoding: console
  # -- Global Settings to configure Karpenter
  settings:
    # -- The maximum length of a batch window. The longer this is, the more pods we can consider for provisioning at one
    # time which usually results in fewer but larger nodes.
    batchMaxDuration: 10s
    # -- The maximum amount of time with no new ending pods that if exceeded ends the current batching window. If pods arrive
    # faster than this time, the batching window will be extended up to the maxDuration. If they arrive slower, the pods
    # will be batched separately.
    batchIdleDuration: 1s
    # -- AWS-specific configuration values
    aws:
      # -- Cluster name.
      clusterName: CLUSTERNAMECLUSTERNAME
      # -- Cluster endpoint. If not set, will be discovered during startup (EKS only)
      # clusterEndpoint: "https://0BDCD51FC6D67A8ABDFB3E396C356F14.gr7.ap-southeast-1.eks.amazonaws.com"
      # clusterEndpoint: ""
      # -- The default instance profile to use when launching nodes
      defaultInstanceProfile: "ROLEROLEROLEROLEROLEROLEROLEROLEROLEROLEROLEROLE"
      # -- If true then instances that support pod ENI will report a vpc.amazonaws.com/pod-eni resource
      enablePodENI: false
      # -- Indicates whether new nodes should use ENI-based pod density
      # DEPRECATED: Use `.spec.kubeletConfiguration.maxPods` to set pod density on a per-provisioner basis
      enableENILimitedPodDensity: true
      # -- If true then assume we can't reach AWS services which don't have a VPC endpoint
      # This also has the effect of disabling look-ups to the AWS pricing endpoint
      isolatedVPC: false
      # -- The VM memory overhead as a percent that will be subtracted from the total memory for all instance types
      vmMemoryOverheadPercent: 0.075
      # -- interruptionQueueName is disabled if not specified. Enabling interruption handling may
      # require additional permissions on the controller service account. Additional permissions are outlined in the docs.
      interruptionQueueName: ""
      # -- The global tags to use on all AWS infrastructure resources (launch templates, instances, etc.) across node templates
      tags:
    # -- Feature Gate configuration values. Feature Gates will follow the same graduation process and requirements as feature gates
    # in Kubernetes. More information here https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features
    featureGates:
      # -- driftEnabled is in ALPHA and is disabled by default.
      # Setting driftEnabled to true enables the drift deprovisioner to watch for drift between currently deployed nodes
      # and the desired state of nodes set in provisioners and node templates
      driftEnabled: false

```

(3). U can run

```sh
helm upgrade --install karpenter . \
  --namespace karpenter \
  --create-namespace \
  -f values-dev.yaml > x.yaml
```

`note:` u ll see that there're (3) 2 times; hope u happy
