### ISSUE TITLE
Karpenter NotReady nodes are not deprovisioned.

### ISSUE THREAD

**Issue by LachezarKolevTide** [aws/karpenter#4277]
### Description

**Observed Behavior**:
Karpenter does not get rid of provisioned nodes that get stuck in a `NotReady` state (the pods themselves get stuck in a `Terminating` state. 
According to this comment https://github.com/aws/karpenter/issues/2021#issuecomment-1538756436 they should.

**Expected Behavior**:
Deprovision every node that becomes `NotReady` (for whatever reason) after 15 minutes.

**Reproduction Steps** (Please include YAML):
- Create a new EKS cluster
- Install Karpenter (0.29.0)
Used provisioner:
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - "on-demand"
        - "spot"
    - key: node.kubernetes.io/instance-type
      operator: NotIn
      values:
        - t2.small
        - t3.small
        - t3a.small
        - t4g.small
        - t2.micro
        - t3.micro
        - t3a.micro
        - t4g.micro
        - t4g.nano
        - t3a.nano
        - t3.nano
        - t2.nano
    - key: karpenter.k8s.aws/instance-cpu
      operator: In
      values: ["1", "2", "4", "8", "12"]
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi
  ttlSecondsAfterEmpty: 120
```

- Log in to an EC2 and run `sudo su; systemctl stop network`

**Versions**:
- Chart Version:  0.29.0
- Kubernetes Version (`kubectl version`):  v1.27.3-eks-a5565ad

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
