### ISSUE TITLE
Add default `securityContext` and `podSecurityContext` to Karpenter deployment

### ISSUE THREAD

**Issue by jonathan-innis** [aws/karpenter#4278]
### Description

**What problem are you trying to solve?**

Currently, Karpenter allows you to set the `securityContext` and `podSecurityContext` within the Helm chart values file but doesn't provide default values that would be "secure by default". We should enforce default values that enforce this by doing things like:

```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
```

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
