### ISSUE TITLE
Pod is scheduled right before karpenter decides to delete a node

### ISSUE THREAD

**Issue by mamoit** [aws/karpenter#4310]
### Description

We're running a lot of Gitlab CICD runners on an EKS cluster that is running karpenter.
It seems to be possible for a CICD job (a pod in kubernetes) to be scheduled in a node that karpenter deems to be deleted a couple of seconds after that pod being scheduled, causing that recently scheduled pod to get killed in the first seconds of execution, causing the CICD pipeline to fail.

It is possible that this may be a configuration error on our side, but I don't know where else to look anymore.

Tried to upgrade from `0.28.1` to `0.29.2` but the issue persists.

**Observed Behavior**:
Sometimes a pod is able to sneak into a node right before it is cordoned.
This causes the pod to be killed.
In the following example the pod was scheduled around 2023-07-20T16:15:11, so ~15s before the first message from karpenter.
```
2023-07-20T16:15:26.133Z        INFO    controller.deprovisioning       deprovisioning via consolidation delete, terminating 1 machines ip-10-0-144-248.eu-central-1.compute.internal/c5a.8xlarge/on-demand     {"commit": "34d50bf-dirty"}
2023-07-20T16:15:26.323Z        INFO    controller.termination  cordoned node   {"commit": "34d50bf-dirty", "node": "ip-10-0-144-248.eu-central-1.compute.internal"}
2023-07-20T16:15:29.151Z        INFO    controller.termination  deleted node    {"commit": "34d50bf-dirty", "node": "ip-10-0-144-248.eu-central-1.compute.internal"}
2023-07-20T16:15:29.500Z        INFO    controller.machine.termination  deleted machine {"commit": "34d50bf-dirty", "machine": "ondemand-ffbb5", "node": "ip-10-0-144-248.eu-central-1.compute.internal", "provisioner": "ondemand", "provider-id": "aws:///eu-central-1c/i-xxxxxxxxxxxxxxxxx"}
```

**Expected Behavior**:
A node that is being deleted should remain cordoned for a while before actually being deleted to avoid this situation.
In this situation it was ~3s, but I've seen it happen with little more than 1s between "cordoned" and "deleted" messages.

**Reproduction Steps** (Please include YAML):
This is quite hard to reproduce, and we only notice it because we're running thousands of jobs and some fail in this situation.

`karpenter-global-settings`
```
apiVersion: v1
data:
  aws.clusterEndpoint: https://xxxxxxxxxxxxxxx.eu-central-1.eks.amazonaws.com
  aws.clusterName: 01-cicd
  aws.defaultInstanceProfile: KarpenterNodeInstanceProfile-01-cicd
  aws.enableENILimitedPodDensity: "true"
  aws.enablePodENI: "false"
  aws.interruptionQueueName: 01-cicd
  aws.isolatedVPC: "false"
  aws.vmMemoryOverheadPercent: "0.1"
  batchIdleDuration: 1s
  batchMaxDuration: 10s
  featureGates.driftEnabled: "false"
```

`provisioner` spec
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  annotations:
    meta.helm.sh/release-name: karpenter-profiles
    meta.helm.sh/release-namespace: karpenter
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ondemand
spec:
  consolidation:
    enabled: true
  limits:
    resources:
      cpu: 1k
      memory: 1000Gi
  providerRef:
    name: default
  requirements:
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values:
    - c
    - m
    - r
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: karpenter.k8s.aws/instance-hypervisor
    operator: In
    values:
    - nitro
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  startupTaints:
  - effect: NoExecute
    key: node.cilium.io/agent-not-ready
    value: "true"
  ttlSecondsUntilExpired: 2592000
  weight: 10
```

**Versions**:
- Chart Version: `0.29.2`
- Kubernetes Version (`kubectl version`): `v1.27.3-eks-a5565ad`

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
