### ISSUE TITLE
[AWS] Worker Nodes not Joining the Cluster when using Custom Launch Templates

### ISSUE THREAD

**Issue by vijayansarathy** [aws/karpenter#432]
I tried provisioning worker nodes by specifying a custom launch template in the Provisioner.
What I noticed is that the IAM role, namely, **KarpenterNodeRole-${CLUSTER_NAME}**, does not get assigned to the node at all and therefore the node never joins the cluster. I am using the latest version 0.2.5. I tried with an earlier version as well and saw the same behavior. Here are the Karpenter images I used:
  
- "public.ecr.aws/karpenter/controller:v0.2.4@sha256:488133ea46bd4be3e15bfb984af5b4e217b6780b83d26a6d41e7c4769aaa720f"
- "public.ecr.aws/karpenter/controller:v0.2.5@sha256:44cf4a340637555ba46289c315d700283443533bb2b084488248cf955faf866a"

Here's the YAML for Provisioner:

```
---
apiVersion: provisioning.karpenter.sh/v1alpha1
kind: Provisioner
metadata:
  namespace: karpenter
  name: t3-custom-provisioner
spec:
  cluster:
    name: "k8s-production-cluster"
    caBundle: "XXXXXX="
    endpoint: "https://XXXXXX.gr7.us-east-1.eks.amazonaws.com"
  ttlSeconds: 30
  instanceTypes:
    - t3.large
    - t3.xlarge
    - t3.2xlarge
  labels:
    node.k8s.aws/launch-template-id: "lt-039ab354e881f2cf1"
```
