### ISSUE TITLE
Karpenter doesn't aware of emptied nodes.

### ISSUE THREAD

**Issue by tirelibirefe** [aws/karpenter#4347]
### Description

**Observed Behavior**:

I have a 3 nodes EKS cluster which has some workloads, something like that:

Each node has 16GB memory (t3.xlarge)

Node1 free memory > 5GB
Node2 free memory > 5GB
Node3 free memory > 5GB

I have 2 deployments, like which names are “RED” and “BLUE”. Each one has currently 0 replicas.

“Red” has memory request 3.5Gi.
“BLUE” hass memory request 1Gi.

Step-1:
I increase the replica count of RED from 0 to 3. Karpenter schedules new pods to nodes evenly.

Node1 free memory > 1.5GB
Node2 free memory > 1.5GB
Node3 free memory > 1.5GB

That’s ok, make sense.

Step-2:
I increase the replica count of RED from 3 to 6. Karpenter grabs a new 16GB node and schedules 3 new pods there.

Node1 free memory > 1.5GB
Node2 free memory > 1.5GB
Node3 free memory > 1.5GB
NewNode1 free memory > about 5-6GB

That’s ok, make sense.

Step-3:
I increase the replica count of BLUE from 0 to 5. Karpenter schedules new pods to nodes evenly.

Node1 free memory > 0.5GB
Node2 free memory > 0.5GB
Node3 free memory > 0.5GB
NewNode1 free memory > about 3-4GB

That’s ok, make sense.

Step-4: That’s the problematic step:
I decrease the replica count of RED from 6 to 0.

Node1 free memory > 4GB
Node2 free memory > 4GB
Node3 free memory > 4GB
NewNode1 free memory > about 13-14GB

As 2 BLUE replicas/pods work on NewNode1, NewNode1 is not terminated by Karpenter. 

Although old nodes have enough memory resource, BLUE pods keep working on NewNode1. I expect these 2 BLUE pods on NewNode1 was terminated and re-created on old nodes which have enough memory resource to run 2 BLUE pods.

Currently I use `.consolidation.enabled` but I can change.
Here is my “podAffinity” config used for BLUE and RED. Maybe the situation is related with it.

```
podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - red
              topologyKey: topology.kubernetes.io/zone
          - weight: 90
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - red
              topologyKey: topology.kubernetes.io/zone
```

**Expected Behavior**:

I expect these 2 BLUE pods on NewNode1 was terminated and re-created on old nodes which have enough memory resource to run 1 BLUE pods.

Is it a normal behavior or something configurable? 

Maybe there is a more appropriate way to keep consolidated the system?

Could you please advise?

Thanks & Regards

**Versions**:
- Chart Version:  v0.29.2
- Kubernetes Version (`kubectl version`): eks 1.27

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
