### ISSUE TITLE
Internal error occurred: failed calling webhook

### ISSUE THREAD

**Issue by jseiser** [aws/karpenter#4350]
### Description

**Observed Behavior**:
```
{"level":"ERROR","time":"2023-07-28T15:32:59.986Z","logger":"controller","message":"Reconciler error","commit":"5b469b8-dirty","controller":"awsnodetemplate","controllerGroup":"karpenter.k8s.aws","controllerKind":"AWSNodeTemplate","AWSNodeTemplate":{"name":"default"},"namespace":"","name":"default","reconcileID":"02565d5d-e127-4fa1-a26b-765e1f594c87","error":"Internal error occurred: failed calling webhook \"defaulting.webhook.karpenter.k8s.aws\": failed to call webhook: Post \"https://karpenter.karpenter.svc:8443/default/karpenter.k8s.aws?timeout=10s\": context deadline exceeded"}
```

**Expected Behavior**:
I would expect to be able to reach the webhook

**Reproduction Steps** (Please include YAML):

1. Run Linkerd and inject all pods in this namespace

```
    dnsPolicy: ClusterFirst
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws-us-gov:iam::xxxx:role/karpenter-qa-karpenter"
    nodeSelector:
      kubernetes.io/os: linux
      dedicated: "true"
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
    replicas: 2
    logLevel: info
    logEncoding: json
    controller:
      resources:
        requests:
          cpu: 100m
          memory: 256M
    settings:
      batchMaxDuration: 15s
      batchIdleDuration: 2s
      aws:
        defaultInstanceProfile: "karpenter-qa-karpenter"
        clusterName: "eks-qa-cluster"
        clusterEndpoint: "https://xxxx.gr7.us-gov-west-1.eks.amazonaws.com"
        interruptionQueueName: "karpenter-qa-karpenter"
      featureGates:
        driftEnabled: true
```

**Versions**:
- Chart Version:  v0.29.2
- Kubernetes Version (`kubectl version`):  1.27

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
