### ISSUE TITLE
AMI ID requirement conflict between Karpenter and Launch Template

### ISSUE THREAD

**Issue by matt-slalom** [aws/karpenter#4357]
### Description

**Background**:
Using EKS Managed Node groups (created with `terraform-aws-modules/eks/aws`) also creates launch templates. However, the launch templates do not contain AMI IDs and attempting to add IDs generates an error. That is, **adding AMI IDs to a launch template is not allowed.**
```shell
Error: updating EKS Node Group (NameOmitted) version: InvalidParameterException: You cannot specify an image id within the launch template, since your nodegroup is configured to use an EKS optimized AMI.
```

**Observed Behavior**:
Karpenter fails to provision a new node and reports `amiIdList` cannot be empty when trying to use the template.
```shell
2023-07-31T17:38:00.634Z	ERROR	controller	Reconciler error	{"commit": "34d50bf-dirty", "controller": "machine.lifecycle", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "Machine": {"name":"gpu-47gfh"}, "namespace": "", "name": "gpu-47gfh", "reconcileID": "8af39500-12d6-4244-a6d4-58e5de1af7c3", "error": "creating machine, creating instance, creating fleet InvalidParameterValue: Parameter 'amiIdList' cannot be empty.\n\tstatus code: 400, request id: f6506f26-5d40-426a-ae26-859b692bb7a4 (f6506f26-5d40-426a-ae26-859b692bb7a4)"}
```

Per what I understand from the [documentation](https://karpenter.sh/docs/concepts/node-templates/), AWSNodeTemplate should default to the correct image, even if one isn't supplied.

**Expected Behavior**:
Karpenter should provision a new node based on the template.

**Reproduction Steps** (Please include YAML):
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: gpu
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: [ "spot" ]
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - p4d.24xlarge
  providerRef:
    name: gpu-spot
  taints:
    - effect: NoSchedule
      key: nvidia.com/gpu
      value: "true"
  ttlSecondsAfterEmpty: 60
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: gpu-spot
spec:
  subnetSelector:
    Name: "some-subnet-*"
  launchTemplate: gpu_spot-01234567890
```

**Versions**:
- Chart Version: v0.29.2
- Kubernetes Version (`kubectl version`): 
```shell
% kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.27.3-eks-a5565ad
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
