### ISSUE TITLE
Karpenter removes nodes from the cluster before kubelet has stopped, causing lease leakage

### ISSUE THREAD

**Issue by cebernardi** [aws/karpenter#4363]
### Description

**Observed Behavior**:
We're making use of [Graceful node shutdown](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta).

When Karpenter reclaims the node, it deletes the node object before the kubelet has stopped, and we hit [this bug](https://github.com/kubernetes/kubernetes/issues/109777): the node leases of deleted nodes are not deleted.

We have also nodepools managed by Cluster Autoscaler and ASG, and those nodes, despite using exactly the same [Graceful node shutdown](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta) configuration, are not affected by the lease leak.

The problem might be that Karpenter deletes the node before terminating the instance (and the kubelet):
https://github.com/aws/karpenter-core/blob/main/pkg/controllers/machine/termination/controller.go#L81-L93

**Expected Behavior**:
Node leases of Karpenter managed nodes are cleaned regardless of the kubelet configuration.

**Reproduction Steps** (Please include YAML):
Create a node template that makes use of [node graceful shutdown](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta), and a provisioner that references that node template:

```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: node-template
spec:
  amiFamily: AL2
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      encrypted: false
      iops: 3000
      throughput: 125
      volumeSize: 80Gi
      volumeType: gp3
  instanceProfile: <instance-profile>
  metadataOptions:
    httpTokens: optional
  securityGroupSelector:
    ClusterId: <clusterid>
    Name: <sg-name>
  subnetSelector:
   <key>: <value>

  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"

    --BOUNDARY
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash
    mkdir -p /etc/systemd/logind.conf.d
    cat << EOF > /etc/systemd/logind.conf.d/50-max-delay.conf
    [Login]
    InhibitDelayMaxSec=360
    EOF

    systemctl restart systemd-logind

    sed -i '/"apiVersion*/a \ \ "shutdownGracePeriod": "3m",' /etc/kubernetes/kubelet/kubelet-config.json
    sed -i '/"shutdownGracePeriod*/a \ \ "shutdownGracePeriodCriticalPods": "2m",' /etc/kubernetes/kubelet/kubelet-config.json

    --BOUNDARY
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash
    exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1


    echo $(jq '.containerLogMaxFiles=3|.containerLogMaxSize="100Mi"' /etc/kubernetes/kubelet/kubelet-config.json) > /etc/kubernetes/kubelet/kubelet-config.json

    --BOUNDARY--
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: provisioner
spec:
  consolidation:
    enabled: true
  providerRef:
    name: node-template
  requirements:
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - us-west-2a
    - us-west-2b
    - us-west-2c
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  ttlSecondsUntilExpired: 1728000
```
then create a pod targeting that provisioner:

```
apiVersion: v1
kind: Pod
metadata:
  name: sleep
spec:
  nodeSelector:
    karpenter.sh/provisioner-name: provisioner
  containers:
  - name: sleep
    image: curlimages/curl:7.81.0
    command: ["/bin/sleep", "infinity"]
    imagePullPolicy: IfNotPresent
```
Karpenter provisions a node, and we can observe the lease:

```
kubectl -n kube-node-lease get lease <node-name> -o yaml

apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2023-08-01T17:38:01Z"
  name: <node-name>
  namespace: kube-node-lease
  ownerReferences:
  - apiVersion: v1
    kind: Node
    name: <node-name>
spec:
  holderIdentity: <node-name>
  leaseDurationSeconds: 40
  renewTime: "2023-08-01T17:41:56.114159Z"
```

if we remove the pod, Karpenter should reclaim the node.

when the node leaves the cluster, the lease is garbage collected, but it gets recreated without `ownerReferences`, and never deleted.

**Versions**:
- Chart Version: `v0.29.0`
- Kubernetes Version (`kubectl version`): `1.23` 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
