### ISSUE TITLE
Nodes scale down and consolidation is not works after decrease size of pods

### ISSUE THREAD

**Issue by qspors** [aws/karpenter#4389]
### Description

**Observed Behavior**:
Nothing happens, log is empty:
last INFO event related with "controller.machine.lifecycle	launched machine" During increasing pods size
**Expected Behavior**:
Instances scale down, consolidation and start smaller instances and pods re-scheduling into smaller node
**Reproduction Steps** (Please include YAML):
I use default pods for test Cluster scale up/down

After deploy big PODS:
Karpenter scale UP my cluster with set of instances:
Log output:
`INFO	controller.machine.lifecycle	launched machine	{"commit": "34d50bf-dirty", "machine", "provisioner": "default", "provider-id": "aws:///us-east-1b/i-0c574d8ae******", "instance-type": "c5d.2xlarge"`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-test
  namespace: test
  labels:
    app: test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: ubuntu-test
          image: ubuntu:latest
          tty: true
          resources:
            requests:
              cpu: "4000m"
              memory: "4Gi"
            limits:
              cpu: "5000m"
              memory: "5Gi"
```

After I tried to decrease size of PODS
to
```
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
```
After my pods is restarting with new resource settings but cluster does't scale down
PODS active in same nodes and no new log events related with scaling or another errors.
If scale UP to bigger values 6000m and so one cluster is scaling UP.
No errors during this tests, I have another errors related with webhooks, but looks like this issues is not related. For example:
`ERROR	webhook.DefaultingWebhook	Reconcile error	{"commit": "34d50bf-dirty", "knative.dev/traceid": "54f1bded-7e41-4918-a102-8ce80a6e1e62", "knative.dev/key": "karpenter/karpenter-cert", `

My config.
```
resource "kubectl_manifest" "karpenter_provisioner" {
  yaml_body = <<-YAML
    apiVersion: karpenter.sh/v1alpha5
    kind: Provisioner
    metadata:
      name: default
    spec:
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
      limits:
        resources:
          cpu: 10000
      providerRef:
        name: default
      ttlSecondsAfterEmpty: 30
  YAML

  depends_on = [
    helm_release.karpenter
  ]
}

resource "kubectl_manifest" "karpenter_node_template" {
  yaml_body = <<-YAML
    apiVersion: karpenter.k8s.aws/v1alpha1
    kind: AWSNodeTemplate
    metadata:
      name: default
    spec:
      subnetSelector:
        karpenter.sh/discovery/${module.eks.cluster_name}: ${module.eks.cluster_name}
      securityGroupSelector:
        karpenter.sh/discovery/${module.eks.cluster_name}: ${module.eks.cluster_name}
      tags:
        karpenter.sh/discovery/${module.eks.cluster_name}: ${module.eks.cluster_name}
  YAML

  depends_on = [
    helm_release.karpenter
  ]
}
```
If delete this PODS Karpenter removes nodes.

**Versions**:
 Karpenter 0.29.2
- Kubernetes Version (`kubectl version`): 
 EKS 1.27, self-managed-nodes
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
