### ISSUE TITLE
Failed to get lease: leases.coordination.k8s.io "<node_ip>" not found

### ISSUE THREAD

**Issue by ThiagoScodeler** [aws/karpenter#4390]
### Description

**Observed Behavior**:

Karperter has been installed with Helm charts (v0.13.1) and it is running properly. When I try to deploy a test application to see it is working, Karpenter launches the EC2 instance but sometimes (random) the nodes stuck with the following message:

"Failed to get lease: leases.coordination.k8s.io "<node_ip>" not found"

Due to that node stuck with "NotReady" on EKS and the pods are not scheduled there. This issue is pretty random and in some pod deployments everything goes well.

```
NAME                         STATUS     ROLES    AGE   VERSION
ip-10-0-1-248.ec2.internal   Ready      <none>   65m   v1.27.3-eks-a5565ad
ip-10-0-2-18.ec2.internal    Ready      <none>   16h   v1.27.3-eks-a5565ad
ip-10-0-3-74.ec2.internal    Ready      <none>   71m   v1.27.3-eks-a5565ad
ip-10-0-6-59.ec2.internal    NotReady   <none>   67s
```

**Reproduction Steps**:

Karpenter on EKS with the following provisioner and nodeTemplate for testing:

```
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: eks-test
spec:
  ttlSecondsAfterEmpty: 60
  ttlSecondsUntilExpired: 604800
  limits:
    resources:
      cpu: 100
  requirements:
    # Include general purpose instance families
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [c5, m5, r5]
    # Exclude small instance sizes
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values: [nano, micro, small, large]
  providerRef:
    name: default
```

```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    kubernetes.io/cluster/test: owned
  securityGroupSelector:
    kubernetes.io/cluster/test: owned
```

Test application:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
          requests:
            cpu: "4"
            memory: 4Gi
        ports:
        - containerPort: 80
```

**Versions**:
- Chart Version: v0.13.1
- Kubernetes Version (`kubectl version`): v1.27.4-eks-2d98532
