### ISSUE TITLE
Add Log query features to kubelet config

### ISSUE THREAD

**Issue by rothgar** [aws/karpenter#4404]
### Description

**What problem are you trying to solve?**
Configuring kubelet to enable log query [feature gates](https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#log-query).

It seems that most of the kubelet configuration settings we support are focused on resource utilization and eviction. Do we have any plans to extend that to other kubelet settings?

The kubelet settings I would like are:
* NodeLogQuery
* enableSystemLogHandler
* enableSystemLogQuery

NodeLogQuery is currently an alpha feature in 1.27 which is why I wanted to start a discussion about future plans for kubelet configuration for these types of settings. I'm assuming for alpha settings they would only be exposed in user-data but GA features might be easier to manage declaratively in the CRD

**How important is this feature to you?**
Medium important because this can be done via user-data, but it would be cleaner to have as part of the kubelet configuration.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
So far, we've mainly been adding KubeletConfiguration that affects scheduling and leaving everything else to user-data. We can reevaulate this stance though since I do agree it's cleaner in one section rather than half in the provisioner and half in user-data.

**Comment by rothgar** [comment]
I never found a clean way to add KUBELET_EXTRA_ARGS to user-data. If we have a documented way or example to do that it would probably help in this situation.

**Comment by bwagner5** [comment]
I don't have a good answer for kubelet extra args, but for kubeletConfiguration, which it looks like the params you want are, we recommend [this](https://karpenter.sh/docs/concepts/node-templates/#specuserdata:~:text=echo%20%22%24(jq%20%27.kubeAPIQPS%3D50%27%20/etc/kubernetes/kubelet/kubelet%2Dconfig.json)%22%20%3E%20/etc/kubernetes/kubelet/kubelet%2Dconfig.json).


```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: kubelet-config-example
spec:
  subnetSelector:
    karpenter.sh/discovery: my-cluster
  securityGroupSelector:
    karpenter.sh/discovery: my-cluster
  userData: |
    #!/bin/bash
    echo "$(jq '.kubeAPIQPS=50' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json
```
