### ISSUE TITLE
Incorrect handling of soft node affiinity

### ISSUE THREAD

**Issue by dnutels** [aws/karpenter#4406]
### Description

**Observed Behavior**:

Provided the following Node Template and Provisioner:

```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: karpenter-examples
  securityGroupSelector:
    karpenter.sh/discovery: karpenter-examples
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 15
```

and the following application manifest:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-app
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: some-app
  template:
    metadata:
      labels:
        app: some-app
    spec:
      terminationGracePeriodSeconds: 0
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: some-app
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values: [eu-west-1a, eu-west-1c]
      containers:
        - name: some-app
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.9
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
```

Karpenter provisions 2 instances in `eu-west-1a`, `eu-west-1c` with 1 Pod remaining in the Pending state.

**Expected Behavior**:

The expected result is to have 3 Pods, spread across 3 AZs. 

**Reproduction Steps** (Please include YAML):

See above.

**Versions**:
- Chart Version: v0.29.2
- Kubernetes Version (`kubectl version`): 1.27

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
