### ISSUE TITLE
Feature suggestion : allow over-provisioning

### ISSUE THREAD

**Issue by cest-pas-faux** [aws/karpenter#4409]
### Description

**What problem are you trying to solve?**

Hello, we're using Karpenter in production for quite a while now and there is a small inconvenience that happens sometimes when consolidation is enabled and a controller is trying to start a new pod that does not fit on the remaining machines.

The controller (here, has been some CICD runner pods and some cronjobs) shows the workload as pending till a machine has been launched (could take somewhere between 45 seconds to 2 minutes). That's not a real issue for cronjobs but the users running CICD jobs are complaining.

Current workarounds known : 

| Workaround | Comment |
| --- | --- | 
| Use fargate for runner pods | Needs extra configuration and the time to have a pod running is around 90 seconds |
| Use [overprovisioner ](https://github.com/codecentric/cluster-overprovisioner) | Works great but a bit overkill to have an app dedicated to this |
| Reduce the requests of the runners | It will squeeze the pods on a node that can't provide enough resources |

**Suggestions :** 

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  # [...]
  consolidation: 
    enabled: true
    keepExtraResources:
      cpu: 3
      memory: 5Gi
```

```yaml
spec:
  # [...]
  consolidation: 
    enabled: true
    ensureAvailable:
      nodes: 1
      resources:
        cpu: 3
        memory: 5Gi
```

**How important is this feature to you?**

That's a very minor inconvenience but this would be a nice-to-have feature to improve the current experience.

---

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
