### ISSUE TITLE
unable to run v0.29.2 on aws eks 1.27

### ISSUE THREAD

**Issue by dmitry-mightydevops** [aws/karpenter#4421]
### Description

I'm unable to run v.0.29.2 in aws eks 1.27
I am able to run v.0.27.6 without any issues though

helm values I pass:

```yaml
➜ helm get values karpenter                                                                                 
USER-SUPPLIED VALUES:
controller:
  resources:
    limits:
      cpu: 250m
      memory: 250Mi
    requests:
      cpu: 100m
      memory: 250Mi
nodeSelector:
  workload: ops
replicas: 1
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::11111111111111:role/KarpenterIRSA-proj-staging-eks-20230812220942059200000005
settings:
  aws:
    clusterEndpoint: https://XXX.gr7.us-east-2.eks.amazonaws.com
    clusterName: proj-staging-eks
    defaultInstanceProfile: Karpenter-proj-staging-eks-20230812230311371900000004
    interruptionQueueName: Karpenter-proj-staging-eks
webhook:
  resources:
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 50m
      memory: 50Mi
```

**Observed Behavior**:

```sh
➜ kgno
NAME                                         STATUS   ROLES    AGE   VERSION
ip-10-110-1-218.us-east-2.compute.internal   Ready    <none>   30d   v1.27.1-eks-2f008fe
ip-10-110-1-22.us-east-2.compute.internal    Ready    <none>   16d   v1.27.1-eks-2f008fe
ip-10-110-2-135.us-east-2.compute.internal   Ready    <none>   30d   v1.27.1-eks-2f008fe
ip-10-110-4-191.us-east-2.compute.internal   Ready    <none>   30d   v1.27.1-eks-2f008fe

➜ helm ls   
NAME                                  	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                              	APP VERSION
karpenter                             	karpenter	10      	2023-08-12 19:34:47.958686723 -0500 CDT	deployed	karpenter-v0.29.2                  	0.29.2     
karpenter-aws-node-termination-handler	karpenter	1       	2023-07-15 17:36:00.107218654 -0500 CDT	deployed	aws-node-termination-handler-0.21.0	1.19.0

➜ kgpo                                   
NAME                         READY   STATUS   RESTARTS      AGE
karpenter-75946cc8c6-pdrr7   0/1     Error    3 (35s ago)   64s

➜ klo -l app.kubernetes.io/name=karpenter


goroutine 1 [running]:
github.com/samber/lo.must({0x24a5760, 0xc0011e0e40}, {0xc000d3faf8, 0x1, 0x1})
	github.com/samber/lo@v1.38.1/errors.go:51 +0x1cd
github.com/samber/lo.Must0(...)
	github.com/samber/lo@v1.38.1/errors.go:72
github.com/aws/karpenter-core/pkg/operator.NewOperator()
	github.com/aws/karpenter-core@v0.29.2/pkg/operator/operator.go:135 +0xc05
main.main()
	github.com/aws/karpenter/cmd/controller/main.go:33 +0x2e
```

**Expected Behavior**:

POD to run

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: karpenter-v0.29.2
- Kubernetes Version: 1.27
