### ISSUE TITLE
consolidation stuck in provision/deprovision loop with overprovisioning pod (pod with negative priority)

### ISSUE THREAD

**Issue by dschaaff** [aws/karpenter#4452]
### Description

We use a deployment of pause pods with a negative priority in conjunction with the [cluster proportional autoscaler's](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler) ladder strategy to maintain some warm nodes in the cluster. Yesterday evening karpenter got stuck in a loop of constantly provisioning then deprovisioning a node to handle a pending overprovisioner pod. 

<img width="439" alt="image" src="https://github.com/aws/karpenter/assets/12867428/7285dd5c-8988-4b47-8fec-28cc1f1d35f9">

**Observed Behavior**:

The cluster proportional autoscaler adds a replica to the overprovisioner deployment. `I0816 19:08:40.370457       1 k8sclient.go:274] Replicas are not as expected : updating replicas from 2 to 3`. The new pod that gets created is stuck in a pending stuck, sometimes for more than 30 minutes.  

Karpenter adds a new node to handle the pending pod

```
karpenter-787f66d8f6-xwqcl controller 2023-08-17T16:16:21.601Z	INFO	controller.provisioner	created machine	{"commit": "34d50bf-dirty", "provisioner": "client-code-isolation", "requests": {"cpu":"15880m","memory":"44632Mi","pods":"13"}, "instance-types": "c5.9xlarge, c5a.8xlarge, c5d.9xlarge, c6a.8xlarge, c6g.8xlarge and 32 other(s)"}
karpenter-787f66d8f6-xwqcl controller 2023-08-17T16:16:23.840Z	INFO	controller.machine.lifecycle	launched machine	{"commit": "34d50bf-dirty", "machine": "client-code-isolation-dbfq9", "provisioner": "client-code-isolation", "provider-id": "aws:///us-west-1a/i-096be7b66ce26d17f", "instance-type": "m6g.4xlarge", "zone": "us-west-1a", "capacity-type": "spot", "allocatable": {"cpu":"15890m","ephemeral-storage":"89Gi","memory":"57632Mi","pods":"234"}}
```

The node gets nominated for scheduling the pod

```
 Normal   Nominated         92s    karpenter          Pod should schedule on: machine/client-code-isolation-dbfq9
```

Karpenter consolidation then immediately deprovisions the node it just created

```
karpenter-787f66d8f6-xwqcl controller 2023-08-17T16:17:56.422Z	INFO	controller.deprovisioning	deprovisioning via consolidation delete, terminating 1 machines ip-10-0-133-149.us-west-1.compute.internal/m6g.4xlarge/spot	{"commit": "34d50bf-dirty"}
karpenter-787f66d8f6-xwqcl controller 2023-08-17T16:17:56.477Z	INFO	controller.termination	cordoned node	{"commit": "34d50bf-dirty", "node": "ip-10-0-133-149.us-west-1.compute.internal"}
karpenter-787f66d8f6-xwqcl controller 2023-08-17T16:17:56.782Z	INFO	controller.termination	deleted node	{"commit": "34d50bf-dirty", "node": "ip-10-0-133-149.us-west-1.compute.internal"}
karpenter-787f66d8f6-xwqcl controller 2023-08-17T16:17:57.090Z	INFO	controller.machine.termination	deleted machine	{"commit": "34d50bf-dirty", "machine": "client-code-isolation-dbfq9", "node": "ip-10-0-133-149.us-west-1.compute.internal", "provisioner": "client-code-isolation", "provider-id": "aws:///us-west-1a/i-096be7b66ce26d17f"}
```

As a result the overprovisioner pod is stuck in pending as it never actually starts on any of the nominated nodes.

```
 Normal   Nominated         7m40s  karpenter          Pod should schedule on: machine/client-code-isolation-984lz
  Normal   Nominated         5m33s  karpenter          Pod should schedule on: machine/client-code-isolation-x769g
  Normal   Nominated         3m32s  karpenter          Pod should schedule on: machine/client-code-isolation-7k4xl
  Normal   Nominated         92s    karpenter          Pod should schedule on: machine/client-code-isolation-dbfq9
```
**Expected Behavior**:

The overprovisioner pod should successfully schedule and run on a new node.

**Reproduction Steps** (Please include YAML):

overprovisioner manifest

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: overprovisioner-client-code-isolation
    app.kubernetes.io/instance: overprovisioner-client-code-isolation
  name: overprovisioning-client-code-isolation
  namespace: overprovisioner
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: overprovisioner-client-code-isolation
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: overprovisioner-client-code-isolation
        app.kubernetes.io/instance: overprovisioner-client-code-isolation
    spec:
      automountServiceAccountToken: true
      containers:
      - image: 602401143452.dkr.ecr.us-west-1.amazonaws.com/eks/pause:3.1-eksbuild.1
        imagePullPolicy: Always
        name: reserve-resources
        resources:
          requests:
            cpu: "15"
            memory: 40Gi
      dnsPolicy: ClusterFirst
      priorityClassName: overprovisioning
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      nodeSelector:
        role: client-code-isolation
      tolerations:
        - key: role
          value: client-code-isolation
          operator: Equal
          effect: NoSchedule
```
the priority class

```yaml
apiVersion: scheduling.k8s.io/v1
description: Priority class used by overprovisioning.
kind: PriorityClass
metadata:
  name: overprovisioning
value: -1
```

cluster proportional autoscaler config

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overprovisioner-client-code-iso-autoscaler
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cluster-proportional-autoscaler
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cluster-proportional-autoscaler
      version: 1.0.1
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 1
  interval: 10m0s
  releaseName: overprovisioner-client-code-iso-autoscaler
  targetNamespace: overprovisioner
  storageNamespace: overprovisioner
  values:
    image:
      repository: registry.k8s.io/cpa/cluster-proportional-autoscaler
      tag: 1.8.6
    resources:
      requests:
        memory: 25Mi
        cpu: 25m
      limits:
        memory: 50Mi
    options:
      namespace: overprovisioner
      target: deployment/overprovisioning-client-code-isolation
      nodeLabels:
        role: client-code-isolation
    config:
      ladder:
        nodesToReplicas:
        - [5, 4]
        - [10, 3]
        - [30, 2]
        - [40, 1]
```

The karpenter provisioner spec for these nodes

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: client-code-isolation
spec:
  labels:
    role: client-code-isolation
  taints:
    - key: role
      value: client-code-isolation
      effect: NoSchedule
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["arm64", "amd64"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: [ "us-west-1a"]
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values:
      - c5
      - c5d
      - c5a
      - c5ad
      - c6
      - c6a
      - c6i
      - c6id
      - c6g
      - c6gd
      - c7g
      - m5
      - m5d
      - m5a
      - m5ad
      - m6a
      - m6i
      - m6id
      - m6g
      - m6gd
      - m7g
      - r5
      - r5d
      - r5a
      - r5ad
      - r6a
      - r6i
      - r6id
      - r6g
      - r6gd
      - r7g
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values:
      - nano
      - micro
      - small
      - medium
      - large
      - xlarge
      - 2xlarge
      - 12xlarge
      - 16xlarge
      - 18xlarge
      - 24xlarge
      - 32xlarge
      - 48xlarge
      - metal
  limits:
    resources:
      cpu: "4800"
      memory: 20Ti
  providerRef:
    name: bottlerocket
  consolidation:
    enabled: true
  ttlSecondsUntilExpired: 1209600 # 14 days
```

**Versions**:
- Chart Version: 0.29.2
- Kubernetes Version (`kubectl version`):  AWS EKS 1.26.7

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Do you have the full logs when this occurred with the list of nodes? 

It looks like the node the pod was supposed to schedule to was launched at 16:16:23Z and it was consolidated at 16:17:56Z which should have left the node enough time (93s) to bootstrap and for the pod to go running. It looks like the node did have enough allocatable resources to accommodate the pod.

What other DaemonSets are you running? What resources do they request? 

Pod that should have scheduled:
CPU 15,000
Mem 40Gi

Node Allocatable:
CPU 15,890m
Mem: 56.28125Gi

**Comment by dschaaff** [comment]
I'm looking at one of the pods involved with the flapping node now and I see a discrepancy in allocatable CPU between the k8s node object and the karpenter machine object that may be the cause.

pod is `overprovisioning-client-code-isolation-66bbc5f75b-4wkk5`

```
  Normal   Nominated         33m                   karpenter          Pod should schedule on: machine/client-code-isolation-2gm2q
  Normal   Nominated         31m                   karpenter          Pod should schedule on: machine/client-code-isolation-gppn6
  Normal   Nominated         29m                   karpenter          Pod should schedule on: machine/client-code-isolation-gp4gr
  Normal   Nominated         27m                   karpenter          Pod should schedule on: machine/client-code-isolation-qtkbg
  Warning  FailedScheduling  23m (x15 over 27m)    default-scheduler  0/57 nodes are available: 1 Insufficient memory, 2 node(s) had untolerated taint {availability-zone: us-west-2b}, 2 node(s) had untolerated taint {role: pilot-light}, 22 Insufficient cpu, 26 node(s) didn't match Pod's node affinity/selector, 5 node(s) had untolerated taint {role: workers}. preemption: 0/57 nodes are available: 22 No preemption victims found for incoming pod, 35 Preemption is not helpful for scheduling..
  Warning  FailedScheduling  18m (x13 over 21m)    default-scheduler  0/59 nodes are available: 2 node(s) had untolerated taint {availability-zone: us-west-2b}, 2 node(s) had untolerated taint {role: pilot-light}, 24 Insufficient cpu, 26 node(s) didn't match Pod's node affinity/selector, 3 Insufficient memory, 5 node(s) had untolerated taint {role: workers}. preemption: 0/59 nodes are available: 24 No preemption victims found for incoming pod, 35 Preemption is not helpful for scheduling..
  Warning  FailedScheduling  13m (x3 over 31m)     default-scheduler  0/59 nodes are available: 1 Insufficient memory, 1 node(s) had untolerated taint {node.kubernetes.io/not-ready: }, 2 node(s) had untolerated taint {availability-zone: us-west-2b}, 2 node(s) had untolerated taint {role: pilot-light}, 23 Insufficient cpu, 26 node(s) didn't match Pod's node affinity/selector, 5 node(s) had untolerated taint {role: workers}. preemption: 0/59 nodes are available: 23 No preemption victims found for incoming pod, 36 Preemption is not helpful for scheduling..
  Warning  FailedScheduling  8m22s (x37 over 34m)  default-scheduler  (combined from similar events): 0/59 nodes are available: 2 node(s) had untolerated taint {availability-zone: us-west-2b}, 2 node(s) had untolerated taint {role: pilot-light}, 24 Insufficient cpu, 26 node(s) didn't match Pod's node affinity/selector, 3 Insufficient memory, 5 node(s) had untolerated taint {role: workers}. preemption: 0/59 nodes are available: 24 No preemption victims found for incoming pod, 35 Preemption is not helpful for scheduling..
  Warning  FailedScheduling  3m25s (x3 over 5m6s)  default-scheduler  0/60 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/not-ready: }, 2 node(s) had untolerated taint {availability-zone: us-west-2b}, 2 node(s) had untolerated taint {role: pilot-light}, 23 Insufficient cpu, 27 node(s) didn't match Pod's node affinity/selector, 3 Insufficient memory, 5 node(s) had untolerated taint {role: workers}. preemption: 0/60 nodes are available: 23 No preemption victims found for incoming pod, 37 Preemption is not helpful for scheduling..
  Normal   Nominated         25s (x13 over 24m)    karpenter          (combined from similar events): Pod should schedule on: machine/client-code-isolation-mzwsg
```

Karpenter provisions a machine

```
karpenter-5b476d9cc4-dxlr6 controller 2023-08-18T15:57:16.101Z	INFO	controller.machine.lifecycle	launched machine	{"commit": "34d50bf-dirty", "machine": "client-code-isolation-mzwsg", "provisioner": "client-code-isolation", "provider-id": "aws:///us-west-2a/i-037515f8de0a97bc4", "instance-type": "m6g.4xlarge", "zone": "us-west-2a", "capacity-type": "spot", "allocatable": {"cpu":"15890m","ephemeral-storage":"89Gi","memory":"57632Mi","pods":"234"}}
karpenter-5b476d9cc4-dxlr6 controller 2023-08-18T15:58:41.803Z	INFO	controller.deprovisioning	deprovisioning via consolidation delete, terminating 5 machines ip-10-1-219-238.us-west-2.compute.internal/m6g.4xlarge/spot, ip-10-1-1-66.us-west-2.compute.internal/m6g.2xlarge/on-demand, ip-10-1-28-113.us-west-2.compute.internal/m6g.2xlarge/on-demand, ip-10-1-6-59.us-west-2.compute.internal/m6g.4xlarge/spot, ip-10-1-201-180.us-west-2.compute.internal/m6g.4xlarge/spot	{"commit": "34d50bf-dirty"}
karpenter-5b476d9cc4-dxlr6 controller 2023-08-18T15:58:41.862Z	INFO	controller.termination	cordoned node	{"commit": "34d50bf-dirty", "node": "ip-10-1-219-238.us-west-2.compute.internal"}
karpenter-5b476d9cc4-dxlr6 controller 2023-08-18T15:58:42.390Z	INFO	controller.termination	deleted node	{"commit": "34d50bf-dirty", "node": "ip-10-1-219-238.us-west-2.compute.internal"}
karpenter-5b476d9cc4-dxlr6 controller 2023-08-18T15:58:42.766Z	INFO	controller.machine.termination	deleted machine	{"commit": "34d50bf-dirty", "machine": "client-code-isolation-mzwsg", "node": "ip-10-1-219-238.us-west-2.compute.internal", "provisioner": "client-code-isolation", "provider-id": "aws:///us-west-2a/i-037515f8de0a97bc4"}
```

Notice that karpenter displays the  allocatable CPU as 15890m. When I describe the karpenter machine object, it also displays the allocatable CPU as 15890m. When I describe the node however, it displays the node allocatable CPU as 15790m. As a result the pod never starts on the node. Karpenter consolidation removes the node and creates a new one for pending pod and thus the loop begins. The question is, why is there a discrepancy between allocatable CPU in karpenter's view and the node's view after the kubelet starts? 

```
Name:         client-code-isolation-mzwsg
Namespace:    
Labels:       karpenter.k8s.aws/instance-category=m
              karpenter.k8s.aws/instance-cpu=16
              karpenter.k8s.aws/instance-encryption-in-transit-supported=false
              karpenter.k8s.aws/instance-family=m6g
              karpenter.k8s.aws/instance-generation=6
              karpenter.k8s.aws/instance-hypervisor=nitro
              karpenter.k8s.aws/instance-memory=65536
              karpenter.k8s.aws/instance-network-bandwidth=5000
              karpenter.k8s.aws/instance-pods=234
              karpenter.k8s.aws/instance-size=4xlarge
              karpenter.sh/capacity-type=spot
              karpenter.sh/provisioner-name=client-code-isolation
              kubernetes.io/arch=arm64
              kubernetes.io/os=linux
              node.kubernetes.io/instance-type=m6g.4xlarge
              role=client-code-isolation
              topology.kubernetes.io/region=us-west-2
              topology.kubernetes.io/zone=us-west-2a
Annotations:  karpenter.sh/managed-by: prd-usw2a
API Version:  karpenter.sh/v1alpha5
Kind:         Machine
Metadata:
  Creation Timestamp:  2023-08-18T15:57:14Z
  Finalizers:
    karpenter.sh/termination
  Generate Name:  client-code-isolation-
  Generation:     1
  Owner References:
    API Version:           karpenter.sh/v1alpha5
    Block Owner Deletion:  true
    Kind:                  Provisioner
    Name:                  client-code-isolation
    UID:                   6a7012e8-5b3f-4d9b-bec1-dc4b047aa720
  Resource Version:        1586650932
  UID:                     6b6ca9bf-704a-4b65-8c08-6604071dfe65
Spec:
  Machine Template Ref:
    Name:  bottlerocket
  Requirements:
    Key:       karpenter.k8s.aws/instance-family
    Operator:  In
    Values:
      c5
      c5a
      c5ad
      c5d
      c6
      c6a
      c6g
      c6gd
      c6i
      c6id
      c7g
      m5
      m5a
      m5ad
      m5d
      m6a
      m6g
      m6gd
      m6i
      m6id
      m7g
      r5
      r5a
      r5ad
      r5d
      r6a
      r6g
      r6gd
      r6i
      r6id
      r7g
    Key:       karpenter.sh/provisioner-name
    Operator:  In
    Values:
      client-code-isolation
    Key:       karpenter.k8s.aws/instance-size
    Operator:  NotIn
    Values:
      16xlarge
      18xlarge
      24xlarge
      2xlarge
      32xlarge
      48xlarge
      large
      medium
      metal
      micro
      nano
      small
      xlarge
    Key:       karpenter.sh/capacity-type
    Operator:  In
    Values:
      on-demand
      spot
    Key:       topology.kubernetes.io/zone
    Operator:  In
    Values:
      us-west-2a
    Key:       role
    Operator:  In
    Values:
      client-code-isolation
    Key:       kubernetes.io/os
    Operator:  In
    Values:
      linux
    Key:       kubernetes.io/arch
    Operator:  In
    Values:
      amd64
      arm64
    Key:       node.kubernetes.io/instance-type
    Operator:  In
    Values:
      c5.12xlarge
      c5.9xlarge
      c5a.12xlarge
      c5a.8xlarge
      c5ad.12xlarge
      c5ad.8xlarge
      c5d.12xlarge
      c5d.9xlarge
      c6a.12xlarge
      c6a.8xlarge
      c6g.12xlarge
      c6g.8xlarge
      c6gd.12xlarge
      c6gd.8xlarge
      c6i.12xlarge
      c6i.8xlarge
      c6id.12xlarge
      c6id.8xlarge
      c7g.12xlarge
      c7g.8xlarge
      m5.12xlarge
      m5.4xlarge
      m5.8xlarge
      m5a.12xlarge
      m5a.4xlarge
      m5a.8xlarge
      m5ad.12xlarge
      m5ad.4xlarge
      m5ad.8xlarge
      m5d.12xlarge
      m5d.4xlarge
      m5d.8xlarge
      m6a.12xlarge
      m6a.4xlarge
      m6a.8xlarge
      m6g.12xlarge
      m6g.4xlarge
      m6g.8xlarge
      m6gd.12xlarge
      m6gd.4xlarge
      m6gd.8xlarge
      m6i.12xlarge
      m6i.4xlarge
      m6i.8xlarge
      m6id.12xlarge
      m6id.4xlarge
      m6id.8xlarge
      m7g.12xlarge
      m7g.4xlarge
      m7g.8xlarge
      r5.12xlarge
      r5.4xlarge
      r5.8xlarge
      r5a.12xlarge
      r5a.4xlarge
      r5a.8xlarge
      r5ad.12xlarge
      r5ad.4xlarge
      r5ad.8xlarge
      r5d.12xlarge
      r5d.4xlarge
      r5d.8xlarge
      r6a.12xlarge
      r6a.4xlarge
      r6a.8xlarge
      r6g.12xlarge
      r6g.4xlarge
      r6g.8xlarge
      r6gd.12xlarge
      r6gd.4xlarge
      r6gd.8xlarge
      r6i.12xlarge
      r6i.4xlarge
      r6i.8xlarge
      r6id.12xlarge
      r6id.4xlarge
      r6id.8xlarge
      r7g.12xlarge
      r7g.4xlarge
      r7g.8xlarge
  Resources:
    Requests:
      Cpu:     15880m
      Memory:  44682Mi
      Pods:    13
  Taints:
    Effect:  NoSchedule
    Key:     role
    Value:   client-code-isolation
Status:
  Allocatable:
    Cpu:                  15890m
    Ephemeral - Storage:  89Gi
    Memory:               57632Mi
    Pods:                 234
  Capacity:
    Cpu:                  16
    Ephemeral - Storage:  100Gi
    Memory:               60561Mi
    Pods:                 234
  Conditions:
    Last Transition Time:  2023-08-18T15:57:58Z
    Status:                True
    Type:                  MachineInitialized
    Last Transition Time:  2023-08-18T15:57:16Z
    Status:                True
    Type:                  MachineLaunched
    Last Transition Time:  2023-08-18T15:57:44Z
    Status:                True
    Type:                  MachineRegistered
    Last Transition Time:  2023-08-18T15:57:58Z
    Status:                True
    Type:                  Ready
  Node Name:               ip-10-1-219-238.us-west-2.compute.internal
  Provider ID:             aws:///us-west-2a/i-037515f8de0a97bc4
Events:                    <none>
```

```yaml
Name:               ip-10-1-219-238.us-west-2.compute.internal
Roles:              <none>
Labels:             beta.kubernetes.io/arch=arm64
                    beta.kubernetes.io/instance-type=m6g.4xlarge
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=us-west-2
                    failure-domain.beta.kubernetes.io/zone=us-west-2a
                    k8s.io/cloud-provider-aws=dec6a35e7a2754b20a51adffa2903a76
                    karpenter.k8s.aws/instance-category=m
                    karpenter.k8s.aws/instance-cpu=16
                    karpenter.k8s.aws/instance-encryption-in-transit-supported=false
                    karpenter.k8s.aws/instance-family=m6g
                    karpenter.k8s.aws/instance-generation=6
                    karpenter.k8s.aws/instance-hypervisor=nitro
                    karpenter.k8s.aws/instance-memory=65536
                    karpenter.k8s.aws/instance-network-bandwidth=5000
                    karpenter.k8s.aws/instance-pods=234
                    karpenter.k8s.aws/instance-size=4xlarge
                    karpenter.sh/capacity-type=spot
                    karpenter.sh/initialized=true
                    karpenter.sh/provisioner-name=client-code-isolation
                    karpenter.sh/registered=true
                    kubernetes.io/arch=arm64
                    kubernetes.io/hostname=ip-10-1-219-238.us-west-2.compute.internal
                    kubernetes.io/os=linux
                    node.kubernetes.io/instance-type=m6g.4xlarge
                    role=client-code-isolation
                    topology.ebs.csi.aws.com/zone=us-west-2a
                    topology.kubernetes.io/region=us-west-2
                    topology.kubernetes.io/zone=us-west-2a
Annotations:        alpha.kubernetes.io/provided-node-ip: 10.1.219.238
                    csi.volume.kubernetes.io/nodeid:
                      {"ebs.csi.aws.com":"i-037515f8de0a97bc4","secrets-store.csi.k8s.io":"ip-10-1-219-238.us-west-2.compute.internal"}
                    karpenter.sh/managed-by: prd-usw2a
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Fri, 18 Aug 2023 08:57:44 -0700
Taints:             role=client-code-isolation:NoSchedule
Unschedulable:      false
Lease:              Failed to get lease: leases.coordination.k8s.io "ip-10-1-219-238.us-west-2.compute.internal" not found
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Fri, 18 Aug 2023 08:58:14 -0700   Fri, 18 Aug 2023 08:57:44 -0700   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Fri, 18 Aug 2023 08:58:14 -0700   Fri, 18 Aug 2023 08:57:44 -0700   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Fri, 18 Aug 2023 08:58:14 -0700   Fri, 18 Aug 2023 08:57:44 -0700   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Fri, 18 Aug 2023 08:58:14 -0700   Fri, 18 Aug 2023 08:57:57 -0700   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:   10.1.219.238
  InternalDNS:  ip-10-1-219-238.us-west-2.compute.internal
  Hostname:     ip-10-1-219-238.us-west-2.compute.internal
Capacity:
  cpu:                16
  ephemeral-storage:  103189828Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  hugepages-32Mi:     0
  hugepages-64Ki:     0
  memory:             64400336Ki
  pods:               234
Allocatable:
  cpu:                15790m
  ephemeral-storage:  94026003504
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  hugepages-32Mi:     0
  hugepages-64Ki:     0
  memory:             58973136Ki
  pods:               234
System Info:
  Machine ID:                 ec2815de8413128023d05a8b91438d4e
  System UUID:                ec2815de-8413-1280-23d0-5a8b91438d4e
  Boot ID:                    d6a0adeb-24de-49bc-b955-facaf9034852
  Kernel Version:             5.15.117
  OS Image:                   Bottlerocket OS 1.14.3 (aws-k8s-1.26)
  Operating System:           linux
  Architecture:               arm64
  Container Runtime Version:  containerd://1.6.20+bottlerocket
  Kubelet Version:            v1.26.6-eks-3316523
  Kube-Proxy Version:         v1.26.6-eks-3316523
ProviderID:                   aws:///us-west-2a/i-037515f8de0a97bc4
Non-terminated Pods:          (12 in total)
  Namespace                   Name                                                  CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                                  ------------  ----------  ---------------  -------------  ---
  buoyant-cloud               buoyant-cloud-metrics-8jqzf                           110m (0%)     1 (6%)      1500Mi (2%)      2Gi (3%)       58s
  consul                      consul-client-qfdz5                                   80m (0%)      0 (0%)      150Mi (0%)       200Mi (0%)     58s
  datadog                     datadog-65lxr                                         100m (0%)     0 (0%)      250Mi (0%)       300Mi (0%)     58s
  fluentd                     fluent-bit-kk9g5                                      100m (0%)     0 (0%)      700Mi (1%)       1000Mi (1%)    58s
  kube-system                 aws-node-tcs6d                                        25m (0%)      0 (0%)      0 (0%)           0 (0%)         58s
  kube-system                 ebs-csi-node-72nlz                                    30m (0%)      0 (0%)      120Mi (0%)       768Mi (1%)     58s
  kube-system                 kube-proxy-vsx9q                                      100m (0%)     0 (0%)      0 (0%)           0 (0%)         58s
  kube-system                 node-local-dns-sz4xs                                  25m (0%)      0 (0%)      50Mi (0%)        0 (0%)         58s
  lacework                    lacework-agent-jn5zh                                  200m (1%)     500m (3%)   512Mi (0%)       1450Mi (2%)    58s
  monitoring                  prometheus-operator-prometheus-node-exporter-tdjkj    50m (0%)      500m (3%)   100Mi (0%)       100Mi (0%)     58s
  secrets-store-csi-driver    secrets-store-csi-driver-b9xfw                        40m (0%)      400m (2%)   290Mi (0%)       450Mi (0%)     58s
  vault                       vault-k8s-csi-provider-qjjcm                          20m (0%)      0 (0%)      50Mi (0%)        512Mi (0%)     58s
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests     Limits
  --------           --------     ------
  cpu                880m (5%)    2400m (15%)
  memory             3722Mi (6%)  6828Mi (11%)
  ephemeral-storage  0 (0%)       0 (0%)
  hugepages-1Gi      0 (0%)       0 (0%)
  hugepages-2Mi      0 (0%)       0 (0%)
  hugepages-32Mi     0 (0%)       0 (0%)
  hugepages-64Ki     0 (0%)       0 (0%)
Events:
  Type     Reason                   Age                From                   Message
  ----     ------                   ----               ----                   -------
  Normal   Starting                 54s                kube-proxy             
  Normal   Synced                   58s                cloud-node-controller  Node synced successfully
  Normal   Starting                 58s                kubelet                Starting kubelet.
  Warning  InvalidDiskCapacity      58s                kubelet                invalid capacity 0 on image filesystem
  Normal   NodeHasSufficientMemory  58s (x2 over 58s)  kubelet                Node ip-10-1-219-238.us-west-2.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    58s (x2 over 58s)  kubelet                Node ip-10-1-219-238.us-west-2.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     58s (x2 over 58s)  kubelet                Node ip-10-1-219-238.us-west-2.compute.internal status is now: NodeHasSufficientPID
  Normal   NodeAllocatableEnforced  58s                kubelet                Updated Node Allocatable limit across pods
  Normal   RegisteredNode           57s                node-controller        Node ip-10-1-219-238.us-west-2.compute.internal event: Registered Node ip-10-1-219-238.us-west-2.compute.internal in Controller
  Normal   NodeReady                45s                kubelet                Node ip-10-1-219-238.us-west-2.compute.internal status is now: NodeReady
```

**Comment by dschaaff** [comment]
Here is our node template for reference 

```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: cordial-bottlerocket
spec:
  amiFamily: Bottlerocket
  metadataOptions:
    httpEndpoint: enabled
    httpPutResponseHopLimit: 2 # required for imdsv2 to work in containers
    httpTokens: optional
  subnetSelector:
    subnet_role: eks
    Tier: private
  securityGroupSelector:
    aws-ids: ${cluster_security_group_id},${worker_security_group_id},${consul_client_sg_id}
  tags:
    karpenter.sh/discovery: ${cluster_name}
  blockDeviceMappings:
    # root device for bottlerocket is small and immutable
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 2Gi
        volumeType: gp3
        encrypted: true
        kmsKeyID: "${aws_ebs_kms_key_arn}"
        deleteOnTermination: true
        throughput: 125
    # this voluem is used for container data
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        encrypted: true
        kmsKeyID: "${aws_ebs_kms_key_arn}"
        deleteOnTermination: true
        throughput: 125
  userData: |
    [settings.metrics]
    send-metrics = false
    [settings.bootstrap-containers.setup-runtime-storage]
    source = "redacted.dkr.ecr.us-west-2.amazonaws.com/cordial/bottlerocket-instance-store-bootstrap:main-597227bd"
    mode = "always"
    essential = false
    [settings.kubernetes]
    event-qps = 50
    event-burst = 100
    registry-qps = 100
    registry-burst = 200
    kube-api-qps = 50
    kube-api-burst = 100
    allowed-unsafe-sysctls = ["net.core.somaxconn", "net.ipv4.tcp_*", "net.ipv4.ip_local_reserved_ports"]
    shutdown-grace-period = "30s"
    shutdown-grace-period-for-critical-pods = "10s"
    [settings.kernel.sysctl]
    "kernel.yama.ptrace_scope" = "0"
    [settings.kubernetes.kube-reserved]
    cpu = "200m"
    memory = "5000Mi"
    [settings.kubernetes.system-reserved]
    cpu = "10m"
    memory = "200Mi"
```
