### ISSUE TITLE
Node stuck in `DeprovisioningBlocked` with 1/2 Status Checks passed. `required label "karpenter.sh/capacity-type" doesn't exist`

### ISSUE THREAD

**Issue by LolloneS** [aws/karpenter#4484]
### Description

**Observed Behavior**:

A node created by Karpenter:
- is not removed by Karpenter
- only passes 1/2 status checks on AWS
- cannot be accessed via SSH (all the other nodes can)

The events on the node report the following:

```
Events:
  Type    Reason                 Age                   From             Message
  ----    ------                 ----                  ----             -------
  Normal  DeprovisioningBlocked  9m43s (x25 over 67m)  karpenter        Cannot deprovision node due to required label "karpenter.sh/capacity-type" doesn't exist
  Normal  RegisteredNode         7m8s                  node-controller  Node $NODE_NAME event: Registered Node $NODE_NAME in Controller
  Normal  DeprovisioningBlocked  38s (x4 over 7m26s)   karpenter        Cannot deprovision node due to required label "karpenter.sh/capacity-type" doesn't exist
```

Indeed, the node did not have all the `karpenter.sh` labels that all other nodes created by the same `Provisioner` had. It only had the following 2 `karpenter.sh` labels:

```
karpenter.sh/initialized=true
karpenter.sh/registered=true
```

<img width="1450" alt="Screenshot 2023-08-23 at 11 04 24" src="https://github.com/aws/karpenter/assets/17729031/cda29124-534f-4224-a32a-d5cf25cdd095">

As we can see, the node was stuck for 5 days in a failed status check scenario. I had to delete it manually.

**Expected Behavior**:

If a node does not show 2/2 status checks passed and is somehow unhealthy according to AWS, it should eventually deleted after a certain period of time (e.g. 1h).

**Reproduction Steps** (Please include YAML):

No reproduction steps as all the other nodes created by the same `Provisioner` work flawlessly. I believe this is something that simply requires some fix in the logic to check if a node is healthy

**Versions**:
- Chart Version: Karpenter 0.29.2: https://github.com/aws/karpenter/releases/tag/v0.29.2
- Kubernetes Version (`kubectl version`): `Major:"1", Minor:"24", GitVersion:"v1.24.13"`

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
@LolloneS One thing I'm curious about here is why the appropriate labels weren't propagated onto the node like we would expect. Is there anything in the Karpenter logs or in your setup that might indicate why Karpenter didn't add _any_ of its labels onto the node other than the registered and initialized labels?

**Comment by LolloneS** [comment]
Hi @jonathan-innis I don't think we have anything strange in our configuration. Karpenter is installed via Helm chart. Here is a sample provisioner we are using. I also believe we only started seeing this in v0.29, whereas we were running 0.27 earlier and saw no issues.


```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: provisioner-spot
spec:
  consolidation:
    enabled: true
  kubeletConfiguration:
    maxPods: 110
  labels:
    cluster: clustername
    managed-by: karpenter
    nodepool: nodepoolid
    role: worker
  limits:
    resources:
      cpu: 4k
      memory: 4000Gi
  provider:
    launchTemplate: clustername-nodepoolid-LaunchTemplate
    subnetSelector:
      tag: value
    tags:
      Name: clusterid-karpenter-spot-worker
      cluster: clusterid
      managed-by: karpenter
      nodepool: nodepoolid
  requirements:
  - key: karpenter.k8s.aws/instance-family
    operator: In
    values:
    - m6a
    - m6i
    - m5a
    - m5
    - r6a
    - r6i
    - r5
    - r5a
    - c6a
    - c6i
    - c5
    - c5a
  - key: karpenter.k8s.aws/instance-size
    operator: In
    values:
    - 4xlarge
    - 8xlarge
    - 9xlarge
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
  - key: karpenter.k8s.aws/instance-hypervisor
    operator: In
    values:
    - nitro
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - eu-west-1a
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  startupTaints:
  - effect: NoExecute
    key: node.cilium.io/agent-not-ready
    value: "true"
  ttlSecondsUntilExpired: 86400
  weight: 8
```
