### ISSUE TITLE
Why was extra disks added . When I specify ebs and ami.

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter#4537]
### Description

- version: v0.29.2

- my Provisioner and AWSNodeTemplate
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: test-group
spec:
  requirements:
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: [ "spot", "on-demand" ]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m6i.2xlarge"]
  labels:
    group: xxxxxx
  consolidation:
    enabled: true
  limits:
    resources:
      cpu: 1000
  providerRef:
    name: test-group
  kubeletConfiguration:
    imageGCHighThresholdPercent: 70
    imageGCLowThresholdPercent: 50
  startupTaints:
    - key: node.cilium.io/agent-not-ready
      value: "true"
      effect: NoExecute
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: test-group
spec:
  subnetSelector:
    aws-ids: "subnet-xxx,subnet-xxx,subnet-xxx"
  securityGroupSelector:
    aws-ids: "sg-xxx,sg-xxx"
  amiSelector:
    aws-ids: ami-05a4284d92d6dxxxx
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        volumeSize: 80Gi
        deleteOnTermination: true
        encrypted: true
        iops: 3000
        throughput: 125
```

first node

- result:
I expanded this provider to 3 nodes. Looking at the storage of the 3 nodes, only the first one is what I want. 
The other two automatically add a few unwanted disks. I don't know why.

second node

<img width="695" alt="image" src="https://github.com/aws/karpenter/assets/60080355/e839653c-ce35-4389-b93a-bf5f4ce87371">

Third node
<img width="627" alt="image" src="https://github.com/aws/karpenter/assets/60080355/20730ac4-3f36-4e08-8cee-7f638be24905">

<img width="628" alt="image" src="https://github.com/aws/karpenter/assets/60080355/60197ba5-096f-4499-9b04-d6fae95de274">
