### ISSUE TITLE
is:issue is:open ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "eng-node-group", incompatible requirements, label "eks.amazonaws.com/nodegroup" does not have known values;

### ISSUE THREAD

**Issue by nandeeshb09** [aws/karpenter#4538]
### Description

**Observed Behavior**: I am trying to apply provision-er and node-template, but every time am getting this error, please help on this.

We have 3 nodegroups on EKS cluster with different ami id.

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: eng-node-group
spec:
  requirements:
    # Include general purpose instance families
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [t3a]
    # Exclude small instance sizes
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values: [nano, micro, small]
  providerRef:
    name: eng-node-group
  ttlSecondsAfterEmpty: 30
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: eng-node-group
spec:
  subnetSelector:
    karpenter.sh/discovery: "cluster-name" # replace with your cluster name
  securityGroupSelector:
    karpenter.sh/discovery: "cluster-name" # replace with your cluster name
  amiSelector:
    aws::ids: "ami-id"
```

**Expected Behavior**:  Its should provision nodes, but its not working for any.

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 1.26.1
- Kubernetes Version (`kubectl version`): 1.22

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
If there's a label that Karpenter isn't aware what the values are, these labels need to be defined at the Provisioner-level. In this case, you need to add a requirment that looks like this into your Provisioner

```yaml
requirements:
- key: eks.amazonaws.com/nodegroup
  operator: In
  values: <insert-expected-values-here>
```
