### ISSUE TITLE
awsNodeTemplate doesnt populate status field

### ISSUE THREAD

**Issue by shmuelarditi** [aws/karpenter#4549]
### Description

**Observed Behavior**:
The AWSNodeTemplate status is not being populated in my QA cluster. Karpenter logs indicate that subnets, security groups, and other AWS-specific configurations have been discovered, but these details are not reflected in the AWSNodeTemplate.

important to say, that i did the exact same thing in production and there the awsNodeTemplate does have all the info under the status field. 
the only reason i noticed it is trying to enable drift through featuregate, and looking at the logs on the controller it sayed:
"error": "getting drift, calculating securitygroup drift, no security groups exist in the AWSNodeTemplate Status" - super wierd we see in the logs they ahve been discovered.

i must say: everything works in terms on provisioning, nodes are provisioned and consolidation is working great, its just drift thats not able to work becuase status field does not exist in the awsNodeTemplate YAML..

**Expected Behavior**:
The AWSNodeTemplate status should be populated with the discovered AWS resources like subnets and security groups, AMI's, etc..

**Reproduction Steps** (Please include YAML):
1. Deploy Karpenter in a QA cluster using the helm chart v0.30.0
here is the terraform resource that deploys the helm chart, including the user values.
```resource "helm_release" "karpenter" {
  count            = var.install_karpenter_infra ? 1 : 0
  namespace        = "karpenter"
  create_namespace = true

  name                = "karpenter"
  repository          = "oci://public.ecr.aws/karpenter"
  repository_username = data.aws_ecrpublic_authorization_token.token.user_name
  repository_password = data.aws_ecrpublic_authorization_token.token.password
  chart               = "karpenter"
  version             = "v0.30.0"

  set {
    name  = "settings.aws.clusterName"
    value = module.eks.cluster_name
  }

  set {
    name  = "settings.aws.clusterEndpoint"
    value = module.eks.cluster_endpoint
  }

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = module.karpenter[0].irsa_arn
  }

  set {
    name  = "settings.aws.defaultInstanceProfile"
    value = module.karpenter[0].instance_profile_name
  }

  set {
    name  = "settings.aws.interruptionQueueName"
    value = module.karpenter[0].queue_name
  }

  set {
    name  = "settings.featureGates.driftEnabled"
    value = var.karpenter_enable_drift ? "true" : "false"
  }
}
```

2. Deploy AWSNodeTemplate and Provisioner.
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
  providerRef:
    name: default
  consolidation: 
    enabled: true
 ---------------------------------------------
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: module.eks.cluster_name
  instanceProfile: module.karpenter[0].instance_profile_name
  securityGroupSelector:
    karpenter.sh/discovery: module.eks.cluster_name
  tags:
    karpenter.sh/discovery: module.eks.cluster_name
```
**current aws node template in kubernetes:**
```apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  annotations:
    karpenter.k8s.aws/nodetemplate-hash: "3240623596759806007"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"karpenter.k8s.aws/v1alpha1","kind":"AWSNodeTemplate","metadata":{"annotations":{},"name":"default"},"spec":{"instanceProfile":"Karpenter-minutecloud-qa-20230802131924822300000007","securityGroupSelector":{"karpenter.sh/discovery":"minutecloud-qa"},"subnetSelector":{"karpenter.sh/discovery":"minutecloud-qa"},"tags":{"karpenter.sh/discovery":"minutecloud-qa"}}}
  creationTimestamp: "2023-09-03T14:01:08Z"
  generation: 1
  name: default
  resourceVersion: "418859471"
  uid: cae25222-b360-4a53-963a-527132c43ece
spec:
  instanceProfile: Karpenter-minutecloud-qa-20230802131924822300000007
  securityGroupSelector:
    karpenter.sh/discovery: minutecloud-qa
  subnetSelector:
    karpenter.sh/discovery: minutecloud-qa
  tags:
    karpenter.sh/discovery: minutecloud-qa
```

**Versions**:
- Chart Version: 0.30.0 (same thing happend in 0.29.0 as well so i tried upgrading)
- Kubernetes Version: v1.25 - EKS
