### ISSUE TITLE
Deprovisioning not triggered on `AWSNodeTemplate.amiSelector` modification

### ISSUE THREAD

**Issue by avnerv** [aws/karpenter#4559]
### Description

**Observed Behavior**:
modifying the `amiSelector` in the `AWSNodeTemplate ` didn't cause the karpenter nodes to be deprovisioned, and the `karpenter.k8s.aws/nodetemplate-hash` remains unchanged as well

**Expected Behavior**:
wrt https://karpenter.sh/docs/concepts/deprovisioning/#two-way-reconciliation, when modifying the `amiSelector` it should detect the machine as drifted by update the `karpenter.k8s.aws/nodetemplate-hash` 

**Reproduction Steps** (Please include YAML): (using terraform)
```
# node templates
resource "kubectl_manifest" "node_template" {
  for_each = local.node_templates

  yaml_body = yamlencode({
    apiVersion = "karpenter.k8s.aws/v1alpha1"
    kind       = "AWSNodeTemplate"
    metadata = {
      name = each.value.name
    }
    spec = {
      amiFamily = "Bottlerocket"
      # to allow deprovisioning when upgrade eks https://karpenter.sh/docs/concepts/deprovisioning/#drift
      amiSelector = {
        "aws::name" = "bottlerocket-aws-k8s-1.25-x86_64-v1.14.3-764e37e4"
      }
      blockDeviceMappings = [
        {
          deviceName = "/dev/xvda"
          ebs = {
            deleteOnTermination = true
            encrypted           = true
            kmsKeyID            = data.aws_kms_key.ebs_eks_host_key.arn
            volumeSize          = "50Gi"
            volumeType          = "gp3"
          }
        },
        {
          deviceName = "/dev/xvdb"
          ebs = {
            deleteOnTermination = true
            encrypted           = true
            kmsKeyID            = data.aws_kms_key.ebs_eks_host_key.arn
            volumeSize          = each.value.volumeSize
            volumeType          = "gp3"
            snapshotID          = try(each.value.snapshotID, null)
          }
        },
      ]
      instanceProfile = "${local.prefix}-eks-test-role"
      metadataOptions = {
        httpEndpoint            = "enabled"
        httpProtocolIPv6        = "disabled"
        httpPutResponseHopLimit = 1
        httpTokens              = "required"
      }
      securityGroupSelector = {
        "aws-ids" = "${data.aws_security_group.eks_ng_sg.id},${data.aws_security_group.eks_ng_sg_outbound_mcac.id}"
      }
      subnetSelector = {
        "h2o/subnet-type" = "payload"
      }
      tags = {
        "karpenter.sh/discovery" = "${local.prefix}-eks"
      }
      userData = <<-USERDATA
        [settings.bootstrap-containers.instance-id]
        source = "<AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/bottlerocket-bootstrap:v0.0.4"
        mode = "always"
        essential = true
        [settings.kernel.sysctl]
        "net.ipv4.conf.all.send_redirects" = "0"
        "net.ipv4.conf.all.accept_redirects" = "0"
        "net.ipv6.conf.all.accept_redirects" = "0"
        "net.ipv4.conf.all.secure_redirects" = "0"
        "net.ipv4.conf.default.secure_redirects" = "0"
        "net.ipv4.conf.all.log_martians" = "1"
        "net.ipv4.conf.default.log_martians" = "1"
      USERDATA
    }
  })

  wait = true
}
```
**Versions**:
- Chart Version: `v0.30.0`
- Kubernetes Version (`kubectl version`): `1.25`

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by avnerv** [comment]
> Can you share the `nodetemplate.status.ami` of before and after changing `AMISelector`?

no overlapping afaict

before:
```
status:
  amis:
    - id: ami-0e3be79612fa7c16f
      name: bottlerocket-aws-k8s-1.25-x86_64-v1.14.3-764e37e4
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
```

after:
```
status:
  amis:
    - id: ami-0b6009494b1ef59a3
      name: bottlerocket-aws-k8s-1.25-x86_64-v1.14.2-0ddb8028
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
```
