### ISSUE TITLE
Document how to change kublet log level

### ISSUE THREAD

**Issue by runningman84** [aws/karpenter#4616]
### Description

**How can the docs be improved?**
Please document how we can change the loglevel of kubelet. 

In our case kublet is startet with this params in AL2:
`````
root      1593  2.2  3.0 1816032 119088 ?      Ssl  05:05  11:52 /usr/bin/kubelet --config /etc/kubernetes/kubelet/kubelet-config.json --kubeconfig /var/lib/kubelet/kubeconfig --container-runtime-endpoint unix:///run/containerd/containerd.sock --image-credential-provider-config /etc/eks/image-credential-provider/config.json --image-credential-provider-bin-dir /etc/eks/image-credential-provider --node-ip=10.7.50.87 --pod-infra-container-image=602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/pause:3.5 --v=2 --cloud-provider=aws --container-runtime=remote --node-labels=karpenter.sh/capacity-type=spot,karpenter.sh/provisioner-name=arm --register-with-taints=arch=arm64:NoSchedule --system-reserved=ephemeral-storage=1Gi,memory=200Mi,cpu=250m --kube-reserved=cpu=250m,ephemeral-storage=1Gi,memory=200Mi --eviction-hard=memory.available<0.2Gi,nodefs.available<10%,nodefs.inodesFree<10% --eviction-soft=nodefs.available<15%,nodefs.inodesFree<15%,memory.available<500Mi --eviction-soft-grace-???period=memory.available=3m0s,nodefs.available=3m0s,nodefs.inodesFree=3m0s --eviction-max-pod-grace-period=180
`````

I have no idea where to change the "--v=2" parameter.

I haven't seen this setting here: https://karpenter.sh/preview/concepts/provisioners/#speckubeletconfiguration

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Does this not work?

https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#LoggingConfiguration

https://karpenter.sh/docs/concepts/node-templates/#al2-and-ubuntu

```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: kubelet-config-example
spec:
  subnetSelector:
    karpenter.sh/discovery: my-cluster
  securityGroupSelector:
    karpenter.sh/discovery: my-cluster
  userData: |
    #!/bin/bash
    echo "$(jq '.kubeAPIQPS=50' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json
```

I could see us supporting logging configuration as a first class parameter.
