### ISSUE TITLE
Karpenter reports provisioner status wrong when empty 

### ISSUE THREAD

**Issue by yuval-almog** [aws/karpenter#4628]
### Description

**Observed Behavior**:
After upgrading to latest karpenter version (0.30.0) we've noticed the provisioner is still reporting cores ,ephemeral-storage, memory pods when there actually are zero nodes in the provisioner 

We have an example provisioner: 
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  annotations:
    karpenter.sh/provisioner-hash: "17279383624591743851"
  creationTimestamp: "2023-04-16T13:23:03Z"
  generation: 6
  labels:
    karpenter.sh/capacity-type: on-demand
  name: r6i-reserved
spec:
  consolidation:
    enabled: true
  kubeletConfiguration:
    clusterDNS:
    - 169.254.20.10
    containerRuntime: containerd
  labels:
    karpenter.sh/capacity-type: on-demand
  limits:
    resources:
      cpu: "0"
  providerRef:
    name: default-node-template
  requirements:
  - key: karpenter.k8s.aws/instance-family
    operator: In
    values:
    - r6i
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: karpenter.k8s.aws/instance-generation
    operator: Gt
    values:
    - "4"
  - key: karpenter.k8s.aws/instance-generation
    operator: Lt
    values:
    - "8"
  - key: karpenter.k8s.aws/instance-cpu
    operator: Lt
    values:
    - "20"
  - key: karpenter.k8s.aws/instance-cpu
    operator: Gt
    values:
    - "0"
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  weight: 48
status:
  resources:
    cpu: "2"
    ephemeral-storage: 104845292Ki
    memory: 16098260Ki
    pods: "29"
```
As you can see status is reported as 2 cores, 29 pods 
However we have no nodes created by this provisioner. The following command returns: 
```
kubectl get machine -l karpenter.sh/provisioner-name=r6i-reserved
No resources found

```
**Expected Behavior**:
Provisioner status should be accurate 

**Reproduction Steps** (Please include YAML):
Create a test provisioner add one node and then remove the node to leave the provisioner with no nodes and look at the status 

**Versions**:
- Chart Version:  0.30.0 
- Kubernetes Version (`kubectl version`):  1.26 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
This is very surprising to me. Do you have any logs from the event? Is it possible that the controller did not have permission to update the status?

**Comment by yuval-almog** [comment]
Hi @ellistarn this problem persist after karpenter pod restart and I still see this issue in my cluster however when i search the logs for this provisioner name I can't find any mention for it 

this is our cluster role 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.30.0
    helm.sh/chart: karpenter-0.30.0
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
  name: karpenter-admin
rules:
  - apiGroups:
      - karpenter.sh
    resources:
      - provisioners
      - provisioners/status
      - machines
      - machines/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
  - apiGroups:
      - karpenter.k8s.aws
    resources:
      - awsnodetemplates
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
```
