### ISSUE TITLE
karpenter 0.30.0 new default securityContexts can break sidecars

### ISSUE THREAD

**Issue by bcha** [aws/karpenter#4657]
### Description

**Observed Behavior**:
We're running Karpenter in EKS Fargate, with Datadog sidecar container to gather metrics etc.
In karpenter 0.30.0 https://github.com/aws/karpenter/pull/4320 removes the ability to define securityContexts in values.yaml -> Datadog sidecar can't handle the new default securityContexts on Pod level -> CrashLoop. 

Of course this isn't datadog-specific issue, the same problem can happen for pretty much any sidecar container that can't handle the new securityContexts.

**Expected Behavior**:
I'd love it if we'd be able to overwrite those default Pod level securityContexts by hand to workaround this. Now it seems like our only sane options are to either a) stop updating Karpenter or b) get rid of the datadog sidecar & lose metrics etc.

**Reproduction Steps** (Please include YAML):
1. install karpenter 0.30.0 with controller.sidecarContainer that can't handle the defaults.

in our values.yaml:
```yaml
controller:
  sidecarContainer:
    - image: public.ecr.aws/datadog/agent:latest
      name: datadog-agent
      env:
        - name: DD_API_KEY
          value: nnn
        - name: DD_SITE
          value: "datadoghq.eu"
        - name: DD_EKS_FARGATE
          value: "true"
        - name: DD_CLUSTER_NAME
          value: nnn
        - name: DD_PROMETHEUS_SCRAPE_ENABLED
          value: "true"
        - name: DD_PROMETHEUS_SCRAPE_CHECKS
          value: '[{"autodiscovery":{"kubernetes_annotations":{"exclude":{"prometheus.io/scrape":"false"},"include":{"prometheus.io/scrape":"true"}},"kubernetes_container_names":["gitlab-runner-*","controller*"]},"configurations":[{"max_returned_metrics":5000}]}]'
        - name: DD_PROMETHEUS_SCRAPE_VERSION
          value: "2"
        - name: DD_KUBERNETES_KUBELET_NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
```

**Versions**:
- Chart Version: 0.30.0
- Kubernetes Version (`kubectl version`): 1.25

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Have you tried setting the securityContext directly on the sidecar container spec that you have above? K8s should respect that securityContext as an override for the top-level pod securityContext

**Comment by ami-descope** [comment]
@bcha 

were you able to define a security context for datadog container on 0.31.1?

im struggling to get this to work, right now datafog makes karpenter controller fail

**Comment by bcha** [comment]
> @bcha
> 
> were you able to define a security context for datadog container on 0.31.1?
> 
> im struggling to get this to work, right now datafog makes karpenter controller fail

We upgraded to 0.31.1 and added the datadog sidecar back with podSecurityContext & controller.securityContext in values. Works fine now.

**Comment by erulabs** [comment]
@bcha Would it be possible to provide your helm chart's values? I've been unable to get karpenter metrics scraped into datadog with the following config:

```
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8000"

controller:
  sidecarContainer:
    - name: datadog-agent
      image: public.ecr.aws/datadog/agent:latest
      env:
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              key: api-key
              name: datadog-secret
        - name: DD_SITE
          value: "datadoghq.com"
        - name: DD_EKS_FARGATE
          value: "true"
        - name: DD_CLUSTER_NAME
          value: "${clusterName}"
        - name: DD_PROMETHEUS_SCRAPE_ENABLED
          value: "true"
        - name: DD_PROMETHEUS_SCRAPE_CHECKS
          value: '[{"autodiscovery":{"kubernetes_annotations":{"exclude":{"prometheus.io/scrape":"false"},"include":{"prometheus.io/scrape":"true"}},"kubernetes_container_names":["karpenter*"]},"configurations":[{"max_returned_metrics":5000}]}]'
        - name: DD_PROMETHEUS_SCRAPE_VERSION
          value: "2"
        - name: DD_KUBERNETES_KUBELET_NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
```
