### ISSUE TITLE
v0.30.0 Karpenter Two Subnets Specified, but Only One Subnet Used

### ISSUE THREAD

**Issue by jhyoonzi** [aws/karpenter#4675]
### Description

**Observed Behavior**:

**Expected Behavior**:

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version:  v0.30.0
- Kubernetes Version (`kubectl version`):  eks 1.27

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
-------------------------------------------------------------------------------------------------------------------------
Hello.

Provisioning AWS nodes with Karpenter. I'm asking because there's a problem during the test.

I set zone setting a,c and subnet selector available area a,c as shown below, but Carpenter is using only the available area c subnet, not the available area a subnet Is there something wrong with the setup? 

Below is a provisioning example.

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: karpenter-provisioner
spec:    
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["t3.medium", "t3.large", "t3.xlarge"]  
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-east-1a", "us-east-1c"]      
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand","spot"]  
  limits:
    resources:
      cpu: "1000"
      memory: 1000Gi
  ttlSecondsAfterEmpty: 30
  labels:
    role: ops
    provision: karpenter
  provider:
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        volumeSize: 50Gi
        volumeType: gp3
    securityGroupSelector:
      karpenter.sh/discovery: centennial
    subnetSelector:
      aws-ids: subnet-a, subnet-c
    tags:
      Name: karpenter.sh/centennial
      karpenter.sh/discovery: centennial
```
