### ISSUE TITLE
Instance gets deleted instantly after creation

### ISSUE THREAD

**Issue by ochabaiev-boku** [aws/karpenter#4676]
### Description

**Setup**
EKS cluster created with module:
```hcl
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.0"

  cluster_name    = local.eks_name
  cluster_version = var.eks_version

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = false

  cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {}
    vpc-cni = {
      resolve_conflicts = "OVERWRITE"
    }
  }

  vpc_id     = module.vpc_data.vpc_id
  subnet_ids = module.vpc_data.private_subnets

  cluster_security_group_additional_rules = {
    ingress_dev = {
      description = "All HTTPS"
      protocol    = "TCP"
      from_port   = 443
      to_port     = 443
      type        = "ingress"
      cidr_blocks = [data.aws_vpc.parent.cidr_block]
    }
    egress_dev = {
      description = "All traffic outbound to NAT."
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "egress"
      cidr_blocks = ["0.0.0.0/0"]
    }
    ingress_nodes_karpenter_ports_tcp = {
      description                = "Karpenter readiness"
      protocol                   = "tcp"
      from_port                  = 8443
      to_port                    = 8443
      type                       = "ingress"
      source_node_security_group = true
    }
  }

  eks_managed_node_group_defaults = {
    disk_size      = 8
    instance_types = ["c5.xlarge"]
  }

  eks_managed_node_groups = {
    apps = {
      min_size     = 1
      max_size     = 10
      desired_size = 1

      instance_types = ["c5.xlarge"]
      capacity_type  = "SPOT"
    }
  }

  node_security_group_additional_rules = {
    ingress_dev = {
      description = "All HTTPS"
      protocol    = "TCP"
      from_port   = 443
      to_port     = 443
      type        = "ingress"
      cidr_blocks = [data.aws_vpc.parent.cidr_block]
    }
    egress_dev= {
      description = "All traffic outbound to NAT."
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "egress"
      cidr_blocks = ["0.0.0.0/0"]
    }
    aws_lb_controller_webhook = {
      description                   = "Cluster API to AWS LB Controller webhook"
      protocol                      = "all"
      from_port                     = 9443
      to_port                       = 9443
      type                          = "ingress"
      source_cluster_security_group = true
    }
  }

  create_aws_auth_configmap = true
  manage_aws_auth_configmap = true
  aws_auth_users            = var.eks_users
  aws_auth_accounts         = var.eks_accounts
  aws_auth_roles = [
    # add in the Karpenter node IAM role for nodes launched by Karpenter
    {
      rolearn  = module.karpenter.role_arn
      username = "system:node:{{EC2PrivateDNSName}}"
      groups = [
        "system:bootstrappers",
        "system:nodes",
      ]
    },
  ]

  cluster_tags = var.assignment_tags
  tags = {
    "karpenter.sh/discovery" = local.eks_name
  }

  providers = {
    kubernetes = kubernetes.data-cluster
  }
}
```
Additionally ebs csi addon installed:
```hcl
module "ebs_csi_driver_controller" {
  source  = "DrFaust92/ebs-csi-driver/kubernetes"
  version = "3.5.0"

  ebs_csi_controller_image                   = ""
  ebs_csi_controller_role_name               = "data${var.environment}-${var.aws_region}-ebs-csi-"
  ebs_csi_controller_role_policy_name_prefix = "data${var.environment}-${var.aws_region}-ebs-csi-"
  oidc_url                                   = module.eks.cluster_oidc_issuer_url

  providers = {
    kubernetes = kubernetes.data-cluster
  }
}
```

Provisioner:
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  labels:
    provisioner: karpenter-default
  ttlSecondsAfterEmpty: 60 # scale down nodes after 60 seconds without workloads (excluding daemons)
  ttlSecondsUntilExpired: 604800 # expire nodes after 7 days (in seconds) = 7 * 60 * 60 * 24
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [t3, c5, m5, r5]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: [medium, xlarge]
  limits:
    resources:
      cpu: 10
  providerRef:
    name: default
```
Node Template:
```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: ${local.eks_name}
  securityGroupSelector:
    karpenter.sh/discovery: ${local.eks_name}
  tags:
    karpenter.sh/discovery: ${local.eks_name}
```
**Steps:**
Trying to create the pod that requires karpenter provisioner node:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/provisioner-name
                operator: In
                values:
                - default    
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

```

**Observed Behavior**:
Instance gets created and then instantly deleted, the deletion is triggered by interruption message
```log
2023-09-21T12:07:04.449Z	INFO	controller.provisioner	found provisionable pod(s)	{"commit": "f013f7b", "pods": 1}
2023-09-21T12:07:04.449Z	INFO	controller.provisioner	computed new machine(s) to fit pod(s)	{"commit": "f013f7b", "machines": 1, "pods": 1}
2023-09-21T12:07:04.460Z	INFO	controller.provisioner	created machine	{"commit": "f013f7b", "provisioner": "default", "machine": "default-9476z", "requests": {"cpu":"125m","pods":"6"}, "instance-types": "c5.12xlarge, c5.18xlarge, c5.24xlarge, c5.2xlarge, c5.4xlarge and 26 other(s)"}
2023-09-21T12:07:06.640Z	INFO	controller.machine.lifecycle	launched machine	{"commit": "f013f7b", "machine": "default-9476z", "provisioner": "default", "provider-id": "aws:///us-east-2b/i-xxxx", "instance-type": "t3.medium", "zone": "us-east-2b", "capacity-type": "spot", "allocatable": {"cpu":"1930m","ephemeral-storage":"17Gi","memory":"3246Mi","pods":"17"}}
2023-09-21T12:07:07.686Z	INFO	controller.interruption	initiating delete for machine from interruption message	{"commit": "f013f7b", "queue": "Karpenter-datadev-us-east-2", "messageKind": "StateChangeKind", "machine": "default-9476z", "action": "CordonAndDrain"}
2023-09-21T12:07:07.970Z	INFO	controller.machine.termination	deleted machine	{"commit": "f013f7b", "machine": "default-9476z", "node": "", "provisioner": "default", "provider-id": "aws:///us-east-2b/i-xxxx"}
```
This sequence of steps repeats itself in the infinite loop.

**Expected Behavior**:
Node successfully provisioned.

**Note1:**
There's a bit similar case in the [troubleshooting](https://karpenter.sh/docs/troubleshooting/) guide, but in my case the EBS encryption is not enabled.

**Note2:**
I have another cluster in another aws account ad this issue is not reproduced there:
```hcl
module "eks" {
    source  = "terraform-aws-modules/eks/aws"
    version = "19.16.0"

    cluster_name    = local.eks_name
    cluster_version = "1.24"

    cluster_endpoint_private_access = true
    cluster_endpoint_public_access  = true

    cluster_addons = {
        kube-proxy         = {}
        vpc-cni            = {}
        coredns            = {}
        aws-ebs-csi-driver = {
            service_account_role_arn = module.ebs_csi_irsa_role.iam_role_arn
            most_recent              = true
        }
    }

    cluster_addons_timeouts = {
        create = "30m"
    }

    vpc_id     = module.vpc.vpc_id
    subnet_ids = module.vpc.private_subnets

    enable_irsa = true

    manage_aws_auth_configmap = true
    aws_auth_roles            = [
        # add in the Karpenter node IAM role for nodes launched by Karpenter
        {
            rolearn  = module.karpenter.role_arn
            username = "system:node:{{EC2PrivateDNSName}}"
            groups   = [
                "system:bootstrappers",
                "system:nodes",
            ]
        },
    ]

    eks_managed_node_group_defaults = {
        disk_size = 50
    }

    # needed for addons deployments
    eks_managed_node_groups = {
        spots = {
            desired_size = 2
            min_size     = 2
            max_size     = 2

            labels = {
                role        = "spots"
                provisioner = "node-pool-spots"
            }

            instance_types = ["t3.medium"]
            capacity_type  = "SPOT"
        }
    }

    tags = {
        Environment              = var.prefix
        "karpenter.sh/discovery" = local.eks_name
    }
}
```

**Versions**: eks 1.24
- Chart Version: v0.30.0-rc.0
- Kubernetes Version (`kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.16-eks-2d98532", GitCommit:"af930c12e26ef9d1e8fac7e3532ff4bcc1b2b509", GitTreeState:"clean", BuildDate:"2023-07-28T16:52:47Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```
```hcl
  required_providers {
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = "1.14"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "2.17.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "2.10.1"
    }
  }
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
