### ISSUE TITLE
Karpenter ignoring disk size settings

### ISSUE THREAD

**Issue by astropanic** [aws/karpenter#4678]
### Description

**Observed Behavior**:

The default 20GB of storage is to short for my use case with node consolidation enabled.
I want double the space - setting it to 40GB.

My `AWSNodeTemplate`:

```
k get AWSNodeTemplate default -o yaml | k neat
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      encrypted: true
      volumeSize: 4Gi
      volumeType: gp3
  - deviceName: /dev/xvdb
    ebs:
      encrypted: true
      volumeSize: 40Gi
      volumeType: gp3
  instanceProfile: k8s-tbd-karpenter
  securityGroupSelector:
    karpenter.sh/discovery: k8s-tbd
  subnetSelector:
    karpenter.sh/discovery: k8s-tbd
  tags:
    karpenter.sh/discovery: k8s-tbd
```

After creating a new node with the provisioner using the mentioned AWSNodeTemplate the disk is still 20GB in size:

```
[root@admin]# lsblk
NAME         MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0          7:0    0  312K  1 loop /.bottlerocket/rootfs/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/licenses
loop1          7:1    0 12.1M  1 loop /.bottlerocket/rootfs/var/lib/kernel-devel/.overlay/lower
nvme1n1      259:0    0   20G  0 disk
`-nvme1n1p1  259:16   0   20G  0 part /.bottlerocket/rootfs/local
nvme0n1      259:1    0    4G  0 disk
|-nvme0n1p1  259:3    0    4M  0 part
|-nvme0n1p2  259:4    0    5M  0 part
|-nvme0n1p3  259:5    0   40M  0 part /.bottlerocket/rootfs/boot
|-nvme0n1p4  259:6    0  920M  0 part
|-nvme0n1p5  259:7    0   10M  0 part
|-nvme0n1p6  259:8    0   25M  0 part
|-nvme0n1p7  259:9    0    5M  0 part
|-nvme0n1p8  259:10   0   40M  0 part
|-nvme0n1p9  259:11   0  920M  0 part
|-nvme0n1p10 259:12   0   10M  0 part
|-nvme0n1p11 259:13   0   25M  0 part
|-nvme0n1p12 259:14   0   41M  0 part /.bottlerocket/rootfs/var/lib/bottlerocket
`-nvme0n1p13 259:15   0    1M  0 part
```

```
k get node ip-xx-xx-xx-xx.xxx.compute.internal -o yaml | yq .status.capacity.ephemeral-storage
20619092Ki
```

**Expected Behavior**:

The disk size matches the size from the AWSNodeTemplate.

```
[root@admin]# lsblk
NAME         MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0          7:0    0  312K  1 loop /.bottlerocket/rootfs/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/licenses
loop1          7:1    0 12.1M  1 loop /.bottlerocket/rootfs/var/lib/kernel-devel/.overlay/lower
nvme1n1      259:0    0   40G  0 disk
`-nvme1n1p1  259:16   0   40G  0 part /.bottlerocket/rootfs/local
nvme0n1      259:1    0    4G  0 disk
|-nvme0n1p1  259:3    0    4M  0 part
|-nvme0n1p2  259:4    0    5M  0 part
|-nvme0n1p3  259:5    0   40M  0 part /.bottlerocket/rootfs/boot
|-nvme0n1p4  259:6    0  920M  0 part
|-nvme0n1p5  259:7    0   10M  0 part
|-nvme0n1p6  259:8    0   25M  0 part
|-nvme0n1p7  259:9    0    5M  0 part
|-nvme0n1p8  259:10   0   40M  0 part
|-nvme0n1p9  259:11   0  920M  0 part
|-nvme0n1p10 259:12   0   10M  0 part
|-nvme0n1p11 259:13   0   25M  0 part
|-nvme0n1p12 259:14   0   41M  0 part /.bottlerocket/rootfs/var/lib/bottlerocket
`-nvme0n1p13 259:15   0    1M  0 part
```

```
k get node ip-xx-xx-xx-xx.xxx.compute.internal -o yaml | yq .status.capacity.ephemeral-storage
41238184Ki
```

**Reproduction Steps** (Please include YAML):

See above

**Versions**:
- Chart Version: karpenter-v0.27.
- Kubernetes Version (`kubectl version`): v1.24.16-eks-2d98532

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
I created an AWSNodeTemplate with the same spec, and I saw my Machines come up with the right ephemeral storage on v0.30.0, tried again on v0.27.3 and saw the same.
```
  spec:
    amiFamily: Bottlerocket
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        encrypted: true
        volumeSize: 4Gi
        volumeType: gp3
    - deviceName: /dev/xvdb
      ebs:
        encrypted: true
        volumeSize: 40Gi
        volumeType: gp3
```

Node resources:
```
  allocatable:
    cpu: 7910m
    ephemeral-storage: "36953110875"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 14744708Ki
    pods: "58"
  capacity:
    cpu: "8"
    ephemeral-storage: 41261776Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 15761540Ki
    pods: "58"
```
