### ISSUE TITLE
seeing reconcile error for validation webhook

### ISSUE THREAD

**Issue by pdeva** [aws/karpenter#4693]
### Description

**Observed Behavior**:
Seeing the following error in our logs

<img width="725" alt="Screenshot 2023-09-25 at 4 31 08 PM" src="https://github.com/aws/karpenter/assets/3190176/d61d5e84-3527-486f-9144-85fc009317e3">

**Expected Behavior**:
no error
**Reproduction Steps** (Please include YAML):

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    component: karpenter
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    namespace: karpenter
    server: https://kubernetes.default.svc
  source:
    chart: karpenter
    repoURL: public.ecr.aws/karpenter
    targetRevision: "v0.30.0"
    helm:
      releaseName: karpenter
      parameters:
        - name: "logLevel"
          value: "info"
        - name: "logEncoding"
          value: "json"
        - name: "controller.logLevel"
          value: "info"
        - name: "controller.logEncoding"
          value: "json"
        - name: "controller.resources.requests.cpu"
          value: "120m"
        - name: "controller.resources.limits.cpu"
          value: "120m"
        - name: "controller.resources.requests.memory"
          value: "320Mi"
        - name: "controller.resources.limits.memory"
          value: "320Mi"
        - name: 'serviceAccount.annotations.eks\.amazonaws\.com/role-arn'
          value: "arn:aws:iam::335881249174:role/KarpenterIRSA-k1-xx"
        - name: "settings.aws.clusterName"
          value: "k1"
        - name: "settings.aws.clusterEndpoint"
          value: "https://xx.yl4.us-east-1.eks.amazonaws.com"
        - name: "settings.aws.defaultInstanceProfile"
          value: "Karpenter-k1-xx"
        - name: "settings.aws.interruptionQueueName"
          value: "Karpenter-k1"
      values: |
        podAnnotations:
          ad.datadoghq.com/controller.checks: |
            {
              "openmetrics": {
                "init_config": {},
                "instances": [
                  {
                    "openmetrics_endpoint": "http://%%host%%:8000/metrics",
                    "namespace": "karpenter",
                    "metrics": ["karpenter_provisioner.*", "karpenter_nodes_created", "karpenter_nodes_terminated"],
                    "max_returned_metrics": 80
                  }
                ]
              }
            }
        topologySpreadConstraints:
          - maxSkew: 1
            minDomains: 3
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
          - maxSkew: 1
            minDomains: 3
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: DoNotSchedule
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: "*"
      kind: Secret
      name: karpenter-cert
      namespace: karpenter
      jqPathExpressions:
        - .data
    - group: "*"
      kind: MutatingWebhookConfiguration
      name: defaulting.webhook.provisioners.karpenter.sh
      jqPathExpressions:
        - .webhooks[0].rules[]
    - group: "*"
      kind: ValidatingWebhookConfiguration
      name: validation.webhook.provisioners.karpenter.sh
      jqPathExpressions:
        - .webhooks[0].rules[]

```

**Versions**:
- Chart Version: karpenter 0.30
- Kubernetes Version (`kubectl version`):  1.27

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
