### ISSUE TITLE
Kubelet configurations on nodes

### ISSUE THREAD

**Issue by toddatapiture** [aws/karpenter#4711]
### Description

Starting with Kubernetes version 1.27 we should now be able to pull Pod container images in parallel (https://kubernetes.io/blog/2023/05/15/speed-up-pod-startup/#parallel-container-image-pulls). This would be extremely helpful for us since our Pods create 3 containers and pull 3 images upon startup. In order to do this you have to set the Kubelet configuration field `serialImagePulls` to `false`. I was looking through Karpenter documentation and noticed a recommendation from you guys to configure Kubelet on a node using userData (https://karpenter.sh/docs/concepts/node-templates/#specuserdata:~:text=echo%20%22%24(jq%20%27.kubeAPIQPS%3D50%27%20/etc/kubernetes/kubelet/kubelet%2Dconfig.json)%22%20%3E%20/etc/kubernetes/kubelet/kubelet%2Dconfig.json).  I attempted doing the same thing but for the field `serializeImagePulls=false`. It appears to have set the field in Kublet but I don't notice any difference. From the event logs it appears to still be pulling images serially. Also, build times do not reflect any reduction in times. Any ideas or pointers on what I might be doing wrong?

Kubelet Configuration on Karpenter provisioned node:

```
{
  "kubeletconfig": {
    "enableServer": true,
    "syncFrequency": "1m0s",
    "fileCheckFrequency": "20s",
    "httpCheckFrequency": "20s",
    "address": "0.0.0.0",
    "port": 10250,
    "tlsCipherSuites": [
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_RSA_WITH_AES_128_GCM_SHA256"
    ],
    "serverTLSBootstrap": true,
    "authentication": {
      "x509": {
        "clientCAFile": "/etc/kubernetes/pki/ca.crt"
      },
      "webhook": {
        "enabled": true,
        "cacheTTL": "2m0s"
      },
      "anonymous": {
        "enabled": false
      }
    },
    "authorization": {
      "mode": "Webhook",
      "webhook": {
        "cacheAuthorizedTTL": "5m0s",
        "cacheUnauthorizedTTL": "30s"
      }
    },
    "registryPullQPS": 5,
    "registryBurst": 10,
    "eventRecordQPS": 50,
    "eventBurst": 100,
    "enableDebuggingHandlers": true,
    "healthzPort": 10248,
    "healthzBindAddress": "127.0.0.1",
    "oomScoreAdj": -999,
    "clusterDomain": "cluster.local",
    "clusterDNS": [
      "172.20.0.10"
    ],
    "streamingConnectionIdleTimeout": "4h0m0s",
    "nodeStatusUpdateFrequency": "10s",
    "nodeStatusReportFrequency": "5m0s",
    "nodeLeaseDurationSeconds": 40,
    "imageMinimumGCAge": "2m0s",
    "imageGCHighThresholdPercent": 85,
    "imageGCLowThresholdPercent": 80,
    "volumeStatsAggPeriod": "1m0s",
    "cgroupRoot": "/",
    "cgroupsPerQOS": true,
    "cgroupDriver": "systemd",
    "cpuManagerPolicy": "none",
    "cpuManagerReconcilePeriod": "10s",
    "memoryManagerPolicy": "None",
    "topologyManagerPolicy": "none",
    "topologyManagerScope": "container",
    "runtimeRequestTimeout": "2m0s",
    "hairpinMode": "hairpin-veth",
    "maxPods": 118,
    "podPidsLimit": -1,
    "resolvConf": "/etc/resolv.conf",
    "cpuCFSQuota": true,
    "cpuCFSQuotaPeriod": "100ms",
    "nodeStatusMaxImages": 50,
    "maxOpenFiles": 1000000,
    "contentType": "application/vnd.kubernetes.protobuf",
    "kubeAPIQPS": 50,
    "kubeAPIBurst": 100,
    "serializeImagePulls": false,
    "evictionHard": {
      "memory.available": "100Mi",
      "nodefs.available": "10%",
      "nodefs.inodesFree": "5%"
    },
    "evictionPressureTransitionPeriod": "5m0s",
    "enableControllerAttachDetach": true,
    "protectKernelDefaults": true,
    "makeIPTablesUtilChains": true,
    "iptablesMasqueradeBit": 14,
    "iptablesDropBit": 15,
    "featureGates": {
      "RotateKubeletServerCertificate": true
    },
    "failSwapOn": true,
    "memorySwap": {},
    "containerLogMaxSize": "10Mi",
    "containerLogMaxFiles": 5,
    "configMapAndSecretChangeDetectionStrategy": "Watch",
    "kubeReserved": {
      "cpu": "80m",
      "ephemeral-storage": "1Gi",
      "memory": "1553Mi"
    },
    "systemReservedCgroup": "/system",
    "kubeReservedCgroup": "/runtime",
    "enforceNodeAllocatable": [
      "pods"
    ],
    "volumePluginDir": "/usr/libexec/kubernetes/kubelet-plugins/volume/exec/",
    "providerID": "aws:///us-west-2a/i-03463f35a9000c659",
    "logging": {
      "format": "text",
      "flushFrequency": "5s",
      "verbosity": 2,
      "options": {
        "json": {
          "infoBufferSize": "0"
        }
      }
    },
    "enableSystemLogHandler": true,
    "enableSystemLogQuery": false,
    "shutdownGracePeriod": "0s",
    "shutdownGracePeriodCriticalPods": "0s",
    "enableProfilingHandler": true,
    "enableDebugFlagsHandler": true,
    "seccompDefault": false,
    "memoryThrottlingFactor": 0.9,
    "registerWithTaints": [
      {
        "key": "jenkins-agent",
        "value": "true",
        "effect": "NoExecute"
      }
    ],
    "registerNode": true,
    "localStorageCapacityIsolation": true,
    "containerRuntimeEndpoint": "unix:///run/containerd/containerd.sock"
  }
}
```

Pod event logs:

```
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  4m17s  default-scheduler  0/5 nodes are available: 5 node(s) didn't match Pod's node affinity/selector. preemption: 0/5 nodes are available: 5 Preemption is not helpful for scheduling..
  Normal   Nominated         4m16s  karpenter          Pod should schedule on: machine/jenkins-nonprod-sandbox-agent-spot-jpbx9
  Normal   Scheduled         3m17s  default-scheduler  Successfully assigned jenkins-nonprod-sandbox/test-pipeline-273-0l8kr-596df-05r36 to ip-10-50-0-95.us-west-2.compute.internal
  Normal   Pulling           3m16s  kubelet            Pulling image "nexus-shared.community.apiture.com:5000/apiture/community/devops/apiture-base-k8s:stable"
  Normal   Pulled            2m12s  kubelet            Successfully pulled image "nexus-shared.community.apiture.com:5000/apiture/community/devops/apiture-base-k8s:stable" in 1m3.628s (1m3.628s including waiting)
  Normal   Created           2m12s  kubelet            Created container main
  Normal   Started           2m12s  kubelet            Started container main
  Normal   Pulling           2m12s  kubelet            Pulling image "647426478431.dkr.ecr.us-east-1.amazonaws.com/docker:20.10.15-dind"
  Normal   Pulled            2m     kubelet            Successfully pulled image "647426478431.dkr.ecr.us-east-1.amazonaws.com/docker:20.10.15-dind" in 12.293s (12.293s including waiting)
  Normal   Created           2m     kubelet            Created container dind
  Normal   Started           2m     kubelet            Started container dind
  Normal   Pulling           2m     kubelet            Pulling image "jenkins/inbound-agent:4.11-1-jdk11"
  Normal   Pulled            102s   kubelet            Successfully pulled image "jenkins/inbound-agent:4.11-1-jdk11" in 17.798s (17.798s including waiting)
  Normal   Created           101s   kubelet            Created container jnlp
  Normal   Started           93s    kubelet            Started container jnlp
```

**Observed Behavior**:
Sequential container image pulls in Pod

**Expected Behavior**:
Parallel container image pulls in Pod

**Reproduction Steps** (Please include YAML):
1. Update Karpenter AWSNodeTemplate to update Kubelet configuration
2. Deploy changes

```
  apiVersion: karpenter.k8s.aws/v1alpha1
  kind: AWSNodeTemplate
  metadata:
    name: jenkins-agent-spot
  spec:
    amiFamily: AL2
    instanceProfile: KarpenterNodeInstanceProfile-jenkins-nonprod-sandbox-us-west-2
    subnetSelector:
      Name: "jenkins-nonprod-sandbox-private*"
    securityGroupSelector:
      Name: "eks-cluster-sg-jenkins-nonprod-sandbox*"
    userData: |
      MIME-Version: 1.0
      Content-Type: multipart/mixed; boundary="BOUNDARY"

      --BOUNDARY
      Content-Type: text/x-shellscript; charset="us-ascii"

      #!/bin/bash
      echo "$(jq '.serializeImagePulls=false' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json

      --BOUNDARY--
    blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          volumeSize: 100
          volumeType: gp3
          iops: 3000
          throughput: 125
          deleteOnTermination: true
```

**Versions**:
- Chart Version: 0.30
- Kubernetes Version (`kubectl version`):  1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
What does `kubectl get --raw "/api/v1/nodes/<nodename>/proxy/configz"` show for this node?

**Comment by toddatapiture** [comment]
Hi @tzneal! The above kubelet config is from me running that command against the node. I just formatted the JSON.

**Comment by tzneal** [comment]
Can you provide the pod spec for a similar pod?

**Comment by toddatapiture** [comment]
Absolutely! 

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    karpenter.sh/do-not-evict: "true"
  labels:
    name: jenkins-agent
spec:
  serviceAccountName: "default"
  nodeSelector:
    purpose: jenkins-agent
  tolerations:
    - key: "jenkins-agent"
      operator: "Exists"
      effect: "NoExecute"
  containers:
    - name: main
      image: <custom_docker_image>
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
      command: []
      tty: true
      args: []
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
          ephemeral-storage: "1Gi"
        limits:
          memory: "2Gi"
          ephemeral-storage: "2Gi"
      volumeMounts:
        - name: docker-certs-client
          readOnly: true
          mountPath: /certs/client
      imagePullPolicy: Always
      env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DOCKER_HOST
          value: tcp://localhost:2376
        - name: DOCKER_TLS_CERTDIR
          value: "/certs"
        - name: DOCKER_TLS_VERIFY
          value: "1"
        - name: DOCKER_CERT_PATH
          value: "/certs/client"
    - name: dind
      image: <docker-in-docker_image_docker:20.10.15-dind>
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
          ephemeral-storage: "1Gi"
        limits:
          memory: "15Gi"
          ephemeral-storage: "12Gi"
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
        - name: docker-certs-client
          mountPath: /certs/client
        - name: docker-certs-ca
          mountPath: /certs/ca
    - name: jnlp
      image: "jenkins/inbound-agent:4.11-1-jdk11"
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
          ephemeral-storage: "1Gi"
        limits:
          memory: "15Gi"
          ephemeral-storage: "15Gi"
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
  imagePullSecrets:
    - name: default
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: docker-certs-client
      emptyDir: {}
    - name: docker-certs-ca
      emptyDir: {}
    - name: "workspace-volume"
      emptyDir:
        medium: ""
```
