### ISSUE TITLE
Karpenter not respecting the do-not-evict annotation on pods while consolidation is enabled

### ISSUE THREAD

**Issue by koreyGambill** [aws/karpenter#4758]
# Description
**Observed Behavior**:
I am using Karpenter to scale nodes for the actions runner controller - to run self hosted github runners.
I have consolidation enabled on the provisioner, but also have the do-not-evict annotation on the pods.
Karpenter is sometimes creating an eviction for the pods even though the do-not-evict exists.
In this instance, the pod had been on the node for 9 seconds. The annotation is applied to the pod immediately from my testing. Then karpenter 9 seconds later (at 12:16:21) cordoned the node in an attempt to consolidate. This should be fine, except that it appears to have also created an eviction (although I don't see evict anywhere in the karpenter logs - the proof of that was from the EKS Audit). Because of the eviction, the pod terminated almost immediately, and then 24 seconds later karpenter deleted the node.

**Expected Behavior**:
Karpenter should not create an eviction for a pod that has the do-not-evict annotation.

# Details

**Node in Question**:ip-10-11-15-28.us-west-2.compute.internal
**Pod in Question**:action-runner-infra-testing-dxhgd-0

**Logs of Incident**:
```
# Logs from karpenter controller
2023-10-06T12:16:21.132Z	INFO	controller.deprovisioning	deprovisioning via consolidation delete, terminating 5 machines ip-10-11-2-6.us-west-2.compute.internal/t3.xlarge/spot, ip-10-11-5-164.us-west-2.compute.internal/t3.xlarge/spot, ip-10-11-10-70.us-west-2.compute.internal/t3.xlarge/spot, ip-10-11-8-128.us-west-2.compute.internal/t3.xlarge/spot, ip-10-11-15-28.us-west-2.compute.internal/t3.xlarge/spot	{"commit": "637a642"}
2023-10-06T12:16:21.399Z	INFO	controller.termination	cordoned node	{"commit": "637a642", "node": "ip-10-11-15-28.us-west-2.compute.internal"}
2023-10-06T12:16:45.253Z	INFO	controller.termination	deleted node	{"commit": "637a642", "node": "ip-10-11-15-28.us-west-2.compute.internal"}
2023-10-06T12:16:45.551Z	INFO	controller.machine.termination	deleted machine	{"commit": "637a642", "machine": "testing-github-runner-provisioner-4m2hf", "provisioner": "testing-github-runner-provisioner", "node": "ip-10-11-15-28.us-west-2.compute.internal", "provider-id": "aws:///us-west-2a/i-0104122d792d910d7"}
```
```
# Logs from Grafana (pod)
2023-10-06T12:16:07.642989216Z stdout F Gathering node details
2023-10-06T12:16:08.064391864Z stdout F node_name: ip-10-11-15-28.us-west-2.compute.internal
...
2023-10-06T12:16:19.373514557Z stdout F 2023-10-06 12:16:19Z: Listening for Jobs
2023-10-06T12:16:21.549609604Z stdout F Prestop hook started
2023-10-06T12:16:22.937198377Z stdout F 2023-10-06 12:16:22Z: Running job: Test Backend / Test Backend (3, ./spec/
```
```
# Logs from `k get events`
52m         Warning   FailedScheduling         pod/action-runner-infra-testing-dxhgd-0                                    0/132 nodes are available: 15 node(s) didn't match Pod's node affinity/selector, 2 node(s) had untolerated taint {purpose: base-components}, 2 node(s) had untolerated taint {purpose: monitoring}, 30 Insufficient cpu, 83 node(s) had untolerated taint {purpose: github-runner}. preemption: 0/132 nodes are available: 102 Preemption is not helpful for scheduling, 30 No preemption victims found for incoming pod..
52m         Normal    Nominated                pod/action-runner-infra-testing-dxhgd-0                                    Pod should schedule on: machine/testing-github-runner-provisioner-4m2hf, node/ip-10-11-15-28.us-west-2.compute.internal
52m         Normal    Scheduled                pod/action-runner-infra-testing-dxhgd-0                                    Successfully assigned actions-runner-system/action-runner-infra-testing-dxhgd-0 to ip-10-11-15-28.us-west-2.compute.internal
52m         Normal    Pulling                  pod/action-runner-infra-testing-dxhgd-0                                    Pulling image "AWS_ACCOUNT.dkr.ecr.us-west-2.amazonaws.com/github-actions-runner:latest"
52m         Normal    Pulled                   pod/action-runner-infra-testing-dxhgd-0                                    Successfully pulled image "AWS_ACCOUNT.dkr.ecr.us-west-2.amazonaws.com/github-actions-runner:latest" in 128.479031ms (128.489663ms including waiting)
52m         Normal    Created                  pod/action-runner-infra-testing-dxhgd-0                                    Created container runner
52m         Normal    Started                  pod/action-runner-infra-testing-dxhgd-0                                    Started container runner
52m         Normal    Pulled                   pod/action-runner-infra-testing-dxhgd-0                                    Container image "docker:dind" already present on machine
52m         Normal    Created                  pod/action-runner-infra-testing-dxhgd-0                                    Created container docker
52m         Normal    Started                  pod/action-runner-infra-testing-dxhgd-0                                    Started container docker
52m         Normal    Evicted                  pod/action-runner-infra-testing-dxhgd-0                                    Evicted pod
52m         Normal    Killing                  pod/action-runner-infra-testing-dxhgd-0                                    Stopping container runner
52m         Normal    Killing                  pod/action-runner-infra-testing-dxhgd-0                                    Stopping container docker
51m         Warning   FailedPreStopHook        pod/action-runner-infra-testing-dxhgd-0                                    PreStopHook failed
```
```
# Logs of eviction from EKS Audit in Cloudwatch
[
    {
        "@timestamp": "2023-10-06 12:16:21.517",
        "verb": "create",
        "@message": {
            "kind": "Event",
            "apiVersion": "audit.k8s.io/v1",
            "level": "RequestResponse",
            "auditID": "f23d88d9-c8c8-4373-b941-40647637abec",
            "stage": "ResponseComplete",
            "requestURI": "/api/v1/namespaces/actions-runner-system/pods/action-runner-infra-testing-dxhgd-0/eviction",
            "verb": "create",
            "user": {
                "username": "system:serviceaccount:karpenter:karpenter",
                "uid": "301c1f1b-d593-4445-b2e1-d080ba3c3476",
                "groups": [
                    "system:serviceaccounts",
                    "system:serviceaccounts:karpenter",
                    "system:authenticated"
                ],
                "extra": {
                    "authentication.kubernetes.io/pod-name": [
                        "karpenter-5876cf965d-qqqrd"
                    ],
                    "authentication.kubernetes.io/pod-uid": [
                        "697a369f-4814-49fa-bea4-c833a854f03c"
                    ]
                }
            },
            "sourceIPs": [
                "10.11.10.136"
            ],
            "userAgent": "karpenter",
            "objectRef": {
                "resource": "pods",
                "namespace": "actions-runner-system",
                "name": "action-runner-infra-testing-dxhgd-0",
                "apiVersion": "v1",
                "subresource": "eviction"
            },
            "responseStatus": {
                "metadata": {},
                "status": "Success",
                "code": 201
            },
            "requestObject": {
                "kind": "Eviction",
                "apiVersion": "policy/v1beta1",
                "metadata": {
                    "name": "action-runner-infra-testing-dxhgd-0",
                    "namespace": "actions-runner-system",
                    "creationTimestamp": null
                }
            },
            "responseObject": {
                "kind": "Status",
                "apiVersion": "v1",
                "metadata": {},
                "status": "Success",
                "code": 201
            },
            "requestReceivedTimestamp": "2023-10-06T12:16:21.462877Z",
            "stageTimestamp": "2023-10-06T12:16:21.482377Z",
            "annotations": {
                "authorization.k8s.io/decision": "allow",
                "authorization.k8s.io/reason": "RBAC: allowed by ClusterRoleBinding \"karpenter-core\" of ClusterRole \"karpenter-core\" to ServiceAccount \"karpenter/karpenter\""
            }
        }
    }
]
```

# Reproduction Steps
```
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: testing-github-runner-provisioner
spec:
  limits:
    resources:
      cpu: '300'
  providerRef:
    name: aws-github-runner
  consolidation:
    enabled: true
  ttlSecondsUntilExpired: 1800  # seconds, goal is to tell karpenter it can deprovision node after 1800 seconds, if the node is empty
  taints:
    - key: purpose
      value: testing-github-runner
      effect: NoSchedule
  labels:
    purpose: testing-github-runner
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: [spot]
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [t3]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: [medium, large, xlarge, xxlarge]
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64

```
```
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: aws-github-runner
spec:
  subnetSelector:
    karpenter.sh/discovery: live-primary-cluster
  securityGroupSelector:
    karpenter.sh/discovery: live-primary-cluster
  instanceProfile: github-instance-profile
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: optional  # Keep AWS CLI v1 compatibility
```

```
# RunnerSet used to spin up the pods

# Used to allow infra to test specific workflows quickly without a dedicated cache
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: action-runner-infra-testing
  namespace: actions-runner-system
spec:
  # replicas: 30
  organization: <ORGANIZATION>
  group: <ORGANIZATION>-k8s-infra-testing-group
  image: <AWS ACCOUNT>.dkr.ecr.<REGION>.amazonaws.com/github-actions-runner:latest
  serviceAccountName: runner-sa
  selector:
    matchLabels:
      app: action-runner
      appgroup: action-runner-infra-testing
  serviceName: action-runner
  template:
    metadata:
      annotations:
        karpenter.sh/do-not-evict: 'true' # This is what I would expect blocks karpenter from making an eviction notice
      labels:
        app: action-runner
        appgroup: action-runner-infra-testing
    spec:
      tolerations:
        - key: purpose
          operator: Equal
          value: testing-github-runner
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: purpose
                    operator: In
                    values:
                      - testing-github-runner
      serviceAccountName: runner-sa
      containers:
        - name: runner
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 2500m
              memory: 2Gi
          volumeMounts:
            - name: aws-config
              mountPath: /root/.aws/config
              subPath: config
              readOnly: true
      volumes:
        - name: aws-config
          secret:
            secretName: aws-config
            items:
              - key: config
                path: config
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: action-runner-infra-testing-autoscaler
  namespace: actions-runner-system
spec:
  # Runners in the targeted RunnerDeployment won't be scaled down
  # for 5 minutes instead of the default 10 minutes now
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    kind: RunnerSet
    name: action-runner-infra-testing
  minReplicas: 2
  maxReplicas: 30
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.25'
    scaleUpFactor: '2'
    scaleDownFactor: '0.5'
```

**Versions**
- Chart Version: 0.30.0
- Kubernetes (kubectl version):
```
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4-eks-2d98532
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
