### ISSUE TITLE
Karpenter spot provisioning integration not working

### ISSUE THREAD

**Issue by 95jinhong** [aws/karpenter#4812]
### Description

**Observed Behavior**:
We have a single spot provisioner in common, and we want the underutilized nodes to be consolidated into other nodes. However, this is not working

<img width="1285" alt="image" src="https://github.com/aws/karpenter/assets/43333982/179d0ad2-a175-4207-91bc-4d6dd8ea128b">

**Expected Behavior**:
If the existing Spot Instance is underutilized and has enough resources to be consolidated to another node, the Spot node should be removed and the pods in use should be moved to another node.

**Actual Behavior**: 
Lightly used nodes are not consolidated over time.
I'm looking at the spot node events and not sure where the problem is.
```
$ kubectl describe nodes <spot-node-name>
Events:
  Type    Reason            Age                  From       Message
  ----    ------            ----                 ----       -------
  Normal  Unconsolidatable  31m (x6 over 127m)   karpenter  Can't remove without creating 2 candidates
  Normal  Unconsolidatable  14m (x6 over 3h25m)  karpenter  Can't replace a spot node with a spot node
```

**Reproduction Steps** (Please include YAML):
provisioner and deployment , pdb files
```
# provisioner.yaml(only use)
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: dev-eks-ddocdoc-spot-common
spec:
  consolidation:
    enabled: true
  labels:
    nodegroup-type: ddocdoc-spot
  limits:
    resources:
      cpu: "500"
      memory: 1000Gi
  providerRef:
    name: aws-node-template-spot-common
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - ap-northeast-2a
    - ap-northeast-2c
  - key: karpenter.k8s.aws/instance-size
    operator: NotIn
    values:
    - nano
    - micro
    - small
    - medium
    - large
    - 9xlrage
    - 12xlarge
    - 18xlarge
    - 24xlarge
  - key: karpenter.k8s.aws/instance-generation
    operator: Gt
    values:
    - "2"
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values:
    - c
  weight: 100

```

```
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-spot
spec:
  replicas: 20
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: nginx-spot
          image: nginx:latest
          resources:
            requests:
              cpu: "0.5"
              memory: 500Mi
          lifecycle:
            preStop:
              exec:
                command:
                - sh
                - -c
                - sleep 10
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodegroup-type
                operator: In
                values:
                - ddocdoc-spot
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nginx
              topologyKey: kubernetes.io/hostname
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nginx
              topologyKey: topology.kubernetes.io/zone
            weight: 100
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: nginx
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
        - labelSelector:
            matchLabels:
              app: nginx
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
```

```
# pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-pdb-spot
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      provisioner: ddocdoc-spot
```

**Versions**:
- Chart Version: 0.31.0
- Kubernetes Version (`kubectl version`):  Client Version : v1.26.3
- Kubernetes Version : AWS EKS 1.25

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
