### ISSUE TITLE
karpenter-convert creates empty fields which are not required

### ISSUE THREAD

**Issue by badrish-s** [aws/karpenter#4823]
### Description

**Observed Behavior**:

[`karpenter-convert`](https://github.com/aws/karpenter/tree/main/tools/karpenter-convert) command on provisioner results in multiple null/empty fields in the resultant NodePool yaml file. Particularly, the field,  `spec.template.metadata.creationTimestamp` is causing below error when trying to deploy the NodePool.

> Error from server (BadRequest): error when creating "nodepool.yaml": NodePool in version "v1beta1" cannot be handled as a NodePool: strict decoding error: unknown field "spec.template.metadata.creationTimestamp

**Expected Behavior**:

`karpenter-convert` to give a NodePool yaml file with only required fields, that can be used for further deployments without any issues.

**Reproduction Steps** (Please include YAML):

Original Provisioner (provisioner.yaml)
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
  limits:
    resources:
      cpu: 10000
  providerRef:
    name: default
  consolidation: 
    enabled: true

```
After running below command, the output NodePool (nodepool.yaml) is :

> karpenter-convert -f provisioner.yaml > nodepool.yaml

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  creationTimestamp: null
  name: default
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  limits:
    cpu: 10k
  template:
    metadata:
      creationTimestamp: null
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      resources: {}
status: {}
```
As you see above, nodepool.yaml has multiple null/empty fields and `spec.template.metadata.creationTimestamp` in particular is causing above mentioned error when I try and deploy the same. Similar behavior can be observed when `karpenter-convert` is used to generate EC2NodeClass yaml file as well. 

It would be useful if `karpenter-convert` can create NodePool/EC2NodeClass files with values pre-populated for all required fields. If there are additional **required** fields that needs user inputs (such as `spec.role` in case of EC2NodeClass), `karpenter-convert` could output them as null/empty but with an appropriate hint/comment preceding the field so as to assist operator fill in the details.

**Versions**:
- Chart Version: 
- Kubernetes Version (`kubectl version`): v1.27

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
