### ISSUE TITLE
Consolidation inefficient when using topologySpreadConstraints with ScheduleAnyway

### ISSUE THREAD

**Issue by rafatio** [aws/karpenter#4907]
### Description

Hey there! We are having some doubts about the consolidation when the workload is using topologySpreadConstraints with ScheduleAnyway and kubernetes.io/hostname as topologyKey. The consolidation isn't happening even though there are a bunch of Nodes with low allocation. We expected that since the constraint is using ScheduleAnyway it shouldn't be a Filter.

**Observed Behavior**:
Starting the workload from scratch in a dedicated provisioner we observed that Karpenter nominates one Pod for each Node, when the first Nodes become available the Kubernetes Scheduler allocates the replicas on those first Nodes, most of other Nodes are empty and are soon removed by the deprovisioning. The final state is something like the image bellow:

![Screenshot 2023-10-24 at 14 44 15](https://github.com/aws/karpenter/assets/3380682/7752e6ea-60f2-4866-9bf2-2df1026d1303)

**Expected Behavior**:
The problem is that the Consolidation isn't happening as we would expect, the Pods should be bin-packed since the ScheduleAnyway shouldn't be treated as a Filter and the consolidation would lower the difference between the number of Pods and the global minimum. Using the image above as example, we expected the Pods from the i-0fd0a001309bcbebc to be reallocated to i-08771a8e0ff138447 as it would improve the allocation of the Nodes, this would also improve the skew from 13 to 10. A describe on the Node that we expected to be consolidated shows it is Unconsolidatable:

```
  Normal   Unconsolidatable         4m2s               karpenter              Can't remove without creating 2 candidates
```

**Reproduction Steps** (Please include YAML):
Provisioner and deployment files
```
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: karpenter-behavior-debug
spec:
  consolidation:
    enabled: true
  kubeletConfiguration:
    kubeReserved:
      cpu: 150m
      ephemeral-storage: 1Gi
      memory: 150Mi
    systemReserved:
      cpu: 150m
      ephemeral-storage: 1Gi
      memory: 200Mi
  labels:
    karpenter-debug-dedicated: "true"
  provider:
    launchTemplate: <redacted>
    subnetSelector:
      kops.k8s.io/instance-group/karpenter-behavior-debug: '*'
      kubernetes.io/cluster/<redacted>: '*'
  requirements:
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - us-east-1b
    - us-east-1c
    - us-east-1d
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: karpenter.k8s.aws/instance-family
    operator: In
    values:
    - c5
  - key: node.kubernetes.io/instance-type
    operator: NotIn
    values:
    - c5.large
    - c6i.large
    - m5.large
    - c5.xlarge
    - c6i.xlarge
  startupTaints:
  - effect: NoSchedule
    key: node.cloudprovider.kubernetes.io/uninitialized
  taints:
  - effect: NoSchedule
    key: dedicated
    value: karpenter-debug
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: karpenter-debug
  name: karpenter-debug
  namespace: karpenter-debug
spec:
  replicas: 20
  selector:
    matchLabels:
      app: karpenter-debug
  template:
    metadata:
      labels:
        app: karpenter-debug
    spec:
      containers:
      - image: nginx
        name: karpenter-debug
        resources:
          limits:
            cpu: "4"
            memory: 1000Mi
          requests:
            cpu: 400m
            memory: 250Mi
      nodeSelector:
        karpenter-debug-dedicated: "true"
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: karpenter-debug
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: karpenter-debug
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
```
**Versions**:
- Chart Version: karpenter-v0.30.0
- Kubernetes Version (`kubectl version`): v1.24.14

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
