### ISSUE TITLE
Support inject multiple cluster-dns-ips to kubelet-config.json

### ISSUE THREAD

**Issue by arestuzi** [aws/karpenter#4934]
### Description

**What problem are you trying to solve?**
1. I want to inject two dns server to pod for backup purpose. One is the coredns service ip address and the other is the localdns service ip address. If the coredns timed out, we can use secondary dns server for resolution.

2. I tried to configure multiple clusterDNS via karpenter provision. Only the first cluster dns injected to kubelet-config.json after scale up by the karpenter.
```
cat provision.yaml 
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
  limits:
    resources:
      cpu: 1000
  providerRef:
    name: default
  consolidation: 
    enabled: true
  kubeletConfiguration: 
    clusterDNS: ["10.0.1.100", "10.0.1.101"]
```
3. Via the source code of [karpenter](https://github.com/aws/karpenter/blob/main/pkg/providers/amifamily/bootstrap/eksbootstrap.go#L72C1-L74C3) and [bootstrap](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L457). we can see the karpenter selected the first entry and pass it as an argument to bootstrap.
4. eksctl support multiple cluster dns configuration and it works
https://eksctl.io/usage/nodegroup-customize-dns/

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
