### ISSUE TITLE
Consolidation replace seem not work in v0.32

### ISSUE THREAD

**Issue by rtrompier** [aws/karpenter#5005]
### Description

**Observed Behavior**:

After a fresh v0.32 installation, with the configuration shared below, I deployed the following deployments (1 pod with `1 cpu / 1Gi memory` and 1 pod with `3 cpu / 3Gi memory`) :

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        "karpenter.k8s.aws/instance-family": "c3"
      containers:
        - name: test
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            requests:
              cpu: 1
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-2
  template:
    metadata:
      labels:
        app: test-2
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        "karpenter.k8s.aws/instance-family": "c3"
      containers:
        - name: test-2
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            requests:
              cpu: 3
              memory: 3Gi
``` 

As no nodes are available, Karpenter is starting a new node. Until here, everything works well.
After a few seconds, I delete my deployment `test-2`. Karpenter should, after a few seconds, replace my node with a smaller one, but **nothing happened**.

I tried with the v0.31 and it works well (see below, we can see Karpenter is removing the node and replace it with another one).

![Screenshot 2023-11-02 at 15 20 35](https://github.com/aws/karpenter/assets/2504924/72ae2db7-a6cc-4c5f-b4c2-fbd48acc8898)

**Expected Behavior**:

Karpenter should start the consolidation and replace the node, with a smaller.

**Reproduction Steps** (Please include YAML):

Karpenter configuration : 

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
  limits:
    cpu: 500
  template:
    metadata:
      labels: {}
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
        - spot
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - a
        - c
        - d
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
        - windows
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
        - arm64
      taints: []
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      encrypted: true
      kmsKeyID: arn:aws:kms:us-east-1:XXXXX:key/XXXXX
      volumeSize: 50Gi
      volumeType: gp3
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: karpenter-sandbox-k8s-test-us-east-1-20231102135728389400000005
  securityGroupSelectorTerms:
  - id: sg-XXX
  subnetSelectorTerms:
  - id: subnet-XXX
  - id: subnet-XXX
  - id: subnet-XXX
  tags:
    Env: test-us-east-1
    Name: karpenter.sh/sandbox-k8s-test-us-east-1/default
    Project: sandbox-k8s
    Terraform: "true"
```

**Versions**:
- Chart Version: `0.32.1`
- Kubernetes Version (`kubectl version`): 
```
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2-eks-f8587cb
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
