### ISSUE TITLE
Karpenter 0.32.1 creates Spot NodeClaim instead of on-demand

### ISSUE THREAD

**Issue by arseny-zinchenko** [aws/karpenter#5015]
### Description

**Observed Behavior**:
When a NodePool has no `karpenter.sh/capacity-type` set, Karpenter trys to create a spot instance:

```
$ kk get nodeclaim -o yaml
...
  spec:
    nodeClassRef:
      name: default
    requirements:
    ...
    - key: karpenter.sh/capacity-type
      operator: In
      values:
      - spot
...
```

But the [documentation](https://karpenter.sh/preview/concepts/nodepools/) says, that:

> - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider **will default to on-demand**

If set `karpenter.sh/capacity-type` to the `["on-demand"]` in the NodePoll manifest, everything is working.

This lead to the error:

```
      message: 'creating instance, with fleet error(s), AuthFailure.ServiceLinkedRoleCreationNotPermitted:
        The provided credentials do not have permission to create the service-linked
        role for EC2 Spot Instances.
```

If an AWS Account has no **AWSServiceRoleForEC2Spot** created (if not using Spots at all).

**Expected Behavior**:

A NodeClaim is created with the `karpenter.sh/capacity-type == on-demand`

**Reproduction Steps** (Please include YAML):

1. create a NodePool without `karpenter.sh/capacity-type`
2. scale Pods
3. check nodeclaims

A NodePool example (with some terraform variables):

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: ${name}

spec:
  template:

    metadata:

    %{ if labels != null ~} 
      labels:
      %{ for k, v in labels ~}
        ${k}: ${v}
      %{ endfor ~}    
    %{ endif ~}

    spec:

    %{ if taints != null ~}
      taints:
        - key: ${taints.key}
          value: ${taints.value}
          effect: ${taints.effect}
    %{ endif ~}

      nodeClassRef:
        name: default
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ${jsonencode(instance-family)}
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ${jsonencode(instance-size)}
        - key: topology.kubernetes.io/zone
          operator: In
          values: ${jsonencode(topology)}
        - key: karpenter.sh/capacity-type
          operator: In 
          values: ["on-demand"]
  # total cluster limits 
  limits:
    cpu: 1000
    memory: 1000Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
```

A NodeClass manifest:

```
    apiVersion: karpenter.k8s.aws/v1beta1
    kind: EC2NodeClass
    metadata:
      name: default
    spec:
      amiFamily: AL2
      role: ${module.eks.eks_managed_node_groups["${local.env_name_short}-default"].iam_role_name}
      subnetSelectorTerms:
        - tags:
            karpenter.sh/discovery: "atlas-vpc-${var.environment}-private"
      securityGroupSelectorTerms:
        - tags:
            karpenter.sh/discovery: ${local.env_name}
      tags:
        Name: ${local.env_name_short}-karpenter
        environment: ${var.environment}
        created-by: "karpneter"
        karpenter.sh/discovery: ${local.env_name}
```

**Versions**:
- Chart Version: `0.32.1`
- Kubernetes Version (`kubectl version`): `v1.28.2-eks-f8587cb`

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
