### ISSUE TITLE
pod health check fails when starting a new node

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter#5041]
### Description

issue: Pods with health checks will fail health checks on newly booted nodes.  But on a booted node, it will work fine.

env:
```
eks: 1.24
karpenter: v0.31.0
```

the step is 
- 1.Pod started, in pending state
- 2.karpenter starts a new node
- 3.The pod is called to the new node
- 4.pod crash.

but this step is work fine:
- 1.karpenter starts a new node
- 2.Create a pod and schedule it on the node where karpenter is started.
- 3.pod run.

## pod yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-general
  namespace: karpenter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      containers:
        - name: goproxy
          image: registry.k8s.io/goproxy:0.1
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 1
      nodeSelector:
        group: general

```

## Provisioner yaml
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: test-group-general
spec:
  requirements:
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: [ "spot", "on-demand" ]
    - key: kubernetes.io/arch
      operator: In
      values: [ "arm64", "amd64" ]
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: In
      values: ["4"]
    - key: "karpenter.k8s.aws/instance-memory"
      operator: In
      values: ["8192"]
  labels:  # this will used by pod nodeSelector label.
    group: general
  consolidation:
    enabled: true
  limits:
    resources:
      cpu: 1000
  providerRef:
    name: test-group-general
  kubeletConfiguration:
    imageGCHighThresholdPercent: 70
    imageGCLowThresholdPercent: 50
    maxPods: 123
  startupTaints:
    - key: node.cilium.io/agent-not-ready
      value: "true"
      effect: NoExecute
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: test-group-general
spec:
  subnetSelector:
    aws-ids: "subnet-xxx"
  securityGroupSelector:
    aws-ids: "sg-xxx"
  tags:
    eks:cluster-name: test-main
    karpenter.sh/discovery: test-main
  metadataOptions:
    httpEndpoint: enabled
    httpPutResponseHopLimit: 2
    httpTokens: optional

```
