### ISSUE TITLE
can not find node.cilium.io/agent-not-ready when describe node

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter#5048]
### Description

env:
eks: 1.25
karpenter: v0.31.2

I have add the config to Provisioner
```
  startupTaints:
    - key: node.cilium.io/agent-not-ready
      value: "true"
      effect: NoExecute
```
and i see the  kuelete has the  param
```
--register-with-taints=node.cilium.io/agent-not-ready=true:NoExecute
```

but when i describe the node. the Taints fields is none.

```

➜  ~ k describe no ip-xxx
Name:               ip-xxx
Roles:              <none>
....
Annotations:        alpha.kubernetes.io/provided-node-ip: xxx
                    csi.volume.kubernetes.io/nodeid: {"ebs.csi.aws.com":"i-xxx"}
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Fri, 03 Nov 2023 09:38:59 +0800
Taints:             <none>
```
