### ISSUE TITLE
Checking EC2 API connectivity, AccessDenied

### ISSUE THREAD

**Issue by noamgreen** [aws/karpenter#5054]
### Description

**Observed Behavior**:
``` 
karpenter-75868b956d-hhkqd controller {"level":"DEBUG","time":"2023-11-09T12:08:16.662Z","logger":"controller","message":"loaded log configuration from file \"/etc/karpenter/logging/zap-logger-config\"","commit":"1072d3b"}
karpenter-75868b956d-hhkqd controller {"level":"DEBUG","time":"2023-11-09T12:08:16.663Z","logger":"controller","message":"discovered karpenter version","commit":"1072d3b","version":"v0.32.1"}
karpenter-75868b956d-hhkqd controller {"level":"FATAL","time":"2023-11-09T12:08:19.277Z","logger":"controller","message":"Checking EC2 API connectivity, AccessDenied: User: arn:aws:sts::xxxxxxxxxx:assumed-role/karpenter-manager/1699531699176343806 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxxxxxx:role/karpenter-manager\n\tstatus code: 403, request id: 57dbe300-501f-4dcd-a5c1-879a944e8e42","commit":"1072d3b"}
``` 

**Expected Behavior**:

**Reproduction Steps** (Please include YAML):

```
logLevel: debug
logConfig:
  enabled: true
  outputPaths:
    - stdout
  errorOutputPaths:
    - stderr
  logEncoding: json
  logLevel:
    global: debug
    controller: debug
    webhook: debug
serviceAccount:
  create: true
  name: "karpenter-manager"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::XXXXXXXXXXXX:role/karpenter-manager"
controller:
  env:
    - name: AWS_REGION
      value: us-east-1
    - name: AWS_DEFAULT_REGION
      value: us-east-1
serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus-operator
settings:
  clusterEndpoint: "https://XCXCXCXCXCXCXXCXCXCXXCXCXCX.gr7.us-east-1.eks.amazonaws.com"
  assumeRoleARN: arn:aws:iam::XXXXXXXXXXXXX:role/-karpenter-manager
  clusterName: "eks-dev"
  interruptionQueueName: "karpenter-sqs"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: service
              operator: In
              values:
                - infra
            - key: env
              operator: In
              values:
                - dev

``` 
**Versions**:
- Chart Version:  0.32.1
- Kubernetes Version (`kubectl version`):  1.24

I add ubuntu pod in the name space and use this pod to test the STS 
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxxxxxx:role/karpenter-manager
  name: test
  namespace: karpenter
spec:
  containers:
  - env:
      - name: AWS_REGION
        value: us-east-1
      - name: AWS_DEFAULT_REGION
        value: us-east-1
    image: ubuntu:latest
    imagePullPolicy: Always
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do echo hi ; sleep 30; done;" ]
    name: test
  serviceAccountName: karpenter-manager
```
i can assume the role and i have access to all EC2 etc... and its working , i can say in cloudtrail i see the karpenter assume the role but i am keep geting this STS access issues  
*as part of testing i add the "AWS_REGION" and "AWS_DEFAULT_REGION" if you dont use "AWS_DEFAULT_REGION" aws cli will ask you to add region to the command *
and one more issues i am not sure why its doing AssumeRole and not AssumeRoleWithWebIdentity  ??

Thanks
