### ISSUE TITLE
Not possible to restrict node based on `instance-pods`

### ISSUE THREAD

**Issue by midu-git** [aws/karpenter#5055]
### Description

**Observed Behavior**:
Until 0.32.1, more precisely until [this](https://github.com/aws/karpenter/pull/4895) commit, it was allowed to use `karpenter.k8s.aws/instance-pods` to restrict the set of EC2 machines for a node pool. This is not possible any more, although the documentation still lists the label `karpenter.k8s.aws/instance-pods` as well-known, cf. https://karpenter.sh/docs/concepts/scheduling/#well-known-labels

**Expected Behavior**:
`karpenter.k8s.aws/instance-pods` should pass the CEL validation.

**Reproduction Steps** (Please include YAML):
```yaml
apiVersion: karpenter.sh/v1beta1
    kind: NodePool
    metadata:
      name: default
      namespace: karpenter
    spec:
      disruption:
        consolidateAfter: 30s
        consolidationPolicy: WhenEmpty
        expireAfter: Never
      limits:
        cpu: 1000
      template:
        spec:
          nodeClassRef:
            name: default
          requirements:
          - key: karpenter.sh/capacity-type
            operator: In
            values:
            - spot
          - key: kubernetes.io/os
            operator: In
            values: ["linux"]
          - key: kubernetes.io/arch
            operator: In
            values: ["amd64"]
          - key: karpenter.k8s.aws/instance-category
            operator: In
            values: ["c", "m", "r"]
          - key: karpenter.k8s.aws/instance-pods
            operator: Gt
            values: ["11"]
          - key: karpenter.k8s.aws/instance-generation
            operator: Gt
            values: ["2"]
```

**Versions**:
- Chart Version: 0.32.1
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
