### ISSUE TITLE
label \"name\" does not have known values (typo of \"karpenter.k8s.aws/instance-accelerator-name\"?

### ISSUE THREAD

**Issue by marcustut** [aws/karpenter#5073]
### Description

**Observed Behavior**:
I just installed Karpenter v0.32.1 on my EKS cluster and when I tested it, this logs came out and the no new nodes are added.

```
{"level":"ERROR","time":"2023-11-13T02:23:56.464Z","logger":"controller.provisioner","message":"Could not schedule pod, incompatible with nodepool \"default\", daemonset overhead={\"cpu\":\"455m\",\"memory\":\"376Mi\",\"pods\":\"4\"}, incompatible requirements, label \"name\" does not have known values (typo of \"karpenter.k8s.aws/instance-gpu-name\"?)","commit":"1072d3b","pod":"tardis-machine/tardis-machine-55595f9d95-776lk"}
{"level":"ERROR","time":"2023-11-13T02:24:06.464Z","logger":"controller.provisioner","message":"Could not schedule pod, incompatible with nodepool \"default\", daemonset overhead={\"cpu\":\"455m\",\"memory\":\"376Mi\",\"pods\":\"4\"}, incompatible requirements, label \"name\" does not have known values (typo of \"karpenter.k8s.aws/instance-accelerator-name\"?)","commit":"1072d3b","pod":"tardis-machine/tardis-machine-55595f9d95-776lk"}
```

**Expected Behavior**:

I expect it to add a new node, this does not make sense to me since none of my workload requires GPU. The nodepool that I have is also select for `t4g` which is arm64 based instances without GPU.

**Reproduction Steps** (Please include YAML):

Install latest `v0.32.1` and use this nodepool

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t"]
        - key: karpenter.k8s.aws/instance-generation
          operator: In
          values: ["4"]
      nodeClassRef:
        name: default
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 24h # One day
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: Ubuntu # AL2 does not support arm64 with GPU (cause error when karpenter trying to discover nodes)
  role: "KarpenterNodeRole-$CLUSTER_NAME"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "$CLUSTER_NAME"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "$CLUSTER_NAME"
```

**Versions**:
- Chart Version: v0.32.1
- Kubernetes Version (`kubectl version`): v1.25.15-eks-4f4795d

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
