### ISSUE TITLE
amiSelectorTerms is not respecting amiFamily when using wildcards in the name field

### ISSUE THREAD

**Issue by chrismld** [aws/karpenter#5091]
### Description

**Observed Behavior**: When using wildcards in the `amiSelectorTerms` the AMIs chosen are not respecting the `amiFamily` field. For instance, I have `amiFamily: AL2` and I'm using a wildcard in the name like `name: '*1.27*'` to only use the v1.27 AMIs. However, when I describe the `EC2NodeClass` object I get a list of Bottlerocket AMIs, like this:

```
Status:
  Amis:
    Id:    ami-0352fcc17a86f3f3b
    Name:  bottlerocket-aws-k8s-1.27-x86_64-v1.16.1-763f6d4c
    Requirements:
      Key:       kubernetes.io/arch
      Operator:  In
      Values:
        amd64
    Id:    ami-0a1f7170f73c46ad4
    Name:  bottlerocket-aws-k8s-1.27-nvidia-aarch64-v1.16.1-763f6d4c
    Requirements:
      Key:       kubernetes.io/arch
      Operator:  In
      Values:
        arm64
```

I noticed this problem when nodes never joined to the cluster, EC2 instances are created without a problem but they never join the cluster. If I leave this running for a while, Karpenter keeps creating more EC2 instances. I looked at the `nodeclaims` but there are no events describing what's missing. Additionally, when I manually remove the `nodeclaim`, Karpenter shows the following error (I've removed sensitive data):

```
{"level":"ERROR","time":"2023-11-14T21:02:41.235Z","logger":"controller.nodeclaim.termination","message":"terminating instances, UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::XXXXXXXX:assumed-role/karpenter-XXXXXXXXXXXXXXX/XXXXXX is not authorized to perform: ec2:TerminateInstances on resource: arn:aws:ec2:eu-west-1:XXXXXXXXXXX:instance/i-XXXXXXXXXXX because no identity-based policy allows the ec2:TerminateInstances action. Encoded authorization failure message: XXXXXXXXXXXXXXXXXXX\n\tstatus code: 403, request id: XXXXXXXXXXXX","commit":"XXXXXXX","nodeclaim":"latest-current-ami-8l92h","nodepool":"latest-current-ami","node":"","provider-id":"aws:///eu-west-1c/i-XXXXXXXXX","nodeclaim":"latest-current-ami-8l92h","id":"i-XXXXXXX"}
```

At first I thought I configured an IAM policy incorrectly but if I removed the `amiSelectorTerms` section, nodes are created and terminated without any problem. BTW, I'm trying to migrate to v1 this blueprint: https://github.com/aws-samples/karpenter-blueprints/blob/main/blueprints/update-nodes-with-drift/latest-current-ami.yaml#L12 ... notice how in previous versions I could use wildcards in `amiSelector` without any problem.

**Expected Behavior**: Nodes should be registered to the cluster, and when I don't need them anymore, they should be terminated successfully.

**Reproduction Steps** (Please include YAML):

```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: latest-current-ami-template
spec:
  amiFamily: AL2
  amiSelectorTerms:
  - name: '*1.27*'
    owner: amazon
  role: "karpenter-karpenter-blueprints"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: karpenter-blueprints
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: karpenter-blueprints
  tags:
    KubernetesVersion: "1.27"
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: latest-current-ami
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 168h0m0s
  limits:
    cpu: 100k
    memory: 5000Gi
  template:
    metadata:
      labels:
        intent: latest-current-ami
    spec:
      nodeClassRef:
        name: latest-current-ami-template
      requirements:
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
        - i
        - d
      - key: karpenter.k8s.aws/instance-cpu
        operator: In
        values:
        - "4"
        - "8"
        - "16"
        - "32"
        - "48"
        - "64"
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: latest-current-ami
spec:
  replicas: 3
  selector:
    matchLabels:
      app: latest-current-ami
  template:
    metadata:
      labels:
        app: latest-current-ami
    spec:
      nodeSelector:
        intent: latest-current-ami
      containers:
      - name: latest-current-ami
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
        resources:
          requests:
            cpu: 512m
            memory: 512Mi
```

For a full reference, we've pushed the current version in this repo: https://github.com/aws-samples/karpenter-blueprints/blob/2cec6c0820c490922542c85b54f3819a50498b1e/blueprints/update-nodes-with-drift/latest-current-ami.yaml and here's the README to follow-up the instructions on how to reproduce: https://github.com/aws-samples/karpenter-blueprints/blob/2cec6c0820c490922542c85b54f3819a50498b1e/blueprints/update-nodes-with-drift/README.md

**Versions**: 0.32.1
- Chart Version: karpenter-v0.32.1
- Kubernetes Version (`kubectl version`): 1.28 (I'm launching a 1.27 node on purpose, it used to work)

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
