### ISSUE TITLE
Karpenter provisions machine types that explicitly not allowed from provisioner

### ISSUE THREAD

**Issue by Izvi-digibank** [aws/karpenter#5095]
### Description

**Observed Behavior**:
R3 instances types are being provisioned although:
```
   - key: node.kubernetes.io/instance-family
      operator: NotIn
      values:
      .
      .
      .
      - r3

```
I see Karpenter has some defaults that probably added to provisioner by mutating webhook. For example, I did not define this filed in my provisioner:
```
 - key: karpenter.k8s.aws/instance-category
    operator: In
      values:
      - c
      - m
      - r
```
The current situation looks to me like "r3 instance-family isn't allowed and all r3 instances are allowed". 

**Expected Behavior**:
User defined `requirements` should be in priority to defaults or mutates.
I expect r3 instance type to not be provisioned if I defined so. 
Alternatively, is there a way to delete defaults / mutates from my provisioner? 

**Reproduction Steps** (Please include YAML):
Provisioner:

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"karpenter.sh/v1alpha5","kind":"Provisioner","metadata":{"annotations":{},"name":"workflows"},"spec":{"limits":{"resources":{"cpu":1250,"memory":"1000Gi"}},"provider":{"amiFamily":"Bottlerocket","blockDeviceMappings":[{"deviceName":"/dev/xvda","ebs":{"deleteOnTermination":true,"encrypted":true,"volumeSize":"200Gi","volumeType":"gp3"}}],"securityGroupSelector":{"aws-ids":"sg-xxxxx"},"subnetSelector":{"xxx":"subnet-xxx,subnet-xxx,subnet-xxx"},"tags":{"karpenter.sh/discovery":"workflows"}},"requirements":[{"key":"node.kubernetes.io/instance-family","operator":"NotIn","values":["c1","cc1","cc2","cg1","cg2","cr1","g1","g2","hi1","hs1","m1","m2","m3","t1","r3"[]},{"key":"karpenter.sh/capacity-type","operator":"In","values":["spot"[]}],"ttlSecondsAfterEmpty":1800}}
  creationTimestamp: "2023-05-11T21:34:28Z"
  generation: 6
  name: workflows
spec:
  limits:
    resources:
      cpu: "1250"
      memory: 1000Gi
  provider:
    amiFamily: Bottlerocket
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 200Gi
        volumeType: gp3
    securityGroupSelector:
      aws-ids: sg-xxx
    subnetSelector:
      aws-ids: subnet-xxx,subnet-xxx,subnet-xxx
    tags:
      karpenter.sh/discovery: workflows
  requirements:
  - key: node.kubernetes.io/instance-family
    operator: NotIn
    values:
    - c1
    - cc1
    - cc2
    - cg1
    - cg2
    - cr1
    - g1
    - g2
    - hi1
    - hs1
    - m1
    - m2
    - m3
    - t1
    - r3
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values:
    - c
    - m
    - r
  - key: karpenter.k8s.aws/instance-generation
    operator: Gt
    values:
    - "2"
  ttlSecondsAfterEmpty: 1800
```

**Versions**:
- Chart Version: 0.27.3
- Kubernetes Version (`kubectl version`): EKS 1.25
- **Kerpenter is installed through Terraform module:**
  "terraform-aws-modules/eks/aws//modules/karpenter" - version 19.16.0
