### ISSUE TITLE
Windows Pods not resolving DNS names

### ISSUE THREAD

**Issue by marciogmorales** [aws/karpenter#5099]
### Description

**Observed Behavior**:

Windows pods aren't resolving DNS names, despite Windows Server version 2019 or 2022, whereas Linux ones are. I narrowed down this issue, and it only occurs when Windows nodes are deployed via Karpenter; the same doesn't happen when nodes are deployed via EKS Node Groups. By the nslookup test, it sounds like Windows pod isn't able to find the DNS Server (CoreDNS). I believe it is something to do with the Windows node EKS bootstrap, but I wasn't able to find the root cause.

NSLOOKUP from a Linux Pod (DNS server is found)

````
PS C:\kube\Apps> kubectl exec -i -t dnsutils -- nslookup www.google.com
Server:         10.100.0.10
Address:        10.100.0.10#53

Non-authoritative answer:
Name:   www.google.com
Address: 142.251.167.147
Name:   www.google.com
Address: 142.251.167.104
Name:   www.google.com
Address: 142.251.167.99
Name:   www.google.com
Address: 142.251.167.106
Name:   www.google.com
Address: 142.251.167.105
Name:   www.google.com
Address: 142.251.167.103
````

NSLOOKUP from a Windows Pod (DNS server is not found)

````
PS C:\kube\Apps> kubectl exec -i -t amazon-eks-gmsa-domainless-2022-699fbdf69d-rtdlr -- nslookup www.google.com
Server:  UnKnown
Address:  10.100.0.10

DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  10.100.0.10

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to UnKnown timed-out
PS C:\kube\Apps> 

````

**Expected Behavior**:

Windows pods resolving DNS names.

**Reproduction Steps** (Please include YAML):

1 - Deploy EKS cluster and Karpenter using the [Karpenter Docs guideline](https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/) , deploy NodeClass and NodePool and run nslookup on the pod.

```
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: windows2022
  annotations:
    kubernetes.io/description: "General purpose NodePool for Windows workloads"
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/os
          operator: In
          values: ["windows"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        name: windows2022
      taints:
      - key: os/windows2022
        effect: NoSchedule
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30 * 24h = 720h
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: windows2022
  annotations:
    kubernetes.io/description: "Nodes running Windows Server 2022"
spec:
  amiFamily: Windows2022
  role: "KarpenterNodeRole-eks-cluster" # replace with your cluster name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-cluster" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-cluster" # replace with your cluster name
  metadataOptions:
    httpProtocolIPv6: disabled
    httpTokens: required
  detailedMonitoring: true
```

**Versions**: 
- EKS: 1.28
- AMI: Windows_Server-2019-English-Core-EKS_Optimized-1.28-2023.10.19 
- AMI: Windows_Server-2022-English-Core-EKS_Optimized-1.28-2023.10.19
- Chart Version: 
- Kubernetes Version (`kubectl version`):  1.28.3

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
