### ISSUE TITLE
Support global cluster limits

### ISSUE THREAD

**Issue by stevehipwell** [aws/karpenter#5141]
### Description

**What problem are you trying to solve?**
I'd like to be able to constrain the total cluster size via CPU & memory limits which cover all Karpenter managed nodes and all other nodes in the cluster. For the non-Karpenter nodes it would work if they needed a specific label to be added to the calculation.

This functionality is already present in Cluster Autoscaler.

The documentation currently claims that the limits on the NodePool are for the whole cluster but I don't think this is the case?

```yaml
# Resource limits constrain the total size of the cluster.
  # Limits prevent Karpenter from creating new instances once the limit is exceeded.
  limits:
    cpu: "1000"
    memory: 1000Gi
```

**How important is this feature to you?**
This could block migration off Cluster Autoscaler for some of our clusters where cost is a significant factor and multiple NodePools are being used.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
