### ISSUE TITLE
NodeNotFound - Inconsistent Behavior

### ISSUE THREAD

**Issue by alexandrospanayi** [aws/karpenter#5222]
### Description

**Observed Behavior**:
I am attempting to test out how we can update our NodePool instance types. I did a direct update to the instance type in the node pool, to observe how our existing pods would behave.

But there is some very inconsistent behavior with how NodeClaims are able to register nodes into the cluster.

I currently have 5 nodeclaims. 4 where able to correctly identify the instance to register, but there's 1 producing the `NodeNotFound` error. All are from the same NodePool.

I have verified the instance is in AWS, however even with debug logging enabled, karpenter produces very little logs and none seem to provide any detail on why a random NodeClaim within the same NodePool can't register its instance.

There are no limits being set on the NodePool.

I've also noticed if I delete the NodeClaim that's stuck with `NodeNotFound` and I simply delete it, the newly created NodeClaim will suddenly be able to detect the node. However this isn't always the case.

**Expected Behavior**:
I expect all nodes within a single NodePool to be able to be properly registered. 

**Reproduction Steps** (Please include YAML):
NodePool:
```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  annotations:
  name: m6a-xlarge-private
spec:
  disruption:
    consolidateAfter: 60s
    consolidationPolicy: WhenEmpty
    expireAfter: Never
  template:
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default-v1-24-private
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - m6a.2xlarge
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - m6a
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
            - 2xlarge
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values:
            - '8'
        - key: karpenter.k8s.aws/instance-memory
          operator: In
          values:
            - '32768'
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - us-east-2a
            - us-east-2b
            - us-east-2c
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
            - arm74
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
  weight: 10
```

NodeClass:
```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default-v1-24-private
spec:
  amiFamily: AL2
  amiSelectorTerms:
    - name: amazon-eks-node-1.24-v20230825
      owner: amazon
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        encrypted: true
        volumeSize: 20Gi
        volumeType: gp3
  detailedMonitoring: true
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: KarpenterNodeRole
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: xyz
    - id: xyz
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: xyz
    - tags:
         xyz: xyz
  tags:
    Name: karpenter-default-v1-24-private
    cluster: xyz
status:
  amis:
    - id: ami-0cbe90a726405b3f8
      name: xyz
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
  instanceProfile: xyz
  securityGroups:
    - id: xyz
      name: xyz
  subnets:
    - id: xyz
      zone: us-east-2a
    - id: xyz
      zone: us-east-2c
    - id:xyz
      zone: us-east-2b
```

**Versions**:
- Chart Version: v0.32.0
- Kubernetes Version (`kubectl version`): 1.24

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
