### ISSUE TITLE
Support volume topological scaling

### ISSUE THREAD

**Issue by tsahiduek** [aws/karpenter#622]
**Tell us about your request**
I would like Karpenter to support scaling nodes on the right topology key based on persistent volume that is bounded to a pod. This was solved in the Kubernetes schedular by implementing [Volume Topology Aware Scheduling](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/volume-topology-scheduling.md).

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When using pods with Persistent Volumes like EBS for example, the volume reside in a specific zone. In order for the pod to be able to reach to a running state in case of node replacement/scale up, Karpenter should identify the zone that the volume resides on, and launch an instance in the same zone
 
**Are you currently working around this issue?**
Using [Cluster Autoscaler](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#i-have-a-couple-of-pending-pods-but-there-was-no-scale-up)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Scoping this into v0.4

**Comment by Noksa** [comment]
I would say this is very useful feature.

Without this we are not able to use statefulsets that use EBS volumes using all AZ in a region.

I would really appreciate if someone could tell us that we will get this feature before NY :)

**Comment by ellistarn** [comment]
It's not currently being worked on, but is high priority. Is there something specific about NY timing that's important? As a short term workaround, you can use multiple statefulsets with a zonal nodeselector. Not great - I know, but it's something.

**Comment by ellistarn** [comment]
I have a work in progress here: https://github.com/aws/karpenter/pull/1015. It's working for both preprovisioned volumes and new volumes, as well as storage class aware topology and PVC aware topology. Need to write some tests, but this will likely land next release.

**Comment by mattcamp** [comment]
Just adding my +1 that this would be a very useful feature.

Currently I'm stuck in a situation where Karpenter has provisioned all my nodes in eu-west-1b and eu-west-1c (despite there being plenty of capacity in 1a), leaving my pods with PV's in eu-west-1a stuck in Init forever.

**Comment by ellistarn** [comment]
Coming in v0.5.4

**Comment by swapnil-omni** [comment]
Is this solved? I am still facing this issue similar to this. 

here is my nodepool and nodeclass
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: nodepool-1
spec:
  template:
    metadata:
      labels:
        type: karpenter
        Service: kap
    spec:
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand", "spot"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["m6a.large", "m6a.xlarge"]
        
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: nodegroup-1
      expireAfter: 72h
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 5m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: nodegroup-1
spec:
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        iops: 3000
        throughput: 125
        volumeSize: 50Gi
        volumeType: gp3
        encrypted: true
  metadataOptions:
    httpPutResponseHopLimit: 2
    httpTokens: optional
  amiFamily: AL2
  amiSelectorTerms:
    - id: ami-07a5681d009c959d2
  role: KarpenterNodeRole-kap-k8s-dev3-failover
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery:  kap-k8s-dev3-failover
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name:  kap-k8s-dev3-failover
  tags:
    app.kubernetes.io/created-by: karpenter
    Service: kap
```

This node class can create node in that specific zone (And it has), but i have a pod which is in pending state as it is scheduled on a node created on different zone.
