### ISSUE TITLE
AWS VPC CNI & Security Groups for Pods issue

### ISSUE THREAD

**Issue by ebolinger-sumologic** [aws/karpenter#639]
When using AWS VPC CNI and Security Groups for pods when a pod is admitted to the cluster the first container has a resource request added to it for a pod-eni like so

```yaml
  resources:
      limits:
        cpu: 100m
        memory: 24Mi
        vpc.amazonaws.com/pod-eni: "1"
      requests:
        cpu: 100m
        memory: 24Mi
        vpc.amazonaws.com/pod-eni: "1"`
```

It seems that AWS does not surface this property of an instance type because Karpenter is not able to see that it could spin up nodes satisfying the pod constraint and it fails in calculating packing.

cluster-autoscaling handles this by allowing tags to be added to the ASG that it controls to work around the information not being available elsewhere.

Pod ENI counts are available for EKS at - https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt
Perhaps that could be combined with the current source of truth to calculate the resource availability.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
