### ISSUE TITLE
KOPs Integration

### ISSUE THREAD

**Issue by RobertLucian** [aws/karpenter#907]
## Description

Looking at https://karpenter.sh/docs/getting-started/, I don't see any introduction into how Karpenter can be used with a Kops-provisioned cluster. I've been trying to get Karpenter to work with Kops clusters, but with no success yet. The docs only mention EKS.

Can someone add a section on how a generic K8s cluster on AWS can get Karpenter installed? Or at least drop some notes in here.

**Comment by ellistarn** [comment]
Hey @RobertLucian. Karpenter is EKS agnostic and should work just fine w/ KOPs. I know @bwagner5 runs it like this. You will need a way to get the KarpenterControllerRole into your pod identity (perhaps https://github.com/jtblin/kube2iam) and then simply helm install Karpenter: https://github.com/aws/karpenter/tree/main/charts/karpenter#installing-the-chart

**Comment by RobertLucian** [comment]
I see. Thanks @ellistarn! That sounds straightforward then. Any @bwagner5 gotchas I should be aware of?

**Comment by geoffcline** [comment]
I think we should have a specific page on kops. It sounds like a prevalent use case.

**Comment by bwagner5** [comment]
Kops will most likely get added to Kops as a managed add-on. 


In my kops config, I've put Karpenter on the control-plane nodes. You can put them on any node group though. 

You'll need to add the IAM policy for Karpenter in the kops cluster spec
```
spec:
...
 additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "ec2:CreateLaunchTemplate",
            "ec2:CreateFleet",
            "ec2:RunInstances",
            "ec2:CreateTags",
            "iam:PassRole",
            "ec2:TerminateInstances",
            "ec2:DescribeLaunchTemplates",
            "ec2:DescribeInstances",
            "ec2:DescribeSecurityGroups",
            "ec2:DescribeSubnets",
            "ec2:DescribeInstanceTypes",
            "ec2:DescribeInstanceTypeOfferings",
            "ec2:DescribeAvailabilityZones",
            "ssm:GetParameter",
          ],
            "Resource": "*"
        }
      ]

``` 

and then your helm values.yaml for Karpenter should look something like this (filling in Cluster Name DNS and Cluster Endpoint):

```
serviceAccount:
  create: true
  name: karpenter
  # Annotations to add to the service account (like the ARN of the IRSA role)
  annotations: {}
controller:
  nodeSelector:
    kubernetes.io/role: master
  tolerations:
    - operator: Exists
      key: node-role.kubernetes.io/master
  affinity: {}
  clusterName: ${CLUSTER_NAME_DNS}
  clusterEndpoint: "https://${KOPS_ENDPOINT}"
webhook:
  env: []
  nodeSelector:
    kubernetes.io/role: master
  tolerations:
    - operator: Exists
      key: node-role.kubernetes.io/master
  affinity: {}
```
