### ISSUE TITLE
Doc improvements for instances that are not in EKS pods list

### ISSUE THREAD

**Issue by dalbhanj** [aws/karpenter#915]
**Tell us about your request**
What do you want us to build?
If Karpenter tries to provision newer instances, for example m6a.* instances that were just announced, these instances fail to join EKS cluster because they are not in [eni max pods list](https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt). While these instances will eventually be added to the list, there will be time when users run into this issue and chew up troubleshooting time. For these scenarios, I would add a notification highlighting this edge scenario 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Documentation improvement highlighting why they ran into the issue. Also, it would be nice to provide workaround solution by asking users to use NotIn operator

**Are you currently working around this issue?**
How are you currently solving this problem?

Yes, currently I'm specifying not to use m6a.* instance types in my default provisioner
```
spec:
  requirements:
  - key: node.kubernetes.io/instance-type
    operator: NotIn
    values:
    - m6a.48xlarge
    - m6a.32xlarge
    - m6a.24xlarge
    - m6a.16xlarge
    - m6a.12xlarge
    - m6a.8xlarge
    - m6a.4xlarge
    - m6a.2xlarge
    - m6a.xlarge
```
**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
