### ISSUE TITLE
karpenter controller (v0.5.0) crashes when requested pod ephemeral storage value is greater than node root volume

### ISSUE THREAD

**Issue by srasun** [aws/karpenter#917]
## Version

**Karpenter**: v0.5.0

## Expected Behavior
The pod should successfully get provisioned

## Actual Behavior
Nodes have an 8G root volume, and when trying to schedule a pod with a request for 100G, the karpenter controller (v0.5.0) crashes.

**Comment by akestner** [comment]
Can you share a little bit more about the crash that you're seeing here (logs, etc)? Also, any Karpenter-related config you can share would be helpful for us to reproduce

**Comment by ellistarn** [comment]
Ephemeral storage is not currently supported, but we absolutely shouldn't be crashing in this case.

**Comment by ellistarn** [comment]
Do you have an example of the pod yaml (not the karpenter controller) that caused this crash?

**Comment by suket22** [comment]
@srasun Could you give us the pod yaml that caused this crash? I'm having trouble reproducing this. 

I tried an emptyDir which schedules fine - 
```
    spec:
      containers:
      - image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
        imagePullPolicy: IfNotPresent
        name: inflate
        resources:
          requests:
            cpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: 100Gi
        name: cache-volume
```

Also tried using generic ephemeral volumes (the provisioner isn't topology-aware for ephemeral volumes so had to constrain that to us-west-2b) but that scheduled fine too - 
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: scratch-storage-class
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.ebs.csi.aws.com/zone
    values:
    - us-west-2b
---
kind: Pod
apiVersion: v1
metadata:
  name: my-app
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/scratch"
        name: scratch-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: scratch-volume
      ephemeral:
        volumeClaimTemplate:
          metadata:
            labels:
              type: my-frontend-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "scratch-storage-class"
            resources:
              requests:
                storage: 100Gi
  ```            

Karpenter controller logs before the crash with debug mode would also be helpful for us to further investigate this.

**Comment by suket22** [comment]
When using a pod requesting ephemeral storage, I do see the Karp controller failing to provision pods. 
```
    spec:
      containers:
      - image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
        imagePullPolicy: IfNotPresent
        name: inflate
        resources:
          requests:
            cpu: "1"
            ephemeral-storage: 50Mi
```
This leads to the controller complaining with - 
```
2022-01-12T00:14:29.525Z	ERROR	controller.provisioning	Failed to compute packing, pod(s) [default/inflate-5479675f7-wqpvx] did not fit in instance type option(s) [m1.small m1.medium m3.medium t3.micro t3a.micro c1.medium t3a.small t3.small c4.large c3.large .... r5ad.24xlarge r5n.24xlarge r5.24xlarge r5dn.24xlarge c6i.32xlarge m6i.32xlarge m6a.32xlarge r6i.32xlarge m6a.48xlarge]	{"commit": "2a8e3de", "provisioner": "default"}
```
This is expected in [our code as per this](https://github.com/aws/karpenter/blob/main/pkg/controllers/provisioning/binpacking/packable.go#L108) since we haven't handled ephemeral-storage and therefore don't really know how to pack this. 

We probably need to callout in our docs that we only support resourceRequests for cpu, memory and gpu (`nvidia.com/gpu` etc) until we add support for ephemeral storage. Given Karpenter controls the size of the root volume (and allocatable is ~the root volume size), we should be able to account for ephemeral storage in our binpacking logic. I'll run this by @bwagner5 as well to check if I'm missing something. 

It might also be worthwhile to log a warn level message with "unknown resourceType "foo", no packing possible" to make this failure more explicit?
