### ISSUE TITLE
Improve Cloudprovider Separation in Provisioner API

### ISSUE THREAD

**Issue by sylr** [aws/karpenter#967]
I would suggest to add a layer between the provisioner provider and its properties, e.g.:

```yaml
apiVersion: karpenter.sh/v1alpha6
kind: Provisioner
metadata:
  name: default
spec:
  ...
  provider:
    aws:
       ...
    azure:
       ...
```

Of course only one cloud provider would be accepted.

The advantage of this design would be to be able to design a strict CRD which would not allow unknown properties (typos, mixed properties from other cloud provider) with an explicit message when creating the Provisioners.

Regards.
