### ISSUE TITLE
Support configuring instance metadata options for AWS provisioner

### ISSUE THREAD

**Issue by orirawlings** [aws/karpenter#969]
**Tell us about your request**
What do you want us to build?

AWS currently documents EKS security best practices, including restricting access to Instance Metadata Service (IMDS) from pods (https://aws.github.io/aws-eks-best-practices/security/docs/iam/#restrict-access-to-the-instance-profile-assigned-to-the-worker-node). Exposure of IMDS is controlled via the metadata options on the Launch Template of provisioned nodes.

EKS Managed Node Groups currently defaults the metadata options to expose both IMDSv1 and IMDSv2 with a maximum hop limit of 2 (https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-eks-supports-ec2-instance-metadata-service-v2/). This favors compatibility for workloads rather than the recommended security hardening.

For Karpenter, it is currently possible to harden security for IMDS by separately creating a Launch Template and referencing it from the Provisioner resource. It would be nice if metadata options were exposed directly in the Provisioner API so that the security best practices could be followed without needing a separate tool like CloudFormation or Terraform for the Launch Templates.

Something like:
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: example
spec:
  ...
  provider:
    ...
    metadataOptions:
      httpEndpoint: enabled
      httpPutResponseHopLimit: 1
      httpTokens: required
```

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

The goal here is to ensure that Provisioner API can be a one-stop shop for users following EKS best practices, without the need to manage EC2 API resources directly.

**Are you currently working around this issue?**
How are you currently solving this problem?

The current approach for anyone following best practices would be to manage a custom Launch Template themselves.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
What is the desired configuration settings for your use case? We should figure out what we want our defaults to be.

**Comment by mikestef9** [comment]
The default should be httptoken required with hop limit of 2, aka IMDSv2 enabled, IMDSv1 disabled. For customers using IRSA everywhere, they can take a step further and set hop limit to 1 (only host networking pods can access IMDS).

**Comment by orirawlings** [comment]
> What is the desired configuration settings for your use case? I'd like to figure out what we want our defaults to be.

For my use case, the desired configuration is:
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: example
spec:
  ...
  provider:
    ...
    metadataOptions:
      httpEndpoint: enabled
      httpPutResponseHopLimit: 1
      httpTokens: required
```

Though my organization is still transitioning and not all workloads will work on this yet.

> The default should be httptoken required with hop limit of 2, aka IMDSv2 enabled, IMDSv1 disabled. For customers using IRSA everywhere, they can take a step further and set hop limit to 1 (only host networking pods can access IMDS).

It seems that EKS Managed Node Groups also requires a hop limit of 2, though they allow httptoken to be optional. This maximizes compatibility with an older AWS SDK version and any code that hasn't been updated to use IMDSv2. In #970 I've started with a hop limit of 2 and HTTP token optional to match EKS MNG.
